### PR TITLE
sqltypes bug: incorrect vitess type returned

### PR DESCRIPTION
**Pull request by sougou**
@erzel 
Bug: b/28409793
MySQL sometimes sets stray flags that have to be ignored.
Specifically, for this query:
select max(uint) from t
MySQL sets the binary flag along with the unsigned flag.
The bug fix changes the behavior where vitess only looks at
the relevant flags and ignores all others.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1665)

### CODE REVIEW

**Comment by erzel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sqltypes/type.go, line 111 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1665#-KGTusUF6k8GBDBjMvZ1:-KGTusUF6k8GBDBjMvZ2:646905134) ([raw file](https://github.com/youtube/vitess/blob/939ec958b291e307ad5ea9577999bf78f4353f2f/go/sqltypes/type.go#L111)):*
Hmm. This wouldn't work if MySQL returns a binary text field (varchar) with the "unsigned"  bit on (for some reason).
The bits we ignore should probably depend on the MySQL type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1665)*

**Comment by sougou** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sqltypes/type.go, line 111 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1665#-KGTusUF6k8GBDBjMvZ1:-KGUAvdreLGg_YkXD-pS:397866196) ([raw file](https://github.com/youtube/vitess/blob/939ec958b291e307ad5ea9577999bf78f4353f2f/go/sqltypes/type.go#L111)):*
Good point. The new fix is less elegant, but more robust.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1665)*

**Comment by erzel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/sqltypes/type.go, line 111 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1665#-KGTusUF6k8GBDBjMvZ1:-KGY3Aifg7Zmad3Mdnb6:1088764132) ([raw file](https://github.com/youtube/vitess/blob/939ec958b291e307ad5ea9577999bf78f4353f2f/go/sqltypes/type.go#L111)):*
Cool. I actually think it's simpler and quicker to understand than the old version.

---

*[go/sqltypes/type.go, line 141 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1665#-KGY3x9f-1ROj-UPG8MP:-KGY3x9f-1ROj-UPG8MQ:-1276465740) ([raw file](https://github.com/youtube/vitess/blob/9eb47e2de2de11b975275f2cf20b7e7f3c0d70ba/go/sqltypes/type.go#L141)):*
Nit: I find it easier to read if there's spaces around the ampersand.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1665)*

**Comment by erzel** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1665#-:-KGY4546kgfn5r-1-tp4:1417088721)*

**Comment by sougou** [comment]
Reviewed 2 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/sqltypes/type.go, line 141 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1665#-KGY3x9f-1ROj-UPG8MP:-KGYBa9gBUGAktfJUttN:1170984603) ([raw file](https://github.com/youtube/vitess/blob/9eb47e2de2de11b975275f2cf20b7e7f3c0d70ba/go/sqltypes/type.go#L141)):*
This is how gofmt formats it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1665)*

**Pull request merged**
