### PR TITLE
add doc about the life of a query

### PR DESCRIPTION
**Pull request by yaoshengzhe**
Life of a query explains the query path from client code to vtgate
to vttablet. It also explains the interactions with topo server, how
the query is handled by vttablet and how the results are returned.

Both regular and streaming queries are included, as well as the
scatter quieries and how it is processed in vtgate.

To help you review the change here is the rendered markdown: https://github.com/yaoshengzhe/vitess/blob/fix_life_of_a_query_doc/doc/LifeOfAQuery.md

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM

The next step for this doc is probably for a tech writer to make it pretty, as only a tech writer can. So I think this is great!

How did you generate the .png files? if you used a helper program, you might want to submit the original format for the images to.

**Comment by yaoshengzhe** [comment]
"How did you generate the .png files?"
I use draw.io, it saves your graph into its own xml format and provides multiple export formats. Not sure if we want to check in these xml files.

**Comment by alainjobart** [comment]
I think we should check in the XML file, yes, so we can change them easily
later...

**Comment by yaoshengzhe** [comment]
xml files added, they can be imported by draw.io

**Comment by shrutip** [comment]
The life of query looks good. But I noticed that it starts from vtgate rpc
and is missing the query routing piece. Do we
want to include that as well ?

**Comment by yaoshengzhe** [comment]
Query routing is part of v3 api and is not covered in this doc (it focuses on v2 api). But if you like, I can add these details. It's not there just because v3 api is not finalized.

**Pull request merged**
