### PR TITLE
bump java to grpc 1.5.0

### PR DESCRIPTION
**Pull request by bbeaudreault**

### CODE REVIEW

**Comment by michael-berlin** [comment]
LGTM

Let's see if Travis will pass here.

**Comment by bbeaudreault** [comment]
I saw the same class not found issue locally but wanted to see if travis would get passed it. Doesn't seem to be, so I'm investigating.

**Comment by bbeaudreault** [comment]
@michael-berlin this is working now.  The error message changed which was breaking some tests, so I fixed that. I also upped the timeout on the test because sometimes on my machine or under load it may take longer than 4s for the vtgate to be accepting queries.

I also tried removing the `netty-tcnative-boringssl-static`, but couldn't. In fact I had to update it to latest as well.

**Comment by michael-berlin** [comment]
Sounds good! Thank you for doing this :-)

Merging now.

**Pull request merged**
