### PR TITLE
Fixed typo on Scaling Mysql docs

### PR DESCRIPTION
**Pull request by onnimonni**
Now the sentence makes more sense and is has lesser amount of doge.

<a href="https://imgflip.com/i/19n9wr"></a>

### CODE REVIEW

**Comment by michael-berlin** [comment]
LGTM

Can you please sign the CLA? After that I can merge the change.

**Comment by onnimonni** [comment]
@michael-berlin I'm using an email address for my git commits which doesn't have an google account, I don't know how to proceed. How can I sign it with that email without having google account for that email?

**Comment by onnimonni** [comment]
Hmm I guess googlebot just had some delay with the CLA. You're welcome.

**Comment by michael-berlin** [comment]
Yep, that worked :) I've merged it.

Thank you!

**Pull request merged**
