### PR TITLE
Move start_vtcombo logic into run_local_database.py. Revert change to…

### PR DESCRIPTION
**Pull request by thompsonja**
… vttest_sample_test

@alainjobart 

run_local_database is now importing sharding_utils.py, a util module currently in the test folder. It may make more sense to move it into py/vttest or maybe a new directory like py/util. Let me know what you think.

### CODE REVIEW

**Comment by alainjobart** [comment]
I am not sure we actually need any of this at all. I mean, obviously, no one can generate the string-encoded proto in their head, so I agree that expecting people to think about it and pass the right parameters to run_local_database.py is too much. However, whatever language you use to start run_local_database will have a proto library that can echo string-encoded protos. So that's much easier...

And the method you use in sharding_utils.py coudl be move to py/vtdb somewhere if needed...

**Comment by alainjobart** [comment]
Hum looking at this sharding_utils.py is not really where it should be, I think it should be in py/vttest, as it is useful for tests only. Sorry about the run around :(

**Comment by thompsonja** [comment]
The main benefit of having the separate flags is so that a user could call run_local_database.py directly for quick tests, like UI tests or other one-off events. Definitely for an automated test the topo_proto flag would be used instead. This primarily saves the step of having to write your own topology proto-to-string script.

**Comment by alainjobart** [comment]
LGTM now, thanks for humoring me :)

Please import into our repo after merging, to make sure it works internally too... (probably need to change a few build files for the added file).

**Pull request merged**
