### PR TITLE
Added rate-limiting of commits in tabletserver and a flag to control the rate

### PR DESCRIPTION
**Pull request by erzel**

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM to use that for your tests. We probably will want something different in the long run, as discussed.

**Comment by sougou** [comment]
Now that I see what you're trying to do, I'm a little hesitant.
This will lead to degraded user experience because the failure happens at the end.
Could we instead throttle the begins. I think it will amount to the same thing, but the app could have saved all the work upfront, and implementing the retry logic at the beginning should be easier too.

**Comment by erzel** [comment]
Thanks for the comments. As Alain noted, this is just for testing purposes right now. 
Sougou -- notice that a client can retry the commit on this failure, so it won't be wasted work.
Or am I missing something?

**Comment by alainjobart** [comment]
But if the commit is throttled more than 30s it will time out. I agree with Sugu, it would be better to throttle the Begin. That's what we'll end up doing with the real implementation too, most likely.

**Comment by sougou** [comment]
The big difference is that a failed commit will cause data corruption for distributed transactions.

**Comment by erzel** [comment]
Good points. I'll change to throttle the begins.

**Comment by erzel** [comment]
For now we will only do this for MapReduce and so the change will be applied internally.

**Pull request closed without merging**
