### PR TITLE
Switch <title> tag ordering for SEO

### PR DESCRIPTION
**Pull request by derekperkins**
Page titles should always come before the site title

### CODE REVIEW

**Comment by sougou** [comment]
@michael-berlin does this change require a publish-site run?

**Comment by michael-berlin** [comment]
Yes, this change will require a publish-site.

re: the change. How about removing the site title completely? It doesn't seem to provide much value? Or would this be bad in terms of SEO? :)

**Comment by bbeaudreault** [comment]
According to HubSpot, that would be bad SEO :P https://website.grader.com/results/vitess.io

**Comment by derekperkins** [comment]
Nice plug @bbeaudreault :)

It's pretty standard to leave the site title at the end. It doesn't have a huge impact there in terms of SEO, but it does add value to the user experience. It's frustrating for us tab junkies to hover over a tab and have the title say "Features", instead of "Features - Vitess".

I've got a number of other SEO related items that I want to tackle in #3171 and a related PR in #3170.

**Comment by michael-berlin** [comment]
I'm closing this PR because the new `seo` jekyll plugin does the same thing for us :)

See: https://github.com/youtube/vitess/pull/3184

btw: For the root page, it reversed the order of the site and the page title i.e. `$site.title | $page.title`:

`Vitess | Vitess is a ...`.

That looks good to me :)

**Pull request closed without merging**
