### PR TITLE
Ceph Backup Storage Plugin

### PR DESCRIPTION
**Pull request by raunak-agarwal-flipkart**
Implemented backup storage for Ceph (which is very much similar to Amazon S3).

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1629)

### CODE REVIEW

**Comment by enisoc** [comment]
I checked that your email address is approved under the Flipkart CLA, but the bot is still getting confused. I think it may be the quotes in your Author info. Those shouldn't be necessary.

You can compare in git log:
```
commit 31f60bc49dee0b562d1c5f5be56ee75072997621
Author: “raunak-agarwal-flipkart” <“raunak.agarwal@flipkart.com”>
Date:   Fri Apr 8 19:44:09 2016 +0530

    cephStorage
```

versus an example of mine:
```
commit de503edfc83a94d88d7cbf82bff330081ce81318
Author: Anthony Yeh <enisoc@google.com>
Date:   Thu Apr 7 18:52:37 2016 -0700

    jdbc: Fix VitessConnectionTest
```

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[examples/local/config.json, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr5Edt7-9fbVBIa6Km:-KEr5EduYEBUAG1_QvIa:986471313) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/examples/local/config.json#L1)):*
Can you rename this to `ceph_backup_config.json` so the purpose is clearer?

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr6U8KmZnYhvyKCFeA:-KEr6U8KmZnYhvyKCFeB:-686102295) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L22)):*
It seems like you're not really using this flag, since the bucket name gets overwritten by the config file.

I suggest to replace this flag with:
``` go
configFilePath = flag.String("ceph_backup_storage_config", "", "Path to JSON config file for ceph backup storage")
```

If you still need to keep `bucket` as a package-local variable, even though it's coming from the config file, you can make it a regular string instead of a flag:
``` go
var (
  configFilePath = flag.String(...)
  bucket string
)
```

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 66 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErgBu2EX03rLukhSYx:-KErgBu2EX03rLukhSYy:1996382618) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L66)):*
This looks like a debug statement that should be removed.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 173 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErgzdG7ibCHiPJiunn:-KErgzdG7ibCHiPJiuno:298953997) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L173)):*
Does this actually work to remove objects recursively?

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 186 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErhGY43Udb5zqycPKI:-KErhGY43Udb5zqycPKJ:933251713) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L186)):*
This comment can be removed since there's no call to `client.Close()` at all.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 199 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr76cupKrcswk4Z4C0:-KEr76cupKrcswk4Z4C1:2018155741) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L199)):*
As noted above, I suggest to create a `-ceph_backup_storage_config` flag, so this can turn into `os.Open(*configFilePath)`.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 202 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr7_WDhGnnflrDPnua:-KEr7_WDhGnnflrDPnub:-602277689) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L202)):*
After checking for error on `Open()`, it is typical to do:

``` go
defer configfile.Close()
```

This ensures the file will be closed regardless of which return path is eventually taken. Note that the json decoder doesn't close the file for you.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 205 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr7wHa2Gmw3ImYhpwS:-KEr7wHbQBk4itun-DFN:945455075) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L205)):*
typo: "parsing"

Usually we just let the `err` convert automatically to string when using it with the `%v` formatter, like this:

``` go
fmt.Errorf("... %v", err)
```

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 208 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErhZ_WPvlXAM8nvGsb:-KErhZ_WPvlXAM8nvGsc:-486316494) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L208)):*
All the above parts that read the config file should be inside this `if bs._client == nil {` block, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629#-:-KEr4gIq_ncc93KcOWL_:-1012979745)*

**Comment by raunak-agarwal-flipkart** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 173 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErgzdG7ibCHiPJiunn:-KEt1E4MH_VI4hVDeahR:687237081) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L173)):*
It is not able to delete objects recursively and I am talking to Minio guys for the same. Need to check more on this part.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 208 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErhZ_WPvlXAM8nvGsb:-KEt20MhJBFM8uZZvi_D:-1387833481) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L208)):*
Need some more clarity, will look again in this part and do the changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629)*

**Comment by enisoc** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 173 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErgzdG7ibCHiPJiunn:-KF6Q9h0lIbGlFmC3Hw-:1063490082) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L173)):*
In the GCS plugin, we also need to implement recursive delete manually:

https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/gcsbackupstorage/gcs.go#L164

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629)*

**Comment by enisoc** [comment]
It looks like the minio client library your using can also work for S3. Can we rename the plugin from "ceph" to "minio" so it's more clear that this isn't only for ceph?

**Comment by raunak-agarwal-flipkart** [comment]
Hi Anthony
Minio client library can be used for S3 as well but S3 provides its own
S3-Go client. I believe using S3's Go client should be preferred to
interact with S3.
Ideally, S3's client should have been used as it provides the base
standards but due to *authentication issues*, I had to Minio-Go client to
interact with Ceph.
I was having trouble with deleting objects, will need to make some code
changes on my end for that. Once deletion functionality is complete, I'll
commit the code and then further look into *S3 integration with both
Minio-Go and S3-Go clients*.


~ Thanks and Regards
Raunak Kumar Agarwal
Ph. 9980125313

**Comment by enisoc** [comment]
I see. That makes sense then. Thanks!

**Comment by raunak-agarwal-flipkart** [comment]
Review status: 4 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[examples/local/ceph_backup_config.json, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr5Edt7-9fbVBIa6Km:-KFE-oo6L0BPLIBIHIo0:-1266483685) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/examples/local/ceph_backup_config.json#L1)):*
Done.
https://github.com/youtube/vitess/commit/d88f6c49fcd8a32faf6dd66fc9f5105e44ff7649
https://github.com/youtube/vitess/blob/ceph1/go/vt/mysqlctl/cephbackupstorage/ceph.go#L25

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr6U8KmZnYhvyKCFeA:-KFE0G9g0G1vp2BtEftG:92320916) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L22)):*
Done.
https://github.com/youtube/vitess/commit/7190584172d97638505710425986d40797aa7324

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 66 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErgBu2EX03rLukhSYx:-KFE0HzemqotFqIXr6e0:-2101808290) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L66)):*
Done. Removed the mentioned statement.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 173 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErgzdG7ibCHiPJiunn:-KFE0OSxULon-ITIX-WQ:-1792130418) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L173)):*
Done.
https://github.com/youtube/vitess/commit/93dd8db97fbb06170bd67e218fa73c9d51622adc

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 186 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErhGY43Udb5zqycPKI:-KFE0Sm7mLs4ZCbOYJ_w:1721177208) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L186)):*
Done.
https://github.com/youtube/vitess/commit/d88f6c49fcd8a32faf6dd66fc9f5105e44ff7649

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 199 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr76cupKrcswk4Z4C0:-KFE0gmxbUNvJ8vHQz3N:92320916) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L199)):*
Done.
https://github.com/youtube/vitess/commit/7190584172d97638505710425986d40797aa7324

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 202 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr7_WDhGnnflrDPnua:-KFE0lpcSgirFsrzkD2C:1721177208) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L202)):*
Done.
https://github.com/youtube/vitess/commit/d88f6c49fcd8a32faf6dd66fc9f5105e44ff7649

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 205 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr7wHa2Gmw3ImYhpwS:-KFE0qOvihEzifu5CYeU:1721177208) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L205)):*
Done.
https://github.com/youtube/vitess/commit/d88f6c49fcd8a32faf6dd66fc9f5105e44ff7649

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 208 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KErhZ_WPvlXAM8nvGsb:-KFE0zy7ln3QI9pwtUd6:1721177208) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L208)):*
Done.
https://github.com/youtube/vitess/commit/d88f6c49fcd8a32faf6dd66fc9f5105e44ff7649

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629)*

**Comment by enisoc** [comment]
Reviewed 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr6U8KmZnYhvyKCFeA:-KFGEzNLA3lGercXwEm9:516734183) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L22)):*
It looks like you're still not using bucket as a flag, since the value given on the command line is ignored and populated from the config file. I suggest replacing this with a simple package-local string variable rather than a flag:

``` go
var (
  configfilePath = ...
  bucket string
)
```

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 25 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG6vhPYQiRpxHElS2M:-KFG6vhPYQiRpxHElS2N:-1614513463) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L25)):*
Flags are in a single global namespace, so by convention we use prefixes to indicate which package defines the flag. In this case, since the flag is defined in package `cephbackupstorage`, it should be named `ceph_backup_storage_config` by convention.

Also the flag description "take backup configuration for backup" sounds confusing to me. I suggest something like "Path to JSON config file for ceph backup storage".

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 181 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG8JvIGW-WXoBcNrSF:-KFG8JvIGW-WXoBcNrSG:-770876572) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L181)):*
Please add `defer close(doneCh)` after this line to make sure cleanup happens if we return with an error before completing the range loop.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 189 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG9BiM1infyP3Ip0Nr:-KFG9BiNxvs5nWjoge5I:729804759) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L189)):*
Usually we just loop over values rather than indexes, like this:

``` go
for _, obj := range arr {
```

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 191 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG9LmzZbHszRr_68hB:-KFG9Ln-oe-eUG5oOphY:402643466) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L191)):*
I don't think it's a good idea to remove all objects concurrently. There can be hundreds of objects in a backup, and we don't want to flood the API all at once. Removing a backup is usually not a time-critical operation, so I don't think it needs to be optimized yet.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 195 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG9rVbVopDloHGxcc3:-KFG9rVc3aVQAqeDuN3Z:-763089186) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L195)):*
We shouldn't use `log.Fatal*()` because it will crash the whole process just because a single operation failed. If you still want to keep this concurrent despite my comment above, the usual way to handle errors inside the goroutine is with `concurrency.AllErrorRecorder`. You can see a code example that uses it here:

https://github.com/youtube/vitess/blob/ee59df6568f2133151b3d40e022ced25428a4434/go/vt/discovery/healthcheck_wait.go#L66

With that said, I still prefer to make this not concurrent, unless you have a good reason it needs to be.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 223 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFGAtCuGJ8TFi5m5chp:-KFGAtCuGJ8TFi5m5chq:296464135) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L223)):*
This defer statement needs to go after the following `if err != nil {}` block. If the file failed to open, we should not call `Close()` on it.

---

*[go/vt/vtctl/backup.go, line 49 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFGESU_B8DmQNte5K_z:-KFGESU_B8DmQNte5Ka-:-257960607) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/vtctl/backup.go#L49)):*
The defer should be moved up one line, directly after the `err != nil` block from `GetBackupStorage`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629)*

**Comment by raunak-agarwal-flipkart** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KEr6U8KmZnYhvyKCFeA:-KFIucjtPHtH7SA1OSBI:-1423640446) ([raw file](https://github.com/youtube/vitess/blob/b746da90c3e6a8d316f3879b778dc1c4aa3e7c8c/go/vt/mysqlctl/cephbackupstorage/ceph.go#L22)):*
Done.
https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 25 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG6vhPYQiRpxHElS2M:-KFIugyZawKGeS6bMKvc:-1183180856) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L25)):*
Done.
https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 181 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG8JvIGW-WXoBcNrSF:-KFIuifr9QZtGtNdmdiJ:1107923998) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L181)):*
Done.https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 189 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG9BiM1infyP3Ip0Nr:-KFIujhYYmd-MhKJ8mH4:-1423640446) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L189)):*
Done.
https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 191 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG9LmzZbHszRr_68hB:-KFIul-xQG9Cri_wae3H:-1423640446) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L191)):*
Done.
https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 223 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFGAtCuGJ8TFi5m5chp:-KFIupgvO6C-_ugVOpb6:-1423640446) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L223)):*
Done.
https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---

*[go/vt/vtctl/backup.go, line 49 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFGESU_B8DmQNte5K_z:-KFIuxCVqAVa4Il3PBEO:-1423640446) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/vtctl/backup.go#L49)):*
Done.
https://github.com/youtube/vitess/commit/3c53dc9d02e02429070855c9e52fbd5b6bb26aa6

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629)*

**Comment by enisoc** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 25 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1629#-KFG6vhPYQiRpxHElS2M:-KFKx03GYj9RNkE6Juqa:-2019749105) ([raw file](https://github.com/youtube/vitess/blob/d730a5f5a922015395e9d8a834e5ea292d38efb6/go/vt/mysqlctl/cephbackupstorage/ceph.go#L25)):*
Sorry I meant the flag string should be changed, not the variable name. Variables in Go don't conventionally use underscores.

Here's what I'm suggesting:

``` go
configFilePath = flag.String("ceph_backup_storage_config", "ceph_backup_config.json", "Path to JSON config file for ceph backup storage")
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1629#-:-KFMemknJG6zoYnGprbB:1417088721)*

**Pull request merged**
