### PR TITLE
add support for a column name as optional argument to DEFAULT

### PR DESCRIPTION
**Pull request by bbeaudreault**
According to https://dev.mysql.com/doc/refman/5.7/en/insert.html:

> Use the keyword DEFAULT to set a column explicitly to its default value. This makes it easier to write INSERT statements that assign values to all but a few columns, because it enables you to avoid writing an incomplete VALUES list that does not include a value for each column in the table. Otherwise, you would have to write out the list of column names corresponding to each value in the VALUES list.
>
> You can also use DEFAULT(col_name) as a more general form that can be used in expressions to produce a given column's default value.

See also: https://dev.mysql.com/doc/refman/5.7/en/miscellaneous-functions.html#function_default

cc @acharis

### CODE REVIEW

**Comment by bbeaudreault** [comment]
@sougou how is that unreasonable? I think if it works in mysql it should work in vitess, within reason considering our need to route queries appropriately for sharded databases.

Also, are you suggesting a change to this PR or a future sanity check feature?

**Comment by bbeaudreault** [comment]
I don't see any special handling of `DEFAULT` with column unspecified. If you'd like me to do something more here, would you mind pointing me at an example?

**Comment by sougou** [comment]
LGTM

I forgot that we treated `default` expressions as complex. The logic I was referring to is this one where we fill in the default value ourselves is no value was specified for a column: https://github.com/youtube/vitess/blob/master/go/vt/vttablet/tabletserver/planbuilder/dml.go#L543,

**Comment by bbeaudreault** [comment]
Ah cool, thanks for clarifying and merge

**Pull request merged**
