### PR TITLE
Case Insensitive Map for getting Column Index

### PR DESCRIPTION
**Pull request by harshit-gangal**
This is needed so that application does not have to take care of exact case of the column.
When a V2 API is called, the column can be in Uppercase or in Mixed Case.
When a V3 API is called, the column are in Lowercase.

It is hard for the application to track when to call with Exact Matching case and when to call in lowercase.

Use of CaseInsensitiveMap will help application to call in case insensitive manner.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1572)

### CODE REVIEW

**Comment by sougou** [comment]
The v2 behavior is inconsistent. It should also return lower-cased column names just like v3.
Nevertheless, it's a good idea to use case-insensitive comparisons on the client side.

**Comment by enisoc** [comment]
Thanks for turning this into a PR. I see what you mean now. I found this in the JDBC [ResultSet](https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html) spec:

> Column names used as input to getter methods are case insensitive. When a getter method is called with a column name and several columns have the same name, the value of the first matching column will be returned.

So I definitely agree we should do this. Do you foresee any problems if we implement it with `String.toLowerCase()` and `ImmutableMap`? It would be nice to be able to still keep the map immutable. It seems like `CaseInsensitiveMap` might be a little smarter about being locale-independent. Have you guys seen problems with locales when using `String.toLowerCase()`? For example, I noticed you or your teammate implemented your own case-insensitive string search in another PR rather than using `toLowerCase()` and `indexOf()`, and I haven't understood why yet.

We should also add a test case to verify this behavior, and add to the javadocs for FieldMap and the Row getters to notify users that `columnLabel` is case-insensitive. I can do that as a separate PR if you don't have time.

**Comment by enisoc** [comment]
As a side note regarding the quote from the spec above, we currently will return the _last_ matching column if multiple columns have the same name. We may consider changing that to match ResultSet as well.

**Comment by harshit-gangal** [comment]
I have changed it according to ResultSet specs.
@enisoc Please go ahead and make the changes.

**Comment by enisoc** [comment]
@harshit-gangal Thanks. I added the docs and test as a new commit on your branch. I decided not to use ImmutableMap after all, because you can't use the map to check for duplicates while building the map.

This should be ready to merge once your company's CLA goes through.

**Comment by harshit-gangal** [comment]
CLA is signed

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1572#-:-KD4kzO0oD3qOeZcZJE8:-2007247675)*

**Comment by harshit-gangal** [comment]
Approve the pull request here https://pullapprove.com/youtube/vitess/pull-request/1572/

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1572#-:-KEYKZpvim9uxPOL_lF1:1417088721)*



[Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/1572/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)

**Pull request merged**
