### PR TITLE
vtgate query logging infrastructure

### PR DESCRIPTION
**Pull request by demmer**
## Overview

Add a logstats implementation to vtgate to add an infrastructure to expose per-query timings to either a log target or in the debug UIs, both aggregated and unaggregated.

Implements #2802

## Tasks 
~This is not currently complete but I wanted to put it up to start the review process while finishing off the implementation.~
This is ready for review

Current status / to do list:

- [x] The basic logstats structure, support in Execute, and unit tests for various cases
- [x] Support for StreamExecute
- [x] Include Row Count in the logstats structure
- [x] Support for non-execute cases (SHOW, DDL, etc)
- [x] Support Errors
- [x] /debug/querylog endpoint for tab-delimited query logs
- [x] /debug/querylogz endpoint for human-readable consumption
- [x] /debug/queryz endpoint for aggregate statistics
- [x] Link the various endpoints into the vtgate debug UI
- [x] Test in a real environment
- [x] Fix data race in vcursor by using atomics
- [x] Fix multiple registrations for querylog HTTP endpoints in vtcombo

## Notes

The logstats structure is currently:
```
type LogStats struct {
	Ctx           context.Context
	Method        string
	Target        *querypb.Target
	StmtType      string
	SQL           string
	BindVariables map[string]*querypb.BindVariable
	StartTime     time.Time
	EndTime       time.Time
	ShardQueries  uint32
	RowsAffected  uint64
	PlanTime      time.Duration
	ExecuteTime   time.Duration
	CommitTime    time.Duration
	Error         error
}
```

I also updated `engine.Plan` to include some basic metrics:

```
type Plan struct {
	// Original is the original query.
	Original string `json:",omitempty"`
	// Instructions contains the instructions needed to
	// fulfil the query.
	Instructions Primitive `json:",omitempty"`
	// Mutex to protect the stats
	mu sync.Mutex
	// Count of times this plan was executed
	ExecCount uint64
	// Total execution time
	ExecTime time.Duration
	// Total number of shard queries
	ShardQueries uint64
	// Total number of rows
	Rows uint64
	// Total number of errors
	Errors uint64
}
```

### CODE REVIEW

**Comment by demmer** [comment]
@sougou This is complete and ready for your review.
A couple of open items I wanted to call to your attention:

1. As part of adding some useful links to the /debug/status page on vtgate, I also included the execution graph similar to what vttablet has, using the QPSByDbType rate counter. That is currently keeping 15 mins of stats at 1 minute intervals.
I'd like to change this to 15 mins at 5 second intervals -- is that ok?

2. I reworked this so that every call to `Execute` or `StreamExecute` emits a LogStats record, regardless of the statement type, with one exception: The mysql plugin issues an implicit "rollback" statement whenever a connection closes. Most of the time this is a no-op since there isn't a transaction in flight, so I skipped emitting the record unless the rollback actually does something.

3. CodeClimate is very unhappy with the change, once again with all sorts of things that I disagree should be errors. Can we disable these checks as described here:
https://docs.codeclimate.com/v1.0/docs/disabling-individual-checks

If not can we instead disable CodeClimate altogether or find another way to do these checks?

**Comment by demmer** [comment]
@sougou This has been updated and rebased to the latest changes in logging. Ready for review.

**Comment by demmer** [comment]
The reason I wanted it was to actually distinguish between queries done via Execute / ExecuteStream and those done via vindex operations.

This is best shown from a snippet in one of the test cases:

```
 	_, err := executorExec(executor, "insert into user(id, v, name) values (1, 2, 'myname')", nil)		
...
 	testQueryLog(t, logChan, "VindexCreate", "INSERT", "insert into name_user_map(name, user_id) values(:name0, :user_id0)", 1)
 	testQueryLog(t, logChan, "TestExecute", "INSERT", "insert into user(id, v, name) values (1, 2, 'myname')", 1)
 ```

In the real world of course that "TestExecute" would be just "Execute".

**Comment by sougou** [comment]
LGTM
Looks like I completely misunderstood what Method stood for. It's confusing because the solution is not perfect. Ideally, one would want to generate one logStats record per request. But that would not work here, because each sub-request of a vindex is a full request by itself.

I feel like we'll end up iterating on this as it gains usage. So, this is good to go as is.

**Comment by demmer** [comment]
Yeah I totally agree -- I originally hoped that we would have a single logStats record per vtgate Execute, but the way the lookup vindexes currently work there wasn't a clear way to do that.

If you have a good idea of how to evolve this work, I'd be happy to revise it.

The other thing I considered along the same lines was whether to record each shard query as part of the record or just the count (which I do now).

If we reworked the vindex stuff then I would definitely want to do the former, much like how the vttablet version tracks each mysql query.

**Pull request merged**
