### PR TITLE
vtctld: Reworked how to get heatmap data and how to set labels

### PR DESCRIPTION
**Pull request by pkulsh**
@michael-berlin

### CODE REVIEW

**Comment by michael-berlin** [comment]
Priyanka, can you please rebase this branch on the latest master and fix the conflicts?

**Comment by pkulsh** [comment]
Done!

**Comment by michael-berlin** [comment]
As discussed offline, I'm merging this branch now and you can fix forward any comments in future pull requests.

This will unblock other pull requests :)

**Comment by pkulsh** [comment]
Review status: all files reviewed at latest revision, 50 unresolved discussions.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 15 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdbXpge8bagwIHfyAl:-KQfkj0qQ1g2faFnF-VH:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L15)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > outer and inner labels
> 
> Please update this comment.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 38 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdbiinuYf75k5qX4Dv:-KQflWBMniys4NxYl3Tp:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L38)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > The following array
> 
> Comment must be of the form:
> 
> `// YGridLines is used to ...`
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 48 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdbtsDMqKBf2OEnwlw:-KQflaHHdEAZHGSk_dOl:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L48)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > This value
> 
> `// tabletMissing represents ...`
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 51 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdbxy5CC3i8eXjwtG8:-KQfladOmh9-r7sns1z-:b-xbyuyb) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L51)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > This value
> 
> `empty indicates ...`
</details>
Removed this variable as it was unused. 

---

*[go/vt/vtctld/tablet_stats_cache.go, line 237 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdiOSV2E53Pj3oM1kl:-KQflvmaisZ-i_w1DK1w:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L237)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > listOfHeatmaps
> 
> Just `heatmaps` :)
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 239 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdcVcwbmt60OxTOjg1:-KQfnS90Xz8EZmzA_NPN:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L239)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Instead of these temporary variables, you can instantiate the a `heatmap` object:
> 
> `var h heatmap`
> 
> Then you can use the fields of the heatmap directly i.e. `h.YGridLines = append(h.YGridLines, ...)`.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 257 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdd7RTj9zQMlZzAHwn:-KQfnmJK9quRh74MKOBm:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L257)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > in reverse
> 
> This comment must go 2 lines deeper because the for loop itself does not start from the end.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 258 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdffGsPxg1j7klbuPO:-KQfnzO2VzxNoX2SZDoI:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L258)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Can you please add a comment here over what you're iterating i.e. over the rows or the columns of the cell's heatmap data?
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 260 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQderOghOi81nT6nmlu:-KQfo1kTPytVYo9O9Oxc:b-xt42ad) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L260)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > if cellAliases == nil {
> 
> In this case it makes more sense to have the case ` != nil` and the move the next line into the if block.
> 
> Can you please add here a comment as well? It's not clear to me why a cell should have data but no label. Does this really happen? Based on the code coverage it does happen :) I'm curious why.
</details>
In the case that the data is aggregated the Aliases array is null since there's no way to aggregate the aliases into one point. Furthermore, returning null for this case allows me to easily distinguish the two cases (aggregated vs unaggregated) on the front end.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 270 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdg9PMttu1IiUcKGwo:-KQfoWyyBC8JJOT9LeyC:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L270)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> nit: missing period :)
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 271 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdgEKn4sbmtxAwd2_m:-KQfoZBP7BLNF7llk4Yf:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L271)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> See comment above. You don't need these temporary structures if you use the field of a `heatmap` instance directly.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 274 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdgqa31cOEnfh2ohdL:-KQfqPx2NLq_fDThR_zW:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L274)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Add a comment and an example what this code addresses?
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 279 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdgu_AivwogbO45WUJ:-KQfqQE2eZixIIGKYCxT:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L279)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Add a comment with an example here?
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 302 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdeev4swryemm4wCa5:-KQfqoZLxNxNDNb5Ojzb:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L302)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > heatmapData
> 
> Please rename this to `cellData`.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 303 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdejV0TVCrCjmE47Qr:-KQfqphK52rzk4Lt_iui:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L303)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > heatmapTabletAliases
> 
> Please rename this to `cellAliases`.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 358 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdirueJfk0vJ7_RKpH:-KQfrGgeKe5GfSfWHKq9:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L358)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Please add a comment here to describe what this method does.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 362 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdiopeQ2z6YvzQx6_R:-KQfquGfyIE65x9d5Sqg:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L362)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > heatmapData
> 
> Please rename this to `cellData`.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 366 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdih83p4f_fCpQd5OF:-KQfrIp2HMjpoO04Xm88:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L366)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> No need to assign a zero value here.
> 
> Go will do it for you.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 369 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdidsYZj_flFwOR5O1:-KQfrK7ChH5-NsliSJO2:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L369)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> nit: missing period
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 377 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdj4BqfLob5aNDd3Eg:-KQfrM6Fiw1U80-Jz9ZN:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L377)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > groups
> 
> typo: group
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 378 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdjDOX0Wo03xRJC31_:-KQfrZA8cEzOC1N-1KFL:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L378)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > metricFunc(tablet)
> 
> You're calling the method multiple times. Please use a variable to store the return value.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 399 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdjlYWnFUNpw5anIbr:-KQfruzNGY1GjTCxblr3:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L399)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> I think this looks nicer/more Go idiomatic:
> 
> ```go
> cellLabel := yLabel{
>   CellLabel: label{Name: cell, Rowspan: 1},
> }
> ```
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 417 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdkt0lz6KF9BjiQ2rK:-KQfsCrsHXimYuCO5Oue:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L417)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > tabletHealthy
> 
> You can change this to `float64(tabletHealthy)`. This way you can avoid the typecast at the return at the end of the function.
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 418 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdk4jc2BXnwJIx-B5f:-KQfsD8x62XbB5oYfREL:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L418)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> "an health" instead of "a health"?
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 425 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdkMoztIYtuV34vKMN:-KQfsjsQlGIbZTmsL8vs:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L425)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > if health < tabletDegraded {
> 
> This can be removed because it never comes true?
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 426 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdkQfdscXx4H8U6UJI:-KQfsrrm-HmO_urGzd1w:bpkp7xv) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L426)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > tabletDegraded
> 
> Based on the code below, the degraded tablet can be considered as healthy if its lag is low enough?
> 
> Maybe just return here?
> 
> The same applies for the other statements below as well.
> 
> I think it's fine to always return degraded or unhealthy if one of the conditions is met.
</details>
My thinking was to handle the case where one condition may make the tablet degraded but another one down the road would have made it unhealthy.  For example, if there was a last error and the lag is over 5 mins- then the tablet has been returned as degraded as set by the last error check but should have been set to unhealthy after the lag check.  I have changed it for now to return anytime the tablet is degraded or unhealthy.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 431 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdlfXElJfXZ8ZqyXed:-KQftlncdZOB-_OV7BAO:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L431)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> You can write this as a switch expression:
> 
> ```go
> switch lag := stats.Stats.SecondsBehindMaster {
> case lag >= lagThresholdUnhealthy:
>   return tabletUnhealthy
> case lag >= lagThresholdDegraded:
>   return tabletDegraded
> }
> ```
</details>
Done.

---

*[go/vt/vtctld/tablet_stats_cache.go, line 436 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdm3KfotW0MvVpmtlW:-KQftmyWqGtYTFi0Jqcu:b-3lp5l8) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L436)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> I think this branch would have never been executed because `< lagThresholdDegraded` would have been true as well?
> 
> See my switch example above how this can be solved by approaching from the max to the min of the range.
</details>
I think you're right. I am sorry that I didn't realize that before!

---

*[go/vt/vtctld/tablet_stats_cache.go, line 445 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdmM8DWyr4q-NDjOiA:-KQfsYFx_C2V-RlMp8zh:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/go/vt/vtctld/tablet_stats_cache.go#L445)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Note: No need to include `== true`.
> 
> Based on my comment above, you can simplify this to the case where we're not serving and return degraded then.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 18 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdqYJIj93cyAlQhxob:-KQfvWUApZQgM534vtgK:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L18)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > <tr [ngStyle]="{'height': getRowHeight()+'px'}">
> 
> I feel like the best way to indent these lines is by the following guide lines:
> 
> - make sure that HTML is always aligned i.e. this `<tr>` should have the same indentation as the ones above
> - start the `<template>` elements at zero indentation and indent them if you nest them (like you do two lines above). You'll end up with different indentations between the regular HTML elements and the template elements. I think that's fine.
> 
> Example:
> ```html
> <template ...
>   <template ...
> 
>   <tr>...
>     <td></td>
>   </tr>
> 
>   </template
> </template>
> ```
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 19 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdp3Aiu7-te2licnau:-KQfvZHuIJtVkzTV_dmB:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L19)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> >  <td  [
> 
> Double space. Remove one.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 22 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdpTuXjOwBhnE35UoG:-KQfweuoFI6tXNL_d0wv:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L22)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Add a comment here why this is necessary.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 26 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdq3I49jhTDyszx3Ee:-KQfwsrQ2ZqimflogxBP:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L26)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > nestedLabel
> 
> Name this `typeLabel` instead? This will be easier to understand then.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 28 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdrHQWyjCcn6xSjet4:-KQfz9HZloScn7lwaeXK:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L28)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > class="bordered"> {{label
> 
> Please remove the whitespace between the attribute and the tags (here it's one space).
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 32 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdpvXOxcsxABteNKIc:-KQfzPULdhrm1sE0WcWC:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L32)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> >  <tr 
> 
> Unindent by 1 space to align it with the previous row.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.html, line 40 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdo_9psVqIBb5mAvV7:-KQg-07k4SBOLIyq7vzj:b-ftipkf) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.html#L40)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> optional: This could go on the same line as `<vt-tablet-popup`?
> 
> If other people do it this way as well, I'm fine with the current version.
</details>
I'm not sure what exactly the style is supposed to be. I couldn't find an example in David's code to see what he did. I just moved the first line up!

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 25 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdn_Tyh9HtArNf1xnT:-KQg-MrLYh-GYpYzCUjU:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.ts#L25)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> typo: its
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 70 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdo8CZTpK7wsBK2w2e:-KQg-iEYsQLnX9dafMVu:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.ts#L70)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Add a comment here how this method is used?
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 83 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdoP8_hru5Z6T247c1:-KQg-nTUU-Npt6xI50rQ:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.ts#L83)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Swap these two lines such that xLabels comes before yLabels.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 127 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQds6Y14hbyhUa3AR6h:-KQg06JUWXvCXJiG4Rbi:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.ts#L127)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > x
> > y
> 
> Can you please name these instead? That's `shard` and cell or type?
> 
> Same comment applies below.
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 207 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdt_r2sx2gxwaahpeC:-KQg0oOt886Rhwi04gPh:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/heatmap.component.ts#L207)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Can you please add comments here?
> 
> For example, in which range is the max value in?
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.html, line 21 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQduhkCJV-TZSMzlzcY:-KQg4IjDOuqnvgYyf0ph:bs2vvh2) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/status.component.html#L21)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> optional: I would prefer we do not use `<br/>` and instead more explicit elements if we need whitespace. But I admit I don't know the best practice for this.
</details>
I removed it for now as the overflow setting adds some padding as well. 

---

*[web/vtctld2/src/app/status/status.component.ts, line 26 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQduvYtn1LQpJq6EOwU:-KQg55D39cqUlkLQuTTS:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/status.component.ts#L26)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> typo: its
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 165 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdw-DTEDEOSOUylQ-o:-KQg5bW_Kx61O3DA6Azm:b-n9dq0s) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/status.component.ts#L165)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Looks like you can have this shorter in TypeScript: http://stackoverflow.com/a/19746771
</details>
That's awesome! Thanks for finding that. 

---

*[web/vtctld2/src/app/status/status.component.ts, line 203 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdwpLpxzEbXs-9J4is:-KQg5hLEtd3vdP5ktIa3:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/status.component.ts#L203)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > map
> 
> You should rename this to `heatmap`, right?
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet-popup.component.html, line 13 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdxnJP0eA05GmcwTjR:-KQg6d3OLYeKoqbGYHpR:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/tablet-popup.component.html#L13)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > title!=null
> 
> You can change this to `!title`, right?
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet-popup.component.html, line 56 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdy1UFNq2HT7MYMsrJ:-KQg6de0G9nLh52hfL-C:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/tablet-popup.component.html#L56)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> Remove this commented code please.
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet-popup.component.ts, line 54 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdyHyMOaMs8anaOb1x:-KQg7RJWdcqIoRsjSPTM:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/tablet-popup.component.ts#L54)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> typo: its
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet-popup.component.ts, line 69 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdyuoL9q7Sx6BZhhqX:-KQg7_Aw9yiqYNaXzHQI:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/tablet-popup.component.ts#L69)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > getType
> 
> Note that you have another `getType` function in different file. This is confusing :)
> 
> I suggest to rename this one to something which expresses that you're converting the enum to a string e.g. `typeToString`.
> 
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet-popup.component.ts, line 81 \[r18\]](https://reviewable.io:443/reviews/youtube/vitess/1969#-KQdy_cdTILYsGZSjyS4:-KQg7dAmvdXG9I9hkS2T:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/fb12bc6e7e3701f758e8e291474717df94f7a573/web/vtctld2/src/app/status/tablet-popup.component.ts#L81)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> `// parseUnaggregatedData ...`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1969)*

**Pull request merged**
