### PR TITLE
v3: VSchemaFormal -> proto3

### PR DESCRIPTION
**Pull request by sougou**
@alainjobart

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1708)

### CODE REVIEW

**Comment by alainjobart** [comment]
My main comments are about the field names in the proto, just to be consistent and use full names (column instead of col for instance). I understand it's all over the place, but now is the time to fix it...

I think we can add 'vindex' as a single word, Vindex in camel case. Because vIndex or VIndex don't look too good...

<details><summary><i>Previously, sougou wrote…</i></summary>
> #### v3: VSchemaFormal \-&gt; proto3
> 
> @alainjobart
> 
> 
> 
</details>


---

Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[go/vt/topo/test/vschema.go, line 40 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4vS_tOZychbacbian:-KI4vS_tOZychbacbiao:894212507) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/go/vt/topo/test/vschema.go#L40)):*
> ```Go
> 	}
> 
> 	err = ts.SaveVSchema(ctx, "test_keyspace", &vschemapb.Keyspace{Sharded: true})
> ```

Maybe add a couple things in here, just for kicks? :)

---

*[proto/vschema.proto, line 2 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4tgRsfascMLliC5NM:-KI4tgRsfascMLliC5NN:-750679974) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L2)):*
> ```protobuf
> // This file contains all the types necessary to make
> // RPC calls to Vttablet.
> ```

Cut&Paste comment ;)

Also, please document the individual fields in the proto file a bit better, if you don't mind... This is the place to document all the vindexes and what they do. Very central, and easy to produce an automated doc if we have to...

---

*[proto/vschema.proto, line 17 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4tzVq6wMOq8K7JDij:-KI4tzVq6wMOq8K7JDik:-314260667) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L17)):*
> ```protobuf
> // Vindex is the vindex info for a Keyspace.
> message Vindex {
>   string type = 1;
> ```

Should this be an enum? Then each value of the enum could also contain a bit more explanation of the vindex type, and the possible parameters...

---

*[proto/vschema.proto, line 26 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4x3414EjJIyggc7bv:-KI4x342WawSWVV0KO70:-776129799) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L26)):*
> ```protobuf
>   string type = 1;
>   repeated ColVindex col_vindexes = 2;
>   Autoinc autoinc = 3;
> ```

AutoIncrement auto_increment = 3;   !!

---

*[proto/vschema.proto, line 30 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4ucYEwtB7uYW7p6l7:-KI4ucYEwtB7uYW7p6l8:1535865527) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L30)):*
> ```protobuf
> 
> // ColVindex is used to associate a column to a vindex.
> message ColVindex {
> ```

ColumnVindex

---

*[proto/vschema.proto, line 31 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uJH6hWHVqD9sJkeM:-KI4uJH6hWHVqD9sJkeN:-1701162853) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L31)):*
> ```protobuf
> // ColVindex is used to associate a column to a vindex.
> message ColVindex {
>   string col = 1;
> ```

column

---

*[proto/vschema.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uDY-U04M2y9SMJmE:-KI4uDY-U04M2y9SMJmF:386730780) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L35)):*
> ```protobuf
> }
> 
> // Autoinc is used to designate a column as auto-inc.
> ```

AutoIncrement maybe?

---

*[proto/vschema.proto, line 37 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uMjYwWHfBvppbniY:-KI4uMjYwWHfBvppbniZ:-1701162853) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L37)):*
> ```protobuf
> // Autoinc is used to designate a column as auto-inc.
> message Autoinc {
>   string col = 1;
> ```

column

---

*[proto/vschema.proto, line 38 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uPtBX0JwxsyNl8-b:-KI4uPtBX0JwxsyNl8-c:837336572) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L38)):*
> ```protobuf
> message Autoinc {
>   string col = 1;
>   string sequence = 2;
> ```

Need to document that one...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1708#-:-KI4wUl0HcOx7TtQ-54F:1312891225)*

**Comment by sougou** [comment]
I'll comply with your name change requests. However, for the record, Go likes short names. For example, they named their type as uint instead of unsigned_integer.

<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> My main comments are about the field names in the proto, just to be consistent and use full names (column instead of col for instance). I understand it's all over the place, but now is the time to fix it...
> 
> I think we can add 'vindex' as a single word, Vindex in camel case. Because vIndex or VIndex don't look too good...
</details>


---

Review status: all files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1708#-:-KI5GweoEvU_uAGjXZYO:755659891)*

**Comment by sougou** [comment]
Review status: 24 of 44 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[go/vt/topo/test/vschema.go, line 40 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4vS_tOZychbacbian:-KIBrmgdM03vxM6fLwQT:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/go/vt/topo/test/vschema.go#L40)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> Maybe add a couple things in here, just for kicks? :)
</details>
Done.

---

*[proto/vschema.proto, line 2 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4tgRsfascMLliC5NM:-KIBroRFYfJlv9X_l26K:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L2)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> Cut&Paste comment ;)
> 
> Also, please document the individual fields in the proto file a bit better, if you don't mind... This is the place to document all the vindexes and what they do. Very central, and easy to produce an automated doc if we have to...
</details>
Done.

---

*[proto/vschema.proto, line 17 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4tzVq6wMOq8K7JDij:-KIBZve0cUXmFB3-VwQ7:799034844) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L17)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> Should this be an enum? Then each value of the enum could also contain a bit more explanation of the vindex type, and the possible parameters...
</details>
This got complicated because tests define their own vindexes, and we don't want those to poison the proto.
And we have another problem: enums don't encode or decode well. They degenerate to their numbers, which makes them unreadable. For example, I tried changing Table.Type to an enum. After that, it will not accept:
  "type": "SEQUENCE" (cannot unmarshal string into Go value of type vschema.TableType)
Instead, it only accepts this:
  "type": 1

Is there something obvious that I'm missing?

---

*[proto/vschema.proto, line 26 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4x3414EjJIyggc7bv:-KIBqk_24n05WCZR75iH:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L26)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> AutoIncrement auto_increment = 3;   !!
</details>
Done.

---

*[proto/vschema.proto, line 30 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4ucYEwtB7uYW7p6l7:-KIBqlDJSIS4ciqBB3RI:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L30)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> ColumnVindex
</details>
Done.

---

*[proto/vschema.proto, line 31 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uJH6hWHVqD9sJkeM:-KIBqltX2CK-WElEoL6J:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L31)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> column
</details>
Done.

---

*[proto/vschema.proto, line 35 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uDY-U04M2y9SMJmE:-KIBqmq956vtXV2Jyzzv:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L35)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> AutoIncrement maybe?
</details>
Done.

---

*[proto/vschema.proto, line 37 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uMjYwWHfBvppbniY:-KIBqvmyjizc31itupoA:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L37)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> column
</details>
Done.

---

*[proto/vschema.proto, line 38 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4uPtBX0JwxsyNl8-b:-KIBqwdc3CEH_wyMeibP:-499146009) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L38)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> Need to document that one...
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1708)*

**Comment by alainjobart** [comment]
:lgtm:

<details><summary><i>Previously, sougou wrote…</i></summary>
> I'll comply with your name change requests. However, for the record, Go likes short names. For example, they named their type as uint instead of unsigned_integer.
</details>


---

Reviewed 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[proto/vschema.proto, line 17 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KI4tzVq6wMOq8K7JDij:-KIDlhLRfoDVaztj43P3:-2125459388) ([raw file](https://github.com/youtube/vitess/blob/53e6ff7b349d08df59199b3be6352e22d9569694/proto/vschema.proto#L17)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> This got complicated because tests define their own vindexes, and we don't want those to poison the proto.
> And we have another problem: enums don't encode or decode well. They degenerate to their numbers, which makes them unreadable. For example, I tried changing Table.Type to an enum. After that, it will not accept:
>   "type": "SEQUENCE" (cannot unmarshal string into Go value of type vschema.TableType)
> Instead, it only accepts this:
>   "type": 1
> 
> Is there something obvious that I'm missing?
</details>
No, I agree, let's keep it string then.

---

*[proto/vschema.proto, line 21 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1708#-KIDllkL5MHTXDsJFpGB:-KIDllkL5MHTXDsJFpGC:-1515223092) ([raw file](https://github.com/youtube/vitess/blob/74295d38a0281cdb8368bd293337acf8676f4900/proto/vschema.proto#L21)):*
> ```protobuf
>   string type = 1;
>   // params is a map of attribute value pairs
>   // that must be dedfined as required by the
> ```

dedfined

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1708#-:-KIDm4SEbkBaX0FLvGJH:1417088721)*

**Pull request merged**
