### PR TITLE
Removing an extra channel in server RPC logs.

### PR DESCRIPTION
**Pull request by alainjobart**
Instead of using a channel logger plus a go routine to
get the data out, use a callback logger, and write data
to the stream directly. Simpler all around.

@enisoc @michael-berlin

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1586)

### CODE REVIEW

**Comment by alainjobart** [comment]
(by the way, ChannelLogger can be removed soon, it is used internally in one place, I'll fix that first, then remove it entirely.)

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/tabletmanager/grpctmserver/server.go, line 452 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1586#-KDQS0Mc4smkYJ8urmDS:-KDQS0MdOaksK6aISRFV:322180673) ([raw file](https://github.com/youtube/vitess/blob/147c090ddcc3b117a6c2d61ac92f72ae8af21548/go/vt/tabletmanager/grpctmserver/server.go#L452)):*
This comment isn't needed anymore since logging is now synchronous.

---

*[go/vt/vtctl/grpcvtctlserver/server.go, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1586#-KDQS8quHPmVbr2LJb6U:-KDQS8quHPmVbr2LJb6V:322180673) ([raw file](https://github.com/youtube/vitess/blob/147c090ddcc3b117a6c2d61ac92f72ae8af21548/go/vt/vtctl/grpcvtctlserver/server.go#L42)):*
This comment isn't needed anymore since logging is now synchronous.

---

*[go/vt/worker/grpcvtworkerserver/server.go, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1586#-KDQSPFClyVtZbs1JRc-:-KDQSPFDCvFYKVwE-LTJ:322180673) ([raw file](https://github.com/youtube/vitess/blob/147c090ddcc3b117a6c2d61ac92f72ae8af21548/go/vt/worker/grpcvtworkerserver/server.go#L42)):*
This comment isn't needed anymore since logging is now synchronous.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1586#-:-KDQSXCJKC--YNtKvTeH:1417088721)*

**Comment by michael-berlin** [comment]
LGTM after Anthony's comments are adressed.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1586#-:-KDTSx8d4hhAyORuCCFR:-1406183033)*

**Comment by alainjobart** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/tabletmanager/grpctmserver/server.go, line 452 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1586#-KDQS0Mc4smkYJ8urmDS:-KDTpgQcX1NWX1q1DLd8:-499146009) ([raw file](https://github.com/youtube/vitess/blob/147c090ddcc3b117a6c2d61ac92f72ae8af21548/go/vt/tabletmanager/grpctmserver/server.go#L452)):*
Done.

---

*[go/vt/vtctl/grpcvtctlserver/server.go, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1586#-KDQS8quHPmVbr2LJb6U:-KDTphXYtHNf9728u0OR:-499146009) ([raw file](https://github.com/youtube/vitess/blob/147c090ddcc3b117a6c2d61ac92f72ae8af21548/go/vt/vtctl/grpcvtctlserver/server.go#L42)):*
Done.

---

*[go/vt/worker/grpcvtworkerserver/server.go, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1586#-KDQSPFClyVtZbs1JRc-:-KDTphxanzwz5GrEjF14:-499146009) ([raw file](https://github.com/youtube/vitess/blob/147c090ddcc3b117a6c2d61ac92f72ae8af21548/go/vt/worker/grpcvtworkerserver/server.go#L42)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1586)*

**Pull request merged**
