### PR TITLE
Stream2

### PR DESCRIPTION
**Pull request by dumbunny**
Keep stream cursors from corrupting transactions.

### CODE REVIEW

**Comment by alainjobart** [comment]
I don't think creating a base class for bson tablet connection, v3 vtgate connection and v2vtgate connection is the way to go here, as we are retiring bson, tablet connection and v3 connection... I'd rather we retire the stuff we don't use first, then refactor?

**Comment by dumbunny** [comment]
I can live with that.

**Comment by alainjobart** [comment]
Should the bug fix be done though?

**Comment by dumbunny** [comment]
I'm going to restrict it to the vtgatev2.py code.

**Pull request closed without merging**
