### PR TITLE
Fixed some lint issues, misspellings, and unused variables.

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by sougou** [comment]
Code climate found some issues. Can you fix?

**Comment by bramp** [comment]
Sure, I can take a look. I'll focus on the sqlparser (and related deps) as that's where I've been focusing.

**Comment by bramp** [comment]
Oh apologises, I misread your last comment. I thought you were asking for me to look at more general code climate issues... Well I went ahead and fixed up some issues elsewhere (and the ones in this pull request) :)

**Comment by bramp** [comment]
I thought as much, so I kept it as a separate commit. Happy to drop if decided.

**Comment by alainjobart** [comment]
Yeah sorry, the KeyRange naming has to stay that way, the core concept is really KeyRange. It happens to be in the key package, so it triggers the warnings... We could rename the package instead... ;)

**Comment by bramp** [comment]
Ok, dropped the KeyRange changes.

**Comment by alainjobart** [comment]
LGTM

**Pull request merged**
