### PR TITLE
Simplify the process to publish the website.

### PR DESCRIPTION
**Pull request by michael-berlin**
Summary:
- Changed scripts to serve vitess.io out of the "docs/" directory (master branch) instead of the gh-pages branch.
- Unpublished "doc/" directory. See first commit message for details.

I recommend to review the changes per commit.

### CODE REVIEW

**Comment by enisoc** [comment]
I checked out your branch and I still see some references to `vitess.io/doc/`:

```
docs/sitemap.xml:22:    <loc>http://vitess.io/doc/</loc>
doc/VTGateV3Features.md:19:The [V3 design](http://vitess.io/doc/V3VindexDesign/) is quite elaborate.
doc/TopologyService.md:104:the [VTGate V3](http://vitess.io/doc/VTGateV3Features/) API.
doc/GettingStartedKubernetes.md:221:    [global cell](http://vitess.io/doc/TopologyService/#global-vs
-local),
```

**Comment by michael-berlin** [comment]
Good point Anthony. I've only searched for *.md, but not for vitess.io/doc/* URLs.

I've changed these links to the new `/user-guide/topology-service.html` page or the plain GitHub pages e.g. https://github.com/youtube/vitess/blob/master/doc/V3VindexDesign.md.

I've also removed the file `vitess.io/doc/index.md` and with that the entry from the sitemap is gone.

**Comment by alainjobart** [comment]
I hate to say this, but I don't like the 'docs' name for the toplevel directory of the web site. I know we already have vitess.io directory, which is the base of the published site, so maybe we can do something else:
- /vitess.io should be the final web site (what you have as 'docs' now)
- what is currently vitess.io could be moved into web/vitess.io, or renamed vitess.io.source / vitess.io.in

other than this major 'detail', I like the spirit of this change :)

**Comment by michael-berlin** [comment]
Alain, I fully agree that the "docs" name is not optimal.

But that's currently the only directory which GitHub supports: https://help.github.com/articles/user-organization-and-project-pages/

They just added this feature in August: https://github.com/blog/2228-simpler-github-pages-publishing

Another thing we could try is to make "docs" a symlink pointing to "vitess.io". Maybe GitHub will correctly interpret that. But in any case, the "docs" entry won't go away with this approach.

I think this is still better than the old gh-pages branch. And I've put a README.md in the docs directory in case somebody on GitHub.com is browsing the directory. You can see here what it looks like: https://github.com/michael-berlin/vitess/tree/cleanup_website_scripts/docs

**Comment by alainjobart** [comment]
LGTM

Oh I didn't realize 'docs' was imposed by github. I withdraw my objection, because then everyone knows what this means.

**Comment by michael-berlin** [comment]
I've changed our GitHub setting to serve vitess.io out of the `docs/` directory and deleted the `gh-pages` branch. It seems to be working :-)

**Pull request merged**
