### PR TITLE
Support more keyword functions

### PR DESCRIPTION
**Pull request by bbeaudreault**
@sougou 

Adds support for timestamp-related functions, such as CURRENT_DATE, LOCAL_TIME, etc. and REPLACE/LEFT. Differentiates between functions that take parenthesis and possibly arguments (keyword_func grammar) vs those that can be used as keywords.

### CODE REVIEW

**Comment by bbeaudreault** [comment]
@sougou since this one was pretty simple, I decided to overload it to also support REPLACE() and LEFT() functions. Will see if there are any others I should add, and also I may fixup FuncExpr a bit to be more flexible (allow Exprs instead of or in addition to SelectExprs)

**Comment by bbeaudreault** [comment]
simplified the grammar, ready for review whenever you have time

**Comment by sougou** [comment]
LGTM
Let me know when you've resolved the conflicts.

**Comment by bbeaudreault** [comment]
@sougou: I fixed the conflicts, and tests are all passing.  Please merge when ready. Thanks for the review!

**Pull request merged**
