### PR TITLE
Few fixes related to vtgate startup.

### PR DESCRIPTION
**Pull request by alainjobart**
Before I change more of the routing code inside vtgate, cleaning up a few things.

* fixing https://github.com/youtube/vitess/issues/3549 as we now error out if vtgate can't reach the topology service.
* waiting for the proper keyspace/shard/tablet type combinations at vtgate startup, instead of a cross product of all possible combinations.
* removing a useless Once() at vtgate Init.

### CODE REVIEW

**Comment by sougou** [comment]
This was added because some tests were crashing. Let's see if they pass now :).

**Comment by alainjobart** [comment]
The PR comment still stands, no way the previous few calls can be called more than once, they register named stats. Unless I'm missing something, this will work. I know, famous last words.

**Comment by alainjobart** [comment]
OK Travis recovered it seems, and now this passes, ready for approval @sougou

**Comment by alainjobart** [comment]
This now also contains a fix for https://github.com/youtube/vitess/issues/3549

**Pull request merged**
