### PR TITLE
Batch

### PR DESCRIPTION
**Pull request by dumbunny**
Fix the BatchVTGateCursor API to be PEP0249 compliant.

### CODE REVIEW

**Comment by sougou** [comment]
Do we need a separate class for this? I think the normal cursor should just implement the executemany and nextset functions.

**Comment by dumbunny** [comment]
I could probably combine them. It means allowing keyspace=None in VTGateCursor.__init__.

**Comment by sougou** [comment]
Ahh. This is V2. Then I think it's fine. My suggestion applies mainly for V3.

**Comment by alainjobart** [comment]
v3 has no batch support anyway yet, does it?
Let's merge v2 and v3 into v2 client soon too.

**Comment by dumbunny** [comment]
Modulo any typos, BatchVTGateCursor has now been merged into VTGateCursor. Still need to support executemany(...keyranges) parameters, though.

**Comment by sougou** [comment]
Excellent! I see that you've also accommodated the multi-sql capability.
LGTM from my side.

**Comment by alainjobart** [comment]
LGTM too!

**Comment by dumbunny** [comment]
Importing shortly. I have some EMD code I want to run by you guys.

**Pull request merged**
