### PR TITLE
replication_reporter: Repair replication even if slave not configured.

### LINKED ISSUE #2162: Former master restarted with existing data doesn't auto-configure as slave
We already support these cases:

* A slave restarted in-place with existing data dir will auto-configure as slave.
* A slave restarted with empty data dir will auto-restore and auto-configure as slave.
* A former master restarted with empty data dir will auto-restore and auto-configure as slave.

But we don't yet support the fourth case:

* A former master restarted in-place with existing data dir.

To support this, one possibility is to configure replication upon vttablet startup if an existing DB is detected and the tablet is a slave type:

https://github.com/youtube/vitess/blob/c18b009e409134419c5c596cf5691a0f87af16e5/go/vt/tabletmanager/restore.go#L72

Another possibility is to evaluate whether it could be safe under some conditions to allow the replication reporter health check to configure replication even if no existing slave status is found:

https://github.com/youtube/vitess/blob/4edf1b231a308db3b6b708d602c25c5ef38d6e54/go/vt/tabletmanager/replication_reporter.go#L39

We'll look more at the possibilities and report back here.

### PR DESCRIPTION
**Pull request by enisoc**
It will still only attempt the repair if the global shard record has a `MasterAlias` specified.

Fixes #2162.

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM
Side note: should we disable InitTablet as master? I think it might still be useful. If we keep it, we should probably keep a test that does it that way...

**Comment by enisoc** [comment]
The tabletmanager test still uses InitTablet as master. I didn't change those because they don't use InitShardMaster. There is also one test case in the reparent test that still uses InitTablet as master.

**Comment by alainjobart** [comment]
OK sounds good then. Is the travis failure for real?

**Comment by enisoc** [comment]
Yes, I missed some tests in the first round of conversions because they had a newline after `init_tablet(`. I just pushed a fix and will wait for it to pass.

**Pull request merged**
