### PR TITLE
refresh vtgate SSL connections on a timer

### PR DESCRIPTION
**Pull request by acharis**
Here we add a jdbc option to refresh the connection if the keystore file has changed.

@harshit-gangal

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, line 177 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyiib7TlyXziP2mDLTd:-Kyiib7TlyXziP2mDLTe:b-joc4ll) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java#L177)):*
> ```Java
>         false);
>     private BooleanConnectionProperty refreshSSLConnectionsOnCertFileModification = new BooleanConnectionProperty(
>         "refreshSSLConnectionsOnKeystoreUpdate",
> ```

I think the property name is too big:
We can just have refreshConnection and give in the description what is does.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, line 179 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyil81y_KWFVapA2UeH:-Kyil81y_KWFVapA2UeI:b7llg4x) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java#L179)):*
> ```Java
>         "refreshSSLConnectionsOnKeystoreUpdate",
>         "When enabled, the driver will monitor for changes to the keystore and truststore files. If any are detected, SSL-enabled connections will be recreated.",
>         true);
> ```

I think we should set this default as false. 
How often does keystore or truststore files is updated?

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 73 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyj-y28J8HMmYjvzyvE:-Kyj-y28J8HMmYjvzyvF:b-njw9b6) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L73)):*
> ```Java
>                         updateVtGateConnHashMap(identifier, hostInfo, connection);
>                     }
>                     if (connection.getUseSSL() && connection.getRefreshSSLConnectionsOnCertFileModification() && vtgateConnRefreshTimer == null) {
> ```

Multiple objects of vtgateConnRefreshTimer would get created as this is not thread safe.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 84 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyijoWSSg9j2CqKN-uE:-KyijoWSSg9j2CqKN-uF:b-nvz0gt) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L84)):*
> ```Java
>                             },
>                             TimeUnit.SECONDS.toMillis(60),
>                             TimeUnit.SECONDS.toMillis(60));
> ```

Instead of setting this to 60sec, we should make it as a property and set default to 60.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 110 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyipwqmz_PP9rCwHVTx:-Kyipwqmz_PP9rCwHVTy:b-jnn50o) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L110)):*
> ```Java
>     }
> 
>     public static class RefreshableVTGateConn extends VTGateConnection {
> ```

This class should be moved to io.vitess.client package.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 122 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyiqgO0Nu-6826zbuY4:-KyiqgO0Nu-6826zbuY5:b-ufomz6) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L122)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>
>         RefreshableVTGateConn(RpcClient client,
>                               VitessJDBCUrl.HostInfo hostInfo,
>                               VitessConnection conn,
>                               String keystorePath,
>                               String truststorePath) {
</details>

This class cannot hold VitessConnection as VTGateConnection is independent of VitessConnection. VitessConnection gets a VTGateConnection from VTGateConnections on the fly while executing a statement. 

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 129 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyikjBIf3r-vF9XJS1J:-KyikjBIf3r-vF9XJS1K:b-lmb7oq) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L129)):*
> ```Java
>             this.truststoreFile = new File(truststorePath);
>             // initial check ensures the mtimes are up-to-date
>             checkKeystoreUpdates();
> ```

The returned value is not used. To ensure initial mtimes are up to date, the returned value needs to be validated.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 178 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyj0FP7S8JrV3BULF9o:-Kyj0FP7S8JrV3BULF9p:b-eyo3dm) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L178)):*
> ```Java
>                     if (existing.checkKeystoreUpdates()) {
>                         updatedCount++;
>                         VTGateConnection old = vtGateConnHashMap.replace(entry.getKey(), getVtGateConn(existing.getHostInfo(), existing.getConn()));
> ```

The replace can happen when a new VitessConnection is created or the logic should be changed to use static ConnectionProperty which should also become part of the identifier.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 180 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyinpOyxzXYqCdxHK1W:-KyinpOyxzXYqCdxHK1X:b1fe8re) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L180)):*
> ```Java
>                         VTGateConnection old = vtGateConnHashMap.replace(entry.getKey(), getVtGateConn(existing.getHostInfo(), existing.getConn()));
>                         try {
>                             Closeables.close(old, true);
> ```

we can directly call old.close() and rather than swallowing exception log it as warn.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, line 177 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyiib7TlyXziP2mDLTd:-Kz-z3LqYdBSeNSTz5lK:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java#L177)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

I think the property name is too big:
We can just have refreshConnection and give in the description what is does.
</blockquote></details>

Done.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, line 179 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyil81y_KWFVapA2UeH:-Kz-z4igYqXxj9Xm5wgK:bkjq7za) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java#L179)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

I think we should set this default as false. 
How often does keystore or truststore files is updated?
</blockquote></details>

in our setup, we use short-lived certificates, so it's fairly often. i've defaulted this to false.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java, line 179 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyil81y_KWFVapA2UeH:-Kz-zc0ujSW6s96XaZmp:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/ConnectionProperties.java#L179)):*
<details><summary><i>Previously, acharis (Alex Charis) wrote…</i></summary><blockquote>

in our setup, we use short-lived certificates, so it's fairly often. i've defaulted this to false.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 84 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyijoWSSg9j2CqKN-uE:-Kz0IgwGlrACH0C_unrE:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L84)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

Instead of setting this to 60sec, we should make it as a property and set default to 60.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 110 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyipwqmz_PP9rCwHVTx:-Kz0LYPMVoSShhfve_b7:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L110)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

This class should be moved to io.vitess.client package.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 180 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyinpOyxzXYqCdxHK1W:-Kz0NUZFSp6hwwry6zOz:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L180)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

we can directly call old.close() and rather than swallowing exception log it as warn.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 73 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyj-y28J8HMmYjvzyvE:-Kz0PE1BvIjaDM3Pc_7h:bgl7c9z) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L73)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

Multiple objects of vtgateConnRefreshTimer would get created as this is not thread safe.
</blockquote></details>

it's in the synchronized block

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 122 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyiqgO0Nu-6826zbuY4:-Kz0QDKaN3Pf0BtUyfPy:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L122)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

>         RefreshableVTGateConn(RpcClient client,
>                               VitessJDBCUrl.HostInfo hostInfo,
>                               VitessConnection conn,
>                               String keystorePath,
>                               String truststorePath) {

This class cannot hold VitessConnection as VTGateConnection is independent of VitessConnection. VitessConnection gets a VTGateConnection from VTGateConnections on the fly while executing a statement. 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 129 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-KyikjBIf3r-vF9XJS1J:-Kz0YDHj5NMcLQH2GzsF:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L129)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

The returned value is not used. To ensure initial mtimes are up to date, the returned value needs to be validated.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by acharis** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 178 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyj0FP7S8JrV3BULF9o:-Kz1SYa3u7TAv_7JJJxV:b-vqzaik) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L178)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

The replace can happen when a new VitessConnection is created or the logic should be changed to use static ConnectionProperty which should also become part of the identifier.
</blockquote></details>

i really don't know what you're saying here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by harshit-gangal** [comment]
Reviewed 3 of 4 files at r2.
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 73 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyj-y28J8HMmYjvzyvE:-KzKTcmd3q3W0xHBkF7h:b-bi9ofc) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L73)):*
<details><summary><i>Previously, acharis (Alex Charis) wrote…</i></summary><blockquote>

it's in the synchronized block
</blockquote></details>

my bad.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java, line 178 at r1](https://reviewable.io:443/reviews/youtube/vitess/3357#-Kyj0FP7S8JrV3BULF9o:-KzKUN-9uCO2qQiMk0UA:b-6ntm5e) ([raw file](https://github.com/youtube/vitess/blob/3996539129214b7099179441b13756a06862d6f2/java/jdbc/src/main/java/io/vitess/jdbc/VitessVTGateManager.java#L178)):*
<details><summary><i>Previously, acharis (Alex Charis) wrote…</i></summary><blockquote>

i really don't know what you're saying here
</blockquote></details>

I mean't, here you are interested in connection property rather than the connection object itself. Connection object (VitessConnection) are short lived but the property is the one which will be same while creating new VitessConnection. So, replace call with connection object does not seems right. But, if it complicated to change the logic to use ConnectionProperty rather than connection. I am ok to keep it as is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357)*

**Comment by harshit-gangal** [comment]
:lgtm:

---

Reviewed 1 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3357#-:-L0gnI7nudGbrattKNoR:bnfp4nl)*

**Pull request merged**
