### PR TITLE
Replication

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @aaijazi 
This fixes the bad states we've been seeing, both for resharding and in steady state. With a lot more unit tests.

### CODE REVIEW

**Comment by enisoc** [comment]
Some general comments:

1) The healthcheck now runs through two code paths that enable/disable queryservice: runHealthCheck and changeCallback. It's harder now to reason about what's ultimately going to happen. And there's a chance they might disagree since part of the logic for "should queryservice be running?" is duplicated in both places.

2) In runHealthCheck, we call IsServing before allow/disallowQueries, but in changeCallback we don't. We should be consistent. Actually it looks like allow/dissalowQueries are idempotent at the SqlQuery level:

https://github.com/youtube/vitess/blob/replication/go/vt/tabletserver/sqlquery.go#L111

**Comment by alainjobart** [comment]
For 1) I agree, this needs to be refactored a bit. Maybe in a different change though.

For 2), the check to see if it's already running was added recently by Sugu, that why I checked at some point. I agree I don't need it any more, will remove that.

**Comment by alainjobart** [comment]
Actually, for 2), we always check to see if it's running before starting it. Also, the logic is a tiny bit different if it not already running (like remembering the error, or the check for db name), so I don't think I want to change that code. That just leaves 1), I'll see what I can do, but I should probably merge this in first, if you agree.

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
