### PR TITLE
Refactoring options for vttest local cluster.

### PR DESCRIPTION
**Pull request by alainjobart**
Using the same style as gRPC Dial options, for instance.

@erzel I think this works better, more code in the library, but argument passing in the tests is much better.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1702)

### CODE REVIEW

**Comment by alainjobart** [comment]
@sougou FYI, that refactored the 'MySQL only' part of it, which you implemented...

**Comment by erzel** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/vt/vttest/local_cluster.go, line 41 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-WyUgZQwf12CGqBd2:-KI-WyUgZQwf12CGqBd3:-933396178) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L41)):*
> ```Go
> type VitessOption struct {
> 	beforeRun func(*Handle) error
> 	afterRun  func()
> ```

Can you add a comment that clarifies that afterRun is executed after the process is executed not after it terminates.

---

*[go/vt/vttest/local_cluster.go, line 57 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-UUyTsIcow_Tmfe0K:-KI-UUyTsIcow_Tmfe0L:-229701357) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L57)):*
> ```Go
> 
> // SchemaDirectory is used to specify a directory to read schema from.
> // It conflicts with Schema / MySQLOnly.
> ```

Maybe explain better what you mean by 'conflicts'?

---

*[go/vt/vttest/local_cluster.go, line 82 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-UJrFcchJzYbaAXB7:-KI-UJrFcchJzYbaAXB8:-147974918) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L82)):*
> ```Go
> // MySQLOnly is used to launch only a mysqld instance, with the specified db name.
> // Use it before Schema option.
> // It is incompativle with the Topology option.
> ```

s/incompativle/incompatible

---

*[go/vt/vttest/local_cluster.go, line 201 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-WmtkuhRXT4m0Belq:-KI-WmtkuhRXT4m0Belr:2037424281) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L201)):*
> ```Go
> 
> // MySQLConnParams builds the MySQL connection params.
> // It's valid only if you used LaunchMySQL.
> ```

There's no longer a LaunchMySQL function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1702)*

**Comment by erzel** [comment]
LGTM. Looks better.

<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> @sougou FYI, that refactored the 'MySQL only' part of it, which you implemented...</details>


---

Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1702#-:-KI-YAhVJoAWaSEum3Lh:1783467111)*

**Comment by alainjobart** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/vt/vttest/local_cluster.go, line 41 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-WyUgZQwf12CGqBd2:-KI-ZEK1WNiWV-7TsIEr:-499146009) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L41)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> Can you add a comment that clarifies that afterRun is executed after the process is executed not after it terminates.</details>
Done.

---

*[go/vt/vttest/local_cluster.go, line 57 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-UUyTsIcow_Tmfe0K:-KI-ZZjDgoHncj4D-sL1:-499146009) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L57)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> Maybe explain better what you mean by 'conflicts'?</details>
Done.

---

*[go/vt/vttest/local_cluster.go, line 82 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-UJrFcchJzYbaAXB7:-KI-Z_O2USB7Y7aVO3bT:-499146009) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L82)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> s/incompativle/incompatible</details>
Done.

---

*[go/vt/vttest/local_cluster.go, line 201 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1702#-KI-WmtkuhRXT4m0Belq:-KI-ZmRYudfV8BRXOO7E:-499146009) ([raw file](https://github.com/youtube/vitess/blob/7196ce6547389b5bd4531ab59aa20110de60fdde/go/vt/vttest/local_cluster.go#L201)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> There's no longer a LaunchMySQL function.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1702)*

**Pull request merged**
