### PR TITLE
Add missing escaping for identifiers

### PR DESCRIPTION
**Pull request by janneku**

### CODE REVIEW

**Comment by sougou** [comment]
Looks good. Tagging @demmer for a second look.

**Comment by demmer** [comment]
From the diffs it looks like this removed all the escaping from column names which at first glance seems like it could be a problem if the column name conflicts with a reserved keyword. Is that not the case?

**Comment by michael-berlin** [comment]
I was wondering about that as well :) Maybe the escaping comes back at a different point and therefore any high level function is not affected?

**Comment by sougou** [comment]
I think this is unsafe. The correct behavior would be to use formatID.

**Comment by janneku** [comment]
As mentioned in the commit messages, Myprintf calls Format interface, which happens to be formatID for for ColIdent and TableIdent.   FormatID uses a list of SQL keywords to decide when to add backticks, hence many identifiers no longer have backticks in the tests.

**Comment by sougou** [comment]
Addressed via #3301.

**Pull request closed without merging**
