### PR TITLE
Add JDBC support for setting transaction isolation on connection

### PR DESCRIPTION
**Pull request by bbeaudreault**
We've been running with this code for a few weeks. I finally got us rebased back on master with @harshit-gangal's v3 code so can upstream this now.

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java, line 308 at r1](https://reviewable.io:443/reviews/youtube/vitess/3232#-KvG4gIE-HC5lOllbKJN:-KvG4gIE-HC5lOllbKJO:bplc68t) ([raw file](https://github.com/youtube/vitess/blob/32dc0b78a2bd179119c993485b9ff40163733d01/java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java#L308)):*
> ```Java
>     public int getTransactionIsolation() throws SQLException {
>         checkOpen();
>         switch (this.vtSession.getSession().getOptions().getTransactionIsolation()) {
> ```

instead of getting transactionIsolation in nested way. Add a method in VTSession class.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java, line 341 at r1](https://reviewable.io:443/reviews/youtube/vitess/3232#-KvG5z1mJLr-samFecCI:-KvG5z1mJLr-samFecCJ:bgtm1hj) ([raw file](https://github.com/youtube/vitess/blob/32dc0b78a2bd179119c993485b9ff40163733d01/java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java#L341)):*
> ```Java
> 
>         Query.ExecuteOptions.TransactionIsolation isolation;
>         switch (level) {
> ```

In connection metadata, there is a method supportsTransactionIsolationLevel(int level). Check this if the isolation level is supported or not. Then set the isolation level.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java, line 358 at r1](https://reviewable.io:443/reviews/youtube/vitess/3232#-KvG6R1T5A2dz-F5JsU1:-KvG6R1T5A2dz-F5JsU2:b2nd4hg) ([raw file](https://github.com/youtube/vitess/blob/32dc0b78a2bd179119c993485b9ff40163733d01/java/jdbc/src/main/java/io/vitess/jdbc/VitessConnection.java#L358)):*
> ```Java
>         }
>         Vtgate.Session session = this.vtSession.getSession();
>         this.vtSession.setSession(session.toBuilder()
> ```

same comment. Create a method in VTSession to set Isolation level.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3232)*

**Comment by bbeaudreault** [comment]
@acharis is going to take this over for me. Requested fixes sound good.

**Comment by acharis** [comment]
there is already a call to supportsTransactionIsolationLevel

**Comment by harshit-gangal** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3232#-:-KxkM6YjTqccy0QlRZa0:bnfp4nl)*

**Comment by sougou** [comment]
@acharis Can you resolve merge conflicts?

**Pull request merged**
