### PR TITLE
Vtgate refactors.

### PR DESCRIPTION
**Pull request by alainjobart**
Starting to implement pieces of doc/TabletRouting.md.

The first part here is to create a srvtopo module that can contain the new logic.

### CODE REVIEW

**Comment by alainjobart** [comment]
@sougou I think this is a good stand-alone PR now, ready for review. We can talk about the next steps.

**Comment by alainjobart** [comment]
@demmer I had missed the work you were doing in the related areas, but I think it's somewhat orthogonal. I like your VSchemaManager, it's a good way to group all the related VSchema functions.

My srvtopo package cannot contain the VSchemaManager, as I don't really want it to depend on vtgate/vindexes. So it stops at the proto layer (vschemapb.SrvVSchema), and vtgate needs to do the rest. If anything, I think this change will simplify a chunk of your work, just register the VSchemaManager as the listener of the WatchSrvVSchema.

**Comment by alainjobart** [comment]
@demmer I missed one part, on adding new methods to SrvTopoServer to save the VSchema. I think this feels a bit out of place there. Instead, how about using the *topo.Server for this purpose? So just changing NewResolver to also take the *topo.Server, save it in the Resolver object, and use that guy to change the VSchema. I think that's more in line with the rest.

**Comment by demmer** [comment]
@alainjobart I considered that as well and frankly that was what I was looking for some guidance / opinions on...

From my read of the code, the narrower SrvTopoServer interface seemed to be intended to describe the methods called from the vtgate tier as opposed to the vtctld tier. As such it seemed better to add the requisite methods to that interface as opposed to passing the full topo.Server all the way down.

As a concrete consequence of this, the sandboxTopo doesn't implement the full topo.Server contract, and if we went with this approach we would have to either make it do that, or change the vtgate tests so it uses the memorytopo.

I'm happy to go either way here but am curious to hear your thoughts.

**Comment by alainjobart** [comment]
I see the SrvTopoServer as different from topo.Server now: it's the interface you use for serving queries. It should be read-only, and just provide a useful view of the topo (and maybe cache it).

So maybe just forward the *topo.Server inside NewResolver to the VSchemaManager, and Resolver can just hang on to the SrvTopoServer...

**Comment by demmer** [comment]
OK let me think about that - another option would be to add an new interface (e.g. `SrvTopoVSchemaOps`) which has these methods to make it clearer what's going on.

**Pull request merged**
