### PR TITLE
Adds support for common SET commands from sql clients

### PR DESCRIPTION
**Pull request by bbeaudreault**
Improvements from testing DataGrip, a popular SQL client from JetBrains/Intellij, against the mysql protocol plugin. It uses mysql-connector-j but also sends these commands at startup and as part of queries.

Allows more than just nil for character_set_results.
Allows net_write_timeout and `set names`/`set charset`/`set character set` as passthrough/no-op.
Warns on ignored SET commands, and increments Warnings counter.

Includes a new feature: Allow `SET sql_select_limit = [N | DEFAULT]` where N is an int64. This utilizes the existing `#maxLimit` code to set an implicit limit to all select queries if the requested limit is less than the max row counts.

### CODE REVIEW

**Comment by sougou** [comment]
Nice work!
Some tests seem to be failing (possibly because something is crashing from run_local_database). Let me know if you have trouble narrowing down. I can try to to patch it in and troubleshoot.

**Comment by bbeaudreault** [comment]
@sougou any chance you can take a look at the test failure? i cant run these tests locally, and i cant really tell what is just travis being travis, and what's real. and for what's real, what's wrong

**Comment by sougou** [comment]
The  symptoms hint at a crashing binary. But the tests are passing on my local box for me also. I've kicked off another run to see what we get.

**Comment by sougou** [comment]
These failed again, and the failures are different enough that I think there may be a real underlying problem. I'll try to spend more time to get to the root cause.

**Comment by sougou** [comment]
Can you address the merge conflicts? I'm secretly hoping the tests may pass after that.

**Comment by sougou** [comment]
Ok. I've found the problem. VTCombo is crashing because on `NewCounters("Warning"...` because vttablet also creates that variable.
I was able to reproduce it with docker, but I don't know why it passes as a non-docker test. It should have crashed...

In any case, this is a real issue to be addressed. This may sound ugly, but we may need to rename that to `VTGateWarnings`.

**Comment by bbeaudreault** [comment]
Ah, good find, sorry about that! I'll rename to VTGateWarnings.

**Comment by sougou** [comment]
LGTM

**Pull request merged**
