### PR TITLE
Multi row insert

### PR DESCRIPTION
**Pull request by harshit-gangal**
Currently work in progress.

To Change and Support:

- Currently separated by different OpCode, but will merge with InsertSharded
- Only support same keyspace id insert in multi-row.
- Needs to validate Auto-Inc behaviour
- Needs to validate non-unique colVindexes
- Run existing tests and write more Test Cases

PS: This pull request is to get initial code review comments.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1843)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
PTAL at this PR now.

**Comment by sougou** [comment]
Looks good overall. Lots of nitpick comments :).
Can you also run the tests with coverage turned on to make sure all code paths are covered?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 322 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZyH9LtFkrxwr8wQcd:-KMZyH9MhAfEshu83JOq:-1530068861) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/router.go#L322)):*
> ```Go
> 	var ks, shard string
> 	inputs := route.Values.([]interface{})
> 	insertIds := make([]int64, len(inputs))
> ```

It looks like you need only the first insert id.

---

*[go/vt/vtgate/router.go, line 324 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZglBZtU2fsZQkixXe:-KMZglBZtU2fsZQkixXf:-1105315797) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/router.go#L324)):*
> ```Go
> 	insertIds := make([]int64, len(inputs))
> 	for rowNum, input := range inputs {
> 		insertid, err := rtr.handleGenerate(vcursor, route.Generate, rowNum)
> ```

We'll need to extend the sequence feature to generate ids in one round trip.

---

*[go/vt/vtgate/router.go, line 340 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZkRU7hSBHrMLrVzk7:-KMZkRU7hSBHrMLrVzk8:1179412130) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/router.go#L340)):*
> ```Go
> 		if rowNum == 0 {
> 			firstKsid = ksid
> 		} else if bytes.Compare(firstKsid, ksid) != 0 {
> ```

The correct way to do this is by using the Verify function like handleNonPrimary does. You could even consider calling handlePrimary for the first value and handleNonPrimary for all subsequent values.
The difference in behavior is that handleNonPrimary will back-compute a value if one is not supplied. That level of smartness may or may not be desirable. But it may be worth it for code reuse.
We've been talking about deprecating the back-compute feature anyways.

---

*[go/vt/vtgate/router.go, line 344 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KM_4z04Rs2lodssjpuI:-KM_4z04Rs2lodssjpuJ:1862494386) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/router.go#L344)):*
> ```Go
> 		}
> 
> 		ks, shard, err = rtr.getRouting(vcursor.ctx, route.Keyspace.Name, vcursor.tabletType, ksid)
> ```

This should be done only once for rowNum==0 right?

---

*[go/vt/vtgate/router_dml_test.go, line 5 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KM_5xsFKbWrjOpTlqPw:-KM_5xsFKbWrjOpTlqPx:-1454923800) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/router_dml_test.go#L5)):*
> ```Go
> // license that can be found in the LICENSE file.
> 
> package vtgate
> ```

We'll need some test cases:
1. Multi-row insert  (success)
2. Multi-row insert (failure, different ksids)
3. Multi-row insert with auto-inc.

---

*[go/vt/vtgate/planbuilder/insert.go, line 59 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZtp8lpC9xzkkDi_km:-KMZtp8lpC9xzkkDi_kn:-954086098) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/planbuilder/insert.go#L59)):*
> ```Go
> 	}
> 	colVindexes := route.Table.ColumnVindexes
> 	routeValues := make([]interface{}, 0, len(values))
> ```

Do you remember why we chose this over [][]interface{}?

---

*[go/vt/vtgate/planbuilder/insert.go, line 61 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZx7znWT76VXAAwpHQ:-KMZx7znWT76VXAAwpHR:-1640994663) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/planbuilder/insert.go#L61)):*
> ```Go
> 	routeValues := make([]interface{}, 0, len(values))
> 	autoIncColInsert := false
> 	indexColInsert := make([]bool, len(colVindexes))
> ```

I don't see this value being used anywhere. Did you add it for troubleshooting?

---

*[go/vt/vtgate/planbuilder/insert.go, line 63 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZuWUh07yXfsCn1WAR:-KMZuWUh07yXfsCn1WAS:-1757593876) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/planbuilder/insert.go#L63)):*
> ```Go
> 	indexColInsert := make([]bool, len(colVindexes))
> 	for rowNum := 0; rowNum < len(values); rowNum++ {
> 		value := make([]interface{}, 0, len(colVindexes))
> ```

This should be values, or rowValues.

---

*[go/vt/vtgate/planbuilder/insert.go, line 65 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZud8veb_7FIia2LCS:-KMZud8wecskEq_V0GTb:-985660825) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/planbuilder/insert.go#L65)):*
> ```Go
> 		value := make([]interface{}, 0, len(colVindexes))
> 		for colNum, index := range colVindexes {
> 			if err := buildIndexPlan(ins, index, &value, rowNum, &indexColInsert[colNum]); err != nil {
> ```

This feels non-idiomatic, mainly because Go doesn't encourage side-effects. Maybe it's better to make buildIndexPlan return the necessary values, and update the values here?
Or just expand the function here.
Also, if you iterated columns first, you could move the findOrInsertPos call to the outer loop.

---

*[go/vt/vtgate/planbuilder/insert.go, line 70 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZvt1YDitzTKXOYQyy:-KMZvt1YDitzTKXOYQyz:-431330519) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/planbuilder/insert.go#L70)):*
> ```Go
> 		}
> 		if route.Table.AutoIncrement != nil {
> 			if err := buildAutoIncrementPlan(ins, route.Table.AutoIncrement, route, &value, rowNum, &autoIncColInsert); err != nil {
> ```

Same comment as buildIndexPlan.

---

*[go/vt/vtgate/planbuilder/insert.go, line 133 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZmvMVqXiOA0cOogVQ:-KMZmvMW3ie7xVt3nAlB:-1566476918) ([raw file](https://github.com/youtube/vitess/blob/459e7e0ae70047a617377b9109289f328698351e/go/vt/vtgate/planbuilder/insert.go#L133)):*
> ```Go
> 	}
> 	if *ColInsert {
> 		spew.Dump(ins.Rows)
> ```

This should be removed, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843#-:-KM_6Z3FWcGJi09zXQjg:1379862794)*

**Comment by harshit-gangal** [comment]
Review status: 3 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 322 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZyH9LtFkrxwr8wQcd:-KMcRSTi5GWmh-ng4JZ9:855432527) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/router.go#L322)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> It looks like you need only the first insert id.
</details>
We would need to send all the insertIds(Auto Increment Ids for all rows) back to the client. This will require involved changes. Therefore would need to understand where all changes needs to be done.

---

*[go/vt/vtgate/router.go, line 340 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZkRU7hSBHrMLrVzk7:-KMcThNHDj58w20hm-DD:987296169) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/router.go#L340)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> The correct way to do this is by using the Verify function like handleNonPrimary does. You could even consider calling handlePrimary for the first value and handleNonPrimary for all subsequent values.
> The difference in behavior is that handleNonPrimary will back-compute a value if one is not supplied. That level of smartness may or may not be desirable. But it may be worth it for code reuse.
> We've been talking about deprecating the back-compute feature anyways.
</details>
Currently handleNonPrimary won't be able to handle varchar types primary key.
Once back-compute feature is deprecated than we can reuse this method.

---

*[go/vt/vtgate/router.go, line 344 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KM_4z04Rs2lodssjpuI:-KMcR4XocRWVpqog9AFd:1707450065) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/router.go#L344)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> This should be done only once for rowNum==0 right?
</details>
It was kept inside the loop for extending the logic to send queries to multiple shard.
But as we are not doing it now. So, this can be added later along with the logic.

---

*[go/vt/vtgate/planbuilder/insert.go, line 61 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZx7znWT76VXAAwpHQ:-KMcQBJGZrfz2qZ0PV-L:554156138) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L61)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> I don't see this value being used anywhere. Did you add it for troubleshooting?
</details>
This is used in findOrInsertPos. For the first row the column name is inserted for autoInc but still every time the column needs to be added in values for the subsequent rows. This variable keep track of it.

---

*[go/vt/vtgate/planbuilder/insert.go, line 133 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZmvMVqXiOA0cOogVQ:-KMcQ47PS2PqvrCQ71BL:-499146009) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L133)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> This should be removed, right?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843)*

**Comment by harshit-gangal** [comment]
Review status: 3 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 340 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZkRU7hSBHrMLrVzk7:-KMd3tobSnPQbZkF1042:1621714034) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/router.go#L340)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary>
> Currently handleNonPrimary won't be able to handle varchar types primary key.
> Once back-compute feature is deprecated than we can reuse this method.
> 
</details>
Done. I understood your point of code reusability but, It was done in this way to extend further to support for multi-Ksid and multi-Shard  

---

*[go/vt/vtgate/planbuilder/insert.go, line 59 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZtp8lpC9xzkkDi_km:-KMd4cjjzAfC8mOnuwDL:-244065423) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L59)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> Do you remember why we chose this over [][]interface{}?
</details>
Eventually routeValues is [][]interfaces.
Implementing this way, I find it better in understanding the logic.
Also, I was harder to append in [][] 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843)*

**Comment by harshit-gangal** [comment]
Review status: 1 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 322 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZyH9LtFkrxwr8wQcd:-KMiYVYZCOmrXujdbq3a:-159766906) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/router.go#L322)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary>
> We would need to send all the insertIds(Auto Increment Ids for all rows) back to the client. This will require involved changes. Therefore would need to understand where all changes needs to be done.
</details>
Done as per http://dev.mysql.com/doc/refman/5.7/en/mysql-insert-id.html

---

*[go/vt/vtgate/router_dml_test.go, line 5 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KM_5xsFKbWrjOpTlqPw:-KMiYbJQnBzKkiuqrkpn:-499146009) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/router_dml_test.go#L5)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> We'll need some test cases:
> 1. Multi-row insert  (success)
> 2. Multi-row insert (failure, different ksids)
> 3. Multi-row insert with auto-inc.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843)*

**Comment by harshit-gangal** [comment]
Review status: 1 of 5 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/vt/vtgate/planbuilder/insert.go, line 63 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZuWUh07yXfsCn1WAR:-KMiqNeOtJ1OdaYFeTP7:-499146009) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L63)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> This should be values, or rowValues.
</details>
Done.

---

*[go/vt/vtgate/planbuilder/insert.go, line 65 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZud8veb_7FIia2LCS:-KMiqOHtSYbT48KZ9fiP:-499146009) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L65)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> This feels non-idiomatic, mainly because Go doesn't encourage side-effects. Maybe it's better to make buildIndexPlan return the necessary values, and update the values here?
> Or just expand the function here.
> Also, if you iterated columns first, you could move the findOrInsertPos call to the outer loop.
</details>
Done.

---

*[go/vt/vtgate/planbuilder/insert.go, line 70 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZvt1YDitzTKXOYQyy:-KMiqOxd6u222F4wUvwK:-499146009) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L70)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> Same comment as buildIndexPlan.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843)*

**Comment by sougou** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 321 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMk7WNXaUQvP9gilxnN:-KMk7WNXaUQvP9gilxnO:-1916640702) ([raw file](https://github.com/youtube/vitess/blob/697a90425e466e20a6a5a97f12ef72f896f00197/go/vt/vtgate/router.go#L321)):*
> ```Go
> 	inputs := route.Values.([]interface{})
> 	for rowNum, input := range inputs {
> 		insertid, err := rtr.handleGenerate(vcursor, route.Generate, rowNum)
> ```

I see that you haven't changed this to all or none. I think this is ok for now. The best time to change this to all or none will be when we implement bulk generate.

---

*[go/vt/vtgate/router.go, line 335 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMk-Wym5Xp-ZuFl41VH:-KMk-Wym5Xp-ZuFl41VI:1149083570) ([raw file](https://github.com/youtube/vitess/blob/697a90425e466e20a6a5a97f12ef72f896f00197/go/vt/vtgate/router.go#L335)):*
> ```Go
> 		colNum := 0
> 		if rowNum == 0 {
> 			ksid, err := rtr.handlePrimary(vcursor, keys[0], route.Table.ColumnVindexes[0], vcursor.bindVars, rowNum)
> ```

I think this will be simpler if you moved it inside the loop. Check for rowNum==0  && i==0. If true assign to firstKsid, else use the value in handleNonPrimary.

---

*[go/vt/vtgate/planbuilder/insert.go, line 61 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZx7znWT76VXAAwpHQ:-KMk5Xsg_XGp3QM2RvOu:356985110) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L61)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary>
> This is used in findOrInsertPos. For the first row the column name is inserted for autoInc but still every time the column needs to be added in values for the subsequent rows. This variable keep track of it.
</details>
Ok. The usage is confusing. What if we got rid of these vars, and instead just appended a new value if pos == -1 || pos >= len(row)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843)*

**Comment by harshit-gangal** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 335 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMk-Wym5Xp-ZuFl41VH:-KMwvIm9Ru1pQj9b1TW2:-499146009) ([raw file](https://github.com/youtube/vitess/blob/697a90425e466e20a6a5a97f12ef72f896f00197/go/vt/vtgate/router.go#L335)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> I think this will be simpler if you moved it inside the loop. Check for rowNum==0  && i==0. If true assign to firstKsid, else use the value in handleNonPrimary.
</details>
Done.

---

*[go/vt/vtgate/planbuilder/insert.go, line 61 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1843#-KMZx7znWT76VXAAwpHQ:-KMxTeemrvNvM0bs46R1:-499146009) ([raw file](https://github.com/youtube/vitess/blob/8a81eac1b150b20c1008cb507e29fc50cb6cbed1/go/vt/vtgate/planbuilder/insert.go#L61)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> Ok. The usage is confusing. What if we got rid of these vars, and instead just appended a new value if pos == -1 || pos >= len(row)?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843)*

**Comment by sougou** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1843#-:-KN1xx2-A5hqrFhKa31J:1417088721)*

**Pull request merged**
