### PR TITLE
configure the mysql server port in the kubernetes example

### PR DESCRIPTION
**Pull request by demmer**
I found this useful for testing the new mysql server protocol support.

### CODE REVIEW

**Comment by michael-berlin** [comment]
re: the port value. Could we just go with the MySQL default port of 3306?

@alainjobart if we enable the feature in the template, I suggest that we add a comment that it's in beta. What do you think?

**Comment by alainjobart** [comment]
In travis I used a different port because 3306 was already taken by the mysql package, but yeah, in this case, 3306 would be good.

**Comment by alainjobart** [comment]
Yes, beta comment sounds good too.

**Comment by demmer** [comment]
@michael-berlin @alainjobart Thanks for the feedback! I made the default port 3306 but also made it configurable since for various reasons it's better for us to run on a different port.

I also added the requested comment about it being in beta to vtgate-up.sh -- not sure if you thought it should be somewhere else as well

**Comment by michael-berlin** [comment]
Thanks!

LGTM

Merging now.

**Pull request merged**
