### PR TITLE
Add a counter for new MySQL connections

### PR DESCRIPTION
**Pull request by aaijazi**
@guoliang100 @sougou 

This will help us track the number of used ports in tests.

### CODE REVIEW

**Comment by alainjobart** [comment]
I thought we wanted the number of connected connections, not the number we open?
Each db conn pool may already have the ability to export varz?

**Comment by sougou** [comment]
Are you trying to detect if we're reaching MySQL's connection limit? Then this counter won't be useful, because you have to count closed connections. But as Alain said, we already have this count: https://github.com/youtube/vitess/blob/master/go/vt/dbconnpool/connection_pool.go#L59, but it's per pool.

**Comment by aaijazi** [comment]
No, as I mentioned, I want to track the number of TCP ports used by MySql tests. I'm assuming that tests are short-lived enough here that the ports won't have enough time to be recycled even if a connection closes - so I want total number of connections that were opened, not number connected.

**Comment by sougou** [comment]
LGTM

**Pull request merged**
