### PR TITLE
Support Casbin as the authorization backend.

### PR DESCRIPTION
**Pull request by hsluoyz**
This PR solves: https://github.com/youtube/vitess/issues/2974

### CODE REVIEW

**Comment by hsluoyz** [comment]
I signed it!

**Comment by sougou** [comment]
This certainly looks exciting. I've also been wanting to cleanup the vitess ACL code, which has been overly complex for what it does.

However, since this is a critical feature for YouTube, we need to cross a few hurdles:
1. Ensure that it has the same functionality as before.
2. Make sure that the code can be imported and plugged in with the internal ACL framework.
3. Make sure that this will not cause performance regressions.

I'll need to learn how casbin works and make a case for it internally. I'll try to find time to do this. Things may be a bit slow as I'm also traveling this month.

**Comment by sougou** [comment]
I'll be closing this PR soon. We know this needs to be done, and it's captured here #3494.

**Comment by hsluoyz** [comment]
Hi. Is there any decision about the Casbin integration? I closed the issue by mistake days ago. I have reopened the issue to wait for the decision.

**Comment by sougou** [comment]
I've added my comments to the issue. Closing this as decided.

**Pull request closed without merging**
