### PR TITLE
Fix parsing of actions when updating Node in workflow UI.

### PR DESCRIPTION
**Pull request by pivanof**
It looks like something has changed recently and now when WorkflowManager
encodes Node into json it behaves similar to proto3: when 'state' and 'style'
in an action have enum value equal to 0, it's getting omitted from the resulting
json. That caused the javascript code to skip adding the Action object to the
Node. I'm fixing the javascript to account for that and consider missing 'state'
and 'style' as being equal to 0.

### CODE REVIEW

**Comment by michael-berlin** [comment]
We should fix this differently in a couple of ways:

- the zero value of an enum should be `<enum>_UNKNOWN`. In that case, it would be a programming error if the UI sees no field or the zero value
- we can change the JSON to not omit the zero value: https://github.com/youtube/vitess/blob/master/go/vt/workflow/node.go#L119 Therefore we must remove the "omitempty" tag

Once these two things are realized, we can remove these existence checks from the UI (unless they're actually part of the UI). For example, the current UI skips actions without a name? Isn't that a programming error as well?

**Comment by michael-berlin** [comment]
One more note:

The vtctld API endpoints use the "jsonpb" Marshaller for protobuf messages: https://github.com/youtube/vitess/blob/master/go/vt/vtctld/api.go#L87

In that case, we emit fields with zero values as well.

Unfortunately, we cannot use that package for non-protobuf structs. Therefore, it's fine to stick with the default JSON marshaller in the workflow manager. But we should not omit zero fields there as well.

**Comment by alainjobart** [comment]
So I had to omitempty flag set for a few values because the code that updates the UI only does so if the value is set. Looking back, this was a mistake: if a value is changed from non-default to 0, it's omitted in the JSON, so the UI won't update it, and keep the default. Not good.

The only place we should have omitifempty is the array of children nodes for a node, where we don't want to update the node sub-tree, but just the node itself.

I like the 0 value being UNKNOWN and a programming error. Would make more sense.

The only remaining question I have is this: do we want to optimize the UI updates, by only sending fields that have changed? This would have an impact on the go side, where we'd need to  somehow know which fields have changed (the current API could allow that, the Modify function could remember the state before, do a diff, send the diff only). That seems to be a lot of work for not much gain, so I vote not to do the diff, and send the full node every time.

**Comment by michael-berlin** [comment]
+1 on sending the full node

If we do it otherwise, we would need to have an extra field which tells the UI which fields are set and which not.

**Comment by alainjobart** [comment]
On Michael's note: no we wouldn't, then we'd use omitifempty, and use the empty value for not setting the parameters, any other value to set it.

But let's not do that. I'll fix the code next week to change the enums, and always assume the fields have values. In the meantime, we can probably submit this PR that fixes a current problem.

**Comment by alainjobart** [comment]
LGTM

**Comment by pivanof** [comment]
I almost started to implement the suggestions... So, Michael, should I implement them or merge this as is?

**Comment by michael-berlin** [comment]
How about merging as is and then creating a new PR for the new changes?

**Comment by pivanof** [comment]
OK. I can do that.

**Pull request merged**
