### PR TITLE
Implemented routing to different views + basic popup template

### PR DESCRIPTION
**Pull request by pkulsh**
@thompsonja 
Implemented routing so that the page changes based on dropdown selections.
Also have a basic popup working upon clicking a tablet.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1957)

### CODE REVIEW

**Comment by pkulsh** [comment]
I changed the code to have it display a separate heatmap component for each keyspace. Also addressed the comments below! 

---

Review status: 7 of 10 files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 72 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPchaIRpJEYOdLD_OV:-KPTdJEEZVPV4e92d6-7:b-4fvl9w) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/heatmap.component.ts#L72)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> The rest of this function from this line below is equivalent (as far as I can tell) to ngAfterViewInit.  I suggest replacing it with a call to ngAfterViewInit instead of duplicating code.
</details>
I removed this method as it was not needed anymore. 

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 112 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPdQmB5-2OISjdzigJ:-KPTimU_J5ksrZubu5rB:b-t3klic) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/heatmap.component.ts#L112)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: spacing around lambda
</details>
According the the ts linter there should be a space to the left and right of the =>.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 129 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPdwtOWemXEuGtNxnn:-KPTgJdYhVeASj_0933n:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/heatmap.component.ts#L129)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> - nit: The reduce functions should be lined up together vertically.
> - I think the lambda syntax is a bit cleaner: reduce((a, b) => a.concat(b))
> - I also think the ternary operator is cleaner for second reduce: reduce((a, b) = a > b ? a : b)
</details>
Done.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 133 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPgJ6R8aORBcebnTaf:-KPTgKVlN-6SkagXSxuN:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/heatmap.component.ts#L133)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> A bit cleaner with a ternary operator:
> let percent = max === 0 ? 1.0 : 1 / max;
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.html, line 13 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPhR9gVs8AacSSGSBX:-KPTgW4y-27qLW3gInJo:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.html#L13)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: extra line
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 34 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPkVE9LCf30wirjda1:-KPTgYu8lag8HPWchSdL:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L34)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> These keys can be inlined.
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 118 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPm5zCe4G_qKn1m-Nh:-KPTgxwc4PIRQCXLMvg3:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L118)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: typo: default
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 127 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPmJDhsbC80krbpjo_:-KPTiwGSVWD3OjEaDpmm:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L127)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: extra space
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 144 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPmkOPqwKZhq9Y_1RV:-KPThUUBOHwtx7gkWx8j:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L144)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> All of these handlers seem to do the same thing, I suggest making a helper function to reduce copy/paste.
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 144 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPmVHl0wEeKHa2c6R5:-KPTix8HgwYlU1rC3V_n:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L144)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: extra space.
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 174 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPmpjrn-7RknAlyMnI:-KPThXyak5lMMhnqDx59:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L174)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: extra space after if and also before null
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 175 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPnUD0us5lORJfh_1l:-KPTizf7sQfavvdBzHJn:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L175)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: I think this is missing a space
</details>
Done.

---

*[web/vtctld2/src/app/status/status.component.ts, line 178 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPnQVkQUb4Ibja4_AH:-KPThsF5dZyHL3eWqsPK:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/status.component.ts#L178)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: fix indentation
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet.component.ts, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPnl78oy2SYr8Z17j_:-KPTi9ChijGqQjtMsvMN:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/tablet.component.ts#L27)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> I think it's fine to skip the temp variable and do push({name: blahblahblah...) directly
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet.component.ts, line 30 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPPnd_J55SurXaeIwdi:-KPTiBWAujiQSytErvE_:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/status/tablet.component.ts#L30)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> nit: Typo (health)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1957#-:-KPTn4D1bMjOV_GUB1bT:bedx07d)*

**Comment by thompsonja** [comment]
LGTM.

We talked offline about how my suggested indentation in status.component.ts got eaten up by reviewable.io formatting, so this lgtm after that change is made.

**Comment by pkulsh** [comment]
Changed!

**Comment by pkulsh** [comment]
Review status: 7 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[web/vtctld2/src/app/api/topology-info.service.ts, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPYbps1NqTnscFOVKlJ:-KPnYeV67vfnmeEWQbHx:b-vj4e1e) ([raw file](https://github.com/youtube/vitess/blob/13502afba3c6428bc9375b0be188594c5095f897/web/vtctld2/src/app/api/topology-info.service.ts#L18)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> I think this would be better named something like getCombinedTopologyInfo or something to that effect.  If in the future another piece of topology info was added, this function name would have to change to getKeyspacesAndCellsAndOtherthing.
</details>
That makes sense! Done.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 34 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPYgLvNXnWjkIO3VZl2:-KPnWbNVC-Jxq8kWpwlt:bfyd5k3) ([raw file](https://github.com/youtube/vitess/blob/7d788669700c644684b9327253500335357027c7/web/vtctld2/src/app/status/heatmap.component.ts#L34)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> I think this could use a brief example of what a yLabel is. Is an example of label "Tablet Type" which contains nestedLabels "Replica" and "Rdonly"?
</details>
The label describes the name of the outer label so cell names. The nested labels describe the inner label so type labels. I have added a comment with an example. 

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 66 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPYcsOA4rZW7u5ceNB6:-KPnWzbqkWydeaRkqh57:bbqrdol) ([raw file](https://github.com/youtube/vitess/blob/7d788669700c644684b9327253500335357027c7/web/vtctld2/src/app/status/heatmap.component.ts#L66)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> Does this work?  I'm surprised you don't need to use (a.Label.Rowspan + b.Label.Rowspan) in the lambda.
</details>
From what I found 'a' describes the previous value of the function so in this case the sum of the label rowspans until label b, while b is the next element in the array. Specifying the 0 means that 'a' starts off with a value of 0.

---

*[web/vtctld2/src/app/status/status.component.ts, line 189 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPYeuKuvVAX7xv0GIGS:-KPnXoQuOZ9A3u6qI8Xw:b-bzjiky) ([raw file](https://github.com/youtube/vitess/blob/7d788669700c644684b9327253500335357027c7/web/vtctld2/src/app/status/status.component.ts#L189)):*
<details><summary><i>Previously, thompsonja-bot (Joshua Thompson) wrote…</i></summary>
> The linter doesn't say anything about this? As an example in python it should look either like:
> 
> this.statusService = this.tabletService.getTabletStats(this.selectedKeyspace,
>                                                                                           this.selectedCell,
>                                                                                           this.selectedType,
>                                                                                           this.selectedMetric)
> with everything lined up, or:
> 
> this.statusService = this.tabletService.getTabletStats(
>     this.selectedKeyspace, this.selectedCell, this.selectedType, this.selectedMetric)
> where the next line is indented 4 spaces. Either way is ok by me.
</details>
The ts linter didn't complain but I changed it according to the second way. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1957)*

**Comment by pkulsh** [comment]
Review status: 7 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[web/vtctld2/src/app/status/heatmap.component.ts, line 66 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KPYcsOA4rZW7u5ceNB6:-KQ1y88SR6m88IOBOZts:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/7d788669700c644684b9327253500335357027c7/web/vtctld2/src/app/status/heatmap.component.ts#L66)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> In that case I suggest to rename `a` and `b` to better clarify this.
> 
> In doubt, just go with what people use in the documentation:
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
> 
> Based on that, I suggest to replace `a` and `b` with `prev` and `cur`.
> 
> Still confusing but at least closer to the documentation.
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet.component.ts, line 26 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KQ1h1zzTYMTByaDl_vB:-KQ20sFz0DXHvJ0ZgPd7:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/1fe60d92717a0dc0ee2f60f9c037c06f358d33db/web/vtctld2/src/app/status/tablet.component.ts#L26)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> optional: Can you just refer to these in the template?
> 
> The indirection via a map is not necessary IMO.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1957)*

**Comment by pkulsh** [comment]
I changed the component ts files so that the imports are all at the app.module level as it should be in rc5. I also renamed the  tablet.component.* files to tablet-popup.component.* as David's recent pull request also had a file called tablet component.  

---

Review status: 6 of 11 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[web/vtctld2/src/app/status/tablet.component.html, line 5 \[r6\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KQ2huokzT5-jDuQNy1W:-KQ457h1nqVGKjkFijHf:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/25053dbb1ea26142a8cff41ecb88db24c2b32b81/web/vtctld2/src/app/status/tablet.component.html#L5)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> > <td class="padded"> Replication Lag </td>
> 
> Let's change all `td` elements as follows:
> 
> - omit the closing tag  (`</td>`) because it's optional for `td`
> - remove the leading whitespace before the text or variable name
> 
> i.e. it should look like this:
> 
> ```html
> <td class="padded">Replication Lag
> ```
> 
> This way it should be almost as readable as your current version but without the extra whitespace around it.
</details>
Done.

---

*[web/vtctld2/src/app/status/tablet.component.ts, line 36 \[r6\]](https://reviewable.io:443/reviews/youtube/vitess/1957#-KQ2hfgNwd5WlJngkjAC:-KQ4-xJBEuEJA4m-pYo-:boafsgg) ([raw file](https://github.com/youtube/vitess/blob/25053dbb1ea26142a8cff41ecb88db24c2b32b81/web/vtctld2/src/app/status/tablet.component.ts#L36)):*
<details><summary><i>Previously, mberlin-bot (Michael Berlin) wrote…</i></summary>
> optional:
> 
> > (typeof this.data.Stats.secondsBehindMaster === 'undefined')
> 
> `== null` does not work here like you have below?
> 
> I would understand if it doesn't. I'm just curious.
</details>
From what I found in typescript a type of undefined means that it doesn't exist or hasn't been set to any value. In this case, it's possible that those fields may not even exist in the strut which is why I need to check whether it's undefined.  On the other hand the lastError field will always be there (since it's an object it won't be omitted as per my understanding) which means that a value of null means that there is actually no error.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1957#-:-KQ4Rd_URvFP6WJihxWB:b-8r688g)*

**Pull request merged**
