### PR TITLE
vtgate batch API

### PR DESCRIPTION
**Pull request by sougou**
This makes vtgate batch API feature-complete. I've also changed the python client API and the tests to be more practical. The keyspace & keyspace_ids used to be bound to a cursor, which is not convenient for multiple queries. The new API instead allows you to specify those for each query.

### CODE REVIEW

**Comment by sougou** [comment]
PTAL again. I've also included the python client changes.

**Comment by alainjobart** [comment]
LGTM but I'd feel better if @dumbunny reviewed the python side too :)

**Comment by sougou** [comment]
@dumbunny https://github.com/youtube/vitess/commit/7d37338d1257fc89e4bfcdaf94209671b9c4052f is the commit where I change the API.

**Comment by sougou** [comment]
In the interest of time, I'm going to merge this. We can fix forward any issues in the client API.

**Pull request merged**
