### PR TITLE
JDBC Implementation

### PR DESCRIPTION
**Pull request by harshit-gangal**
This pull request contains changes for implementing JDBC on current Vitess client.
This is currently work in progress.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1558)

### CODE REVIEW

**Comment by enisoc** [comment]
Reviewed 27 of 27 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 2 of 3 files at r5, 1 of 1 files at r6, 4 of 5 files at r7.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 139 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCb2AwdXXXy3v3vQkyt:-KCb2Awe3x6E_6-V_UNy:-163343870) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L139)):*
VTGateTx commit() and rollback() calls should have `.checkedGet()` to make them synchronous. I'm realizing now it was dangerous to make these methods async since there's nothing to enforce that you must call `checkedGet()`. I'm thinking we should add blocking wrappers around VTGateConn and VTGateTx that always call `checkedGet()` for you, and use that instead. I'll look into that.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 157 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCaxjxe781LSYnd36lr:-KCaxjxe781LSYnd36ls:-1665110068) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L157)):*
Why do you catch and re-wrap SQLException, instead of letting it propagate? In the low-level API, we throw specific subclasses of SQLException to give more information. Are you hiding that information on purpose?

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbSA5mzMH3LVxwlMnR:-KCbSA5ntZ_KtluNxnbS:531029033) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L27)):*
When would you not want to use bind variables? VTGate and VTTablet are both designed for use with bind variables. Vitess will be much less efficient without bind variables because nothing can be cached.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 166 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbA0RZWhDKMS3IkBFW:-KCbA0RZWhDKMS3IkBFX:-1060725988) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L166)):*
I don't think it's right to use streamExecute() by default. Stream execute is meant for OLAP, and bypasses VTTablet's protections against slow or overly-expensive queries. I think we should use execute() by default, and possibly provide an option on VitessConnection to use streaming, which you should only do against RDONLY tablets and only from batch jobs (not serving end-user requests).

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 320 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbRSzIRHGs4OFuv5Om:-KCbRSzJXINlHusY3Z9v:-1712069286) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L320)):*
Is it possible to avoid filling parameterMap when USE_BIND_VARIABLES is true, and vice versa? It seems inefficient to convert every parameter to string twice (once to call setMapVariable() and once in the lower-level API when it processes bindVariables).

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 342 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbQsa3-W6pGlPhYk43:-KCbQsa3-W6pGlPhYk44:-1983433781) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L342)):*
Don't you need to escape `value` to make sure it's safe as a quoted string literal?

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbT5AE-nDk9N0DdTDq:-KCbT5AE-nDk9N0DdTDr:-915587261) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L56)):*
This hides the original exception `e` which may contain useful information for debugging why the `getFields` failed. In general, I don't see why you can't just let the SQLException from getFields propagate out unchanged.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 175 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbb8KiFLYuRdoDvvrK:-KCbb8KiFLYuRdoDvvrL:-1979281469) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L175)):*
This `-1` offset is due to an unfortunate oversight on my part while implementing the Row class. I didn't notice that columnIndex is supposed to be 1-based in JDBC ResultSet. I would like to change Row to be 1-based, but first I need to make sure it won't break our existing users. I'll look into it.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 259 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbUpE2EuVk7eF4xql7:-KCbUpE2EuVk7eF4xql8:-1994004282) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L259)):*
This pattern of using `getString` and reparsing seems inefficient. The low-level Vitess API is already parsing the raw value and returning Integer from `row.getObject()`. Then in `this.getString()` you convert that Integer back to String. Then here you take that string and parse it back to int.

If the issue is that you want to control the conversion yourself, we should instead expose a method from the low-level Vitess API to let you get the raw value without any attempt to convert. Even better would be that we should change the low-level Vitess Row class to make its getInt() behave the same way JDBC ResultSet.getInt() is supposed to. Then here you would just directly call `row.getInt()`. Can you comment on what might need to change to make the low-level get*() methods pass-through compatible like that?

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 668 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbi3KpSEjdWw5yFu2S:-KCbi3KqRcrOdT3tmRl9:-140761280) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L668)):*
Note that `row.getObject()` parses and converts the value every time you call it. So you are incurring the cost of parsing every time `isNull()` is called, and then you're incurring it again later to actually get the value.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by enisoc** [comment]
Nice work! I think we just need to clean up some integration points between this connector and the underlying low-level Vitess API. Right now there seems to still be some mismatch in these interfaces. I mentioned some things in the Reviewable.io comments that I plan to work on, which should help with this.

**Comment by harshit-gangal** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 139 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCb2AwdXXXy3v3vQkyt:-KCdS7qsscao2nninxqT:-474963468) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L139)):*
For now. Will take care of that in jdbc classes

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 157 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCaxjxe781LSYnd36lr:-KCdU6iwow5spBPOnEWH:464760262) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L157)):*
I can actually just write try and finally block. Will do that

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbSA5mzMH3LVxwlMnR:-KCd0nuxOshuHKoW5-Xu:221723535) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L27)):*
We want to use bind variables every time. But, currently the client accepts very less raw data types. We know that anything can be converted to string and then send as bind variables. But, want to enhance client first and then will remove this part of the code.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 166 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbA0RZWhDKMS3IkBFW:-KCd1QgVQQkWwiFy56NU:1933569949) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L166)):*
We can do that. Will update the pull request

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbT5AE-nDk9N0DdTDq:-KCdUVQ3s-WivXsoDUs6:412529523) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L56)):*
Will do that

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by harshit-gangal** [comment]
Review status: 15 of 27 files reviewed at latest revision, 10 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 139 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCb2AwdXXXy3v3vQkyt:-KD-_C1NgA59L0Q9mXRp:-499146009) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L139)):*
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 320 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbRSzIRHGs4OFuv5Om:-KD-bwu_LD6JOPGqM-F2:-499146009) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L320)):*
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbT5AE-nDk9N0DdTDq:-KD-c0GyHcIuFI-t78L4:-1627232149) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L56)):*
Done. Original Exception is not hidden, only that additional error message is added to the existing exception.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 259 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbUpE2EuVk7eF4xql7:-KD-YUhsi2xmKWpGkjtK:1168341781) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L259)):*
We want to make things more flexible for the user.
If the user has declared a datatype as varchar, it can still call getInt() on it provided the data is numeric.
Not just that.
Currently if someone has datatype as INT64, then using your client directly I cannot call getInt() because it expects the object type to be Integer.class.
Whereas we are trying to make things flexible for the user so that they can call any method like getShort, getInt, getLong, etc.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by enisoc** [comment]
Reviewed 1 of 10 files at r9, 1 of 6 files at r10, 10 of 11 files at r11.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 139 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCb2AwdXXXy3v3vQkyt:-KD0Qnl54S9KquGrzeSL:-943879203) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L139)):*
I will soon add the mentioned blocking wrappers in https://github.com/youtube/vitess/pull/1566

That should make it easier to avoid this kind of problem.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 320 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbRSzIRHGs4OFuv5Om:-KD0SxNG26BGh4sv1ELx:-2046731725) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L320)):*
I meant to avoid producing the string and calling setMapVariable() at all. But if the plan is to eventually always use bind variables (as mentioned elsewhere) then it's fine for now.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 175 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbb8KiFLYuRdoDvvrK:-KD0TtVB7rN3T-9Vjaj3:1264153290) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L175)):*
This will be fixed soon in https://github.com/youtube/vitess/pull/1565

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 259 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbUpE2EuVk7eF4xql7:-KD0U1NnKiM0UYbHV_Qj:-1127347284) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L259)):*
I see. Then this is fine for now. I'll work on pushing this capability down into the low-level Row class. Then we can simplify this layer.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by enisoc** [comment]
Reviewed 3 of 9 files at r12, 6 of 6 files at r14, 9 of 9 files at r15.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by harshit-gangal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 320 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbRSzIRHGs4OFuv5Om:-KDRv4HzDYutAdzW2eHP:-662924169) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L320)):*
Will remove it once we merge https://github.com/youtube/vitess/pull/1495

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 342 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbQsa3-W6pGlPhYk43:-KDRvNMLeK6PyREYo65f:133335428) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L342)):*
This will not be required once we use bind variables only.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by harshit-gangal** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 668 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbi3KpSEjdWw5yFu2S:-KDS4LtEptDEITkerx7t:122222480) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L668)):*
To solve this, either we should expose getRawValue method or write a isNull method in client.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by enisoc** [comment]
Reviewed 6 of 7 files at r16.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 668 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbi3KpSEjdWw5yFu2S:-KE8_jcf7wVfczPDEEwC:1302521957) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L668)):*
It should be possible to eliminate isNull() from VitessResultSet. The low-level Row class already will return null when the type allows, to indicate SQL NULL. You shouldn't need to maintain your own `wasNullFlag` either, since the Row class already does this and provides `wasNull()`.

There are some places where you'll need to check if the object returned from Row is null before attempting to do type conversion. However, those will go away too once I push the type conversion down into the Row class.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by harshit-gangal** [comment]
Review status: 28 of 31 files reviewed at latest revision, 5 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 668 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbi3KpSEjdWw5yFu2S:-KESrhTUSRMhqK9codD9:-171214664) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L668)):*
isNull is still needed as type conversion is done here. But have removed wasNullFlag as it was maintained in client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by harshit-gangal** [comment]
*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 320 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbRSzIRHGs4OFuv5Om:-KE_FFexMV5jv4XOiXTY:-499146009) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L320)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1558)*

**Comment by enisoc** [comment]
:lgtm:

The CLA bot is confused by some commits from Naveen with an alternate email address, but I verified he is covered so I will override this time.

---

Reviewed 19 of 24 files at r21, 5 of 5 files at r24.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 139 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCb2AwdXXXy3v3vQkyt:-KEnDl5j4rjVExHs6xDM:1219008341) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L139)):*
The blocking wrappers are ready, but we can make that change after this PR so resolving this thread.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 668 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1558#-KCbi3KpSEjdWw5yFu2S:-KEnEr6OAZnb9yiGxVdI:-1691335553) ([raw file](https://github.com/youtube/vitess/blob/c6fcebb994816609ec78ccf2de1d8565ec309d85/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L668)):*
Ok we will revisit whether the need for isNull() can be avoided after I push full type conversion down to the low-level client.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1558#-:-KEnFtQNVchjfBJt7sP4:1126344374)*

**Comment by enisoc** [comment]
I'm looking into the Travis failure before merging. It's the Java target that's failing.

**Pull request merged**
