### PR TITLE
Update scripts for latest grpc, 0.12.

### PR DESCRIPTION
**Pull request by alainjobart**
Note we now use the gRPC protobuf submodule for install,
to be sure its version matches gRPC.

@enisoc this is the first part. I need to do docker next.

How about we just install all the modules we depend upon in a single tree (the 'dist' directory, or even maybe a directory higher) instead of each of them being in their own directory?

### CODE REVIEW

**Comment by enisoc** [comment]
I don't see a clean way to check if this will work in Travis before merging to master. I think I would have to delete the master Travis cache, but then if anyone merges anything it will re-establish the cache with the old grpc version.

A while ago I came up with a hack to get more granular control of the Travis cache:

https://github.com/youtube/vitess/blob/master/travis/php_init.sh#L32

If we do something similar here in `travis/install_grpc.sh`, you could check for the `ver_file`, and if it doesn't exist or is out of date, delete both dist/grpc and dist/protobuf and start from scratch. This will ensure that nothing in the cache will interfere with your new builds. At the same time, it will avoid having to also rebuild everything else in the cache (like the PHP interpreter).

As a bonus, I think this would also make it easier on everyone whenever we bump the grpc version. Instead of saying, "I just bumped the version, please delete dist/{grpc,protobuf} and run bootstrap.sh", you can just say, "Always run bootstrap.sh after pulling master and it will automatically update anything that needs to be updated".

As for merging all the dist trees, I could be convinced if there's a significant benefit. However, it has been nice in the past (and especially so with my granular plan above) to be able to `rm -rf dist/something` and start from scratch for just that part.

**Comment by alainjobart** [comment]
OK I'll modify the install script so the file marker also contains the version number, set to 0.12 now, and also remove the protobuf dist.

**Comment by enisoc** [comment]
You may also need to update the list of cached directories in `.travis.yml`. It will probably pass without fixing that, but it may fail on a subsequent run if all the required directories aren't cached.

**Comment by alainjobart** [comment]
@enisoc OK I think this is good now, PTAL. I had to clear travis cache, as predicted, but then everything works as expected.

**Comment by enisoc** [comment]
LGTM

**Comment by enisoc** [comment]
Regarding the tox issue, it's apparently known. @michael-berlin found the following issues:

https://github.com/grpc/grpc/issues/4592
https://github.com/grpc/grpc/issues/4473

He's looking into it, but I think it should be ok to merge this. I'd like to go ahead and update the php grpc plugin to the latest beta, which requires grpc 0.12.

I can add the `--ignore-installed` and parallel make flags we tried earlier today, after you merge this.

**Comment by michael-berlin** [comment]
re: the tox issue

In https://github.com/grpc/grpc/pull/4323 grpc changed tox.ini to use the new directive "-r<requirements file>" instead of specifying the dependencies.

This feature [requires tox 1.6.1](http://tox.readthedocs.org/en/latest/example/basic.html#depending-on-requirements-txt) but Ubuntu Trusty comes only with 1.6.0.

We only run into the issue If tox is installed system-wide (```python-tox``` package).
If not, gRPC's build_python.sh magically uses the tox binary which is in the virtualenv. 

I see the following two fixes on the grpc side:
- do not use the -r... directive
- always use the newer tox from the virtualenv

**Comment by alainjobart** [comment]
OK then I'll merge this, and we'll fix forward.

**Comment by michael-berlin** [comment]
Example when build_python.sh fails due to the old Tox version:

```sh
$ CONFIG=opt ./tools/run_tests/build_python.sh
...
tox --notest
...
py27 installdeps: -rrequirements.txt
...
ERROR: could not install deps [-rrequirements.txt]
_____________________________________________________________________________________________________________________________________ summary ______________________________________________________________________________________________________________________________________
ERROR:   py27: could not install deps [-rrequirements.txt]
```

tox version:

```sh
$ tox --version
1.6.0 imported from /usr/lib/python2.7/dist-packages/tox/__init__.pyc
```

**Comment by michael-berlin** [comment]
FYI: I've created an issue with Travis to get ```python-six``` whitelisted for installing via apt-get:

https://github.com/travis-ci/apt-package-whitelist/issues/2317

The process is automated and we should have a result within a day.

**Comment by michael-berlin** [comment]
```python-six``` is now whitelisted by Travis.

To recap, with this PR, we introduced two new dependencies:
- tox
- python-six

Currently, these dependencies are "managed" by ```travis/install_grpc.sh``` and the user doesn't have to care about it.

If we want to get the dependencies out of there, we would have to e.g. add them to our list of dependencies: http://vitess.io/getting-started/local-instance.html#install-dependencies

For ```tox```, I feel we definitely should not do that.

```python-six``` is now required because protobuf requires it.
I assume somebody who is going to use our python client might therefore require it?
That sounds like we want to have it as explicit dependency then?

@alainjobart @enisoc Do you agree?

If so, I'll make the necessary changes.

**Comment by alainjobart** [comment]
Agreed, explicit dependency on python-six (very stable package), and not
tox (as it will not be required soon I guess?).

Thanks!

**Pull request merged**
