### PR TITLE
unify call path so both new mycnf's and loaded mycfn's inherit the same defaults

### PR DESCRIPTION
**Pull request by bbeaudreault**
@sougou @rnavarro 

I tested this on one of my keyspaces -- deleting the tmpdir from my existing my.cnf to simulate not having a value there.  This appropriately sets the tmp dir to the default value.

### CODE REVIEW

**Comment by acharis** [comment]
lame travis:
```[ERROR] Failed to execute goal org.xolstice.maven.plugins:protobuf-maven-plugin:0.5.0:compile (default) on project vitess-grpc-client: protoc failed to execute because: /home/travis/.m2/repository/com/google/protobuf/protobuf-java-util/3.0.2/protobuf-java-util-3.0.2.jar was not a readable artifact: error in opening zip file -> [Help 1]```

**Comment by bbeaudreault** [comment]
test failure is in java and unrelated to this change.

**Comment by sougou** [comment]
Looks like this is failing for all builds now. Anyone know how to fix this?

**Comment by michael-berlin** [comment]
> Looks like this is failing for all builds now. Anyone know how to fix this?

I think I fixed the problem by dropping the Travis caches.

When I looked at it, the error was that Maven tried to download from "nexus.codehaus.org" which is shut down since 2015. It looks like it tries to use that repository because Travis provides a list of repositories in $HOME/.m2/settings.xml and it's still included there.

I don't know why this hasn't been a problem before.

In the past, people worked around the problem by rewriting the respective entry in that file. Since May, Travis has fixed the problem upstream. See here for details: https://github.com/travis-ci/travis-ci/issues/4629

However, we're always caching $HOME/.m2 to speed up builds and therefore the cached version was probably still on the old, bad settings.xml. My hope is that by dropping the caches, we're on the good, fixed file now and therefore the test has passed.

If this happens again, we'll have to inspect the settings.xml further to see what's in there.

**Comment by rnavarro** [comment]
Thanks for looking into that @michael-berlin !

Can this one get merged yet?

**Comment by rnavarro** [comment]
Also, as a note, I manually applied these patches and my tablets fired up again.

w00t!

**Pull request merged**
