### PR TITLE
vtdb.tablet client uses error codes instead of string parsing

### PR DESCRIPTION
**Pull request by aaijazi**
@alainjobart @dumbunny 

Some clean-up here. I think I'll use a similar structure for the VTGate clients, this was mostly testing my ideas out.

Before making the VTGate client changes, I'll be sure to add test cases to vtgateclientest.

### CODE REVIEW

**Comment by enisoc** [comment]
@aaijazi FYI I'm currently making changes in vtgateclienttest and I was planning to add error test cases soon (but haven't yet). Let's coordinate on that to make sure we don't overlap.

**Comment by aaijazi** [comment]
@enisoc sounds good. I was planning on starting my changes tomorrow, so we can coordinate in person. (or just let me know when you're starting to make changes)

**Comment by alainjobart** [comment]
We want to retire tablet.py, it's the direct vttablet access we don't want to support in python. I guess now that this is done, might as well submit it :)

LGTM

**Comment by aaijazi** [comment]
Merging this now that I've made Travis pass (and there might be race conditions with Travis passing / caching). I'll fix forward if anybody has additional comments.

**Pull request merged**
