### PR TITLE
Log down SQL and BindVariables for SplitQuery

### PR DESCRIPTION
**Pull request by guokeno0**
@sougou @erzel

### CODE REVIEW

**Comment by sougou** [comment]
lgtm

**Comment by guokeno0** [comment]
I signed it!

**Comment by guokeno0** [comment]
I signed it!

**Comment by guokeno0** [comment]
I signed it!

**Comment by guokeno0** [comment]
Confirm

**Comment by erzel** [comment]
Thanks for the quick fix for this, Jeff.

**Pull request closed without merging**
