### PR TITLE
Replication

### PR DESCRIPTION
**Pull request by alainjobart**
@aaijazi @enisoc @sougou 

This is what I want to submit before this week snap, and import, and fix stubby and stubbyp3 to also pass the tests.

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM

**Comment by alainjobart** [comment]
@guokeno0 you might want to look at this too, should help you :)

**Comment by alainjobart** [comment]
OK will merge and work on import then.

**Comment by aaijazi** [comment]
Generally looks good, but it would be good to add the tests back that I mentioned above.

**Comment by alainjobart** [comment]
@aaijazi Dunno where my comment went, but we *definitely* need the error test cases. When you add your errors, we'll add the test cases back to make sure every single error triggered on the server side for every canonical error goes through.

**Comment by aaijazi** [comment]
@alainjobart thought about it some more, and I think we should definitely add the tests back now. They'll be needed for BsonRPC anyways, and they'll be extremely helpful for my error changes to make sure that we don't break compatibility.

**Pull request merged**
