### PR TITLE
Make the mysql failure checks more explicit.

### PR DESCRIPTION
**Pull request by shrutip**
@guoliang100 @alainjobart 
DatabaseError is a parent class of other exceptions. This is to check that we aren't accidentally throwing
IntegrityError etc.

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM (I assume checking the real child exception is not possible?)

**Comment by shrutip** [comment]
This particular case throws DatabaseError (parent exception). The particular bug I was trying to catch is when one of vtgate clients threw IntegrityError for this case but was not caught by this test.

**Comment by guoliang100** [comment]
LGTM

**Comment by alainjobart** [comment]
OK cool.

**Pull request merged**
