### PR TITLE
Force tablet onto specific nodes.  Automatically deduce node count when ...

### PR DESCRIPTION
**Pull request by thompsonja**
...creating a cluster.

Also replaced gcutil with gcloud compute.

@henryanand @enisoc

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM with one question: Do you need to force placement only for better resource utilization in benchmarks? Or does the use of SSDs only work with one tablet per node?

**Comment by thompsonja** [comment]
The main purpose is indeed to ensure that the distribution of tablets to nodes doesn't have any impact on benchmarking efforts.  I haven't fully tested running tablets on SSDs yet (next step), but if this also helps then it's a win-win.

**Comment by enisoc** [comment]
Ok SGTM. Just for the record though, if SSD doesn't work with multiple tablets on a node, we need to fix that. So I'd like to request that once you start testing SSDs, that you also try *without* the forced placement, and let me know if it causes an issue.

**Comment by thompsonja** [comment]
sgtm

**Pull request merged**
