### PR TITLE
PHP client - ProtoUtils fix after last vterrors changes

### PR DESCRIPTION
**Pull request by Rastusik**
Regarding this issue: https://github.com/youtube/vitess/issues/2620

### CODE REVIEW

**Comment by sougou** [comment]
LGTM
Sorry about the oversight. I'll merge once the tests pass.

**Comment by Rastusik** [comment]
what do you mean by oversight? :)

**Comment by michael-berlin** [comment]
PHP tests may have caught this? The problem is we had to disable them in Travis due to a weird issue we couldn't fix.

**Comment by alouane** [comment]
Check 58 code line youtube/vitess@15235a5#commitcomment-21131018

**Comment by sougou** [comment]
@Rastusik Can you resolve the merge conflicts?

**Comment by michael-berlin** [comment]
Sorry, that was my bad. Turns out I could resolve the conflict through a GitHub web UI.

**Pull request merged**
