### PR TITLE
Keep _vt.local_metadata table across backup-restore operations.

### PR DESCRIPTION
**Pull request by pivanof**
So far local_metadata contained only data needed for Orchestrator and we didn't
need to preserve that data across restores because it was about the vttablet
running near MySQL. With the plan to store some data about the database itself
(e.g. id of a schema swap already executed on the database) we need to save
the table's contents in a backup and preserve it after restore.
This change achieves that. The data used by Orchestrator gets repopulated
immediately after restore, so that functionality is not changed.

@alainjobart

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1898)

### CODE REVIEW

**Comment by alainjobart** [comment]
:lgtm:  with two comments to address.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/mysqlctl/backup.go, line 623 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi4o7-wVnPXI47qEet:-KNi4o7-wVnPXI47qEeu:-530134947) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/backup.go#L623)):*
> ```Go
> 	}
> 	if toRestore < 0 {
> 		log.Infof("Auto-restore is enabled, but no backups were found. Starting up empty.")
> ```

should be logger.? I know you copied it from somewhere else where it was already log. but i think this should be logger.

---

*[go/vt/mysqlctl/backup.go, line 638 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi4q7a4gprr0qViMY1:-KNi4q7a4gprr0qViMY2:-85846170) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/backup.go#L638)):*
> ```Go
> 		}
> 		if !ok {
> 			log.Infof("Auto-restore is enabled, but mysqld already contains data. Assuming vttablet was just restarted.")
> ```

logger.?

---

*[go/vt/mysqlctl/local_metadata.go, line 54 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi5OqHr-XOkJ9r2jns:-KNi5OqHr-XOkJ9r2jnt:-972923933) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/local_metadata.go#L54)):*
> ```Go
> 		query := fmt.Sprintf(
> 			"INSERT INTO _vt.local_metadata (name,value) VALUES ('%s','%s') "+
> 				"ON DUPLICATE KEY UPDATE value = '%s'", k, v, v)
> ```

We probably want to escape quotes in there, to prevent SQL ingestions. I am not sure if we already have a quote method anywhere...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1898#-:-KNiHOEmRasguiBoH1Iz:-1397510896)*

**Comment by pivanof** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/mysqlctl/backup.go, line 623 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi4o7-wVnPXI47qEet:-KNmAT62I71reUo-ahcK:-1672434269) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/backup.go#L623)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> should be logger.? I know you copied it from somewhere else where it was already log. but i think this should be logger.
</details>
Does logger prints the message into local logs in addition to sending it to the streaming RPC? I thought it's not and that's why both log and logger are needed. Am I wrong?

---

*[go/vt/mysqlctl/local_metadata.go, line 54 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi5OqHr-XOkJ9r2jns:-KNmAiiDKVJlz_CBHwsf:30882157) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/local_metadata.go#L54)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> We probably want to escape quotes in there, to prevent SQL ingestions. I am not sure if we already have a quote method anywhere...
</details>
Argh. Reviewable doesn't show the diff for renamed files properly. :-(

It was already like this. But I've changed it anyway since I'm changing the query. PTAL.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1898)*

**Comment by alainjobart** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/mysqlctl/backup.go, line 623 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi4o7-wVnPXI47qEet:-KNmNiVj7mY6PmbjD9rB:1864736469) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/backup.go#L623)):*
<details><summary><i>Previously, pivanof (Pavel Ivanov) wrote…</i></summary>
> Does logger prints the message into local logs in addition to sending it to the streaming RPC? I thought it's not and that's why both log and logger are needed. Am I wrong?
</details>
in rpc_backup.go line 83 we create a TeeLogger to console and remote side, before calling Restore. So I think this would log locally too...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1898)*

**Comment by pivanof** [comment]
Review status: 3 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/mysqlctl/backup.go, line 623 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi4o7-wVnPXI47qEet:-KNmSnnHE8WM3xtPAHpB:-1218290097) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/backup.go#L623)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> in rpc_backup.go line 83 we create a TeeLogger to console and remote side, before calling Restore. So I think this would log locally too...
</details>
Ah, right. Then I squashed these two log messages together. Hopefully that is okay (even though one was Info and another Error).
Done.

---

*[go/vt/mysqlctl/backup.go, line 638 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNi4q7a4gprr0qViMY1:-KNmT22wgRVRzEn8fFMZ:-499146009) ([raw file](https://github.com/youtube/vitess/blob/186e24bcc4427a4ca8dc4c28b338d480b7ac463d/go/vt/mysqlctl/backup.go#L638)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> logger.?
</details>
Done.

---

*[go/vt/mysqlctl/backup.go, line 688 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1898#-KNmUGdOhMqRiibfppyz:-KNmUGdOhMqRiibfppz-:-3215076) ([raw file](https://github.com/youtube/vitess/blob/24f3a6f9cda2c2e92cd254a04e3bb99429906dcd/go/vt/mysqlctl/backup.go#L688)):*
> ```Go
> 	// so it's there before we start announcing ourselves.
> 	logger.Infof("Restore: populating local_metadata")
> 	err = populateLocalMetadata(mysqld, localMetadata)
> ```

I found that I didn't check for an error return here. Added now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1898)*

**Comment by alainjobart** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1898#-:-KNmXQ-kPikabCFv5eKE:1417088721)*

**Pull request merged**
