### PR TITLE
vt: case preserve column names

### PR DESCRIPTION
**Pull request by sougou**
@erzel for split query
@michael-berlin for vtworker
@enisoc and @alainjobart for the rest

I've created two interchangeable types: cistring.CIString and sqlparser.ColIdent. Those who don't want to depend on sqlparser are supposed to use CIString. Others can use either type depending on which is more convenient. sqlparser.ColIdent has the necessary functions to be in the AST.

Cases are mostly preserved. There are some exceptions:

- View names are always lowercased, because they get stored as table names in AST structs. This affects only DDLs. So, it should have no material impact.
- Function name cases are preserved, except for the 'if' function. Since that is a reserved word, it gets lowercased by the tokenizer. Again, there should be no material impact.

The general approach I've used is to convert case-insensitive data into CI types as early as possible. This way, the compiler is likely to catch more accidental comparisons. The main caveat is that this does not work in situations where a variable gets anonymized into an interface. I found a few places: Printf, DeepEqual & JSON. Hopefully, there shouldn't be more. If there are, we just have to fix forward.
The worker code uses protobufs to store the schema. So, column names have remained normal strings there.

Ive added new tests using some reasonable judgment.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1688)

### CODE REVIEW

**Comment by sougou** [comment]
#1620

**Comment by erzel** [comment]
LGTM on splitquery after you address my comments.

<details><summary><i>Previously, sougou wrote…</i></summary>
> #1620 </details>


---

Reviewed 7 of 47 files at r1.
Review status: 7 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/tabletserver/splitquery/full_scan_algorithm.go, line 198 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLoA-j9c25zDqTRm6F:-KHLoA-kJO6jruuLqqLW:1388736739) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/tabletserver/splitquery/full_scan_algorithm.go#L198)):*
> ```Go
> 	result := make([]string, 0, len(splitColumns))
> 	for _, splitColumn := range splitColumns {
> 		result = append(result, prevBindVariablePrefix+splitColumn.Val())
> ```

Same comment here. Use the canonicalized (lowered) name for the splitColumn name.

---

*[go/vt/tabletserver/splitquery/split_params.go, line 210 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLlvgCj3v2lXbGTy9n:-KHLlvgDN-aWSDgc-XL1:-423324298) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/tabletserver/splitquery/split_params.go#L210)):*
> ```Go
> // isStringSlicePrefix returns true if 'potentialPrefix' is a prefix of the slice
> // 'slice'.
> func isStringSlicePrefix(potentialPrefix []sqlparser.ColIdent, slice []cistring.CIString) bool {
> ```

Rename this method to isColIdentSlicePrefix since it uses ColIdent's now.

---

*[go/vt/tabletserver/splitquery/splitter.go, line 32 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLnEO_1Lvocecv4gq7:-KHLnEOaXHvJJb8DuQ95:243384602) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/tabletserver/splitquery/splitter.go#L32)):*
> ```Go
> 	for _, splitColumn := range splitter.splitParams.splitColumns {
> 		splitter.startBindVariableNames = append(
> 			splitter.startBindVariableNames, startBindVariablePrefix+splitColumn.Val())
> ```

It makes more sense to me to have the bind variable name use the lower-case version so it's not dependent on the user's query.
This should be fine with the user, since this bind variable is internal and the user should not depend on its name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688#-:-KHLoT7e6Rs9sll_rtc8:-336494705)*

**Comment by sougou** [comment]
Review status: 4 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/tabletserver/splitquery/full_scan_algorithm.go, line 198 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLoA-j9c25zDqTRm6F:-KHM1xSaPLUuCMPe87ig:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/tabletserver/splitquery/full_scan_algorithm.go#L198)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> Same comment here. Use the canonicalized (lowered) name for the splitColumn name.</details>
Done.

---

*[go/vt/tabletserver/splitquery/split_params.go, line 210 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLlvgCj3v2lXbGTy9n:-KHM2ErN1hr5Vmrb-4--:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/tabletserver/splitquery/split_params.go#L210)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> Rename this method to isColIdentSlicePrefix since it uses ColIdent's now.</details>
Done.

---

*[go/vt/tabletserver/splitquery/splitter.go, line 32 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLnEO_1Lvocecv4gq7:-KHM2apuAklTDPn336j5:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/tabletserver/splitquery/splitter.go#L32)):*
<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> It makes more sense to me to have the bind variable name use the lower-case version so it's not dependent on the user's query.
> This should be fine with the user, since this bind variable is internal and the user should not depend on its name.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688)*

**Comment by enisoc** [comment]
Reviewed 40 of 47 files at r1.
Review status: 44 of 47 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/cistring/cistring.go, line 15 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLrUggFE8JPv0sFOth:-KHLrUggFE8JPv0sFOti:-814392526) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L15)):*
> ```Go
> // CIString is an immutable case-insensitive string.
> type CIString struct {
> 	val, lowered string
> ```

Can you add to the doc comment an explanation of why you chose the "extra storage" implementation rather than "lowercase on compare"? Is it mainly for the CPU during comparisons? Or do you expect the conversion-on-compare to put extra load on the GC?

---

*[go/cistring/cistring.go, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLr2HW8NrPSYuqfsfG:-KHLr2HX-pSlhZ7xvTx_:-1794298935) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L18)):*
> ```Go
> 	// nocompare prevents this struct from being compared
> 	// with itself.
> 	nocompare func()
> ```

At lunch, we discussed the zero byte version of this, used here: https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/replication/replication.go#L31

Will that work here?

---

*[go/cistring/cistring.go, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLsJYMRf8zCM3sKaCa:-KHLsJYMRf8zCM3sKaCb:-241275478) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L22)):*
> ```Go
> 
> // NewCIString creates a new CIString.
> func NewCIString(str string) CIString {
> ```

This should be called `New()` as in `cistring.New()`. Or if you foresee other case-insensitive types later, you could name the package `ci` and have `ci.NewString()`.

---

*[go/cistring/cistring.go, line 34 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLtd4j77Tc4aT-UsOj:-KHLtd4j77Tc4aT-UsOk:-589058304) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L34)):*
> ```Go
> 
> // Val returns the case-preserved value of the string.
> func (s CIString) Val() string {
> ```

The name `Val()` seems ambiguous. What about `Original()` and `Lowered()`?

---

*[go/cistring/cistring.go, line 46 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLvx7eI_dKT8unV-e8:-KHLvx7eI_dKT8unV-e9:-830044636) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L46)):*
> ```Go
> 
> // Equal returns true if the input is case-insensitive
> // equal to the string. If the input is already lower-cased,
> ```

For cases where you want to lowercase once and compare in a loop, maybe you could recommend a pattern like this:

```go
ciInput := ci.NewString(input)
for ... {
  if ciName.Equal(ciInput) {
    ...
  }
}
```

This has the benefit of avoiding manual calls to `strings.ToLower()` in places where you interoperate with CIS, which will help if the specific lowercasing behavior of CIS is ever changed (for locale fixes, for example).

---

*[go/cistring/cistring.go, line 48 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLuGBhr60Iu7ivdQkc:-KHLuGBiXDwM55fhpj-R:902234268) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L48)):*
> ```Go
> // equal to the string. If the input is already lower-cased,
> // it's more efficient to check if s.Lowered()==in.
> func (s CIString) Equal(in string) bool {
> ```

Do you ever need to compare `CIString` to another `CIString`? Usually I would expect `CIString.Equal()` to have signature `CIString.Equal(CIString)`, and then the version for comparing to something other than `CIString` would be suffixed like `CIString.EqualString(string)`.

---

*[go/vt/sqlparser/ast.go, line 1746 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHM3lURDAEBXrZt5hxh:-KHM3lUSRA-t2U1YNtq1:-1693815519) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/sqlparser/ast.go#L1746)):*
> ```Go
> // ColIdent is a case insensitive SQL identifier. It will be escaped with
> // backquotes if it matches a keyword.
> type ColIdent cistring.CIString
> ```

If you embed, you won't have to duplicate the `CIString` API (`String()`, `Val()`, `Lowered()`, etc.):

``` go
type ColIdent struct {
  cistring.CIString
}
```

Is there a reason you prefer wrapping over embedding?

---

*[test/vtgatev3_test.py, line 359 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHM5NtdQmsbd9DN0pOB:-KHM5NtdQmsbd9DN0pOC:1533318820) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/test/vtgatev3_test.py#L359)):*
> ```Python
> 
>     # Test case sensitivity
>     cursor.execute('select Id, Name from vt_user where iD = :id', {'id': 1})
> ```

Is there a test for giving the case used in schema if they do `select *`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688)*

**Comment by sougou** [comment]
Review status: 23 of 47 files reviewed at latest revision, 11 unresolved discussions.

---

*[go/cistring/cistring.go, line 15 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLrUggFE8JPv0sFOth:-KHMEcN3VTmM1fFyj8pk:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L15)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Can you add to the doc comment an explanation of why you chose the "extra storage" implementation rather than "lowercase on compare"? Is it mainly for the CPU during comparisons? Or do you expect the conversion-on-compare to put extra load on the GC?</details>
Done.

---

*[go/cistring/cistring.go, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLr2HW8NrPSYuqfsfG:-KHM6yGEyvsYpphJ6E9_:385597094) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L18)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> At lunch, we discussed the zero byte version of this, used here: https://github.com/youtube/vitess/blob/master/go/vt/mysqlctl/replication/replication.go#L31
> 
> Will that work here?</details>
It turns out that the zero-byte version (array) still consumes one word. I tested both options and the size of the struct was the same 40 bytes. So, I chose the simpler looking code.

---

*[go/cistring/cistring.go, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLsJYMRf8zCM3sKaCa:-KHM849EqvqMwxhLJgYD:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L22)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This should be called `New()` as in `cistring.New()`. Or if you foresee other case-insensitive types later, you could name the package `ci` and have `ci.NewString()`.</details>
Done.

---

*[go/cistring/cistring.go, line 34 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLtd4j77Tc4aT-UsOj:-KHM9-9d6pnZqOi4mpR9:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L34)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> The name `Val()` seems ambiguous. What about `Original()` and `Lowered()`?</details>
Done.

---

*[go/cistring/cistring.go, line 46 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLvx7eI_dKT8unV-e8:-KHMFVZr1VNpXdeXhVaF:-1559694127) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L46)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> For cases where you want to lowercase once and compare in a loop, maybe you could recommend a pattern like this:
> 
> ```go
> ciInput := ci.NewString(input)
> for ... {
>   if ciName.Equal(ciInput) {
>     ...
>   }
> }
> ```
> 
> This has the benefit of avoiding manual calls to `strings.ToLower()` in places where you interoperate with CIS, which will help if the specific lowercasing behavior of CIS is ever changed (for locale fixes, for example).</details>
I'm neutral both ways. This still doesn't address the situation where the input is already lowercased, but one always has the option of using Lowered: ciName.Lowered() == input. I'll leave those parts alone for now.

---

*[go/cistring/cistring.go, line 48 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLuGBhr60Iu7ivdQkc:-KHMGpkVj1PEyfLrwZkx:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L48)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Do you ever need to compare `CIString` to another `CIString`? Usually I would expect `CIString.Equal()` to have signature `CIString.Equal(CIString)`, and then the version for comparing to something other than `CIString` would be suffixed like `CIString.EqualString(string)`.</details>
Done.

---

*[go/vt/sqlparser/ast.go, line 1746 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHM3lURDAEBXrZt5hxh:-KHMAPhSHfNk4PbwAX90:198673305) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/sqlparser/ast.go#L1746)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> If you embed, you won't have to duplicate the `CIString` API (`String()`, `Val()`, `Lowered()`, etc.):
> 
> ``` go
> type ColIdent struct {
>   cistring.CIString
> }
> ```
> 
> Is there a reason you prefer wrapping over embedding?</details>
I've avoided embedding because it has generally led to confusion in the past. Also, the last time I tested, it didn't work for things like MarshalJSON. The wrapping also lets you freely cast the two types back and forth.

---

*[test/vtgatev3_test.py, line 359 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHM5NtdQmsbd9DN0pOB:-KHMBeWekQNDNrwdn_xd:-984555101) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/test/vtgatev3_test.py#L359)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Is there a test for giving the case used in schema if they do `select *`?</details>
Quite a few: data/test/tabletserver/exec_cases.txt. I changed the schema to contain mixed case column names.
I did the same thing for the v3 tests also (data/test/vtgate/*.txt).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688)*

**Comment by enisoc** [comment]
LGTM for the parts outside splitquery.

<details><summary><i>Previously, erzel (Erez Louidor) wrote…</i></summary>
> LGTM on splitquery after you address my comments.</details>


---

Reviewed 21 of 22 files at r3.
Review status: 44 of 47 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/cistring/cistring.go, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLr2HW8NrPSYuqfsfG:-KHMnQhrtMzerpweoc1n:798743538) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L18)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> It turns out that the zero-byte version (array) still consumes one word. I tested both options and the size of the struct was the same 40 bytes. So, I chose the simpler looking code.</details>
Ah they must have "fixed the glitch" that I was taking advantage of :) Your way is safer anyway, since they may someday decide that the compiler *can* compare two zero-length arrays of uncomparable things...

---

*[go/vt/sqlparser/ast.go, line 1746 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHM3lURDAEBXrZt5hxh:-KHMoprDLOQtoTgDng3l:5174689) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/vt/sqlparser/ast.go#L1746)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> I've avoided embedding because it has generally led to confusion in the past. Also, the last time I tested, it didn't work for things like MarshalJSON. The wrapping also lets you freely cast the two types back and forth.</details>
ok

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688#-:-KHMphrA5LkB4bFqjbT3:-1351160296)*

**Comment by enisoc** [comment]
Review status: 44 of 47 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/cistring/cistring.go, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLr2HW8NrPSYuqfsfG:-KHMscn604lwpuHURelF:-1997520024) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L18)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Ah they must have "fixed the glitch" that I was taking advantage of :) Your way is safer anyway, since they may someday decide that the compiler *can* compare two zero-length arrays of uncomparable things...</details>
It turns out, you can still make it take zero space, as long as it's not the last field in the struct:

https://github.com/golang/go/commit/6f07ac2f280847ee0346b871b23cab90869f84a4

I'll make a PR to fix the other use so it's not the last field.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688)*

**Comment by sougou** [comment]
Review status: 42 of 47 files reviewed at latest revision, 4 unresolved discussions.

---

*[go/cistring/cistring.go, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1688#-KHLr2HW8NrPSYuqfsfG:-KHNjqNqr7taG75ahtbt:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5290b99a93c6acf3c666f9a13f04da25c66f670b/go/cistring/cistring.go#L18)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> It turns out, you can still make it take zero space, as long as it's not the last field in the struct:
> 
> https://github.com/golang/go/commit/6f07ac2f280847ee0346b871b23cab90869f84a4
> 
> I'll make a PR to fix the other use so it's not the last field.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688)*

**Comment by enisoc** [comment]
Reviewed 2 of 2 files at r4.
Review status: 44 of 47 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1688)*

**Pull request merged**
