### PR TITLE
WIP -- DDL/DBA fixes while working through liquibase migrations

### PR DESCRIPTION
**Pull request by bbeaudreault**
I'm running all of HubSpot's migrations through a test keyspace in vitess to prove out the liquibase integration. As I do that I'm running into some compatibility fixes, which this PR aims to fix.

I'll let you know when to take a look, for now feel free to ignore.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/2671)

### CODE REVIEW

**Comment by bbeaudreault** [comment]
This is ready for review.

@ashudeep-sharma can you review the java parts? It shouldn't be too complex. The background is that Liquibase requires access to these `supportsMixedCaseIdentifiers` functions. We are already doing `SHOW VARIABLES` in `initializeDBProperties`, so I see no reason not to add another variable there. I added test coverage for the new functions.

@sougou can you review the DDL parser changes? They also should be pretty straightforward. All new parser constructs tested in parse_test.

**Comment by ashudeep-sharma** [comment]
@bbeaudreault : I just looked at the Java files affected by this change there is just a minor comment, Also went through the details of  lower_case_table_names variable for mysql ref: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_lower_case_table_names and mariadb ref : https://mariadb.com/kb/en/mariadb/server-system-variables/ .It looks like behavior is the same for both. In your change you just modified the files for VitessMySQLDatabaseMetadata.java. Can you please make this change in VitessMariaDBDatabaseMetadata.java as well.

---

Reviewed 1 of 9 files at r1.
Review status: 1 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/DBProperties.java, line 11 at r1](https://reviewable.io:443/reviews/youtube/vitess/2671#-KgDZiNX-KHK0LtRg-C9:-KgDZiNX-KHK0LtRg-CA:b-4eohqt) ([raw file](https://github.com/youtube/vitess/blob/00bb305e0986f6f2d8e74302140df58d4824498c/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/DBProperties.java#L11)):*
> ```Java
>     private final String minorVersion;
>     private final int isolationLevel;
>     private final boolean lowerCaseTableNames;
> ```

Please change this variableName to casesensitiveComparison or something else and accordingly do the function Name change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2671#-:-KgD_PUVhmZdPaH7tZra:b-kwhgcl)*

**Comment by bbeaudreault** [comment]
Thanks @ashudeep-sharma. I added it to mariadb and updated tests. Also renamed per your request.

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/DBProperties.java, line 11 at r1](https://reviewable.io:443/reviews/youtube/vitess/2671#-KgDZiNX-KHK0LtRg-C9:-KgEXSy4fI8V4SNkZBG9:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/00bb305e0986f6f2d8e74302140df58d4824498c/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/DBProperties.java#L11)):*
<details><summary><i>Previously, ashudeep-sharma (Ashu) wrote…</i></summary><blockquote>

Please change this variableName to casesensitiveComparison or something else and accordingly do the function Name change.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2671#-:-KgEXXdrkAmVBOyxvrf3:b-sxv17c)*

**Comment by ashudeep-sharma** [comment]
Thanks @bbeaudreault , JDBC changes looks good.

---

Reviewed 2 of 9 files at r1, 4 of 4 files at r2.
Review status: 6 of 10 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2671#-:-KgEl24f0T8hqCH1VfTq:b7qxjdb)*

**Comment by ashudeep-sharma** [comment]
:lgtm: fo JDBC Changes

---

Review status: 6 of 10 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2671#-:-KgElEpRxMrs49bE74Kk:b-y66od6)*

**Comment by ashudeep-sharma** [comment]
@bbeaudreault : You might have to retrigger the build as the Travis Build is failing.

**Comment by bbeaudreault** [comment]
@sougou when you get a chance, this PR is finished up. I added `START TRANSACTION`, not sure what you think about how I did it. I treated it the same as `begin`, as a special case in `vtgate.go`

**Pull request merged**
