### PR TITLE
add helper functions to ease use of fake vtgate for testing

### PR DESCRIPTION
**Pull request by yaoshengzhe**
1. add [Start/Stop]FakeVtGateServer which simply starts/stops a fake server
2. StartFakeVtGateServer returns a VTGateServerice and its address

### CODE REVIEW

**Comment by alainjobart** [comment]
I actually don't think this is a good idea: it introduces a dependency from vtgateconntest to gorpc, which we don't want. vtgateconntest is supposed to only test an interface...

**Comment by alainjobart** [comment]
(look at the stubby one internally, you'll see what I mean)

**Comment by yaoshengzhe** [comment]
@alainjobart ok, got it. But then my question would be how do we unit test a vtgate client ? Client test may call vtgateconntest.CreateFakeServer and start a fake vtgate anyway, there will be duplicate code (see current go/vt/vtgate/gorpcvtgateconn/conn_rpc_test.go). What about move these two helper functions out of vtgateconntest package ? Maybe move them to vtgate package. I feel it makes write unit test a little bit easier (for components that needs a running vtgate).

**Comment by alainjobart** [comment]
How about a vtgateconntestutils package?

**Comment by sougou** [comment]
For my go driver, I started with trying to reuse this, and ended up writing my own. There is some duplication, but the subtle differences are harder to manage from the common code, and I think they'll tend to diverge as we try to do different things with them.
So, I'm thinking it may not be worth it.

**Pull request closed without merging**
