### PR TITLE
update sequence initialization doc

### PR DESCRIPTION
**Pull request by demmer**
Add a quick mention to the docs that the sequence table needs a bootstrap row inserted.

### CODE REVIEW

**Comment by sougou** [comment]
:+1: can you also run publish-site? http://vitess.io/internal/publish-website/

**Comment by demmer** [comment]
@sougou I just ran publish-site but see tons of diffs... that doesn't seem expected to me.

**Comment by acharis** [comment]
there's a bunch of `<span></span>` in there

**Comment by demmer** [comment]
Yeah I don't know how spanner ended up spamming into my PR (lol)...

I just ran publish-site.sh as per instructions.

**Comment by sougou** [comment]
LGTM

Netlify looks good. So, I'll just merge.

**Pull request merged**
