### PR TITLE
Remove shardgateway from integration tests

### PR DESCRIPTION
**Pull request by guoliang100**
@alainjobart 

Separate the work of clean up integration tests into another PR.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1683)

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM good size change, thanks :)

**Comment by guoliang100** [comment]
@alainjobart 

Please take a look at the integration test changes. They make sure the tests work with other vtgate gateway implementations.

**Comment by alainjobart** [comment]
In these tests, I notice you're changing the:

start_vttablet(init_...)

into:

init_tablet(...)
start(vttablet)

I don't think you should do that, as my change is fixing it too, using init_tablet_type inside start_vttablet, and waiting for the right NOT_SERVING state. Maybe wait for my change to go in?

**Comment by alainjobart** [comment]
(which should be as soon as travis passes)

**Comment by guoliang100** [comment]
I supply tablet_index through init_tablet() to enable the call topo_server().update_addr in start_tablet().
If init_tablet() is not needed, I can move the logic to start_tablet() and maybe remove init_tablet() completely?

**Comment by alainjobart** [comment]
Ah I missed that part, it's fine, you can leave it as init_tablet then. Moving it to start_tablet would work as well, if you wanna do that work.

Then the only comment I have is to merge my changes (that are in now), and don't wait on tablet type any more, as it's not gonna change ever. Instead, wait for the serving state to be 'SERVING' if you want to wait for a healthy tablet...

**Pull request merged**
