### PR TITLE
Support for Hex strings: #2235

### PR DESCRIPTION
**Pull request by sougou**
As mentioned in the issue, I still allow 0x literals,
but will make future changes to prevent Vitess from
mis-interpreting those values.
I've added some missing tests in the process.

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM

**Comment by adkhare** [comment]
@sougou for the upgrade process here, do we need to upgrade all tablets and then vtgate or can we just upgrade vtgate

**Comment by sougou** [comment]
You'll need to update vttablets as well as vtgates, in any order.

**Comment by sougou** [comment]
Some tests are failing because the `0x` construct is used in a couple of places. I'll fix those before submitting.

**Comment by sougou** [comment]
@mberlin PTAL at the new commit. I'm rerunning the tests. They're passing so far.
Couldn't find any other place that used the `0x` construct.

**Comment by sougou** [comment]
After some internal discussion, it may be too dangerous to yank `0x` support without verifying prior use. So, I'll bring it back. However, I'll see if I can prevent vitess from mis-interpreting it. In other words, support it only as pass-through. But this will be through a subsequent change.

**Comment by michael-berlin** [comment]
go/vt/worker changes LGTM

**Comment by sougou** [comment]
KeyspaceId being shorter than 8 bytes is a possibility, and allowed. One of the tests failed: TestUint64FromKeyspaceId. I'll just add a comment explaining why I copy.

**Comment by michael-berlin** [comment]
> KeyspaceId being shorter than 8 bytes is a possibility, and allowed. One of the tests failed: TestUint64FromKeyspaceId. I'll just add a comment explaining why I copy.

SG

**Pull request merged**
