### PR TITLE
Let TableACL clear query plan cache on acl reload

### PR DESCRIPTION
**Pull request by guokeno0**

### CODE REVIEW

**Comment by guokeno0** [comment]
@sougou  @yaoshengzhe 

TableACL should invalidate query plan cache upon reloads

**Comment by guokeno0** [comment]
@alainjobart this bug is now bothering us internally

**Comment by sougou** [comment]
This is getting ugly very fast. The root cause is that tableACLs are not part of TabletServer, like query rules are.
I think it will be better if you added an InitTableACL function in TabletServer, which in turn calls tableacl.Init, and also clears the query cache.
We can then eventually morph the API to mimic query rules.

**Comment by guokeno0** [comment]
Agree, this is not in its best form. I'm not sure why it wasn't in TabletServer. Just adding a initTableACL is not enough (the query plan cache need to be cleared upon every ACL update). But if we can move this inside tabletserver, then we are pretty much done.

**Comment by guokeno0** [comment]
@alainjobart @yaoshengzhe could you confirm the change? Basically I think if we want to make this change cleaner, we will have to move tableacl inside tabletserver so that tableacl can call tabletserver APIs

**Comment by sougou** [comment]
What I meant was that you could add something like this to TabletServer
func (tsv *TabletServer) InitTableACL(...) {
  tabletacl.Init(...)
  tsv.qe.schemaInfo.ClearQueryPlanCache()
}
That way, we avoid the callback function, and it's more readable.

**Comment by guokeno0** [comment]
Update: we could use tabletserver.RegisterFunctions to register tablet controller with tableacl, as queryrule does

**Comment by guokeno0** [comment]
@sougou @alainjobart  @yaoshengzhe Turns out that we cannot use RegisterFunctions because it causes cyclic dependency: tabletserver depends on tableacl because query plan refer to some tableacl objects and tableacl will depend on tabletserver if we use RegisterFunctions or some other forms of exported APIs (this PR uses a implicit callback to avoid this, but the essential problem is the same).

If we don't want tableacl to register the callback, I propose to move tableacl inside tabletserver and tabletserver can register itself to chubbyacl/simpleacl (like how we deal with queryrules) this way, we can make chubbyacl and simpleacl push acl updates to all tabletserver clients and later if we want, we can even unify tableacl and queryrule implementations.

**Comment by sougou** [comment]
Bummer. If you promise fix it in the future, you can submit this now :).

**Comment by guokeno0** [comment]
@sougou I'll create a bug as a reminder. Getting this in first to unblock our internal users

**Pull request merged**
