### PR TITLE
query service: low level reconnect logic

### PR DESCRIPTION
**Pull request by sougou**
@alainjobart @enisoc 
If MySQL is restarted underneath query service, all connections
become invalid. This ends up returning one error per connection
until everything heals.
This CL changes the low-level exec to do a transparent reconnect
and retry if such an error was detected. But this is done only
if you're not in a transaction.
The test for this is hairy and slow. Probably flaky also. So,
I've commented it out after making sure it passes.

### CODE REVIEW

**Comment by enisoc** [comment]
Is the test only slow because of the fixed sleeps? In other tests, we have ways of waiting for mysqld to start or stop without a fixed sleep (polling for socket file, waiting on pid to term). It shouldn't be too hard to reuse or port some of that in queryservice_test.

LGTM other than the commented-out test. :)

**Comment by sougou** [comment]
The problem was with the restart after the shutdown. Somehow, mysql wasn't coming up properly without that sleep. I felt like that could cause flakiness.
I'll see if I can figure out a more deterministic way to restart. If @alainjobart can't wait, I can look at it after merging this.

**Comment by sougou** [comment]
It looks like I also broke some unit tests... I'll prepare a fix tomorrow.

**Comment by alainjobart** [comment]
Thanks for working on this, this is cool. I can wait for a fix to the tests, yes. I'd feel better with tests!

I bet mysqld is not 100% shut down when it removes the socket file (it's just not ready to serve any more), and the new one starting up right away would mess things up. We should probably wait for mysqld to be 100% gone, but we don't have the subprocess handle...

**Comment by sougou** [comment]
As discussed, I'll work on unflaking the test post-merge.

**Pull request merged**
