### PR TITLE
Add stats to track dangling tablet conn.

### PR DESCRIPTION
**Pull request by guoliang100**
@alainjobart @sougou

### CODE REVIEW

**Comment by guoliang100** [comment]
@aaijazi @alainjobart @sougou 
Ping.

**Comment by aaijazi** [comment]
Code looks fine, but I have no context on the problem that's being solved here, so withholding an LGTM. Do we suspect that tabletconn connections aren't being closed properly?

Also, is this meant to be a short-term counter just for instrumentation?

**Comment by guoliang100** [comment]
When closing a connection, we purposely leave it open if there are ongoing queries.
We want to track how many connections are left open, which should not be very high.

**Comment by aaijazi** [comment]
LGTM

**Pull request merged**
