### PR TITLE
moved STATUS and VARIABLES to non_reserved_keyword

### PR DESCRIPTION
**Pull request by slanning**
Being in reserved_keyword was making queries using status as a column impossible,
so I moved STATUS to non_reserved_keyword.
I also moved VARIABLES since I'd guess it's the same situation.

I wasn't sure about GLOBAL and SESSION, so I left them for now,
but possibly they also should be in non_reserved_keyword. (?)

### CODE REVIEW

**Comment by sougou** [comment]
Oops! Looks like we encountered a race condition with @dweitzman. Can you resolve the conflicts? We should still get your `variables` change in.

**Comment by bbeaudreault** [comment]
also, does travis check for shift/reduce conflicts? hard to catch those in review but that's the reason for the `reserved_keyword` vs `non_reserved_keyword`. We had tried to put all of the keywords in the most permissive bucket possible. But I see these 2 are recently new so 🤞 no conflicts.

**Comment by sougou** [comment]
Thanks for the warning @bbeaudreault. I just checked it, and we have introduced conflicts. Looks like we'll need to rework the other PR.

**Comment by bbeaudreault** [comment]
No prob. Wonder if the travis script can be enhanced to scrape for the conflict message output from `make`

**Comment by sougou** [comment]
It looks like this change is good after all. So, I'll just wait for Scott to fix the merge conflicts, and merge this. This should fix the previously introduced shit/reduce conflicts.

**Comment by slanning** [comment]
I messed that up, didn't I....

**Comment by sougou** [comment]
LOL. You've angered Google's CLA bot.

**Comment by slanning** [comment]
Sorry, this is probably simple to fix but I'm not getting it and it's late, so I'm just going to make a new PR...

**Pull request closed without merging**
