### PR TITLE
Regenerate php protobuf files.

### PR DESCRIPTION
**Pull request by pivanof**
@michael-berlin @alainjobart 

Apparently these files were not generated for quite some time.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1854)

### CODE REVIEW

**Comment by michael-berlin** [comment]
This looks like a gRPC generator change?

How did you generate them? Using the docker image which Alain created?

**Comment by alainjobart** [comment]
I actually re-generated them a couple days ago... the change you have seems to imply a library has changed (like the proto generation library). That seems weird, as we pin them to a specific version... @enisoc would know more.

**Comment by pivanof** [comment]
I just ran "make php_proto", that's it.

**Comment by alainjobart** [comment]
Just ran it too, and it didn't produce any diff... Maybe your docker images are more recent than mine...

**Comment by enisoc** [comment]
I agree it looks like a generator change, either the PHP part or the base protoc. It could be that we updated the pinned version of one of those, but didn't regenerate the PHP protos.

In any case, I ran `make php_proto` myself and it generated the same diffs as this PR, so :lgtm:.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1854#-:-KM5iYuHXydkb--r3H_s:-1042597209)*

**Pull request merged**
