### PR TITLE
proto: Update generated Go protobuf files.

### PR DESCRIPTION
**Pull request by michael-berlin**
I don't know why this has changed. But we must update the generated code to keep the Travis check happy.

@pivanof @enisoc @alainjobart 

If Travis does not pass here, it's an issue with my local machine.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1891)

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM I have the same issue, but travis passed without this earlier today for me...

**Comment by michael-berlin** [comment]
@pivanof suggested that the different output is caused by different Go versions.

It looks like this is the case. Go 1.7 has changes to the compression library: https://tip.golang.org/doc/go1.7

Given that, I'm considering to do the following changes:

- exclude the binary literals for the file descriptors from the proto travis test
- stop generating protobufs on every `make build` because this will create different protobuf files for people who are not using Go 1.7

**Comment by alainjobart** [comment]
Can we use a go 1.7 image in Travis?

**Comment by michael-berlin** [comment]
> Can we use a go 1.7 image in Travis?

We can also do that.

But we deliberately want to run the same Go version which we require as minimum and that's currently 1.6.

**Comment by michael-berlin** [comment]
The fixes are in place now. Can somebody please review the the changes? :)

**Comment by alainjobart** [comment]
So with just the 'ignore gzip diff' commit, why do we need the Makefile change as well?

**Comment by michael-berlin** [comment]
To avoid confusion for users who don't run Go 1.7:

They would run `make build` and the protobuf files would get generated with a different content. This will clutter their `git status`. In the worst case, they'll send us pull requests where the changed protobuf files are included.

**Comment by alainjobart** [comment]
LGTM then, makes sense.

**Pull request merged**
