### PR TITLE
skip "make build" for unit_test target in travis

### PR DESCRIPTION
**Pull request by yaoshengzhe**

### CODE REVIEW

**Comment by yaoshengzhe** [comment]
Waiting for travis build: https://travis-ci.org/youtube/vitess/builds/64983601

**Comment by alainjobart** [comment]
You seem to add a dependency on 'build' from the other targets, shouldn't that dependency be in the Makefile itself?

**Comment by yaoshengzhe** [comment]
That's true, better to let make target to decide if it wants to do build or not.

**Comment by yaoshengzhe** [comment]
Checked the makefile again, it seems we intentionally not add build as a dependency for each test.

**Comment by michael-berlin** [comment]
I've checked the memory usage within Travis with and without the additional "build" target.

There is no measurable difference and therefore I suggest to keep things as they are and do not merge this PR.

with build:
https://travis-ci.org/youtube/vitess/builds/65026858#L6199
CPU: 369% Memory: 1344976 kB

without build:
https://travis-ci.org/youtube/vitess/builds/65028888#L6159
CPU: 562% Memory: 1356000 kB

Nonetheless, the difference between the two Travis runs exposes the actual problem: Some Travis VMs do not reclaim the memory used by the Linux disk cache (listed as "cached" in the "free" output). Therefore, the available memory shrinks with every additional dependency installed. This is a bug in the Travis platform.

I've let them known in their IRC channel for now. I'll probably also file a bug with them later.

**Comment by yaoshengzhe** [comment]
great findings, thank you.

**Pull request closed without merging**
