### PR TITLE
Fixing vtctl and execute keyranges

### PR DESCRIPTION
**Pull request by erzel**
Hi Jeff, as we discussed yesterday, here is a pull-request that:
1. Fixes vtctl to disallow only one of sharding key column and sharding key type to be set, 
2. Removes the special-case logic in mapKeyRangesToShards so that if it's called on the set of empty key-ranges it will return an empty set of shards.

This PR also fixes the zookeeper mirror since the old one stopped hosting our zookeeper version.
@michael-berlin @guokeno0

### CODE REVIEW

**Comment by erzel** [comment]
Also, I'll probably won't be around to submit this. Can one of you please do this for me if you're both ok with the changes? Thanks.

**Comment by guokeno0** [comment]
LGTM if you can fix the tests.

**Comment by michael-berlin** [comment]
I'll fix the tests later. Enjoy your vacation Erez!

**Comment by michael-berlin** [comment]
I'm closing this pull request because I merged it in another pull request with the test fix here: https://github.com/youtube/vitess/pull/1372

@erzel Some general feedback on your Git workflow:

- Please always use meaningful Git commit messages and avoid temporary messages like ";". Every Git commit message will show up in the history and places like "git blame". Therefore, I always aim for self-contained commit messages which make it easy for others to understand the intent behind a change.
- You can also amend commits or squash multiple commits into one if you want to clean up any temporary Git commits. I'm more than happy to show you some Git magic when you're back :)

**Pull request closed without merging**
