### PR TITLE
Print human-readable tables for CLI queries.

### PR DESCRIPTION
**Pull request by enisoc**
@michael-berlin 

The table output is similar to the `mysql` CLI.

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1523)

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM with one minor comment: do you have one end2end test that exercises the non-JSON output?

**Comment by michael-berlin** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/vtctl/query.go, line 501 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1523#-KBPC2Bc6_ubHO_pIPGN:-KBPC2Bc6_ubHO_pIPGO:1837841646) ([raw file](https://github.com/youtube/vitess/blob/7dccef5c74eb1970ab4bc1a7c6f115648f86c6ce/go/vt/vtctl/query.go#L501)):*
logutil.Logger being anonymous makes it more difficult for me to grasp here that "lw.Printf" will call the Printf from "logutil.Logger". I would prefer if you give the member a name.

---

*[test/tabletmanager.py, line 109 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1523#-KBPD7EgQBVd9BOjEAxb:-KBPD7EgQBVd9BOjEAxc:-1126043125) ([raw file](https://github.com/youtube/vitess/blob/7dccef5c74eb1970ab4bc1a7c6f115648f86c6ce/test/tabletmanager.py#L109)):*
Turns out we have a JSON Style Guide :)

https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format

> Property names must be camel-cased, ascii strings.

That means the first letter should be lowercase. Do we want to change it to match that style? You just have to add the json tag to the struct for that?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1523)*

**Comment by enisoc** [comment]
I didn't write a test for human-readable output yet because I didn't want it to be a change-detector test. I'll think about it again and see what makes sense.

**Comment by enisoc** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/vtctl/query.go, line 501 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1523#-KBPC2Bc6_ubHO_pIPGN:-KBPFRKxGsRaRhRW0aWf:-1323014304) ([raw file](https://github.com/youtube/vitess/blob/7dccef5c74eb1970ab4bc1a7c6f115648f86c6ce/go/vt/vtctl/query.go#L501)):*
I made the call explicit and added a comment that explains what it's doing.

---

*[test/tabletmanager.py, line 109 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1523#-KBPD7EgQBVd9BOjEAxb:-KBPFjVFTVrzyLsS9bTG:-1180110562) ([raw file](https://github.com/youtube/vitess/blob/7dccef5c74eb1970ab4bc1a7c6f115648f86c6ce/test/tabletmanager.py#L109)):*
At first I did make them lowercase with field tags, but then I noticed the rest of the execute commands on vtctl (VtGate*, VtTablet*) were already returning JSON with capital names. So I made mine consistent with those. If you prefer, we could change all of them to lowercase? That would require adding JSON tags on sqltypes.Result.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1523)*

**Comment by michael-berlin** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[test/tabletmanager.py, line 109 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1523#-KBPD7EgQBVd9BOjEAxb:-KBPc-MdHQWd6htT1uiY:544703717) ([raw file](https://github.com/youtube/vitess/blob/7dccef5c74eb1970ab4bc1a7c6f115648f86c6ce/test/tabletmanager.py#L109)):*
Thanks for keeping it consistent :)

If it's not too much work for you, let's make all lowercase? I'll let you decide.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1523)*

**Comment by enisoc** [comment]
Review status: 4 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/tabletmanager.py, line 109 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1523#-KBPD7EgQBVd9BOjEAxb:-KBPg7Bx-vk0bYOwynYC:2026139047) ([raw file](https://github.com/youtube/vitess/blob/7dccef5c74eb1970ab4bc1a7c6f115648f86c6ce/test/tabletmanager.py#L109)):*
So it turns out generated protobuf code doesn't follow the JSON style guide either. It uses underscore names rather than camel case:

https://github.com/youtube/vitess/blob/master/go/vt/proto/query/query.pb.go#L263

Since querytypes.Result contains querypb.Fields, we have to follow the protobuf convention to keep it consistent.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1523)*

**Comment by michael-berlin** [comment]
LGTM

Thanks for updating the JSON fields!

---

Reviewed 4 of 4 files at r3, 8 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1523#-:-KBPlCeLxQ8TiLuPanik:887216356)*

**Pull request merged**
