### PR TITLE
discovery: Guarantee that HealthCheck stops calling the listener after HealthCheck.Close() returned.

### PR DESCRIPTION
**Pull request by michael-berlin**
@guoliang100 

You can ignore the first two commits. They're identical to https://github.com/youtube/vitess/pull/1724 since this PR is based on that PR.

**Description:**

Without this change, it's difficult to synchronize the shutdown of a listener implementation and HealthCheck.

For example, a listener implementation could send to a channel for every update. But the shutdown of the listener implementation will close that channel and future sends to it will panic. Therefore, a HealthCheck.Close() must guarantee the user that the listener won't be called anymore when it returned. After that, the listener can shut down itself.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1726)

### CODE REVIEW

**Comment by guoliang100** [comment]
LGTM

**Comment by michael-berlin** [comment]
@guoliang100 PTAL at the last commit.

I had to add it because the code prolonged our unit test execution internally. With the commit, this is fixed now.

**Comment by michael-berlin** [comment]
And a second commit for another problem was necessary :) Please review this one as well.

**Comment by guoliang100** [comment]
LGTM

**Pull request merged**
