### PR TITLE
Adds basic jdbc support for PreparedStatement#getParameterMetaData()

### PR DESCRIPTION
**Pull request by bbeaudreault**
getParameterMetaData is required for apache commons query runner,
which uses parameterCount to validate passed parameters against expected.
Implementation was pulled from mysql-connector-java's PreparedStatement$ParseInfo
class, and greatly simplified to support just the parameter counting.

### CODE REVIEW

**Comment by ashudeep-sharma** [comment]
Changes looks good in general. I have few comments , can you please incorporate those?
Also it would be great if you can format the code. There are some extra newlines in calculateParameterCount(), it would be good if we follow the same type of formatting in all the files.

---

Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java, line 27 at r1](https://reviewable.io:443/reviews/youtube/vitess/2437#-K_nsKLDQmr8az2i_wfM:-K_nsKLDQmr8az2i_wfN:b-ykoiqh) ([raw file](https://github.com/youtube/vitess/blob/296dcb44156b26e7e7c0545efbee93541186e79d/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java#L27)):*
> ```Java
>     return parameterCount;
>   }
> ```

Since you are implementing the basic simple version of  ParameterMetadata. It should check for Parameter bounds, the JDBC specification recommends that the param Value should be between 1 and paramsCount. Please check this for every function.

If it was implemented for different fields the checks are already in place in VitessResultSetMetaData functions.
Please check the bounds for each of the implementation.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java, line 66 at r1](https://reviewable.io:443/reviews/youtube/vitess/2437#-K_nrRi8TAkhCHIl6p1S:-K_nrRi8TAkhCHIl6p1T:bm0or1g) ([raw file](https://github.com/youtube/vitess/blob/296dcb44156b26e7e7c0545efbee93541186e79d/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java#L66)):*
> ```Java
>   @Override
>   public int getParameterMode(int param) throws SQLException {
>     return param;
> ```

This doesn't seems to be correct as per Java Doc specification, this function does the following:
/**
     * Retrieves the designated parameter's mode.
     *
     * @param param the first parameter is 1, the second is 2, ...
     * @return mode of the parameter; one of
     *        <code>ParameterMetaData.parameterModeIn</code>,
     *        <code>ParameterMetaData.parameterModeOut</code>, or
     *        <code>ParameterMetaData.parameterModeInOut</code>
     *        <code>ParameterMetaData.parameterModeUnknown</code>.
     * @exception SQLException if a database access error occurs
     * @since 1.4
     */
In mysql implementation its returning ParameterMetaData.parameterModeIn, i don't think this function should return param.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 480 at r1](https://reviewable.io:443/reviews/youtube/vitess/2437#-K_nx85u5y_YiLtHcRD9:-K_nx85u5y_YiLtHcRDA:b-1dc59o) ([raw file](https://github.com/youtube/vitess/blob/296dcb44156b26e7e7c0545efbee93541186e79d/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L480)):*
> ```Java
> 
>     public ParameterMetaData getParameterMetaData() throws SQLException {
>         if (this.parameterMetadata == null) {
> ```

Before checking the parameterMetadata, it should check for the validity of connection, there is checkOpen() function in this class.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 587 at r1](https://reviewable.io:443/reviews/youtube/vitess/2437#-K_nxvcVcQTcnGX_bgaP:-K_nxvcVcQTcnGX_bgaQ:b-r08ncq) ([raw file](https://github.com/youtube/vitess/blob/296dcb44156b26e7e7c0545efbee93541186e79d/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L587)):*
> ```Java
>     }
> 
>     private static int findStartOfStatement(String sql) {
> ```

This function can be moved to StringUtils.java

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java, line 726 at r1](https://reviewable.io:443/reviews/youtube/vitess/2437#-K_nz2kxuFKMvlDQSWIZ:-K_nz2kxuFKMvlDQSWI_:b-mdh2rw) ([raw file](https://github.com/youtube/vitess/blob/296dcb44156b26e7e7c0545efbee93541186e79d/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java#L726)):*
> ```Java
>             .put("select * from foo where a = ? and b = \\?", 1) // not valid sql but validates escaping
>             .build();
> ```

Please incorporate some DMLs as well in the test-case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2437#-:-K_nzErviyHsphI4Ux9p:b-sas4o)*

**Comment by ashudeep-sharma** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java, line 729 at r1](https://reviewable.io:443/reviews/youtube/vitess/2437#-K_o7eedq0cztiyjTEaP:-K_o7eeeWDjWD9QuOFWc:b4t097a) ([raw file](https://github.com/youtube/vitess/blob/296dcb44156b26e7e7c0545efbee93541186e79d/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessPreparedStatementTest.java#L729)):*
> ```Java
>         for (Map.Entry<String, Integer> testCase : testCases.entrySet()) {
>             VitessPreparedStatement statement = new VitessPreparedStatement(mockConn, testCase.getKey());
>             Assert.assertEquals(testCase.getKey(), testCase.getValue().longValue(), statement.getParameterMetaData().getParameterCount());
> ```

All tests only cover getParameterCount(), i think its good to add tests for other functions as well which have been implemented. It will be beneficial in terms of getting the code coverage as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2437)*

**Comment by bbeaudreault** [comment]
Thanks for the review. I'll incorporate all comments and push for a re-review later today

**Comment by bbeaudreault** [comment]
@ashudeep-sharma @harshit-gangal ready for re-review. Everything should be addressed.

**Comment by ashudeep-sharma** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java, line 68 at r2](https://reviewable.io:443/reviews/youtube/vitess/2437#-Ka0vMpVT_4cGQ1HYbFw:-Ka0vMpVT_4cGQ1HYbFx:b-tlppjr) ([raw file](https://github.com/youtube/vitess/blob/9c2ee9a2c840cdf2a9f2969bcb824426c143c2a1/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java#L68)):*
> ```Java
>     @Override
>     public int getParameterMode(int param) throws SQLException {
>         return parameterModeIn;
> ```

Make it explicit ParameterMetaData.parameterModeIn 

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessParameterMetaDataTest.java, line 39 at r2](https://reviewable.io:443/reviews/youtube/vitess/2437#-Ka0vZCz_sOuIGn2Ol6K:-Ka0vZD-1t43kCrwX9iN:bd8txtb) ([raw file](https://github.com/youtube/vitess/blob/9c2ee9a2c840cdf2a9f2969bcb824426c143c2a1/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessParameterMetaDataTest.java#L39)):*
> ```Java
>             metaData.getParameterType(0);
>             Assert.fail();
>         } catch (SQLException e) {
> ```

Please check the corresponding exception Message here.

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessParameterMetaDataTest.java, line 45 at r2](https://reviewable.io:443/reviews/youtube/vitess/2437#-Ka0veMFz01sz5ciHOwN:-Ka0veMFz01sz5ciHOwO:bd8txtb) ([raw file](https://github.com/youtube/vitess/blob/9c2ee9a2c840cdf2a9f2969bcb824426c143c2a1/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessParameterMetaDataTest.java#L45)):*
> ```Java
>             metaData.getParameterType(2);
>             Assert.fail();
>         } catch (SQLException e) {
> ```

Please check the corresponding exception Message here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2437)*

**Comment by ashudeep-sharma** [comment]
Changes looks good, just a few minor comments. After that we can merge it.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java, line 16 at r2](https://reviewable.io:443/reviews/youtube/vitess/2437#-Ka0wLEeBuIUXuhEXL4a:-Ka0wLEeBuIUXuhEXL4b:buhzixw) ([raw file](https://github.com/youtube/vitess/blob/9c2ee9a2c840cdf2a9f2969bcb824426c143c2a1/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessParameterMetaData.java#L16)):*
> ```Java
>      * statement metadata
>      */
>     VitessParameterMetaData(int count) {
> ```

Make this as public and move the VitessParameterMetaDataTest.java file under com.flipkart.vitess.jdbc.test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2437#-:-Ka0vm-SQDtakFJqb-f2:b-yqov9b)*

**Comment by bbeaudreault** [comment]
Thanks again Ashu.  I'll take care of the couple of comments.

Regarding moving the Test class -- can you expand upon your reasonings here? In my opinion it's a general best practice in Java to keep the visibility of your classes and members as private as possible. The way I usually see projects structured is with test classes in the same package as the class their testing.

If you'd like consistency, I would be more than happy to move all of the other test classes into the right package, rather than their own distinct `test` package.

**Comment by ashudeep-sharma** [comment]
@bbeaudreault : Yes the comment regarding the test-case was just to maintain the consistency. It would be great if you can move the other test classes to the right package.

**Comment by bbeaudreault** [comment]
@ashudeep-sharma this is all set now. I addressed your 3 comments, and moved all of the JDBC tests into the main jdbc package

**Comment by bbeaudreault** [comment]
Not sure if I need sign off from one of the approved mergers, i.e. @sougou @alainjobart?

**Comment by ashudeep-sharma** [comment]
:lgtm:

---

Reviewed 18 of 18 files at r3.
Review status: 2 of 13 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2437#-:-Ka5kCOg15ZYmQx1BhWo:bnfp4nl)*

**Comment by bbeaudreault** [comment]
Thanks @ashudeep-sharma!

**Comment by bbeaudreault** [comment]
@alainjobart @sougou this is ready and signed off on. Can I get a merge when one of you has a moment?

**Comment by sougou** [comment]
LGTM

**Comment by bbeaudreault** [comment]
thanks

**Pull request merged**
