### PR TITLE
JDBC - With IncludedFields.ALL, adds support for all non-encoding field metadata

### PR DESCRIPTION
**Pull request by bbeaudreault**
@ashudeep-sharma 

Part 2 of 3. This one adds support for all of the VitessResultSetMetadata getters. I've preserved the old default values when IncludedFields != ALL. I've added tests to ensure that all works as expected.  FieldWithMetadata is similar to `mysql-connector-j` Field.java, but wraps our Field proto. You'll notice that it adds support for remapping fields to their real java type based on flags passed from mysql -- more of that to come when we do the last part (char encodings)

FieldWithMetadata has 100% test coverage, and all new code in other classes have near that as well.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/2489)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Reviewed 6 of 15 files at r1.
Review status: 6 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java, line 40 at r1](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbF0S8e3Bid-2SDJGiy:-KbF0S8e3Bid-2SDJGiz:b-lxof6d) ([raw file](https://github.com/youtube/vitess/blob/5d68bb403a1de7b33112fa987818493d5fd83c6b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java#L40)):*
> ```Java
>     private BooleanConnectionProperty transformedBitIsBoolean = new BooleanConnectionProperty(
>         "transformedBitIsBoolean",
>         "If the driver converts TINYINT(1) to a different type, should it use BOOLEAN instead of BIT for future compatibility with MySQL-5.0, as MySQL-5.0 has a BIT type?",
> ```

This is not required as there is no plan to support anything before 5.6.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java, line 130 at r1](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbF0zwJWe4eokD-1xsq:-KbF0zwJWe4eokD-1xsr:b-xg6enn) ([raw file](https://github.com/youtube/vitess/blob/5d68bb403a1de7b33112fa987818493d5fd83c6b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java#L130)):*
> ```Java
>     }
> 
>     public void setTransformedBitIsBoolean(boolean transformedBitIsBoolean) {
> ```

Same for method

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 65 at r1](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbFI3vyNEHwaGGyWyFA:-KbFI3vyNEHwaGGyWyFB:b-qr571x) ([raw file](https://github.com/youtube/vitess/blob/5d68bb403a1de7b33112fa987818493d5fd83c6b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L65)):*
> ```Java
>     }
> 
>     public VitessResultSet(VitessConnection connection, Cursor cursor, VitessStatement vitessStatement) throws SQLException {
> ```

No need to pass connection here.
VitessStatement contains the connection object and should be reused.
This has led to so many code modification.
Kindly remove it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by harshit-gangal** [comment]
Review status: 5 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 61 at r2](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbFxOTUuY6Dn3_eCWxU:-KbFxOTUuY6Dn3_eCWxV:behh4kn) ([raw file](https://github.com/youtube/vitess/blob/3f927f2ee161a2dbc87d534bacae1b278413172a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L61)):*
> ```Java
> 
>     public VitessResultSet(VitessConnection connection, Cursor cursor) throws SQLException {
>         this(connection, cursor, null);
> ```

I meant. not to pass connection object at all.
ResultSet already maintains the reference for Statement and Statement maintains the reference of Connection. So, If you need Connection object then ask statement to provide rather than keeping the reference again and adding another constructor.

Constructor with VitessResultSet(Cursor) is only for test and not used anywhere else. So, that should not be a concern.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by bbeaudreault** [comment]
@harshit-gangal most of the lines changed are due to the DatabaseMetadata classes using a constructor which does not pass a valid VitessStatement. I can change all of them to not pass a connection at all, but then they will get a dummed down version of the VitessResultSet/FieldWithMetadata. Perhaps that is fine for those use-cases.  If that's the case, I'll have to add a null check and throw an SQLException on trying to access metadata for those use-cases.  Thoughts?

**Comment by bbeaudreault** [comment]
Also, in the next PR (for character encoding) I add another function on VitessResultSet which uses the VitessConnection -- I can similarly re-use the VitessStatement and null-check where appropriate, but just letting you know

**Comment by harshit-gangal** [comment]
Those who do not pass Statement to ResultSet are the ones which do not get data from the datastore(mysql) or are accumulating content from multiple calls. I think it will be fine to throw error for those cases.

---

Review status: 3 of 14 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489#-:-KbG07vT1X8GeRF58E0M:bm4q8gn)*

**Comment by bbeaudreault** [comment]
Ok, thanks for the comments. I'll push another commit in a few mins based on this conversation.

**Comment by bbeaudreault** [comment]
I simplified a bit, but just noticed I can fix some of the mocking now in VitessDatabaseMetadataTest -- will ping again when ready for another look

**Comment by bbeaudreault** [comment]
@harshit-gangal ok, ready for re-review. I had to keep some of the changes in VitessResultSetTest.java because the connection actually has implications on the results of those tests.

**Comment by bbeaudreault** [comment]
@harshit-gangal any chance you'll have time this week to take another look? thanks!

**Comment by sougou** [comment]
I heard @harshit-gangal is out for the week. Let's see if @ashudeep-sharma can help. Otherwise, we'll just have to wait for him.

**Comment by bbeaudreault** [comment]
Oh thanks for the note @sougou. Sounds good

**Comment by harshit-gangal** [comment]
Reviewed 1 of 4 files at r3, 7 of 13 files at r4.
Review status: 8 of 12 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/FieldWithMetadata.java, line 130 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnINr6TuXC4TOwm_wS:-KbnINr7A3VwpIUeQR25:b-mr4f4x) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/FieldWithMetadata.java#L130)):*
> ```Java
>     private void checkConnection() throws SQLException {
>         if (connection == null) {
>             throw new SQLException(Constants.SQLExceptionMessages.SQL_FEATURE_NOT_SUPPORTED);
> ```

Error message should be related to connection not created/does not exist.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java, line 66 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnJKEAeFB8D95TUeCo:-KbnJKEAeFB8D95TUeCp:b-obokci) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java#L66)):*
> ```Java
> 
>     public int isNullable(int column) throws SQLException {
>         return getField(column).isNotNull() ? 0 : 2;
> ```

what does value "2" means?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by harshit-gangal** [comment]
Reviewed 5 of 13 files at r4.
Review status: 10 of 12 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessMariaDBDatabaseMetadata.java, line 6 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnLzZ1y62i2P_OhSGd:-KbnLzZ1y62i2P_OhSGe:b4qrljm) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessMariaDBDatabaseMetadata.java#L6)):*
> ```Java
> import com.youtube.vitess.proto.Query;
> 
> import java.sql.*;
> ```

do not club the imports

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by bbeaudreault** [comment]
Thanks for the re-review @harshit-gangal, and welcome back!

Pushed fixes for your latest comments. In terms of imports, in my latest revisions I do not modify VitessMariaDBDatabaseMetadata.java at all, so those imports were like that. If you'd like me to push a commit just fixing the imports in that file, let me know and I'd be happy to.

**Comment by harshit-gangal** [comment]
Mark all the completed items here: https://reviewable.io/reviews/youtube/vitess/2489
This helps in tracking the changes.

**Comment by bbeaudreault** [comment]
Review status: 8 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java, line 40 at r1](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbF0S8e3Bid-2SDJGiy:-KbFyAryRfmf_uphfAci:ba3dfob) ([raw file](https://github.com/youtube/vitess/blob/5d68bb403a1de7b33112fa987818493d5fd83c6b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java#L40)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

This is not required as there is no plan to support anything before 5.6.
</blockquote></details>

Removed

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java, line 130 at r1](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbF0zwJWe4eokD-1xsq:-KbFy9qKTzPblt_TdY8a:ba3dfob) ([raw file](https://github.com/youtube/vitess/blob/5d68bb403a1de7b33112fa987818493d5fd83c6b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/ConnectionProperties.java#L130)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

Same for method
</blockquote></details>

Removed

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/FieldWithMetadata.java, line 130 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnINr6TuXC4TOwm_wS:-KbosoGXToSVvQIkxt2c:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/FieldWithMetadata.java#L130)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

Error message should be related to connection not created/does not exist.
</blockquote></details>

Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 65 at r1](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbFI3vyNEHwaGGyWyFA:-KbFtiR4HTq_CEU1ObpC:by5onwc) ([raw file](https://github.com/youtube/vitess/blob/5d68bb403a1de7b33112fa987818493d5fd83c6b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L65)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

No need to pass connection here.
VitessStatement contains the connection object and should be reused.
This has led to so many code modification.
Kindly remove it.
</blockquote></details>

Thanks for the review. Actually most of the code line changes use the other constructors which do not pass in a VitessStatement. But I created a new constructor which can re-use the connection in the VitessStatement which cleaned up 4 lines in VitessStatement and VitessPreparedStatement, which works for me!

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 61 at r2](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbFxOTUuY6Dn3_eCWxU:-KbosqiNOUCFDJ1HoU-D:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3f927f2ee161a2dbc87d534bacae1b278413172a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L61)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

I meant. not to pass connection object at all.
ResultSet already maintains the reference for Statement and Statement maintains the reference of Connection. So, If you need Connection object then ask statement to provide rather than keeping the reference again and adding another constructor.

Constructor with VitessResultSet(Cursor) is only for test and not used anywhere else. So, that should not be a concern.

</blockquote></details>

Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java, line 66 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnJKEAeFB8D95TUeCo:-KbosvhWwmMVuIpHQABJ:b-9l8bbq) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java#L66)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

what does value "2" means?
</blockquote></details>

Fixed in the code to make more sense

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessMariaDBDatabaseMetadata.java, line 6 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnLzZ1y62i2P_OhSGd:-Kbot-LlcDkPYoH0sMzU:b-damh8g) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessMariaDBDatabaseMetadata.java#L6)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

do not club the imports
</blockquote></details>

I had modified this in the past but per a previous request ended up backing out all changes to this file. so the `java.sql.*` is actually how it exists in master

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by bbeaudreault** [comment]
Done, and will do in the future.

---

Review status: 8 of 13 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489#-:-Kbotc20uoz2-EHH_qnr:bfdxhu4)*

**Comment by harshit-gangal** [comment]
Reviewed 1 of 4 files at r3, 1 of 13 files at r4, 2 of 3 files at r6.
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java, line 66 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnJKEAeFB8D95TUeCo:-KbyQL7R8F_CnuH3WAyB:b-tag6rw) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java#L66)):*
<details><summary><i>Previously, bbeaudreault (Bryan Beaudreault) wrote…</i></summary><blockquote>

Fixed in the code to make more sense
</blockquote></details>

Should this not return ResultSetMetaData.columnNullable instead of ResultSetMetaData.columnNullableUnknown

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessResultSetTest.java, line 202 at r5](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbyQt7almVCdRsWymcH:-KbyQt7almVCdRsWymcI:b-62xiu6) ([raw file](https://github.com/youtube/vitess/blob/95390d017cf2cc6d5a269bfec6ad1977c681e0ed/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessResultSetTest.java#L202)):*
> ```Java
>             .addFields(Query.Field.newBuilder().setName("col2").build()).build());
> 
>         VitessResultSet vitessResultSet = new VitessResultSet(cursor, getVitessStatement());
> ```

Is it required to pass VitessStatement object in all the tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by bbeaudreault** [comment]
Review status: 12 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java, line 66 at r4](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbnJKEAeFB8D95TUeCo:-Kc-evqqT8aicY9SwcJB:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/d0557ce36e6ae861c532da246713bc3123c44c08/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSetMetaData.java#L66)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

Should this not return ResultSetMetaData.columnNullable instead of ResultSetMetaData.columnNullableUnknown
</blockquote></details>

Done.

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessResultSetTest.java, line 202 at r5](https://reviewable.io:443/reviews/youtube/vitess/2489#-KbyQt7almVCdRsWymcH:-Kc-dbAdF5pVI2-83jhm:b-3mhs2q) ([raw file](https://github.com/youtube/vitess/blob/95390d017cf2cc6d5a269bfec6ad1977c681e0ed/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/VitessResultSetTest.java#L202)):*
<details><summary><i>Previously, harshit-gangal wrote…</i></summary><blockquote>

Is it required to pass VitessStatement object in all the tests?
</blockquote></details>

Ok, I removed it from a couple of tests that didn't need it. But it is good to keep it in all of the tests that actually test the return value of the various getters. The reason is, in my next PR I'll be adding support charset encodings -- at that point, we'll always want to be able to check the connections configurations for these various things.

Does it sound ok to leave these here, considering they will become useful in the next PR?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489)*

**Comment by harshit-gangal** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r7.
Review status: 11 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2489#-:-KcSNC2vtVVe7HXAH_-v:bnfp4nl)*

**Comment by bbeaudreault** [comment]
Thanks @harshit-gangal!

**Comment by bbeaudreault** [comment]
@sougou would you mind merging this when you get the chance? Got the LGTM from harshit

**Comment by sougou** [comment]
LGTM

**Pull request merged**
