### PR TITLE
Add Kubernetes StatefulSet demo.

### PR DESCRIPTION
**Pull request by enisoc**
These are presenter materials that can be used to demo Vitess in
Kubernetes with StatefulSet and PersistentVolume support.

@sougou @CaptTofu

### CODE REVIEW

**Comment by CaptTofu** [comment]
thank you!

**Comment by sougou** [comment]
I can merge this in if you can fix the codecliemate issues :)

**Comment by CaptTofu** [comment]
Sorry for the delay! Busy week. I will look at the codeclimate issues - never used codeclimate, but might as well start.

**Comment by sougou** [comment]
Can you create an updated PR? Alain has migrated us to etcd2.

**Comment by arthurnn** [comment]
cc @shlomi-noach

**Comment by enisoc** [comment]
The main purpose of this PR was to share the demo with Patrick for his talk. The demo itself is actually pretty old. The new version of this demo will be much simpler after the Vitess Operator is ready.

**Pull request closed without merging**
