### PR TITLE
Remove tabletserver.GetSessionId, update PHP proto files.

### PR DESCRIPTION
**Pull request by alainjobart**
@guoliang100 @sougou for the first two non-PHP commit.

@enisoc for the last two docker and PHP related changes.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1678)

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM for the PHP proto parts.

---

Reviewed 16 of 37 files at r1.
Review status: 16 of 37 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Makefile, line 107 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1678#-KGxfI6DZ8M0fI4jPP0D:-KGxfI6EJ_3z7qakkCq5:-418755402) ([raw file](https://github.com/youtube/vitess/blob/d6028e9ecaa846fdb9c5f9f14d6bc7dd6c59c0e7/Makefile#L107)):*
Ideally we would copy the proto files in when we run the container, rather than having to rebuild the image every time, but this should work for now. I can fix it later.

---

*[Makefile, line 110 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1678#-KGxex2eoGsRUpycbUUT:-KGxex2eoGsRUpycbUUU:-1841292678) ([raw file](https://github.com/youtube/vitess/blob/d6028e9ecaa846fdb9c5f9f14d6bc7dd6c59c0e7/Makefile#L110)):*
Technically, the proto compiler also generates `php/src/{descriptor,php}.php`, although I think they would only change if we upgrade the compiler version.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1678#-:-KGxgJXt1Ew6pmhMe6Pl:-1379740261)*

**Comment by alainjobart** [comment]
Review status: 16 of 37 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Makefile, line 107 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1678#-KGxfI6DZ8M0fI4jPP0D:-KGxiLulTYnTnuAB30iP:823546692) ([raw file](https://github.com/youtube/vitess/blob/d6028e9ecaa846fdb9c5f9f14d6bc7dd6c59c0e7/Makefile#L107)):*
My docker knowledge is limited, I agree, but couldn't do it in a short amount of time. That's why I added the dependency on the image building, as a work around, to make sure we do both at the same time.

---

*[Makefile, line 110 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1678#-KGxex2eoGsRUpycbUUT:-KGxioZ2j1qFrcHENfcd:-813033153) ([raw file](https://github.com/youtube/vitess/blob/d6028e9ecaa846fdb9c5f9f14d6bc7dd6c59c0e7/Makefile#L110)):*
I'll fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1678)*

**Comment by sougou** [comment]
LGTM for tabletserver.

**Comment by guoliang100** [comment]
LGTM for Go changes.

**Pull request merged**
