### PR TITLE
Added splitquery.Splitter and test.

### PR DESCRIPTION
**Pull request by erzel**
@dumbunny please take a look.

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1527)

### CODE REVIEW

**Comment by erzel** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/vt/tabletserver/splitquery/split_params.go, line 50 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBngwug_FuUo7EDmfrs:-KBngwug_FuUo7EDmfrt:-1439928213) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/split_params.go#L50)):*
Comment from: @dumbunny: You are already checking len(selectAST.From) in the previous if statement.
My reply: Thanks. Removed.

---

*[go/vt/tabletserver/splitquery/splitter_test.go, line 140 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBnhsM69wQC-AB6LMM6:-KBnhsM69wQC-AB6LMM7:-701231109) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter_test.go#L140)):*
Comment from @dumbunny: "The parentheses around the inner AND factors and the comparators are not needed due to operator precedence. Only the outermost parentheses are needed."

These are auto-generated. I can tweak the algorithm to make it rely on precedence order, but do you think that would be better?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1527)*

**Comment by dumbunny** [comment]
*[go/vt/tabletserver/splitquery/splitter_test.go, line 140 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBnhsM69wQC-AB6LMM6:-KBo2XPriCURAGL07Rc4:-1804345304) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter_test.go#L140)):*
Removing the parentheses around the (<, =, <=) expressions would make it more clear (change ParenBoolExpr to just BoolExpr). On the other hand, it is easy for programmers to forget AND vs. OR, so removing the expressions around the and is not worthwhile.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1527)*

**Comment by dumbunny** [comment]
*[go/vt/tabletserver/splitquery/splitter.go, line 247 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoErRw8sHW028ibruR:-KBoErRw8sHW028ibruS:-1191077869) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter.go#L247)):*
Should be "assertion %v >= %v failed"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1527)*

**Comment by dumbunny** [comment]
*[go/vt/tabletserver/splitquery/split_algorithm_interface.go, line 12 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoGWXrFUt5OnSH6FhA:-KBoGWXrFUt5OnSH6FhB:397014281) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/split_algorithm_interface.go#L12)):*
The above line should replace the period after the "If" phrase with a comma.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1527)*

**Comment by dumbunny** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[go/vt/tabletserver/splitquery/splitter.go, line 197 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoF8BmuJ_d20vTISnQ:-KBoF8BmuJ_d20vTISnR:-1355630494) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter.go#L197)):*
(as stated elsewhere, change ParenBoolExpr to BoolExpr).

---

*[go/vt/tabletserver/splitquery/splitter.go, line 198 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoG6T-UF4Mxjm6Nf4m:-KBoG6T-UF4Mxjm6Nf4n:478691673) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter.go#L198)):*
You should add a test that checks a 3-tuple inequality.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1527)*

**Comment by erzel** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/vt/tabletserver/splitquery/split_algorithm_interface.go, line 12 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoGWXrFUt5OnSH6FhA:-KBoVy-6YxnOG3nx9paS:255542303) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/split_algorithm_interface.go#L12)):*
Thanks! Done.

---

*[go/vt/tabletserver/splitquery/splitter.go, line 197 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoF8BmuJ_d20vTISnQ:-KBoW1GXmbCl_ABS7kkV:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter.go#L197)):*
Done.

---

*[go/vt/tabletserver/splitquery/splitter.go, line 198 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoG6T-UF4Mxjm6Nf4m:-KBoW21iK3XadEI9BYxv:490966939) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter.go#L198)):*
Ok if I do that in the next PR?

---

*[go/vt/tabletserver/splitquery/splitter.go, line 247 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBoErRw8sHW028ibruR:-KBoW4ApFZwtQMZ8suET:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter.go#L247)):*
Done.

---

*[go/vt/tabletserver/splitquery/splitter_test.go, line 140 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1527#-KBnhsM69wQC-AB6LMM6:-KBoW5hXLO3-i8h3kxjg:-1068511459) ([raw file](https://github.com/youtube/vitess/blob/5b2d34c6653f6dd50a895dc228b81ceb9de1e2cb/go/vt/tabletserver/splitquery/splitter_test.go#L140)):*
Agreed. Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1527)*

**Comment by dumbunny** [comment]
LGTM

**Pull request merged**
