### PR TITLE
Added unit tests for vtdb.tablet using the mock library

### PR DESCRIPTION
**Pull request by aaijazi**
@enisoc: I think I vendored the mock library correctly, but please take a look. The only file you need to look at is bootstrap.sh. Also let me know if I need to do anything else to get it working on docker etc.

@alainjobart 

The second commit contains the bug fix and promised unit tests.

### CODE REVIEW

**Comment by enisoc** [comment]
Since it requires an installation step anyway, can we vendor it as a tbz, like we do for zookeeper?

**Comment by enisoc** [comment]
Or, if there's a reliable way to download a given revision, we could use wget like we do for proto3?

**Comment by aaijazi** [comment]
@enisoc changed it so that I vendored as a tar.gz. I'd prefer not to wget, because I don't want our build to break due to an external website going away or changing its structure.

I rewrote the git history so we don't have the mock source checked in until the end of time. We will instead have the mock binary file, which is 800K and not likely to change much.

**Comment by enisoc** [comment]
LGTM

**Comment by aaijazi** [comment]
@enisoc: it seems like my test if failing in the Docker test runner. I assume I need to update the bootstrap docker image, but I'm not able to. I modified the PYTHONPATH in Dockerfile.common, and then tried running `make docker_bootstrap flavor=mariadb` and `make docker_bootstrap flavor=mysql56`, but that didn't seem to work.

Advice?

**Comment by enisoc** [comment]
The Makefile doesn't automatically rebuild the "common" image. So it should work if you first run "make docker_bootstrap flavor=common" before building the other two.

**Pull request merged**
