### PR TITLE
Jdbc preparedstatement func

### PR DESCRIPTION
**Pull request by ashudeep-sharma**
This Pull Request Contains the following Changes:

- Added Support for setObject(int parameterIndex, Object parameterObject, int targetSqlType,
        int scaleOrLength) function in PreparedStatement.
- Fixing DatabaseMetadata Test-cases, shuffled the expected and actual Parameters in Asset.AssertEquals
- Implementation of getVersionColumns() in DatabaseMetadata
- Added Test-cases for the above functionalities.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1631)

### CODE REVIEW

**Comment by naveen-nahata** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 707 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1631#-KF0fVhILLpnO5ggOGuF:-KF0fVhILLpnO5ggOGuG:13527187) ([raw file](https://github.com/youtube/vitess/blob/418624f80ae378db4abdc8c9cf8839a7a5a0abf7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L707)):*
Can we add these utilities in StringUtils ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1631)*

**Comment by enisoc** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 707 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1631#-KF0fVhILLpnO5ggOGuF:-KF6TvYYFFZPofGTEgqr:5172523) ([raw file](https://github.com/youtube/vitess/blob/418624f80ae378db4abdc8c9cf8839a7a5a0abf7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L707)):*
+1

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1631)*

**Comment by ashudeep-sharma** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 707 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1631#-KF0fVhILLpnO5ggOGuF:-KF7z4kHnUV4v0MQVOTT:2117675008) ([raw file](https://github.com/youtube/vitess/blob/418624f80ae378db4abdc8c9cf8839a7a5a0abf7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L707)):*
Done. Incorporated in commit https://github.com/youtube/vitess/commit/5f72fbb205e0558749463ccd03bf456ba858ad42

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1631)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1631#-:-KFAkmDPxmnpT3ySJ972:1417088721)*

**Comment by ashudeep-sharma** [comment]
Merged this branch to Master in commit https://github.com/youtube/vitess/commit/f1638400447648e4ba08b1df74b776b2f6284f4a

**Pull request merged**
