### PR TITLE
Adding support for gRPC TLS in Vitess.

### PR DESCRIPTION
**Pull request by alainjobart**
With this change, go and python clients can now be encrypted. It means all communications within a Vitess cluster can be secure.

The server side takes a cert and a key, and an optional ca list for which clients can connect.
The client side takes a cert and key (if it needs it to connect to the master), and a ca list to validate the server identity.

With this, tableACLs on vttablet side can be used to grant access for specific clients to specific tables.

@sougou @enisoc

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1616)

### CODE REVIEW

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1616#-:-KEX_48Wx07TUoY_ASg1:1417088721)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1616#-:-KEY8-k7pnIXMNYYM0eU:1417088721)*

**Comment by sougou** [comment]
LGTM

**Comment by enisoc** [comment]
@alainjobart I tried to `./preview-site.sh`, but it looks like the `<img src="https://raw.githubusercontent.com...` trick doesn't work for SVG, perhaps because the server gives it a Content-Type of `text/plain`. Can you switch it to PNG, which seems to work for LifeOfAQuery?

**Comment by alainjobart** [comment]
My guess is the local preview server won't work, but the final web site will work. I'd like to try it out, at least. I don't want to maintain PNG files when the SVG version can be imported and worked on directly with other tools, if possible... Do you mind publishing as an experiment, and I'll make the PNG if it doesn't work?

**Comment by enisoc** [comment]
Published: http://vitess.io/user-guide/transport-security-model.html

**Comment by enisoc** [comment]
If you want to use SVG, I think it will work if you move the SVG file to $VTTOP/vitess.io/images and link to `http://vitess.io/images/blah.svg`. I suspect it's because of this:

https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#why-is-this-necessary-cant-i-just-load-files-from-github-directly

**Pull request merged**
