### PR TITLE
Introduce error for types that can't be bound to proto3.

### PR DESCRIPTION
**Pull request by dominichamon**
Plumb the error all the way through the stack.

I didn't spot any proto3 tests to which i could add something, but let me know if i just missed them.

### CODE REVIEW

**Comment by dominichamon** [comment]
@sougou @michael-berlin

**Comment by michael-berlin** [comment]
@alainjobart proto.BindVariablesToProto3() looks like a perfect candidate for a unit test.

But it looks like we don't have one yet? We should add one later? I can take care of that.

**Comment by dominichamon** [comment]
@michael-berlin i agree. i went looking :)

**Comment by michael-berlin** [comment]
LGTM

Thanks a lot for the contribution Dominic :-)

I go ahead and merge it now.

**Comment by alainjobart** [comment]
On the unit test comment:
- we have some coverage already in the protocol tests, where we send structures back and forth.
- that code is going away, once we switch to proto3 everywhere. Then all we'll have is conversion from proto2 to proto3 and back.

Then, I agree we should have unit tests for code like this, especially error cases. Let's add some when the code is more stable and won't go away in a month.

**Pull request merged**
