### PR TITLE
Refactor sql_builder.py

### PR DESCRIPTION
**Pull request by dumbunny**
@michael-berlin

### CODE REVIEW

**Comment by michael-berlin** [comment]
LGTM

**Comment by dumbunny** [comment]
@michael-berlin This change is non-trivial now. I added some base classes to sql_builder (BaseSQLUpdateExpr, BaseSQLWhereExpr, etc.), and added some code coverage in sql_builder_test.py.

**Comment by michael-berlin** [comment]
LGTM

The test looks great :-)

Feel free to address my comments. I'll let you decide how far you want to go there.

**Comment by dumbunny** [comment]
PTAL. I'll make the new target and look into splitting utils.py up.

**Pull request merged**
