### PR TITLE
Fix for Issue:1731, drop table if exists may not result in schema change

### PR DESCRIPTION
**Pull request by ashudeep-sharma**
This Pull Request covers the fix for issue #1731, 
Certain Statements like drop table if exists may not result in a schema change. This fix validates if the schema diff is zero and the query is dropStr, it shouldn;t throw an error in ApplySchema. 

@michael-berlin , @alainjobart .Please check and let me know in case of any concerns.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1764)

### CODE REVIEW

**Comment by michael-berlin** [comment]
Thank you very much for this!

It looks good and I fully support this change.

I left a few comments. Can you please realize these? After that, I'll merge it. Thanks!

<details><summary><i>Previously, ashudeep-sharma (Ashu) wrote…</i></summary>
> #### Fix for Issue:1731, drop table if exists may not result in schema change
> 
> This Pull Request covers the fix for issue #1731, 
> 
> Certain Statements like drop table if exists may not result in a schema change. This fix validates if the schema diff is zero and the query is dropStr, it shouldn;t throw an error in ApplySchema. 
> 
> 
> 
> @michael-berlin , @alainjobart .Please check and let me know in case of any concerns.
> 
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[go/vt/schemamanager/tablet_executor.go, line 94 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbFhEBp3XkSUb5dkkm:-KJbFhEBp3XkSUb5dkkn:2081716986) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L94)):*
> ```Go
> }
> 
> func (exec *TabletExecutor) getParsedDDLS(ctx context.Context, sqls []string) ([]*sqlparser.DDL, error) {
> ```

Please rename this to "parseDDLs" because it's actually not parsed yet and the method actively parses the statements.

get* implies that it's already parsed and stored as a field.

(FYI: Even if this was a field getter, Go discourages to use "get" as prefix for these because it's redundant. I.e. the method would be called parsedDDLs(). I understand that it's different in Java :) )

---

*[go/vt/schemamanager/tablet_executor.go, line 94 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbGlGQeEce2D22fxPL:-KJbGlGQeEce2D22fxPM:-1673100328) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L94)):*
> ```Go
> }
> 
> func (exec *TabletExecutor) getParsedDDLS(ctx context.Context, sqls []string) ([]*sqlparser.DDL, error) {
> ```

By turning this into a helper function, you can simplify its signature:

- make it a (static) function instead of a (class/struct) method: therefore remove "(exec *TabletExecutor)"
- remove the "ctx" parameter because it's not used

---

*[go/vt/schemamanager/tablet_executor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbIaHsHA68W30JWudn:-KJbIaHsHA68W30JWudo:994361898) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L119)):*
> ```Go
> 	}
> 
> 	parsedDDLs, err := exec.getParsedDDLS(ctx,sqls)
> ```

You must always handle errors returned by functions.

A simple return in case of an error is fine here:

```go
parsedDDLs, err := exec.getParsedDDLS(ctx,sqls)
if err != nil {
  return err
}
```

Note: The unit tests are currently failing because you don't return the error here. When you add the error check, they should succeed again.
FYI: You can run the unit tests as follows:

 ```sh
cd go/vt/schemamanager
go test
```

---

*[go/vt/schemamanager/tablet_executor.go, line 172 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbItLjFVAEtw5JikEa:-KJbItLjFVAEtw5JikEb:-551174761) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L172)):*
> ```Go
> 	}
> 
> 	parsedDDLs, err := exec.getParsedDDLS(ctx,sqls)
> ```

Same comment as above:

A simple return in case of an error is missing here:

```go
parsedDDLs, err := exec.getParsedDDLS(ctx,sqls)
if err != nil {
  return err
}
```

---

*[go/vt/schemamanager/tablet_executor.go, line 180 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbHzHD_KbLT-8OqLb9:-KJbHzHD_KbLT-8OqLbA:1964312638) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L180)):*
> ```Go
> 			"AfterSchema",
> 			schemaDiff.AfterSchema)
> 		if len(diffs) == 0 && parsedDDLs[i].Action!= sqlparser.DropStr{
> ```

nit: missing space before "!=" and "{". The precommit should have warned you about it and asked you to run "goimports" on the file first.

"goimports" will auto-format the file for you:

```sh
goimports -w go/vt/schemamanager/tablet_executor.go
```

When you use "GoClipse", you can also configure it to always run it on save.

---

*[go/vt/schemamanager/tablet_executor.go, line 180 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbJ4ZfOEc-n16F5t2A:-KJbJ4ZfOEc-n16F5t2B:1816943710) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L180)):*
> ```Go
> 			"AfterSchema",
> 			schemaDiff.AfterSchema)
> 		if len(diffs) == 0 && parsedDDLs[i].Action!= sqlparser.DropStr{
> ```

I would prefer to explicitly call out this exemption and add a comment for it.

In addition to that, I think we should only exempt it if it's a DROP IF EXISTS and not every DROP. I understand that the SQL Parser currently cannot tell you the difference. Therefore, it's fine to add a TODO for this for now.

Based on these comments, I propose the following change:

```go
		if len(diffs) == 0 {
			if parsedDDLs[i].Action == sqlparser.DropStr {
				// DROP IF EXISTS on a nonexistent table does not change the schema. It's safe to ignore.
				// TODO(mberlin): Extend sqlparser to find out if the DDL contains IF EXISTS and check for it as well.
				continue
			}
			return fmt.Errorf("Schema change: '%s' does not introduce any table definition change.", sqls[i])
		}
```

---

*[test/schema.py, line 279 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbO8MmcORMGMpr6HD5:-KJbO8MmcORMGMpr6HD6:-75861138) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L279)):*
> ```Python
>     self._check_tables(shard_1_master, 4)
> 
>   def test_schema_changes_drop_if_exists(self):
> ```

I suggest to rename it to `test_schema_changes_drop_nonexistent_tables` because it's more about testing the behavior of dropping nonexistent tables than DROP TABLE IF EXISTS specifically.

---

*[test/schema.py, line 280 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbLaWm-PmKtrOVVlOU:-KJbLaWnXEfrOBesAPyl:234482535) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L280)):*
> ```Python
> 
>   def test_schema_changes_drop_if_exists(self):
>     self._apply_initial_schema()
> ```

I suggest to add a short comment here to explain what the test is supposed to test:

```py
    """Tests the PreflightSchema logic for dropping nonexistent tables.

    If a table does not exist, DROP TABLE should error during preflight
    because the statement does not change the schema as there is
    nothing to drop.
    In case of DROP TABLE IF EXISTS though, it should not error as this
    is the MySQL behavior the user expects.
    """
```

---

*[test/schema.py, line 284 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbMnKwzgk9r7NYWotl:-KJbMnKxLYbBJk0RRz54:380615054) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L284)):*
> ```Python
>     self._check_tables(shard_1_master, 4)
> 
>     drop_table = ('DROP TABLE vt_select_test06;\n')
> ```

I suggest to use a more explicit table name here which will self-explain the fact that the table does not exist.

e.g.:

```py
drop_table = ('DROP TABLE nonexistent_table;)
```

---

*[test/schema.py, line 284 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbMt96MtqeuVQvU52X:-KJbMt96MtqeuVQvU52Y:-1143738735) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L284)):*
> ```Python
>     self._check_tables(shard_1_master, 4)
> 
>     drop_table = ('DROP TABLE vt_select_test06;\n')
> ```

nit: No "\n" necessary at the end.

---

*[test/schema.py, line 286 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbJvHA8IbPcyZR7n97:-KJbJvHA8IbPcyZR7n98:366987687) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L286)):*
> ```Python
>     drop_table = ('DROP TABLE vt_select_test06;\n')
>     stdout = self._apply_schema(test_keyspace, drop_table, expect_fail=True)
>     self.assertIn('Unknown table', ''.join(stdout))
> ```

Based on the code above, it looks like this fails in the actual operation and not in the preflight phase?

If that's the case, can you please add a TODO here? Feel free to tag it with my name.

```
# TODO(mberlin): This currently fails during the actual change.
# schemamanager should fail in preflight instead. Change the error message 
# we check for once schemamanager prevents this in the preflight phase.
```

---

*[test/schema.py, line 288 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbL5CzRragaH_SStUd:-KJbL5CzRragaH_SStUe:1183660520) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L288)):*
> ```Python
>     self.assertIn('Unknown table', ''.join(stdout))
> 
>     #This Query may not result in schema change and should be allowed
> ```

nit: Missing space after "#".
nit: Missing period at the end. (Always try to use full sentences.)

---

*[test/schema.py, line 292 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbLCbhnrHcP8WAbRcP:-KJbLCbhnrHcP8WAbRcQ:-795085262) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L292)):*
> ```Python
>     self._apply_schema(test_keyspace, drop_if_exists)
> 
>   # check number of tables
> ```

nit: comment not correctly indented.

I suggest to remove it instead. The code is self-explanatory enough :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1764#-:-KJbVZ7bFla3T2BFJtOg:1644363784)*

**Comment by ashudeep-sharma** [comment]
Review status: 0 of 2 files reviewed at latest revision, 13 unresolved discussions.

---

*[go/vt/schemamanager/tablet_executor.go, line 94 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbFhEBp3XkSUb5dkkm:-KJf5gCfvd2QsVgN8urI:541070942) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L94)):*
> goimports -w go/vt/schemamanager/tablet_executor.go

---

*[go/vt/schemamanager/tablet_executor.go, line 94 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbGlGQeEce2D22fxPL:-KJf6SK1sbvzwPJ5sP-c:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L94)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> By turning this into a helper function, you can simplify its signature:
> 
> - make it a (static) function instead of a (class/struct) method: therefore remove "(exec *TabletExecutor)"
> - remove the "ctx" parameter because it's not used
</details>
Done.

---

*[go/vt/schemamanager/tablet_executor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbIaHsHA68W30JWudn:-KJf7DRisQ1A0dsaZUv1:1862931100) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L119)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> You must always handle errors returned by functions.
> 
> A simple return in case of an error is fine here:
> 
> ```go
> parsedDDLs, err := exec.getParsedDDLS(ctx,sqls)
> if err != nil {
>   return err
> }
> ```
> 
> Note: The unit tests are currently failing because you don't return the error here. When you add the error check, they should succeed again.
> FYI: You can run the unit tests as follows:
> 
>  ```sh
> cd go/vt/schemamanager
> go test
> ```
</details>
I tried fixing TestTabletExecutorExecute in tablet_executor_test.go, there seems to be a weird problem that i identified, the queries like "drop table" and "drop table if exists" corresponds to 2 rows in schemaDiff array in preflightSchemaChanges function, one of them being nil. I just want to checkout why is it happening that it results in 2 schemadiffs, ideally it should result in only one diff.

Also just wanted to checkout that we are not doing null check for schemaDiff in this piece of code:

for i, schemaDiff := range schemaDiffs {
		diffs := tmutils.DiffSchemaToArray(
			"BeforeSchema",
			schemaDiff.BeforeSchema,
			"AfterSchema",
			schemaDiff.AfterSchema)
		if len(diffs) == 0 {
			if parsedDDLs[i].Action == sqlparser.DropStr {
				// DROP IF EXISTS on a nonexistent table does not change the schema. It's safe to ignore.
				// TODO(mberlin): Extend sqlparser to find out if the DDL contains IF EXISTS and check for it as well.
				continue
			}
			return fmt.Errorf("Schema change: '%s' does not introduce any table definition change.", sqls[i])
		}
	}
Is it okay to go with this change? Let me know your thoughts and i will fix the tests.

---

*[go/vt/schemamanager/tablet_executor.go, line 172 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbItLjFVAEtw5JikEa:-KJf6P4l7R4Yi2j4y4xP:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L172)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Same comment as above:
> 
> A simple return in case of an error is missing here:
> 
> ```go
> parsedDDLs, err := exec.getParsedDDLS(ctx,sqls)
> if err != nil {
>   return err
> }
> ```
</details>
Done.

---

*[go/vt/schemamanager/tablet_executor.go, line 180 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbJ4ZfOEc-n16F5t2A:-KJf6NEGjvaob4OFE582:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L180)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> I would prefer to explicitly call out this exemption and add a comment for it.
> 
> In addition to that, I think we should only exempt it if it's a DROP IF EXISTS and not every DROP. I understand that the SQL Parser currently cannot tell you the difference. Therefore, it's fine to add a TODO for this for now.
> 
> Based on these comments, I propose the following change:
> 
> ```go
> 		if len(diffs) == 0 {
> 			if parsedDDLs[i].Action == sqlparser.DropStr {
> 				// DROP IF EXISTS on a nonexistent table does not change the schema. It's safe to ignore.
> 				// TODO(mberlin): Extend sqlparser to find out if the DDL contains IF EXISTS and check for it as well.
> 				continue
> 			}
> 			return fmt.Errorf("Schema change: '%s' does not introduce any table definition change.", sqls[i])
> 		}
> ```
</details>
Done.

---

*[go/vt/schemamanager/tablet_executor.go, line 180 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbHzHD_KbLT-8OqLb9:-KJf6O-lIGS_OwbezEr_:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L180)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> nit: missing space before "!=" and "{". The precommit should have warned you about it and asked you to run "goimports" on the file first.
> 
> "goimports" will auto-format the file for you:
> 
> ```sh
> goimports -w go/vt/schemamanager/tablet_executor.go
> ```
> 
> When you use "GoClipse", you can also configure it to always run it on save.
</details>
Done.

---

*[test/schema.py, line 279 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbO8MmcORMGMpr6HD5:-KJf6BfoQLqFz4AFzLhJ:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L279)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> I suggest to rename it to `test_schema_changes_drop_nonexistent_tables` because it's more about testing the behavior of dropping nonexistent tables than DROP TABLE IF EXISTS specifically.
</details>
Done.

---

*[test/schema.py, line 280 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbLaWm-PmKtrOVVlOU:-KJf6AcRhghM2ycULEvM:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L280)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> I suggest to add a short comment here to explain what the test is supposed to test:
> 
> ```py
>     """Tests the PreflightSchema logic for dropping nonexistent tables.
> 
>     If a table does not exist, DROP TABLE should error during preflight
>     because the statement does not change the schema as there is
>     nothing to drop.
>     In case of DROP TABLE IF EXISTS though, it should not error as this
>     is the MySQL behavior the user expects.
>     """
> ```
</details>
Done.

---

*[test/schema.py, line 284 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbMt96MtqeuVQvU52X:-KJf68uUn4xcvbUq5qBC:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L284)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> nit: No "\n" necessary at the end.
</details>
Done.

---

*[test/schema.py, line 284 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbMnKwzgk9r7NYWotl:-KJf69pxuV8Hxj2ddhRG:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L284)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> I suggest to use a more explicit table name here which will self-explain the fact that the table does not exist.
> 
> e.g.:
> 
> ```py
> drop_table = ('DROP TABLE nonexistent_table;)
> ```
</details>
Done.

---

*[test/schema.py, line 286 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbJvHA8IbPcyZR7n97:-KJf688Ot-d2vwqq753v:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L286)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Based on the code above, it looks like this fails in the actual operation and not in the preflight phase?
> 
> If that's the case, can you please add a TODO here? Feel free to tag it with my name.
> 
> ```
> # TODO(mberlin): This currently fails during the actual change.
> # schemamanager should fail in preflight instead. Change the error message 
> # we check for once schemamanager prevents this in the preflight phase.
> ```
</details>
Done.

---

*[test/schema.py, line 288 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbL5CzRragaH_SStUd:-KJf61TGJtRI-QdeZb90:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L288)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> nit: Missing space after "#".
> nit: Missing period at the end. (Always try to use full sentences.)
</details>
Done.

---

*[test/schema.py, line 292 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbLCbhnrHcP8WAbRcP:-KJf60EnNevtO88SXWcK:-499146009) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/test/schema.py#L292)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> nit: comment not correctly indented.
> 
> I suggest to remove it instead. The code is self-explanatory enough :)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1764)*

**Comment by michael-berlin** [comment]
Reviewed 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[go/vt/schemamanager/tablet_executor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbIaHsHA68W30JWudn:-KJl9c3xZyRJqgNsOMk4:806157632) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L119)):*
<details><summary><i>Previously, ashudeep-sharma (Ashu) wrote…</i></summary>
> I tried fixing TestTabletExecutorExecute in tablet_executor_test.go, there seems to be a weird problem that i identified, the queries like "drop table" and "drop table if exists" corresponds to 2 rows in schemaDiff array in preflightSchemaChanges function, one of them being nil. I just want to checkout why is it happening that it results in 2 schemadiffs, ideally it should result in only one diff.
> 
> Also just wanted to checkout that we are not doing null check for schemaDiff in this piece of code:
> 
> for i, schemaDiff := range schemaDiffs {
> 		diffs := tmutils.DiffSchemaToArray(
> 			"BeforeSchema",
> 			schemaDiff.BeforeSchema,
> 			"AfterSchema",
> 			schemaDiff.AfterSchema)
> 		if len(diffs) == 0 {
> 			if parsedDDLs[i].Action == sqlparser.DropStr {
> 				// DROP IF EXISTS on a nonexistent table does not change the schema. It's safe to ignore.
> 				// TODO(mberlin): Extend sqlparser to find out if the DDL contains IF EXISTS and check for it as well.
> 				continue
> 			}
> 			return fmt.Errorf("Schema change: '%s' does not introduce any table definition change.", sqls[i])
> 		}
> 	}
> Is it okay to go with this change? Let me know your thoughts and i will fix the tests.
</details>
The nil error was my bad. I fixed it here: https://github.com/youtube/vitess/pull/1770

The test will keep failing because we changed the code. It will stop failing when the parser exposes an IF EXISTS flag to us and we extend the fake.

For now, I suggest to delete the test. The test were actually two, so I did split them: https://github.com/youtube/vitess/pull/1771

Please merge the master or rebase your branch to the latest master. Then you'll have the two changes.

After that, you can comment the TestTabletExecutorExecute_PreflightWithoutChangesIsAnError  test and leave a TODO there that we can uncomment it when we improve that code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1764)*

**Comment by ashudeep-sharma** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/schemamanager/tablet_executor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbIaHsHA68W30JWudn:-KJlfwd6GfxK8tTc1AYr:-479568718) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L119)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> The nil error was my bad. I fixed it here: https://github.com/youtube/vitess/pull/1770
> 
> The test will keep failing because we changed the code. It will stop failing when the parser exposes an IF EXISTS flag to us and we extend the fake.
> 
> For now, I suggest to delete the test. The test were actually two, so I did split them: https://github.com/youtube/vitess/pull/1771
> 
> Please merge the master or rebase your branch to the latest master. Then you'll have the two changes.
> 
> After that, you can comment the TestTabletExecutorExecute_PreflightWithoutChangesIsAnError  test and leave a TODO there that we can uncomment it when we improve that code.
</details>
Done.
Commented out the test and verified that the go test ran fine on my machine. I am a bit curious to know if its a bit involved task to parse If Exists clause from Drop Table, if not i can take that up, might need some initial points :).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1764)*

**Comment by michael-berlin** [comment]
:lgtm:

<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Thank you very much for this!
> 
> It looks good and I fully support this change.
> 
> I left a few comments. Can you please realize these? After that, I'll merge it. Thanks!
</details>


---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/schemamanager/tablet_executor.go, line 119 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1764#-KJbIaHsHA68W30JWudn:-KJnhUVdxUJwNxpP7cYw:-254796520) ([raw file](https://github.com/youtube/vitess/blob/6b7e075d44baaa588371a32790b9d36d3e9b09f1/go/vt/schemamanager/tablet_executor.go#L119)):*
<details><summary><i>Previously, ashudeep-sharma (Ashu) wrote…</i></summary>
> Done.
> Commented out the test and verified that the go test ran fine on my machine. I am a bit curious to know if its a bit involved task to parse If Exists clause from Drop Table, if not i can take that up, might need some initial points :).
</details>
It's a bit of work. If you want to give it a try,  here's what needs to be done:

Sugu already showed me what needs to be done for that.
(I'm currently busy with other stuff and won't be able to do it myself in the next weeks.)

- extend the parser. This can be based on what Sugu showed me here: https://github.com/youtube/vitess/compare/master...sougou:mberlin?expand=1
=> the parser change takes place in "go/vt/sqlparser/sql.y"
- once the parser is changed, the parser Go code (sql.go) needs to be regenerated:
```sh
cd go/vt/sqlparser/
make
```

- in ast.go you can see that Sugu added a new field "IfExists". After the parser code (sql.go) is regenerated, it will always fill in this field for you.
- That's all you need to use it in the preflight schema code

Since the parser changes, the unit tests for it must be updated as well. The unit test has already cases for DROP IF EXISTS.
https://github.com/youtube/vitess/blob/master/go/vt/sqlparser/parse_test.go#L515

The unit test compares against the output of the Format() function. You must extend that to output "if exists" as well and then output the test cases:
https://github.com/youtube/vitess/blob/dc4c86779742ba9df5f16d4023996c480b097809/go/vt/sqlparser/ast.go#L391

(Initially, Sugu did not support IF EXISTS on purpose in the parser because it was not relevant for other parts of Vitess. Therefore, the Format() function currently omits "if exists".)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1764#-:-KJnnxVaIIJ-kBGfwHac:1417088721)*

**Comment by ashudeep-sharma** [comment]
Thanks Michael for the details, i will give it a try in the next few days and will get back in case i run into issues.

**Pull request merged**
