### PR TITLE
WIP: Sync proto files after changing the gRPC (?) version.

### PR DESCRIPTION
**Pull request by michael-berlin**
@alainjobart 

These changes are generated after running "make proto". Without these, "make build" does not succeed. But why do the tests pass for others without this change?

### CODE REVIEW

**Comment by yaoshengzhe** [comment]
would be better if we could auto generate these files when proto definition changes, I guess we could use "go generate" command to achieve this.

**Comment by alainjobart** [comment]
You probably bootstrapped with a new version of gRPC library that we don't have yet. With this change, we're gonna need to re-bootstrap (which is fine!). Once gRPC is stable, this pain should go away. We could use godeps for gRPC lib, but not sure how that works with programs that generate other files.

I didn't want to generate the .pb files every time because right now only the go gRPC library is needed to build, not the full C++ proto + gRPC library. If we're OK with adding the dependency for everybody, I'm fine generating them.

**Comment by michael-berlin** [comment]
I've deleted dist/grpc and then run bootstrap.sh.

That means I should have the gRPC version which is intended?

Not automatically building the proto is fine for me. I'm just wondering if I am the only one who recently ran bootstrap.sh?

**Comment by alainjobart** [comment]
I think bootstrap.sh was just recently changed to use '-u' for gRPC
library, which would force an update.

**Comment by yaoshengzhe** [comment]
'-u' is added, so bootstrap.sh will force to update the gRPC to the latest version. "go get" currently does not support package versioning and I feel force people to upgrade to the latest version would be better. FYI, I clone a clean vitess repo and ./bootstrap.sh; . ./dev.env; make build, everything works fine to me.

**Comment by michael-berlin** [comment]
Thanks for figuring this out :-)

https://github.com/youtube/vitess/pull/675 indeed fixes an existing installation like mine. I'm deleting this one.

**Pull request closed without merging**
