### PR TITLE
Support ENUM, VARCHAR and TIMESTAMP comparisons

### PR DESCRIPTION
**Pull request by tirsen**

### CODE REVIEW

**Comment by sougou** [comment]
enum and varchar cannot be trivially compared. Here are some counter-examples:

```
mysql> create table a(id int, val varchar(8), primary key(id));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into a values(1, 'a'), (2, 'B');
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select * from a order by val;
+----+------+
| id | val  |
+----+------+
|  1 | a    |
|  2 | B    |
+----+------+
2 rows in set (0.00 sec)

mysql> select * from a order by binary(val);
+----+------+
| id | val  |
+----+------+
|  2 | B    |
|  1 | a    |
+----+------+
2 rows in set (0.00 sec)
```

Varchar comparison is dictated by collation rules. For VTGate to match them, it needs to mimic MySQL's rules. The strategy I have in mind is to additionally pull `weight_string(val)` which will give me a lexically comparable equivalent of the string.

For enum:
```
mysql> insert into a values(1, 'b'), (2, 'a');
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> select * from a order by val;
+----+------+
| id | val  |
+----+------+
|  1 | b    |
|  2 | a    |
+----+------+
2 rows in set (0.00 sec)

mysql> select * from a order by binary(val);
+----+------+
| id | val  |
+----+------+
|  2 | a    |
|  1 | b    |
+----+------+
2 rows in set (0.00 sec)
```

Enum ordering depends on the enum number, not string. We have to look at an approach similar to `weight_string`, but that returns the underlying number instead of the string.

**Comment by tirsen** [comment]
I see. Well this works very well for us since we don't sort on ENUM or VARCHAR, we just use them in aggregations. So I suppose we would need to use this Vitess fork instead of the mainline until functionality has been implemented in the mainline.

**Comment by sougou** [comment]
Even for equality comparisons, mysql treats 'a' == 'A'. So, unless you're very confident about your data, you may still get some surprises.

The good news is that the `weight_string` approach is not too hard because most of the groundwork for it is already done. I can get back to it once I clear my backlog, or guide someone if they have the bandwidth.

**Comment by sougou** [comment]
@tirsen can we close this? I'll work on the more correct fix when I catch up on my backlogs.

**Comment by sougou** [comment]
I'll be closing this unless there are objections.

**Pull request closed without merging**
