### PR TITLE
Added support for IS [NOT] (TRUE|FALSE). Fixed IS [NOT] NULL 

### PR DESCRIPTION
**Pull request by shlomi-noach**
The sqlparser failed on the following valid statements:
- select 1 from t where a is true
- select 1 from t where a is not true
- select 1 from t where (a + b) is true
- select 1 from t where a is false
- select 1 from t where a is not false
- select 1 from t where (a < b) is true

Also, IS [NOT] NULL was incomplete. The parser failed on:
- select 1 from t where (a + b) is null
- select 1 from t where (a + b) is not null

(IS NULL was not aupported for a boolean_expression but only for a condition)

Treatment of IS TRUE, IS FALSE and IS NULL is identical.
Do note that IS NULL (and likewise IS TRUE, IS FALSE) is recognized in two distinct formats:
- NullCheck (existing format)
- NullExpr (new format)
The latter has a BoolExpr instead of a ValExpr and this unfortunate split seems to be required (or else there can be further magic I'm unaware of).

I've added tests in parse_pass to demonstrate and validate the new supported syntax.

### CODE REVIEW

**Comment by sougou** [comment]
This is a much deeper issue, and the CL only touches the surface. What is the intent of this change?
Do you actually want to use these constructs, or are you just trying to make this grammar more complete?

This particular construct: 'select 1 from the where col is true' is the problematic one. What you're saying is that col is a boolean. This means that col should be allowed to participate in all boolean arithmetic, not just for 'is true', etc. If you abstract this out, you'll eventually end up merging boolean_expression and value-expression into one 'expression' that allows random intermixing of all boolean and arithmetic constructs.

OTOH, what is the practical use of boolean columns? To us, the answer was that they're not very useful. Most people don't use them because there are plenty of more efficient ways (like bitfields) to achieve the same functionality. So, we made a decision to not support them in vitess.

This simple decision allowed us to come up with a simpler and more robust grammar where we could clearly differentiate value expression constructs from the boolean ones.

Looking at your CL with the above background:
- Constructs like 'is false', etc. can be allowed. I mainly left them out because they're usually confusing and not very useful. But I can be convinced otherwise.
- 'is false' implies that the operand is a boolean. So, such constructs should only be allowed for a boolean_expression.
- For 'is [not] null', one can argue that they're applicable to boolean expressions also. I also don't think it will introduce any grammar conflicts. Again, my opinion here is that one shouldn't use this construct beyond testing the value of a column.

**Comment by shlomi-noach** [comment]
The use of `IS TRUE` is real, not just for the purpose of making the grammar more complete.
A common use of `IS TRUE` (and in fact also for `IS FALSE`) is to make sure some value is non-zero *and* non-null. For the sake of interest, let's discuss the case for `IS FALSE`:
`select * from t where (a > b) is false` strictly requires that `a > b`. Compare this to:
` select * from t where a > b`. In this latter query a row where a is `NULL` or b is `NULL` makes the `where` condition non-true -- though it's also non-false! So using `is false` is a way to reduce the SQL 3-valued logic to 2-valued.

Otherwise `is true` is a way of explicitly requiring that a value is non-zero. It is sometimes a redundant clause, but may make for a *clearer* query. This is a matter of convention, I agree.

Truly (pun intended), the best use cases are when NULLs are involved. Another such case is when using aggregate functions. Consider this snippet from [common_schema](https://common-schema.googlecode.com/svn/trunk/common_schema/doc/html/introduction.html) (a project I'm authoring):
```
CREATE OR REPLACE
ALGORITHM = TEMPTABLE
SQL SECURITY INVOKER
VIEW slave_status AS
  SELECT 
    SUM(IF(is_io_thread, TIME, NULL)) AS Slave_Connected_time,
    SUM(is_io_thread) IS TRUE AS Slave_IO_Running,
    SUM(is_sql_thread OR (is_system AND NOT is_io_thread)) IS TRUE AS Slave_SQL_Running,
    (SUM(is_system) = 2) IS TRUE AS Slave_Running,
    SUM(IF(is_sql_thread OR (is_system AND NOT is_io_thread), TIME, NULL)) AS Seconds_Behind_Master
  FROM 
    processlist_repl
;
```
Ignore the `VIEW` and look at the query: it transposes some table data via a common trick: `SUM(IF(some_col_holds_condition, col_value, NULL))`. But it might just be the case that `SUM` returns `NULL`, whilst the computed column should be a true (no pun) boolean value. `IS NULL` does it.

More examples can be provided, but I suggest that the above can represent honest use cases.

**Comment by sougou** [comment]
The 'is true' and 'is false' part of the argument sounds reasonable.
However, 'value_expression is true/false' will be a problem. I did a quick read-up on boolean arithmetic. MySQL seems to follow the C-style convention of non-zero is true: http://dev.mysql.com/doc/refman/5.5/en/logical-operators.html.
To allow this kind of syntax requires us to add a 'boolean_expression: value_expression' rule, which will transitively allow 'value_expression is true/false'. Unfortunately, this results in grammar conflicts just as I feared. So, it will be non-trivial to support this the correct way.
In other words, it's not a good idea to add an explicit 'value_expression is true/false' construct in the grammar. We should instead find a way to make the grammar look at a value expression as a bool expression, but without the conflicts.
The other constructs look good.

As for the AST, I've not given it much thought yet. I feel like there may be value in combining all the 'IS' expressions into one. I'll need to look at use cases first.

Speaking of use cases, changing the grammar is only part of the story. We also need to look at how these changes affect downstream processing. These two in particular:
- https://github.com/youtube/vitess/blob/master/go/vt/vtgate/planbuilder (select.go & where.go for sure)
- https://github.com/youtube/vitess/tree/master/go/vt/tabletserver/planbuilder. This is probably not affected, but I need to verify.

**Comment by sougou** [comment]
The silence is deafening :). If you still want the feature and don't want to break vitess, I can spin up a CL that does the first half for now: (BoolExpr (is| is not) (true|false|null).
As mentioned, ValExpr will take more work.

**Comment by shlomi-noach** [comment]
Haha, sorry. I thought you were taking a look into and was awaiting your
thoughts.

Yes, I want the feature if possible, much appreciated.

**Comment by sougou** [comment]
I'm _finally_ getting around to this :). Looking at it with a fresh set of eyeballs, I think your original proposal is a good one. If we special-cased the 'value_expression IS...' constructs, they don't really cause any grammar conflicts.
I'll retrofit this change into a new PR, and make sure the rest of the vitess stack can handle the new constructs also.

**Comment by shlomi-noach** [comment]
\o/

**Pull request closed without merging**
