### PR TITLE
Update color scheme. Remove unused CSS. This change modifies the site…

### PR DESCRIPTION
**Pull request by AndyDiamondstein**
… colors to follow guidance in the Material Design specification: https://www.google.com/design/spec/style/color.html#. It also changes the names of the color references in the CSS to use more clear variable names (primary, lighter, darker, accent) than (main, second, third, etc.). The changes to the favicon and image are to use the same colors in our images as on the site.

### CODE REVIEW

**Comment by aaijazi** [comment]
LGTM

**Comment by AndyDiamondstein** [comment]
Thanks. I went to merge the pull request and noticed that the Travis CI
build failed. Does that mean I shouldn't merge the pull request?
https://github.com/youtube/vitess/pull/1160

Or is there anything else I should do before merging it?

On Fri, Oct 2, 2015 at 10:56 AM, Ammar Aijazi <notifications@github.com>
wrote:

> LGTM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/youtube/vitess/pull/1160#issuecomment-145050644>.
>



-- 
Andy Diamondstein
Technical Writer
YouTube
650-253-4101 (desk)
415-812-7670 (cell)

**Comment by aaijazi** [comment]
The Travis failure was preexisting, and should be fixed now. You can update
with master and verify that Travis now passes on your branch.

**Comment by enisoc** [comment]
Published.

**Pull request merged**
