### PR TITLE
Update go-grpc to 1.7.0.

### PR DESCRIPTION
**Pull request by alecthomas**

### CODE REVIEW

**Comment by tirsen** [comment]
We're testing this in our unit tests and staging environment now.

**Comment by tirsen** [comment]
This is running in production for us now. We're seeing a significant drop in bandwidth usage.

**Comment by tirsen** [comment]
And here's some graphs, of CPU and bandwidth drop.
screen shot 2017-10-13 at 3 52 19 pm
screen shot 2017-10-13 at 3 53 28 pm

**Comment by bbeaudreault** [comment]
Awesome, +1 for this :)

**Comment by derekperkins** [comment]
@tirsen What's the scale on those charts? Are you using half the bandwidth/cpu that you were before?

**Comment by sougou** [comment]
LGTM
Exciting!

**Pull request merged**
