### PR TITLE
Resharding

### PR DESCRIPTION
**Pull request by alainjobart**
This is part of the topology server conversion to proto3: converting ShardReplication and Endpoints objects. Upon import, will have to fix the conversion to/from proto2 for chubby (but the proto2 versions won't change).

(still need to do SrvKeyspace, SrvShard, Tablet, Keyspace, and Shard).

### CODE REVIEW

**Comment by alainjobart** [comment]
@enisoc
(also I cherry-picked the encrypted port change already, so that's why the code is not in this)

**Comment by enisoc** [comment]
Can we rename ShardReplication.ReplicationLink to ShardReplication.Link in the proto? It seems like it always has to be referred to by its fully-qualified name, right?

LGTM otherwise.

**Comment by alainjobart** [comment]
It's not even a link any more, just a record, so maybe it should just be 'Tablet'. But yeah, it's a good time to rename it, I'll do that.

**Comment by alainjobart** [comment]
Renamed the structure, will wait for green Travis before merging.
@enisoc nothing extra from what we discussed, take a look if you want.

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
