### PR TITLE
java/example: Exit with non-zero return value in case of an error.

### PR DESCRIPTION
**Pull request by michael-berlin**
@enisoc Since the example is currently broken, Travis will fail now on this PR :)

I've confirmed locally that adding .checkedGet() to the two transaction calls makes the example pass again. So I'll wait for your commit to be merged before merging this one.

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1534)

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM

**Comment by enisoc** [comment]
Is this ready? I'd like this in before the beta cut.

**Comment by michael-berlin** [comment]
Yes, sorry I forgot to hit the merge button :(

**Comment by michael-berlin** [comment]
Waiting for Travis to pass.

**Pull request merged**
