### PR TITLE
Allow to use app2 and workflows in the k8s and local examples.

### PR DESCRIPTION
**Pull request by pivanof**
- Add vtctld2 app files into vitess/lite docker image used in the k8s example.
- Add flags to vtctld to use those files to render app2 and allow to use
  workflows.
- Add the same flags in the local example.

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM

**Comment by pivanof** [comment]
I've expanded the PR. PTAL.

**Comment by alainjobart** [comment]
LGTM we may also want to pass the flag to allow master election of the vtctld workflow manager, I think for etcd and zk it's just passing the extra flag.

**Comment by pivanof** [comment]
Added the master election flag. Tested it, it seems to work (nothing breaks).

**Comment by thompsonja** [comment]
LGTM

**Comment by alainjobart** [comment]
LGTM

**Pull request merged**
