### PR TITLE
mproto.QueryResult -> sqltypes.Result

### PR DESCRIPTION
**Pull request by sougou**
mproto is not quite dead yet. I still need to kill RPCError.

### CODE REVIEW

**Comment by alainjobart** [comment]
I think you can remove all the _bson files now. And sqltypes/result_test.bson.

LGTM otherwise, it's one more step forward!

**Comment by sougou** [comment]
I don't think we're quite ready to pull the plug on result_bson. I just put a panic in that function and the integration tests started failing.

**Comment by alainjobart** [comment]
Oh I think I know why, client -> vtgate still uses bson in python, which would as a side effect bson-encode/decode Result. I'm just saying we should just remove *all* _bson.go files, that should then work...

**Comment by sougou** [comment]
Then I would've had to change the python clients to use the new vitess types. Instead, I massaged the bson encoders to continue transmitting mysql types.
Strangely, I had more confidence in the bson change :).

**Comment by alainjobart** [comment]
I think you can merge this in now then.
Once done, I'll change the binlog code and the tabletmanager stuff to use the proto3 directly, they don't need the new Result. My guess is most of vtgate won't either, but I'm not a specialist there...

**Pull request merged**
