### PR TITLE
just skip any unparseable rbr events

### PR DESCRIPTION
**Pull request by bbeaudreault**
@alainjobart not sure if this is what you had in mind. I kept the panic for the NYI types, since I figured that may have other consequences.

### CODE REVIEW

**Comment by alainjobart** [comment]
Ah you also have to fix go/mysqlconn/replication_test.go for this to work, see travis.

**Comment by alainjobart** [comment]
I'll merge when travis passes. :)

**Comment by bbeaudreault** [comment]
@alainjobart can you kick the test off again? i think the failure looks like our usual unrelated problem?

**Comment by michael-berlin** [comment]
> @alainjobart can you kick the test off again? i think the failure looks like our usual unrelated problem?

Out of curiosity: When you log in with your GitHub account on Travis CI, can you then restart the test yourself?

**Comment by bbeaudreault** [comment]
@michael-berlin I'd love to be able to, but unfortunately I can't. I've looked for it a few times and just looked again. I think possibly only committers can.

**Comment by michael-berlin** [comment]
I've added you as collaborator to our project. Please accept the invite in your email.

Maybe after that you're able to retrigger tests yourself.

The other thing to keep in mind: Some tests are known to be flaky e.g. the "local_example" when it cannot download all artifacts from Maven Central. When these fail, I ignore it and merge it anyway. We can still fix forward if only that test was broken. If you see a flaky test a lot of times, feel free to file an issue. We should fix that to get the flaky rate down.

**Comment by michael-berlin** [comment]
Forgot to mention: As a collaborator, you're able to push branches to our repo, but not to the master or release branches. That means merges into master still have to be done by the team. Write access to the repo is probably not relevant for you since you're working in your own fork.

**Comment by bbeaudreault** [comment]
Thanks @michael-berlin. I appreciate the effort, but sadly that didn't seem to work. A quick googling shows that only those with write access see the refresh button that kicks off a build. I can probably make due with pushing an empty commit or amending and force pushing as a way to kick off new builds for now.

**Comment by michael-berlin** [comment]
Yeah, that's too bad.

I agree: Force pushing or not worrying about known flaky tests are good workarounds.

**Comment by bbeaudreault** [comment]
@michael-berlin FYI not sure what changed (maybe it was cached when we were testing this before), but I can now restart individual jobs in a build or entire builds, or cancel a running build. So either you did something else, or collaborator role eventually makes this functionality available. Thanks again!

**Pull request merged**
