### PR TITLE
Update to gRPC 1.0.0 and protobuf 3.0.0.

### LINKED ISSUE #2002: PHP Composer Dependecy Forces Problematic Dependency
The [php-client package](https://packagist.org/packages/vitess/php-client#v2.0.0) depends explicitly on grpc `dev-release-0_13` and as such is several versions behind the current release of grpc (`v1.0.0`).

Would it be possible for this dependency to be updated to use a newer version? There are currently conflicts between protobuf libraries because a dependency of grpc was forked. This can be temporarily "fixed" by using this fake repo [pixelfederation/datto-Protobuf-PHP-fake](https://github.com/pixelfederation/datto-Protobuf-PHP-fake) as a composer override, but that solution is error-prone and can cause issues.

### PR DESCRIPTION
**Pull request by enisoc**
Fixes #2002

@Rastusik FYI

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM thanks for doing this!

[Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/2012/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)

**Comment by Rastusik** [comment]
@enisoc thanks, I'll address the pdo driver dependencies on monday

**Comment by enisoc** [comment]
FYI, this is all passing locally for me, but Travis is failing to build the gRPC PHP plugin. Still looking into why - the build error seems to be hidden by `./configure`.

**Comment by enisoc** [comment]
Since PHP is segfaulting on Travis now even without this change (#2081), there's no need to hold this up on Travis PHP, so I'm going to submit this to unblock the conversion to gRPC 1.0. The PHP test on this PR branch passes in Docker. We'll work on fixing PHP in Travis separately.

**Pull request merged**
