### PR TITLE
java: Add blocking (synchronous) client wrapper.

### PR DESCRIPTION
**Pull request by enisoc**
@erzel 

Using this wrapper when you want a synchronous API ensures that you don't accidentally forget to call `checkedGet()` on asynchronous methods when you don't use the result.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1566)

### CODE REVIEW

**Comment by erzel** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingConn.java, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1566#-KD00T9Cctbg_38JWCiI:-KD00T9DxUgTqigSRssF:1924885631) ([raw file](https://github.com/youtube/vitess/blob/86ae71fe5a2ad4eee93bb69f12518d562533551e/java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingConn.java#L22)):*
Nit: '* */' -->  '*/' 
Looks more consistent.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingTx.java, line 34 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1566#-KD02FaOlV12ffBWCLay:-KD02FaOlV12ffBWCLaz:-261300200) ([raw file](https://github.com/youtube/vitess/blob/86ae71fe5a2ad4eee93bb69f12518d562533551e/java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingTx.java#L34)):*
Where is this used?

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateConn.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1566#-KD01YrRAIm18EMuZyKJ:-KD01YrRAIm18EMuZyKK:-1247075600) ([raw file](https://github.com/youtube/vitess/blob/86ae71fe5a2ad4eee93bb69f12518d562533551e/java/client/src/main/java/com/youtube/vitess/client/VTGateConn.java#L56)):*
Nit: '* */' --> '*/'.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1566)*

**Comment by erzel** [comment]
BTW. You can likely get java readability with all this code, if you're interested.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1566#-:-KD077SMTXsQFAdBo0ml:-625047598)*

**Comment by enisoc** [comment]
That would be nice. I'll look into it. :)

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingConn.java, line 22 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1566#-KD00T9Cctbg_38JWCiI:-KD0I2vTqXAR7okLYTOX:-499146009) ([raw file](https://github.com/youtube/vitess/blob/86ae71fe5a2ad4eee93bb69f12518d562533551e/java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingConn.java#L22)):*
Done.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingTx.java, line 34 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1566#-KD02FaOlV12ffBWCLay:-KD0IG7WKCiMIAdmcLnv:1282497787) ([raw file](https://github.com/youtube/vitess/blob/86ae71fe5a2ad4eee93bb69f12518d562533551e/java/client/src/main/java/com/youtube/vitess/client/VTGateBlockingTx.java#L34)):*
Nowhere.  Removed.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateConn.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1566#-KD01YrRAIm18EMuZyKJ:-KD0Ic_MIG54M21C1V6K:-499146009) ([raw file](https://github.com/youtube/vitess/blob/86ae71fe5a2ad4eee93bb69f12518d562533551e/java/client/src/main/java/com/youtube/vitess/client/VTGateConn.java#L56)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1566#-:-KD0Ixc3EYRcUdTpPYQA:-562330656)*

**Comment by enisoc** [comment]
@erzel PTAL

**Comment by erzel** [comment]
:lgtm:

---

Review status: 3 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1566#-:-KD4pPLTc41774PTEHJm:1417088721)*

**Pull request merged**
