### PR TITLE
vtworker: Add gRPC server interface (required refactoring).

### PR DESCRIPTION
**Pull request by michael-berlin**
@alainjobart  @aaijazi 

Please have both a look at this. I ran into a cyclic import dependency when I tried to naively add the server interface. Please see the commit messages (second commit) for the full details.

### CODE REVIEW

**Comment by aaijazi** [comment]
LGTM, nice work, although it'd be good to get sign-off from @alainjobart as well.

**Comment by alainjobart** [comment]
LGTM, yes this is very nice.

(when you import into google3, you'll have to move the youtube-specific diff worker there too).

**Comment by michael-berlin** [comment]
@alainjobart @aaijazi 

I've added the client side and made several changes to vtworker.

Can you please review them? (all commits except the first four which you have already signed off)

With these commits, I consider the open-source side of the vtworker RPC interface done.

**Comment by aaijazi** [comment]
LGTM, most of my feedback doesn't require action. I think I would like to see you add the additional panic handler though.

**Comment by aaijazi** [comment]
LGTM

**Pull request merged**
