### PR TITLE
Support USE statements, which may optionally have quoted identifiers

### PR DESCRIPTION
**Pull request by bbeaudreault**
@alainjobart was having trouble finding tests for this particular area

### CODE REVIEW

**Comment by bbeaudreault** [comment]
@sougou thoughts on this? i don't think it's superseded by https://github.com/youtube/vitess/pull/2751/files

**Comment by sougou** [comment]
Forgot to mention. #2751 will be followed by a more universal implementation of USE that will make this obsolete, which is why I haven't approved this.
We were waiting for 2.1 to be cut. So, now I can submit that after @michael-berlin approves, and work on the subsequent PRs. :)

**Comment by bbeaudreault** [comment]
Ok sounds good, thanks. If that's the case I'm going to hijack this PR for the travis testing and add my unapproved code snippet from https://github.com/youtube/vitess/issues/2677 for inverting the single-db `/0` logic. It will make it easier on my developers who are using the mysql prompt while we wait for the followup PRs.

**Comment by bbeaudreault** [comment]
@sougou where did we land with:

> Forgot to mention. #2751 will be followed by a more universal implementation of USE that will make this obsolete, which is why I haven't approved this.

I know you added `USE` support, but do we still have cases where doing `USE foo/0` results in more query flexibility than `USE foo`?

**Comment by sougou** [comment]
For all practical purposes. `foo` and `foo/0` should work the same. There may be some exotic corner cases where it may not work. So, this can be closed.

**Comment by bbeaudreault** [comment]
Ok I'll close this for now and enter a separate issue if we run into issues. Thanks

**Pull request closed without merging**
