### PR TITLE
Clean out py/vtdb/__init__.py.

### PR DESCRIPTION
**Pull request by dumbunny**

### CODE REVIEW

**Comment by dumbunny** [comment]
@alainjobart Please review commented-out __init__.py lines -- remove or keep commented?

**Comment by alainjobart** [comment]
I really have no idea what these guys are for... is there some doc out there?

**Comment by dumbunny** [comment]
@alainjobart Well, codesearch comes up with nothing for any of those three variables. I figured you'd remember them.

**Comment by alainjobart** [comment]
They come from this:
https://www.python.org/dev/peps/pep-0249/#globals
so if we claim to be compliant, we should leave them. Maybe also add the link to the doc.

**Pull request merged**
