### PR TITLE
Allow specifying the subdir to use for vttablet

### PR DESCRIPTION
**Pull request by bbeaudreault**
Isolating based on the UID should be unnecessary in most cases, especially within kubernetes.

I'd be happy to make this the default and remove the flag, if requested. I was concerned about breaking this for people with existing tablets.

@pivanof @alainjobart

### CODE REVIEW

**Comment by bbeaudreault** [comment]
This is still WIP actually -- I found a couple other changes I'd like to make for more flexible directory structure.

**Comment by bbeaudreault** [comment]
This is ready for review. I changed mysqctld to check for the my.cnf file instead of the whole tablet dir. This allows greater flexibility for attaching separate storage devices for parts of the tablet dir, in that I can symlink them into place before mysqctld is run.

I did see `createTopDir` does some symlinking, but it requires a very strict schema. That is, the symlinked dirs must exist in VTDATAROOT, and there must be 1 per top level directory. It also does unnecessary reverse linking. I'm looking to put mysql data + innodb on one device, bin + relay logs on another, and the rest of the tablet dir on the last one.

If you'd prefer, I could add 4 new flags (1 per top level dir) for specifying "external location" and have `createTopDir` optionally use that when creating symlinks. I.E. for my purposes: `-tablet_external_innodb_dir /vt/db/data/innodb -tablet_external_data_dir /vt/db/data/mysql -tablet_external_relay_log_dir /vt/db/logs/relay -tablet_external_bin_log_dir /vt/db/logs/bin`. In this case `/vt/db/data` and `/vt/db/logs` are the separate device mounts, with 2 subdirs each.

**Comment by ilmerovingio** [comment]
Link #2586

**Comment by bbeaudreault** [comment]
Thanks for linking @ilmerovingio  -- note in this case I decided to add the option for specifying what subdirectory you want it to take, rather than just putting in VTDATAROOT like we discussed. I find it useful in my env not to have the tablet files in VTDATAROOT, but in a subdir. This way I can have other vitess-related dirs in VTDATAROOT as well and keep the structure clean.

**Comment by ilmerovingio** [comment]
I agree that your solution is way more clean. 

👍 also for the new flags that you proposed. They could be very handy in deployment with multiple partitions/disks

**Comment by alainjobart** [comment]
LGTM @sougou can you please review and merge when ready?

I also agree the old way could be retired, after we change all integration tests to use the new flag.

**Comment by ilmerovingio** [comment]
This close #2586 thanks @bbeaudreault for the PR!

**Pull request merged**
