### PR TITLE
v3: revised vindexes

### PR DESCRIPTION
**Pull request by sougou**
@enisoc @ashudeep-sharma 
* Using md5 instead of 3des for hashing.
* ToLower has been replaced with a unicode normalizer using Go's collation libraries. Reference is here: http://www.unicode.org/reports/tr10/#Multi_Level_Comparison. I'm using level 1, which should be at least as conservative as MySQL's utf8_unicode_ci collation.
* Renamed the vindexes to be more precise.
* Fixed []byte vs. string issue that was causing the new vindexes to fail.

@enisoc: This introduces a new dependency on golang.org/x/text. So, the docker images will need to be updated?

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1654)

### CODE REVIEW

**Comment by ashudeep-sharma** [comment]
Review status: 0 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLWM9XfWj4wfOTOCUy:-KGLWM9XfWj4wfOTOCUz:-204465510) (no related file):*
Changes looks good. I will test it out on my cluster.

---

*[go/vt/vtgate/router.go, line 365 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLUu49XNtduXJ1BkSo:-KGLUu4A8_WYocV6Aez_:1118339848) ([raw file](https://github.com/youtube/vitess/blob/e00aed574378f7736c6774ca76bab1046039b809/go/vt/vtgate/router.go#L365)):*
Was this the code segment where you are converting byte array to string?

---

*[go/vt/vtgate/vindexes/binarymd5_test.go, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLUJ_PXuIq-ucQu0DK:-KGLUJ_PXuIq-ucQu0DL:528844696) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/binarymd5_test.go#L27)):*
This test input is the same as first one, i guess you intend to use all lowercase  letters ["test"].

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654)*

**Comment by enisoc** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[bootstrap.sh, line 113 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLSWK2qd6NUJVC5kiJ:-KGLSWK2qd6NUJVC5kiK:582762418) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/bootstrap.sh#L113)):*
This is no longer the place for library dependencies. Please see the all-caps comment above. :)

In your case, I think these are the new dependencies you need:

``` sh
$ govendor fetch golang.org/x/text/collate
$ govendor fetch golang.org/x/text/language
$ git add vendor/vendor.json
```

---

*[go/vt/vtgate/vindexes/unicodeloosemd5.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLVSwRTRnmQU6cDo-M:-KGLVSwRTRnmQU6cDo-N:1374668682) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/unicodeloosemd5.go#L74)):*
Do you have a citation for why you think English is the right choice to match (or collapse at least as much) what `utf8_unicode_ci` does? I didn't see anything special mentioned about English in the godoc for the `collate` and `language` packages.

---

*[go/vt/vtgate/vindexes/unicodeloosemd5_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLYlbf3butOQ9CutVb:-KGLYlbf3butOQ9CutVc:-2035432397) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/unicodeloosemd5_test.go#L30)):*
Please add a test case with trailing space characters of various types (space, tab, newline, etc).

> All MySQL collations are of type PADSPACE. This means that all CHAR, VARCHAR, and TEXT values in MySQL are compared without regard to any trailing spaces.
http://dev.mysql.com/doc/refman/5.6/en/char.html

I'm not sure what the `collate` package will do, but it's likely you'll need to change something to make it pass.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654)*

**Comment by ashudeep-sharma** [comment]
*[a discussion](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLWM9XfWj4wfOTOCUy:-KGLi4x2wb2qbfuFhbWu:1270023968) (no related file):*
Verified that the []byte vs string bug has been fixed with these set of changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654)*

**Comment by sougou** [comment]
Review status: 10 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/vt/vtgate/router.go, line 365 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLUu49XNtduXJ1BkSo:-KGNyfcQs5OGCkwaPZQv:677251276) ([raw file](https://github.com/youtube/vitess/blob/e00aed574378f7736c6774ca76bab1046039b809/go/vt/vtgate/router.go#L365)):*
Yes.

---

*[go/vt/vtgate/vindexes/binarymd5_test.go, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLUJ_PXuIq-ucQu0DK:-KGNymqdADG7uMxlwrya:1391166915) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/binarymd5_test.go#L27)):*
It's a repeatability test, to make sure that the same input produces the same output.

---

*[go/vt/vtgate/vindexes/unicodeloosemd5.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLVSwRTRnmQU6cDo-M:-KGNzT7m7yTxEhlYIxTl:1751090239) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/unicodeloosemd5.go#L74)):*
The reference is here: http://www.unicode.org/reports/tr10/#Introduction. In short, unicode seems to define a universal (or default) order. But various locales have conflicting order, which they have the right to override.
Unfortunately, the Go library requires you to specify a locale. So, I chose English assuming that it won't override the Unicode universal order.  After all, the tyrant english speakers invented unicode :). But I couldn't find an easy way to verify this.
Also, the locale differences are not an issue for level 1, because the conservative comparison makes them all equal.

---

*[go/vt/vtgate/vindexes/unicodeloosemd5_test.go, line 30 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLYlbf3butOQ9CutVb:-KGO3Aln73vdmQrrpqDo:215554194) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/unicodeloosemd5_test.go#L30)):*
Nice catch. Go is treating spaces as significant. Fortunately, MySQL seems to only ignore trailing spaces. Not tabs, etc.

---

*[bootstrap.sh, line 113 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLSWK2qd6NUJVC5kiJ:-KGNyXiOME4OwnuZIN1r:-499146009) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/bootstrap.sh#L113)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/vtgate/vindexes/unicodeloosemd5.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLVSwRTRnmQU6cDo-M:-KGOXMumvs2_3epRP6mm:-1325608442) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/unicodeloosemd5.go#L74)):*
Ok I would just suggest to include that comment you just wrote in the code then. The current comment makes it sound like you did verify that English is the same as the universal order, which may make it harder to debug if that later turns out to be untrue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654#-:-KGOYGX17sABLEksL-pE:1417088721)*

**Comment by sougou** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/vtgate/vindexes/binarymd5_test.go, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLUJ_PXuIq-ucQu0DK:-KGOfT9XwwI6d9BsSZG3:-499146009) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/binarymd5_test.go#L27)):*
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654)*

**Comment by sougou** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/vtgate/vindexes/unicodeloosemd5.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1654#-KGLVSwRTRnmQU6cDo-M:-KGOh5DNsJRG3uD-ZHGj:9602593) ([raw file](https://github.com/youtube/vitess/blob/16174fc5e20dd370d1220ddcf9ade91d842767f0/go/vt/vtgate/vindexes/unicodeloosemd5.go#L74)):*
Done.
This will show up in the next PR, which fixes another bug.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1654)*

**Pull request merged**
