### PR TITLE
Revert "Add optional effective_caller_id parameter to vtgate_client.py."

### PR DESCRIPTION
**Pull request by michael-berlin**
This reverts commit 0b77390fbc41b356dd34fb9b8b3428444fa05a68.

Reason: Broke internal users.

### CODE REVIEW

**Comment by guokeno0** [comment]
I think @dumbunny just need to include his stubby changes to fix this. So I recommend @dumbunny to do the import, that will fix it

**Comment by michael-berlin** [comment]
@guokeno0 

I've talked to @dumbunny. He'll make the internal changes first and then merge the open-source changes.

To unblock current imports, I'll therefore revert his changes in this PR.

In general, we should always aim for states where we don't block other people from merging changes.

**Comment by yaoshengzhe** [comment]
@michael-berlin you could delete these changes while doing import, an explicit revert is not quite necessary. I don't see a urgent to import at this time.

**Comment by michael-berlin** [comment]
I didn't do this for multiple reasons:
- Some changes from Dean got through without explicit review. So we fix that by reverting them.
- It's difficult for the current person who does the import to know which changes have to be reverted.
- Requiring to re-apply the changes to every import will make future imports more cumbersome. In general, I prefer fast reverts over forward fixes to unblock people. In addition, it makes life for the person easier who is supposed to fix it: They don't have to rush the fix and can test it intensively first.

**Comment by yaoshengzhe** [comment]
I see, then it totally makes sense. I agree we need to be conscious about changes and may break internal code base. I usually send out an email saying that I will do a non-trivial change and let people do their imports first.

**Pull request merged**
