### PR TITLE
Remove RPCError from proto3 responses where it's unused

### PR DESCRIPTION
**Pull request by aaijazi**
@alainjobart @enisoc 

Won't check this in until all internal changes are done

### CODE REVIEW

**Comment by alainjobart** [comment]
Your gRPC python proto compiler is out of date, you need to remove you grpc and protobuf directories from your dist directory, and re-run 'make proto'...

**Comment by aaijazi** [comment]
Good catch, updated and re-ran. Looks like I'll have to update the Java gRPC client as well.

**Comment by alainjobart** [comment]
There you go, diff is good now. Ping me here when you want me to look at it again.

**Comment by aaijazi** [comment]
@alainjobart @enisoc PTAL

FYI: @yaoshengzhe

**Comment by alainjobart** [comment]
LGTM.

**Comment by enisoc** [comment]
The proto change should also affect the generated Java, right? Can you try `mvn clean verify` in the `java/client` folder? We should figure out how to make it auto-generate when `make proto` is run...

**Comment by alainjobart** [comment]
The java build recompiles the proto every time, I believe?

**Comment by enisoc** [comment]
Yeah but if you only run the Java tests inside Docker, the changed files won't get saved.

**Comment by aaijazi** [comment]
Turns out that we have a java/.gitignore file that hides all the maven artifacts, including the generated Java code, from git. I'm going to merge this PR as-is.

**Pull request merged**
