### PR TITLE
add EnablePublishStats flag in queryctl.go

### PR DESCRIPTION
**Pull request by yaoshengzhe**
This change allows one to publish system variables optionally.

### CODE REVIEW

**Comment by sougou** [comment]
lgtm
This is slightly different from what we discussed, but this will work too.

**Comment by yaoshengzhe** [comment]
@sougou, I am not sure if there is another way to avoid expvar.Publish (it is the most expensive call in the unit tests, cost about 99% of the time)

**Comment by sougou** [comment]
I was only mentioning the option of using an empty name as magic value instead of an explicit bool.
But the explicit value is probably more readable anyways.

**Comment by yaoshengzhe** [comment]
The empty name magic should work, but still we need to make changes to the queryservice code. (E.g. SqlQuery and QueryEngine need a name) To keep things consistent, I've decided to add a bool variable for CachePool, ConnPool, TxPool (even though they have a name already).

BTW, if you prefer the empty name approach, I could add names to SqlQuery and QueryEngine. My intention is to keep things consistent and that will increase the code readability.

**Comment by sougou** [comment]
This is fine as is. No need to use empty name.

**Pull request merged**
