### PR TITLE
A few simple fixes: proto equals, slave connection error reporting, ...

### PR DESCRIPTION
**Pull request by alainjobart**
* fixing proto compares. When better proto library hits, these will fail.
* no more mysqlconn.
* slave connections now detect and return errors properly.

BUG=37574309

### CODE REVIEW

**Comment by bbeaudreault** [comment]
Would it be possible when you guys submit PRs against google internal bugs to include the text of the bug in the PR? At least as much as is shareable. It will help us know if it's a bug we should all care about externally, the severity, etc.

**Comment by alainjobart** [comment]
I am not sure what we can share... in this case, the proto library is being optimized for the proto team, and in doing so they need to add fields in the generated objects, so direct comparison of protos now fails.

**Comment by sougou** [comment]
Google has made internal bugs externally shareable. There's some process we have to follow.

**Comment by bbeaudreault** [comment]
I understand some bugs may not be shareable, or the full text may never be shareable.  I guess I'm just looking for a little more than just `BUG: ######`.  What you provided in your followup comment is enough -- it seems to me that I don't need to rush to pull in this change.

**Pull request merged**
