### PR TITLE
Vitess database metadata test

### PR DESCRIPTION
**Pull request by ashudeep-sharma**
This Branch Contains the following changes:
*Minor fixes in VitessDatabaseMetada and ResultSet implementation.
*Adding Tests for VitessDatabaseMetadata and ResultSetMetadata
*Code Refactoring.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1575)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Reviewed 6 of 7 files at r1.
Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1575)*

**Comment by harshit-gangal** [comment]
Reviewed 1 of 7 files at r1.
Review status: 0 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1575)*

**Comment by harshit-gangal** [comment]
:lgtm:

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1575#-:-KD-TAmhobj1rFlxorH7:1417088721)*

**Comment by harshit-gangal** [comment]
Reviewed 6 of 12 files at r2, 3 of 14 files at r3, 2 of 3 files at r5, 3 of 5 files at r6, 1 of 2 files at r7, 4 of 4 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 506 \[r8\]](https://reviewable.io:443/reviews/youtube/vitess/1575#-KD-jSbtjZIXOBmAmc3p:-KD-jSbtjZIXOBmAmc3q:794938260) ([raw file](https://github.com/youtube/vitess/blob/a46643b815378b14807de8179d52745a88045333/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L506)):*
Need + 1 to the index at which the column is found. As the underlying layer works on base 0 index whereas ResultSet works on base 1 index

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1575)*

**Comment by enisoc** [comment]
Reviewed 3 of 14 files at r3, 2 of 3 files at r5, 1 of 2 files at r7, 3 of 4 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java, line 506 \[r8\]](https://reviewable.io:443/reviews/youtube/vitess/1575#-KD-jSbtjZIXOBmAmc3p:-KD0PzW8gZPihfEo-sIi:-414289764) ([raw file](https://github.com/youtube/vitess/blob/a46643b815378b14807de8179d52745a88045333/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessResultSet.java#L506)):*
Note that I'm going to merge a fix for this soon: https://github.com/youtube/vitess/pull/1565

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1575)*

**Pull request merged**
