### PR TITLE
 Start mysqld for mysql_upgrade with --skip-grant-tables and --skip-networking.

### PR DESCRIPTION
**Pull request by pivanof**
When mysqld is started on a database from an older version (the only use case
when mysql_upgrade will do anything and is really necessary) it may fail to
start due to mysql.* tables having old structure. --skip-grant-tables will
ensure that mysqld doesn't try to read mysql.* tables before mysql_upgrade fixed
their structure. Since anyone can connect to mysqld without password when it's
started with --skip-grant-tables, we should also pass --skip-networking to it.

To make passing those flags to mysqld possible I'm extending notion of
mysqld_start hook to accept list of any arguments that should be passed to
mysqld.

@enisoc

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1890)

### CODE REVIEW

**Comment by enisoc** [comment]
:lgtm: with some nits

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/cmd/mysqlctl/mysqlctl.go, line 98 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1890#-KNdmfdymrpMpWMVWcqQ:-KNdmfdymrpMpWMVWcqR:-1936016024) ([raw file](https://github.com/youtube/vitess/blob/394a62d8bfed2ff56c10175e27ba03da33770984/go/cmd/mysqlctl/mysqlctl.go#L98)):*
> ```Go
> 	waitTime := subFlags.Duration("wait_time", 5*time.Minute, "how long to wait for startup")
> 	var mysqldArgs flagutil.StringListValue
> 	subFlags.Var(&mysqldArgs, "mysqld_args", "List of coma-separated flags to pass additionally to mysqld")
> ```

s/coma/comma/

---

*[go/vt/mysqlctl/backup.go, line 658 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1890#-KNdmxvH1zR7JNsI5NBS:-KNdmxvH1zR7JNsI5NBT:930339494) ([raw file](https://github.com/youtube/vitess/blob/394a62d8bfed2ff56c10175e27ba03da33770984/go/vt/mysqlctl/backup.go#L658)):*
> ```Go
> 	// mysqld needs to be running in order for mysql_upgrade to work.
> 	logger.Infof("Restore: starting mysqld for mysql_upgrade")
> 	err = mysqld.Start(ctx, []string{"--skip-grant-tables", "--skip-networking"})
> ```

Please add to the comment above, explaining why we pass these two flags in particular.

---

*[go/vt/mysqlctl/mysqld.go, line 172 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1890#-KNdnM7CYrsfHSLmRa7e:-KNdnM7DZ2tMVJaI1fkz:-689133910) ([raw file](https://github.com/youtube/vitess/blob/394a62d8bfed2ff56c10175e27ba03da33770984/go/vt/mysqlctl/mysqld.go#L172)):*
> ```Go
> // hook, or by running mysqld_safe in the background.
> // If a mysqlctld address is provided in a flag, Start will run remotely.
> func (mysqld *Mysqld) Start(ctx context.Context, mysqldArgs []string) error {
> ```

You could also use make `Start()` a variadic function so it would be unnecessary to add `[]string{}` in places that don't pass any extra args. It's up to you if you think it's worthwhile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1890#-:-KNdoDuOWJRkgjE3jcVA:-630046853)*

**Comment by pivanof** [comment]
Review status: 3 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/cmd/mysqlctl/mysqlctl.go, line 98 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1890#-KNdmfdymrpMpWMVWcqQ:-KNesh-PoW_qGBER2xOt:-499146009) ([raw file](https://github.com/youtube/vitess/blob/394a62d8bfed2ff56c10175e27ba03da33770984/go/cmd/mysqlctl/mysqlctl.go#L98)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> s/coma/comma/
</details>
Done.

---

*[go/vt/mysqlctl/backup.go, line 658 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1890#-KNdmxvH1zR7JNsI5NBS:-KNetRMvu1qyzvLNt7oS:-1620626842) ([raw file](https://github.com/youtube/vitess/blob/394a62d8bfed2ff56c10175e27ba03da33770984/go/vt/mysqlctl/backup.go#L658)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Please add to the comment above, explaining why we pass these two flags in particular.
</details>
Done. PTAL.

---

*[go/vt/mysqlctl/mysqld.go, line 172 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1890#-KNdnM7CYrsfHSLmRa7e:-KNetoSMwgJaKatiwI60:150447700) ([raw file](https://github.com/youtube/vitess/blob/394a62d8bfed2ff56c10175e27ba03da33770984/go/vt/mysqlctl/mysqld.go#L172)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> You could also use make `Start()` a variadic function so it would be unnecessary to add `[]string{}` in places that don't pass any extra args. It's up to you if you think it's worthwhile.
</details>
I like this idea, definitely worthwhile. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1890)*

**Comment by enisoc** [comment]
Reviewed 8 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1890)*

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
