### PR TITLE
Removing the 'want_fields' flag for tm.ExecuteFetchAs*.

### PR DESCRIPTION
**Pull request by alainjobart**
Defaulting it to true. Not worth the hassle.

@enisoc @sougou @thompsonja

### CODE REVIEW

**Comment by alainjobart** [comment]
@aaijazi for the last commit, part of the clean-up to remove the '2' methods.

**Comment by sougou** [comment]
lgtm

**Comment by aaijazi** [comment]
LGTM

**Comment by thompsonja** [comment]
lgtm

**Pull request merged**
