### PR TITLE
No more EndPoints in topology.

### PR DESCRIPTION
**Pull request by alainjobart**
WIP for now, not ready for review. Starting with the tests, then will do more.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1698)

### CODE REVIEW

**Comment by alainjobart** [comment]
@guoliang100 ready for review now.

@enisoc @michael-berlin FYI

**Comment by michael-berlin** [comment]
LGTM on the vtworker changes.

I left some minor comments.

<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> @guoliang100 ready for review now.
> 
> 
> 
> @enisoc @michael-berlin FYI</details>


---

Review status: 0 of 96 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/discovery/healthcheck.go, line 80 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHv7oOjzbxUPmFnJKct:-KHv7oOjzbxUPmFnJKcu:-748618891) ([raw file](https://github.com/youtube/vitess/blob/c32483d205b45b4ebe04d58acb84826d58d3a858/go/vt/discovery/healthcheck.go#L80)):*
> ```Go
> // Alias returns the alias of the tablet.
> // The return value can be used e.g. to generate the input for the topo API.
> func (e *TabletStats) Alias() *topodatapb.TabletAlias {
> ```

If you like, you can remove this function now. (I only added it recently for my usage in vtworker.)

Getting the Alias is much more straight forward now.

---

*[go/vt/discovery/healthcheck.go, line 659 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHv8GleaWMl3Tn9-wyx:-KHv8GleaWMl3Tn9-wyy:1724703365) ([raw file](https://github.com/youtube/vitess/blob/c32483d205b45b4ebe04d58acb84826d58d3a858/go/vt/discovery/healthcheck.go#L659)):*
> ```Go
> 
> // StatusAsHTML returns an HTML version of the status.
> func (epcs *TabletsCacheStatus) StatusAsHTML() template.HTML {
> ```

There are a few receiver names here and there which still have the old name.

I also saw "ep" and "epList" as variable names.

It would be best to rename them all eventually?

In this particular case, the receiver should be shortened as well to a 1 or 2 letter word.

---

*[go/vt/worker/topo_utils.go, line 28 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHv6I74lupyssYyCine:-KHv6I75sv1XVIM_YV9j:1276826892) ([raw file](https://github.com/youtube/vitess/blob/c32483d205b45b4ebe04d58acb84826d58d3a858/go/vt/worker/topo_utils.go#L28)):*
> ```Go
> 	// Therefore, the default for this variable must be higher
> 	// than vttablet's -health_check_interval.
> 	waitForHealthyTabletsTimeout = flag.Duration("wait_for_healthy_rdonly_endpoints_timeout", 60*time.Second, "maximum time to wait if less than --min_healthy_rdonly_endpoints are available")
> ```

I'm fine with changing the flag as well to be consistent here.

I can do that in a separate internal CL later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1698#-:-KHvBOpqzzHCMwvoNQO9:1837384191)*

**Comment by alainjobart** [comment]
New commit coming to address these,thanks.

<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> LGTM on the vtworker changes.
> 
> I left some minor comments.</details>


---

Review status: 0 of 96 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/discovery/healthcheck.go, line 80 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHv7oOjzbxUPmFnJKct:-KHvNgXYSDxK8YIi11xJ:-499146009) ([raw file](https://github.com/youtube/vitess/blob/c32483d205b45b4ebe04d58acb84826d58d3a858/go/vt/discovery/healthcheck.go#L80)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> If you like, you can remove this function now. (I only added it recently for my usage in vtworker.)
> 
> Getting the Alias is much more straight forward now.</details>
Done.

---

*[go/vt/discovery/healthcheck.go, line 659 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHv8GleaWMl3Tn9-wyx:-KHvNiKQHHOFI7NG2y9D:-622645347) ([raw file](https://github.com/youtube/vitess/blob/c32483d205b45b4ebe04d58acb84826d58d3a858/go/vt/discovery/healthcheck.go#L659)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> There are a few receiver names here and there which still have the old name.
> 
> I also saw "ep" and "epList" as variable names.
> 
> It would be best to rename them all eventually?
> 
> In this particular case, the receiver should be shortened as well to a 1 or 2 letter word.</details>
I renamed most of the ones I found in the next commit.

---

*[go/vt/worker/topo_utils.go, line 28 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHv6I74lupyssYyCine:-KHvNm2gts2eXYUJAuEv:455643927) ([raw file](https://github.com/youtube/vitess/blob/c32483d205b45b4ebe04d58acb84826d58d3a858/go/vt/worker/topo_utils.go#L28)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> I'm fine with changing the flag as well to be consistent here.
> 
> I can do that in a separate internal CL later.</details>
Yes I didn't want to change any externally visible flags as part of this. Thanks for doing this later. :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1698#-:-KHvNsrUT8Gitk4mrfj0:744338502)*

**Comment by guoliang100** [comment]
You also need to change go/cmd/vtgate/status.go because of EndPointsCacheStatus change in healthcheck.go

<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> New commit coming to address these,thanks.</details>


---

Reviewed 96 of 96 files at r1.
Review status: 84 of 97 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1698#-:-KHvR3DDsg42Q1IDUv9q:-1256209896)*

**Comment by alainjobart** [comment]
I think status.go uses TabletsCacheStatus, which contents hasn't changed (even though the name changed, but the name is unused in the html renderer).

In any case, we have integration tests that test the rendering, right?

<details><summary><i>Previously, guoliang100 (Liang) wrote…</i></summary>
> You also need to change go/cmd/vtgate/status.go because of EndPointsCacheStatus change in healthcheck.go</details>


---

Review status: 84 of 97 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1698#-:-KHvZmtUuIJ3dlr3CtbN:-1655824367)*

**Comment by guoliang100** [comment]
Reviewed 13 of 13 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[go/cmd/vtgate/status.go, line 236 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1698#-KHx0b2tDmUkW1P4GuBi:-KHx0b2tDmUkW1P4GuBj:-1270528746) ([raw file](https://github.com/youtube/vitess/blob/e36f9db5553d76374902c6608b7128793e8979ba/go/cmd/vtgate/status.go#L236)):*
> ```Go
>     <th>Shard</th>
>     <th>TabletType</th>
>     <th>EndPointsStats</th>
> ```

Please also rename this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1698)*

**Comment by guoliang100** [comment]
Please rename the line in status.go, and then LGTM

<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> I think status.go uses TabletsCacheStatus, which contents hasn't changed (even though the name changed, but the name is unused in the html renderer).
> 
> In any case, we have integration tests that test the rendering, right?</details>


---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1698#-:-KHx1H-peAcewbGjSXZO:741819653)*

**Pull request merged**
