### PR TITLE
RIP gorpc tablet conn. We have a working gRPC version.

### PR DESCRIPTION
**Pull request by alainjobart**
@sougou @michael-berlin @enisoc

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM

**Comment by aaijazi** [comment]
LGTM!

**Comment by alainjobart** [comment]
@aaijazi @michael-berlin worker.py is busted here, but I don't think that has anything to do with anything I did. It also fails on my workstation, with a different error it seems.

We've been burned by this guy flakiness for a long time now, is there really nothing that can make this better?

**Comment by aaijazi** [comment]
I'm taking a look at this, my first guess is that something really did change. I'm seeing a couple of failures due to "context deadline exceeded". Maybe not this PR, but a previous one changes the expected behavior in some way. Both the failures are in test_reparent_during_worker_copy (the test that runs second), not in test_mysql_down_during_worker_copy.

The third failure is due to something even stranger: "E1109 23:02:21.157272   47173 vtworker.go:81] init() failed: the specified shard test_keyspace/0 is not in any overlapping shard". I'm inclined to dismiss this as a previous teardown not quite cleaning up correctly, so maybe not worth investigating.

@michael-berlin feel free to take this over if you'd like during the week, as I'm not going to get too many chances to work on it.

**Comment by michael-berlin** [comment]
@aaijazi I'll look into it tomorrow.

**Comment by michael-berlin** [comment]
worker.py is failing since this PR because it switched the tabletmanager protocol from BSON to gRPC.

We never ran worker.py with --protocol-flavors=grpc. Otherwise, we would have seen the original issue earlier.

The issue is that the current master gets reparented and therefore it (correctly) replies with an error "I'm read-only now. I cannot execute this SUPER LONG query for you." Since we include the full SUPER LONG query in the error,  it grows to 20kB and this makes gRPC choke. I've filed a bug with them: https://github.com/grpc/grpc-go/issues/443

I'll temporarily fix the issue tomorrow on our side by truncating the returned error. 

btw: The tablet sends out the error, but vtworker never sees the error and the respective RPC times out after two minutes on vtworker's side (context deadline exceeded). We don't retry on an exceeded deadline yet and therefore the test fails. I'll fix this as well.

**Comment by enisoc** [comment]
Great detective work! I think you mean it was PR #1299 that caused it. The test happened to pass on that one, so we didn't notice.

**Comment by michael-berlin** [comment]
Yes, you're right. PR https://github.com/youtube/vitess/pull/1299 caused it :)

**Comment by aaijazi** [comment]
Nice bit of sleuthing @michael-berlin! Thanks for the follow-up work and filing the bug.

We can limit the number of queries we send per RPC request, which should limit the returned error size. Truncating seems like it's probably better though.

Yep, you're right, we should absolutely retry on exceeded deadline, I don't know why we're not.

**Pull request merged**
