### PR TITLE
test refactor & v3 demo

### PR DESCRIPTION
**Pull request by sougou**
* A cleanup of the tests to make it easy to bring up an entire keyspace cluster in keyspace_util.py. We should look at migrating some of our tests to this framework. test/demo.py shows how it's used.
* A demo app. To run it:
  * Launch test/demo.py in one window, wait for 'the cluster is up, press enter to shut it down...' message.
  * cd examples/demo/ and run: python -m CGIHTTPServer

The ports are currently hard-coded:
* 8000 for the demo
* 15010 for vtctld. This will let you view the topo and vschema
* 15009 for vtgate: The test has this port hard-coded for now

Kill the python server, and press enter on the test/demo.py window to tear everything down.

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM with a few comments:

1) I think it'd be nice to put it in examples/demo, so everything is in one place.

2) I tried the demo, but it hangs for me. The demo.py cluster seems to come up fine and I can access vtctld and all that. But when I launch the frontend and visit the URL, the html template loads but then the page hangs. It never even gets around to requesting demo.js according to the log:

$ python -m CGIHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
10.68.156.242 - - [19/Jan/2015 21:23:20] code 404, message File not found
10.68.156.242 - - [19/Jan/2015 21:23:20] "GET /___rPc_sWiTcH___ HTTP/1.0" 404 -
10.68.156.242 - - [19/Jan/2015 21:23:20] "GET / HTTP/1.1" 200 -

Requests to the server from other tabs also hang until I press "Stop" in the first tab. I guess the server is single-threaded... maybe the browser's request pattern is causing a deadlock? This is Chrome 40 beta.

**Comment by sougou** [comment]
Did you 'cd demo/' before launching the http server? That may be why.
I'll see if there's a way to specify the root dir. Then you can launch it from anywhere.

**Comment by sougou** [comment]
The issue with moving it out of test/ is that I'd have to require a PYTHONPATH to find the rest of the support test files, which complicates the setup. We have to find a way out of that, eventually. Otherwise, all our files will end up there.
But I can definitely move the demo/ directory under examples/.

**Comment by enisoc** [comment]
Yeah, I was in the demo folder. It seems to be related to the proxy actually. I was running the demo on my workstation and accessing it from my laptop at home:

Access from workstation (remote desktop): works
Access from home (VPN): works
Access from home (proxy): demo.py server deadlocks (have to spam Ctrl-C to kill it)

So I guess the demo is fine, and it's just the proxy doing something weird.

**Comment by sougou** [comment]
Yeah. Looks like your proxy's trying to talk to the web server. This is what I see in my logs:

~/...vitess/examples/demo> python -m CGIHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
172.25.75.88 - - [19/Jan/2015 21:47:58] "GET / HTTP/1.1" 200 -
172.25.75.88 - - [19/Jan/2015 21:47:59] "GET /demo.js HTTP/1.1" 200 -
172.25.75.88 - - [19/Jan/2015 21:47:59] "POST /cgi-bin/data.py HTTP/1.1" 200 -
...

Were you able to execute queries? Do they work for you?

PS: I'v moved demo -> examples/

**Comment by enisoc** [comment]
Yup, the queries work for me. Fun to play with. :)

**Pull request merged**
