### PR TITLE
Vttest cleanup.

### PR DESCRIPTION
**Pull request by alainjobart**
Convert all tests to new vttest go launcher.
Remove old go LaunchVitess implementation.

### CODE REVIEW

**Comment by alainjobart** [comment]
@vmg this is the follow-up from your new go native cluster work.

**Comment by sougou** [comment]
LGTM

**Comment by arthurnn** [comment]
This is pretty sweet.
Any plans on removing the python scripts too? or they need to stay?

**Comment by alainjobart** [comment]
They're next on my list, after I convert all known usages to the new go version. :)

(also, the go version now forks vtcombo, but why oh why should we do that, when we can just link it in?)

**Comment by arthurnn** [comment]
> also, the go version now forks vtcombo, but why oh why should we do that, when we can just link it in?

We should. We did the vtcombo call to simplify the vttest backport.
Ideally, IMO we should have vttest that can link the vtcombo components. And maybe, even, merge the both?

**Comment by vmg** [comment]
This looks great! Thank you @alainjobart. Sorry I missed the mention last week, I was sick. 🤢

**Pull request merged**
