### PR TITLE
Prometheus adapters for Vitess stats var types

### PR DESCRIPTION
**Pull request by mattharden**
This is the beginning of support for integration with Prometheus. It still remains to select which vars will be exported to Prometheus and determine what their names and help text should be. Then they can be registered with Prometheus by calling promstats.NewCollector to create collectors and calling prometheus.Register on each collector to register them with the Prometheus registry.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1703)

### CODE REVIEW

**Comment by enisoc** [comment]
My original goal was to have everything we already publish to `expvar` automatically published to Prometheus as well. Is that not a goal of your integration work? If not, I can work on that separately after you're done.

<details><summary><i>Previously, mattharden (Matt Harden) wrote…</i></summary>
> #### \[WIP\] Prometheus Integration
> 
> This is the beginning of support for integration with Prometheus. It still remains to select which vars will be exported to Prometheus and determine what their names and help text should be. Then they can be registered with Prometheus by calling promstats.NewCollector to create collectors and calling prometheus.Register on each collector to register them with the Prometheus registry.
> 
> 
> </details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/promstats/collector_test.go, line 10 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI-U86Qm3NEuTZXvXTv:-KI-U86REgAJVXTSRmBI:1004226217) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L10)):*
> ```Go
> 	"github.com/youtube/vitess/go/stats"
> 
> 	pb "github.com/prometheus/client_model/go"
> ```

For these new Go dependencies, the way to [update our vendor config](https://github.com/youtube/vitess/blob/master/bootstrap.sh#L131) is like this:

```sh
govendor fetch github.com/prometheus/client_golang/prometheus
govendor fetch github.com/prometheus/client_model/go
git add vendor/vendor.json
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KI-UX0jVY5VuoCeq_Ea:-1182621557)*

**Comment by mattharden** [comment]
This is the initial PR. I was going to actually add vars in a later PR. I'm not sure whether the existing information is sufficient to devise a correct name for Prometheus; see https://prometheus.io/docs/practices/naming/.

<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> My original goal was to have everything we already publish to `expvar` automatically published to Prometheus as well. Is that not a goal of your integration work? If not, I can work on that separately after you're done.</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KI-XVxy79KCh4Fm7Svx:-2137392409)*

**Comment by enisoc** [comment]
Ah I see. I'll review what's there so far then.

For the long term, I'm thinking we may need to introduce our own interface, for which we implement wrappers for both Prometheus and expvar. We'd then replace all uses of expvar with the new interface. If we need extra info for the Prometheus implementation, we can inject that into each call site as we convert it. The expvar implementation will just ignore the extra info. This would mirror the way we wrap other pluggable things like ZK vs etcd.

If you were thinking of something else, let me know and we can talk more about it.

<details><summary><i>Previously, mattharden (Matt Harden) wrote…</i></summary>
> This is the initial PR. I was going to actually add vars in a later PR. I'm not sure whether the existing information is sufficient to devise a correct name for Prometheus; see https://prometheus.io/docs/practices/naming/.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KI0wA0zKXwIoW2z6qjS:1342965254)*

**Comment by enisoc** [comment]
Looks good overall. Just some style nits in the tests.

<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Ah I see. I'll review what's there so far then.
> 
> For the long term, I'm thinking we may need to introduce our own interface, for which we implement wrappers for both Prometheus and expvar. We'd then replace all uses of expvar with the new interface. If we need extra info for the Prometheus implementation, we can inject that into each call site as we convert it. The expvar implementation will just ignore the extra info. This would mirror the way we wrap other pluggable things like ZK vs etcd.
> 
> If you were thinking of something else, let me know and we can talk more about it.
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[go/promstats/collector_test.go, line 21 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4yn95zpIWfYarTPIc:-KI4yn95zpIWfYarTPId:-1492437623) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L21)):*
> ```Go
> 	v.Set(1234)
> 	metrics := make(chan prometheus.Metric, 1)
> 	go c.Collect(metrics)
> ```

Since you made a buffered channel, you don't need to launch a goroutine here. Since you're immediately blocking on the result below, the behavior of the test will be the same either way if the `c.Collect()` call blocks.

---

*[go/promstats/collector_test.go, line 23 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4xQ_B-y-eS1W5OQsV:-KI4xQ_CO92MW2pbl2C3:1920395413) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L23)):*
> ```Go
> 	go c.Collect(metrics)
> 	met := <-metrics
> 	if want, got := `Desc{fqName: "test_name", help: "test_help", constLabels: {}, variableLabels: []}`, met.Desc().String(); want != got {
> ```

By convention, the style guide says to use the order `got, want` and `got != want` in Go tests.

---

*[go/promstats/collector_test.go, line 24 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4xdsLT_jcvknQhHKk:-KI4xdsLT_jcvknQhHKl:622865175) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L24)):*
> ```Go
> 	met := <-metrics
> 	if want, got := `Desc{fqName: "test_name", help: "test_help", constLabels: {}, variableLabels: []}`, met.Desc().String(); want != got {
> 		t.Errorf("want %q, got %q", want, got)
> ```

By convention, got/want errors look like this:

``` go
t.Errorf("met.Desc() = %q, want %q", got, want)
```

---

*[go/promstats/collector_test.go, line 92 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4yEG25fFAVjYqxqtj:-KI4yEG3jseD7pHCjWwU:160412708) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L92)):*
> ```Go
> 
> func TestFloat(t *testing.T) {
> 	v := stats.NewFloat("Floaty McFloatface")
> ```

lol

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KI4zT4OWvr9488olRrP:-727602363)*

**Comment by enisoc** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[go/promstats/collector.go, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI5-8tV8I7q9DsoisWR:-KI5-8tV8I7q9DsoisWS:-1523177837) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector.go#L1)):*
> ```Go
> package promstats
> ```

Please add a brief package comment:

``` go
/*
Package promstats contains adapters for ...
*/
package promstats
```

Also, since this is specific to the `vitess/go/stats` package, I recommend placing it as a subpackage thereof: `vitess/go/stats/promstats`. This makes browsing the code directories nicer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703)*

**Comment by mattharden** [comment]
I'm thinking about modeling the way go-kit/metrics is doing it. See https://github.com/go-kit/kit/tree/master/metrics. They create a few interfaces that represent metric types (Gauge, Counter, Histogram) and then provide helper functions that create each of these types for the supported backends. So the code that collects metrics can be agnostic as to expvar/stats vs. Prometheus. When creating the metric instances you would need to call either the expvar/stats constructor or the Prometheus constructor with the right information - name, help, description, type, unit, field names, whatever. In fact we could consider just using go-kit/metrics for this, which would get us support for statsd for free.

<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Looks good overall. Just some style nits in the tests.</details>


---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[go/promstats/collector_test.go, line 21 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4yn95zpIWfYarTPIc:-KI9V1hhOXs-O4xmnev_:-2053563207) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L21)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Since you made a buffered channel, you don't need to launch a goroutine here. Since you're immediately blocking on the result below, the behavior of the test will be the same either way if the `c.Collect()` call blocks.</details>
Technically we only block until the first metric is sent on the channel. These collectors *should* only send one metric, but if they send more than one, the test would hang rather than just have a leak. Maybe I should pull this out into a function to run a single collection and pass back the metrics in a slice.

---

*[go/promstats/collector_test.go, line 92 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4yEG25fFAVjYqxqtj:-KI9VYkWLKsUmCLZSVFd:433011564) ([raw file](https://github.com/youtube/vitess/blob/c1aae4cc26a9284ddb4b66f814bd39d920cf0838/go/promstats/collector_test.go#L92)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> lol</details>
Yeah, so there's a bug in stats.NewFloat; it always publishes, even if the name is empty. At least one other constructor does that as well. So to avoid that bug I gave this metric a name (and decided to be cute in the process). I should fix the bug thogh.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KI9SHDnnImmoIyaFyFz:-39475721)*

**Comment by mattharden** [comment]
PTAL

<details><summary><i>Previously, mattharden (Matt Harden) wrote…</i></summary>
> I'm thinking about modeling the way go-kit/metrics is doing it. See https://github.com/go-kit/kit/tree/master/metrics. They create a few interfaces that represent metric types (Gauge, Counter, Histogram) and then provide helper functions that create each of these types for the supported backends. So the code that collects metrics can be agnostic as to expvar/stats vs. Prometheus. When creating the metric instances you would need to call either the expvar/stats constructor or the Prometheus constructor with the right information - name, help, description, type, unit, field names, whatever. In fact we could consider just using go-kit/metrics for this, which would get us support for statsd for free.
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/promstats/collector_test.go, line 10 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI-U86Qm3NEuTZXvXTv:-KKFSZBXUE8DUmv6vwtD:-1229098022) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector_test.go#L10)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> For these new Go dependencies, the way to [update our vendor config](https://github.com/youtube/vitess/blob/master/bootstrap.sh#L131) is like this:
> 
> ```sh
> govendor fetch github.com/prometheus/client_golang/prometheus
> govendor fetch github.com/prometheus/client_model/go
> git add vendor/vendor.json
> ```
</details>
Do we really want to vendor these dependencies? The transitive closure of the dependencies isn't that small:

github.com/beorn7/perks/quantile
github.com/golang/protobuf/proto
github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/prometheus/client_model/go
github.com/prometheus/common/expfmt
github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
github.com/prometheus/common/model
github.com/prometheus/procfs

I see two options to avoid that. We could make the prometheus adapter a separate plug-in with its own vendored or non-vendored dependencies, or we could avoid the prometheus client altogether, and directly implement the RPC model, so that we're only dependent on the protobuf definitions in github.com/prometheus/client_model.

---

*[go/promstats/collector_test.go, line 21 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4yn95zpIWfYarTPIc:-KKF_kqtu3BJEuswjEKj:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector_test.go#L21)):*
<details><summary><i>Previously, mattharden (Matt Harden) wrote…</i></summary>
> Technically we only block until the first metric is sent on the channel. These collectors *should* only send one metric, but if they send more than one, the test would hang rather than just have a leak. Maybe I should pull this out into a function to run a single collection and pass back the metrics in a slice.
</details>
Done.

---

*[go/promstats/collector_test.go, line 23 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4xQ_B-y-eS1W5OQsV:-KKF_j_VeZE-7YXsFVqK:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector_test.go#L23)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> By convention, the style guide says to use the order `got, want` and `got != want` in Go tests.
</details>
Done.

---

*[go/promstats/collector_test.go, line 24 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI4xdsLT_jcvknQhHKk:-KKF_jAExdi2B1q851V7:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector_test.go#L24)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> By convention, got/want errors look like this:
> 
> ``` go
> t.Errorf("met.Desc() = %q, want %q", got, want)
> ```
</details>
Done.

---

*[go/promstats/collector.go, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI5-8tV8I7q9DsoisWR:-KJr-aiZ-YG1Gn-kfiJL:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector.go#L1)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Please add a brief package comment:
> 
> ``` go
> /*
> Package promstats contains adapters for ...
> */
> package promstats
> ```
> 
> Also, since this is specific to the `vitess/go/stats` package, I recommend placing it as a subpackage thereof: `vitess/go/stats/promstats`. This makes browsing the code directories nicer.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KKFbDzL3aIE9xO-hqqG:676965300)*

**Comment by enisoc** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/promstats/collector_test.go, line 10 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI-U86Qm3NEuTZXvXTv:-KKKyRrelT4ftgEbPyCm:280819357) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector_test.go#L10)):*
<details><summary><i>Previously, mattharden (Matt Harden) wrote…</i></summary>
> Do we really want to vendor these dependencies? The transitive closure of the dependencies isn't that small:
> 
> github.com/beorn7/perks/quantile
> github.com/golang/protobuf/proto
> github.com/matttproud/golang_protobuf_extensions/pbutil
> github.com/prometheus/client_model/go
> github.com/prometheus/common/expfmt
> github.com/prometheus/common/internal/bitbucket.org/ww/goautoneg
> github.com/prometheus/common/model
> github.com/prometheus/procfs
> 
> I see two options to avoid that. We could make the prometheus adapter a separate plug-in with its own vendored or non-vendored dependencies, or we could avoid the prometheus client altogether, and directly implement the RPC model, so that we're only dependent on the protobuf definitions in github.com/prometheus/client_model.
</details>
Now that we use govendor, I think it's acceptable to add those dependencies. Note that it's not vendoring in the sense of adding the actual files to our repository; we're just adding an entry to vendor.json that tells the end user's govendor binary which libraries to download.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703)*

**Comment by mattharden** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/promstats/collector_test.go, line 10 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1703#-KI-U86Qm3NEuTZXvXTv:-KKLGVPkJSrzSmRcLAl0:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1fce0b140174f2aedfe349336a0629fedeb86334/go/promstats/collector_test.go#L10)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Now that we use govendor, I think it's acceptable to add those dependencies. Note that it's not vendoring in the sense of adding the actual files to our repository; we're just adding an entry to vendor.json that tells the end user's govendor binary which libraries to download.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1703#-:-KKLLXIqSWcFr1YYHMRR:1417088721)*

**Comment by enisoc** [comment]
I'm building the new docker bootstrap images now.

**Pull request merged**
