### PR TITLE
Updating the example with New Vschema format

### PR DESCRIPTION
**Pull request by ashudeep-sharma**
This Pull Request corrects the Vschema Definition with the new version

### CODE REVIEW

**Comment by demmer** [comment]
@ashudeep-sharma A similar change needs to be made in the `sharding-kubernetes` doc.

**Comment by ashudeep-sharma** [comment]
@demmer Thanks for the information, added the changes in sharding-kubernetes.html

**Comment by michael-berlin** [comment]
Head's up: The changed files are generated and must not be edited manually.

Instead, you need to edit the files under the `doc/` directory. See also the README.md file in the `docs/` directory: https://github.com/youtube/vitess/tree/master/docs

There's unfortunately no easy way to avoid this confusion because "docs" is the hardcoded directory used for serving the website. You cannot change it in GitHub.

I'll port back the changes of this PR later.

**Comment by ashudeep-sharma** [comment]
@michael-berlin Now I remember sometime back you had made the changes to markdown files and then generate these files. I have updated the changes in Markdown files here https://github.com/youtube/vitess/pull/2615

**Pull request merged**
