### PR TITLE
Resharding

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc 
Lots of boiler plate stuff in there, glad it's done.

### CODE REVIEW

**Comment by alainjobart** [comment]
@aaijazi can also look at this.
I'll run an import afterwards, then I can hide out of the office next week. ;)

**Comment by aaijazi** [comment]
Since it's mostly boilerplate, I only skimmed the grpc tabletmanager client/server implementations. I assume that if the existing tests pass, it's okay. 

I noticed you don't have any tests for the proto converters. Any reason for that? I imagine it would be a good idea to get coverage for the edge cases (nils, empty things, etc.).

Otherwise, LGTM

**Comment by alainjobart** [comment]
Re: tests for conversion corner cases: I agree it's lacking support here. But the next phases will include retiring the non-proto3 versions, and we won't need the translations any more. So I'm not too keen on adding laborious tests that will be retired fairly soon.

(the non-edge cases are handled already by the unit tests for the communications).

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
