### PR TITLE
Add Docker images for Percona Server.

### PR DESCRIPTION
**Pull request by enisoc**
[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1547)

### CODE REVIEW

**Comment by alainjobart** [comment]
Is it really a different GTID implementation than MySQL 5.6?

**Comment by enisoc** [comment]
I don't think so. This was contributed as a patch file by another Googler, and I turned it into a PR so I can take a look and clean it up. I asked him if there are any changes in the copied GTID files, and he said he just copied them because he's not familiar with how our flavor plugin system works. So I should be able to dedup those Go files.

**Comment by michael-berlin** [comment]
I reviewed the whole change because I was interested in the GTID implementation  ;)

So I left some comments there. I didn't know that you didn't write this, so excuse me when I meant you :)

---

Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks broke.

---

*[bootstrap.sh, line 143 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvKVsxWdfmVlRR3imj:-KBvKVsyoU1xxz-BzDPR:300169741) ([raw file](https://github.com/youtube/vitess/blob/1159a1216594e2a2e4fcea1f6799896c5d0e34de/bootstrap.sh#L143)):*
Why do you want to remove the default? I liked that :) Less things to configure and worry about.

---

*[dev.env, line 88 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvMCV15a9R4SvkXXWE:-KBvMCV2-5sYTw4ilPrx:1538413923) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/dev.env#L88)):*
Fix indentation please. (Should be the same as the case before.)

---

*[docker/bootstrap/build.sh, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBywmxrg92rRa_Wo8YY:-KBvRbkCBKrWHNT8xxM1:-1603063397) ([raw file](https://github.com/youtube/vitess/blob/1159a1216594e2a2e4fcea1f6799896c5d0e34de/docker/bootstrap/build.sh#L18)):*
Why that?

---

*[docker/bootstrap/Dockerfile.percona, line 8 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvRwIalTCVfrGemPsP:-KBvRwIalTCVfrGemPsQ:891464483) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/docker/bootstrap/Dockerfile.percona#L8)):*
Mix of tabs and spaces. Convert all to spaces?

---

*[docker/lite/Dockerfile.percona, line 5 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvSXltjOS4jmaMdbbM:-KBvSXltjOS4jmaMdbbN:677026233) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/docker/lite/Dockerfile.percona#L5)):*
RUN?

---

*[docker/lite/Dockerfile.percona, line 9 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvSMS_9iSssKciawsv:-KBvSMS_9iSssKciawsw:1630076832) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/docker/lite/Dockerfile.percona#L9)):*
Mixed tabs and spaces.

---

*[docker/lite/Dockerfile.percona, line 18 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvSac79X94ABrKCoLA:-KBvSac79X94ABrKCoLB:1908601647) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/docker/lite/Dockerfile.percona#L18)):*
Could we source these from a common file?

---

*[go/vt/mysqlctl/mysql_flavor_percona.go, line 167 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvUESplie0K9fPOZ11:-KBvUESplie0K9fPOZ12:746685952) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/go/vt/mysqlctl/mysql_flavor_percona.go#L167)):*
missing period

---

*[go/vt/mysqlctl/replication/percona_gtid.go, line 73 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvoOdThmv9nwWZSR3X:-KBvoOdThmv9nwWZSR3Y:675410446) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/go/vt/mysqlctl/replication/percona_gtid.go#L73)):*
Missing period.

---

*[go/vt/mysqlctl/replication/percona_gtid_set.go, line 36 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1547#-KBvqh-6r0Zto9YOKOo8:-KBvqh-6r0Zto9YOKOo9:1656442335) ([raw file](https://github.com/youtube/vitess/blob/57b8c23da2854bcb9b8b4fa494b6a729b6296cfd/go/vt/mysqlctl/replication/percona_gtid_set.go#L36)):*
It would be nice to have here a comment with an example for "s".

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1547#-:-KByxW4bh0L_Ei57VdE-:-738258330)*

**Comment by alainjobart** [comment]
If the GTID code is the same as MySQL 5.6, it just shouldn't be duplicated... The rest I think is just using the right docker image for Percona in our scripts.

**Comment by enisoc** [comment]
I've cleaned it up to re-use the `MySQL56` flavor since it's supposed to be compatible. PTAL.

``` sh
$ go run test.go -flavor=percona
35 PASSED, 0 FLAKY, 0 FAILED, 0 SKIPPED
```

**Comment by michael-berlin** [comment]
LGTM

---

Review status: 2 of 6 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1547#-:-KC33VsLlXHccDarmVGQ:676834233)*

**Comment by michael-berlin** [comment]
Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1547)*

**Comment by alainjobart** [comment]
LGTM cool!

[Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/1547/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)

**Pull request merged**
