### PR TITLE
Fix TableACL SuperUser feature by enforcing group authorization

### PR DESCRIPTION
**Pull request by guokeno0**

### CODE REVIEW

**Comment by guokeno0** [comment]
@michael-berlin @alainjobart 

The DBA user should be able to bypass all CallerID logic. This is now achievable by making DBA a member of Superuser group

**Comment by guokeno0** [comment]
Hmm, tests are broken because SuperUser ACL needs a default ACL factory, fixing this

**Comment by michael-berlin** [comment]
The error message is misleading: Instead of two or more registered AclFactory-s, I guess there is no AclFactory registered at all.

Registration takes place in vttablet.go:85 when -table-acl-config is set. This is probably not the case for most end2end tests.

After the registration "tableacl.Init()" is called. Is it safe to assume that this always has to be called to be in a usable state? In that case, we should always skip ACL checks if the tableacl package is not initialized? e.g. add a function "tableacl.IsInitialized()" and always call it before the ACL check?

@yaoshengzhe If you have time, feel free to look over it as well and give input. Thanks!

**Comment by guokeno0** [comment]
@sougou @michael-berlin @alainjobart 

Get all tests passed. Now the Superuser feature should be able to do group authentication and allow DBA to send whatever query. And two other side fixes:

- Removed all panics in tableacl.go since they complicate error handling.

- Let VTTablet always call tableacl.Init() to make sure an initialization always happen

**Comment by yaoshengzhe** [comment]
@michael-berlin 

"After the registration "tableacl.Init()" is called. Is it safe to assume that this always has to be called to be in a usable state? In that case, we should always skip ACL checks if the tableacl package is not initialized? e.g. add a function "tableacl.IsInitialized()" and always call it before the ACL check?"

I remember the default configuration will skip tableacl check. If it was turned on, I think it is better to return error if it has not been initialized properly.

**Comment by michael-berlin** [comment]
LGTM

As discussed offline, we can merge this change and fix the style issues later.

Therefore, I'm merging this now.

**Pull request merged**
