### PR TITLE
mysql: Support new types GEOMETRY & JSON

### PR DESCRIPTION
**Pull request by sougou**
This is just the server side. I'll add support for Go & Python after this, and then ask other owners to update accordingly.

### CODE REVIEW

**Comment by sougou** [comment]
#2210

**Comment by alainjobart** [comment]
Somewhat unrelated, but can mysql look into the JSON structure? Can the json fields be used in the WHERE clause for instance?

**Comment by alainjobart** [comment]
LGTM

**Comment by michael-berlin** [comment]
> Somewhat unrelated, but can mysql look into the JSON structure? Can the json fields be used in the WHERE clause for instance?

Yes, they can. There's a `JSON_EXTRACT` function for that and recently also a more readable operator `->`: https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html

You can also add a generated column which extracts a field of the JSON object and then create an index for the generated column: https://dev.mysql.com/doc/refman/5.7/en/create-table-secondary-indexes.html#json-column-indirect-index

**Comment by alainjobart** [comment]
I guess my real question was: do we then support that operator and way to access the data in our query engine?

**Comment by sougou** [comment]
I think we may need to make some minor tweaks to the grammar. I'll need to study that part first.

**Pull request merged**
