### PR TITLE
[Vitess JDBC] vtGate Manager implementation

### PR DESCRIPTION
**Pull request by naveen-nahata**
These changes are to shared vtGateConn across VitessConnection.

---
This change is [Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1559)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 62 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCohiOj1KmtuxxptkGf:-KCohiOj1KmtuxxptkGg:138053168) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L62)):*
increment counter before your round robin logic

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by harshit-gangal** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java, line 75 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCp7fiLY2HWHN3ZvaUN:-KCp7fiLY2HWHN3ZvaUO:602586564) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java#L75)):*
Add Dbname, username, streamQuery Property to be used by connection

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java, line 163 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpBlzsmMnFFv2ly1xD:-KCpBlzsmMnFFv2ly1xE:-1106340505) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java#L163)):*
make info property case insensitive

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 66 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpCS8ZoX-l0tNcKRut:-KCpCS8ZoX-l0tNcKRuu:-184328540) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L66)):*
Remove empty code block

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 71 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpCd2mWnwYc_dW0jyp:-KCpCd2mWnwYc_dW0jyq:-518536277) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L71)):*
no need to create an integer object before converting to String

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 103 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEh_M4f9UhhbU-wdK:-KCpEh_M4f9UhhbU-wdL:1086998049) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L103)):*
catch the exception so that all the VTGate Connection can be closed

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java, line 19 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEvmDoAFA1XzmDpCp:-KCpEvmDoAFA1XzmDpCq:-699858377) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java#L19)):*
This method is only called by VitessConnection class, move to the same class

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java, line 40 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpFxz-ialLGTjG4FdH:-KCpFxz-ialLGTjG4FdI:1923032690) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java#L40)):*
This method is only used by VitessJDBCUrl, move to same class

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java, line 76 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpHbZGL7wU3Ri9WcVG:-KCpHbZGL7wU3Ri9WcVH:-193462681) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java#L76)):*
validate starting position condition. Also check If we have an alternate readable logic for parsing query params

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessJDBCUrlTest.java, line 20 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpLf02Jl3-sHZcg-zZ:-KCpLf02Jl3-sHZcg-z_:-1831591854) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessJDBCUrlTest.java#L20)):*
first parameter is expected value and second parameter is actual value.
Change all your Assert statements.

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessVTGateManagerTest.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpMKnMmn6jnuJIn1uO:-KCpMKnMmn6jnuJIn1uP:-1831591854) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessVTGateManagerTest.java#L56)):*
first parameter is expected value and second parameter is actual value.
Change all your Assert statements.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by naveen-nahata** [comment]
Review status: 1 of 9 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java, line 75 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCp7fiLY2HWHN3ZvaUN:-KCtZ4el9rcz637CHyIf:721584992) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java#L75)):*
Will add n another commit.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java, line 163 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpBlzsmMnFFv2ly1xD:-KCtZ-ToHRcpCHk7UmOg:1103334166) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java#L163)):*
Will add n another request.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 62 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCohiOj1KmtuxxptkGf:-KCtYvOgZI0czSxTdzzy:1302721005) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L62)):*
https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 66 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpCS8ZoX-l0tNcKRut:-KCtYsvrVznE17lQL67C:1302721005) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L66)):*
https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 71 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpCd2mWnwYc_dW0jyp:-KCtYqVDRd51BzlMb_OH:-1794475637) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L71)):*
Done

https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 103 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEh_M4f9UhhbU-wdK:-KCtYoOKcoivvXaNUJby:1302721005) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L103)):*
https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java, line 19 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEvmDoAFA1XzmDpCp:-KCtVBfp2sXBpoGZyZPb:-831479990) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java#L19)):*
VTGateManager Call this while creating context. 

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java, line 40 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpFxz-ialLGTjG4FdH:-KCtYiNVzsHRaHdQX2s7:1302721005) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/CommonUtils.java#L40)):*
https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java, line 76 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpHbZGL7wU3Ri9WcVG:-KCtYa2Pg76Z5F2Qnx_4:402316111) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java#L76)):*
Made changes https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessJDBCUrlTest.java, line 20 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpLf02Jl3-sHZcg-zZ:-KCtYVMlThoG50lsycfo:1302721005) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessJDBCUrlTest.java#L20)):*
https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---

*[java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessVTGateManagerTest.java, line 56 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpMKnMmn6jnuJIn1uO:-KCtYPdTX_TWsv6JTLum:1302721005) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/test/java/com/flipkart/vitess/jdbc/test/VitessVTGateManagerTest.java#L56)):*
https://github.com/youtube/vitess/commit/73356bdaf30f8df4a0ed24c1dd244a3d057f80cd

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by harshit-gangal** [comment]
Reviewed 5 of 8 files at r2.
Review status: 6 of 9 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 103 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEh_M4f9UhhbU-wdK:-KCta3ys5wfePvEgRgOi:1523138048) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L103)):*
Capture the exception message of the original exception

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by enisoc** [comment]
Reviewed 8 of 8 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java, line 147 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw9537rALrYKz-XBmh:-KCw9537rALrYKz-XBmi:451335807) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java#L147)):*
Why do you need to worry about case when searching for `"="`?

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 53 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw08hkyN8ZxbCNZNK7:-KCw08hkyN8ZxbCNZNK8:-250640754) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L53)):*
Why is the `+1` there? Isn't that too high?

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 62 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw0HZBePYdY3U_a5RL:-KCw0HZCr2QGZpTvQbH1:-633924561) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L62)):*
This should be unnecessary if you remove the `+1` in the constructor, right?

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 71 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw0aBXFk0pvF6chtNo:-KCw0aBYqWm3c9vyWBzP:1585574668) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L71)):*
I think this can just be `return hostname + port + userIdentifier;`

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java, line 89 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw9CcKE5H_hdjDDY_M:-KCw9CcKE5H_hdjDDY_N:-2022687409) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java#L89)):*
Can you give an example of why it's necessary to search for both upper and lower? Is there a reason you can't force a locale with known properties with `String.toLowerCase(Locale)`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by naveen-nahata** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java, line 147 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw9537rALrYKz-XBmh:-KCy089gT9rD4OV4HI31:792468999) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java#L147)):*
In this case it doesn't make sense however indexOfIgnoreCase is generic implementation. 

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 53 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw08hkyN8ZxbCNZNK7:-KCy1rTHAj9W6QOVIq6c:-884807277) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L53)):*
This can be removed as i am always taking %.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 62 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw0HZBePYdY3U_a5RL:-KCy22pVxJV_vHG73v9A:1719166088) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L62)):*
In every request i will increase counter, to get vtGateInstance of different host,port combination, still need to to module. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by naveen-nahata** [comment]
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java, line 163 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpBlzsmMnFFv2ly1xD:-KCyrdmDi6NNDtlT1cEb:-874280894) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessJDBCUrl.java#L163)):*
As discuss will keep it case insensitive only.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 71 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw0aBXFk0pvF6chtNo:-KCyul0aAPeroQmB78y2:-1349731359) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L71)):*
Yes we can do. Incorporated in commit : https://github.com/youtube/vitess/commit/9056e260b60753cc0ce5cdc34463e860cceb9359.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 103 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEh_M4f9UhhbU-wdK:-KCyuz6RkwWVSme59kSY:-1533252997) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L103)):*
Added in commit : https://github.com/youtube/vitess/commit/9056e260b60753cc0ce5cdc34463e860cceb9359

---

*[java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java, line 89 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCw9CcKE5H_hdjDDY_M:-KCyvATss4S98d57gRNj:1809284730) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/util/StringUtils.java#L89)):*
In our case this method is used only to get first position of '='

Modified code to use String method "indexOf", modified code accordingly : https://github.com/youtube/vitess/commit/5ca94273ea8ffa13b3b377cf0d3b9541725d12a9

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by enisoc** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by naveen-nahata** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java, line 75 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCp7fiLY2HWHN3ZvaUN:-KD2GNtXpQaeUnIINChJ:823026260) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessDriver.java#L75)):*
Done : https://github.com/youtube/vitess/commit/2ab647c3cb7016702d359edbe254a59274919243

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Comment by naveen-nahata** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java, line 103 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1559#-KCpEh_M4f9UhhbU-wdK:-KD7Yrflgt_QlOdisXmX:-1610411257) ([raw file](https://github.com/youtube/vitess/blob/21a9c485d10202805751aa9240be6aafda77597b/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessVTGateManager.java#L103)):*
https://github.com/youtube/vitess/commit/630c743e028ebfc2fefd97eb5c1f13e121e98f75

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1559)*

**Pull request merged**
