### PR TITLE
Batch generated keys

### PR DESCRIPTION
**Pull request by acharis**
@harshit-gangal  @bbeaudreault 
we follow the mysql-connector-j convention to always retrieve generated keys for batch queries.

### CODE REVIEW

**Comment by bbeaudreault** [comment]
@harshit-gangal this LGTM and has been reviewed/deployed internally. Let us know what you think.

**Comment by harshit-gangal** [comment]
Reviewing now.

**Comment by harshit-gangal** [comment]
Reviewed 2 of 3 files at r1, 2 of 2 files at r2.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessStatement.java, line 397 at r3](https://reviewable.io:443/reviews/youtube/vitess/3064#-Krkv-0eJcznB9VjvIJX:-Krkv-0eJcznB9VjvIJY:b-2d6jkf) ([raw file](https://github.com/youtube/vitess/blob/5255c7b6c17c992a8ef1f20be0f660362d210918/java/jdbc/src/main/java/io/vitess/jdbc/VitessStatement.java#L397)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>
>         } else if (this.batchGeneratedKeys != null) {
>             ArrayList<ArrayList<String>> keys = new ArrayList<ArrayList<String>>();
>             for (int i = 0; i < this.batchGeneratedKeys.length; i++) {
>                 long insertId = this.batchGeneratedKeys[i][0];
>                 long rowsAffected = this.batchGeneratedKeys[i][1];
>                 for (int j = 0; j < rowsAffected; j++) {
>                     ArrayList<String> row = new ArrayList<String>(1);
>                     row.add(String.valueOf(insertId + j));
>                     keys.add(row);
>                 }
>             }
>             return new VitessResultSet(columnNames, columnTypes, keys, this.vitessConnection);
>         }
</details>

can you use String[][] data instead of keys that way there will be no need to call VitessResultSet explicitly.

---

*[java/jdbc/src/main/java/io/vitess/jdbc/VitessStatement.java, line 666 at r3](https://reviewable.io:443/reviews/youtube/vitess/3064#-KrkrkEz9bT6PIHCukyd:-KrkrkEz9bT6PIHCukye:b-6p1ugn) ([raw file](https://github.com/youtube/vitess/blob/5255c7b6c17c992a8ef1f20be0f660362d210918/java/jdbc/src/main/java/io/vitess/jdbc/VitessStatement.java#L666)):*
> ```Java
>             if (null == cursorWithError.getError()) {
>                 try {
>                     int rowsAffected = (int) cursorWithError.getCursor().getRowsAffected();
> ```

Calculation of rowsAffected should follow the logic:

long rowsAffected = cursor.getRowsAffected();

if (rowsAffected > Integer.MAX_VALUE) {
   truncatedUpdateCount = Integer.MAX_VALUE;
} else {
   truncatedUpdateCount = (int) rowsAffected;
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3064)*

**Comment by acharis** [comment]
`can you use String[][] data` ...
I can, but at the cost of another loop, so that i can get the right length

**Comment by bbeaudreault** [comment]
@harshit-gangal this is ready for another look

**Comment by harshit-gangal** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3064)*

**Comment by harshit-gangal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/3064#-:-KsUYL7YtlCVPKzuYl9i:bnfp4nl)*

**Pull request merged**
