### PR TITLE
Composer.json and composer.lock  updates after switching to official …

### PR DESCRIPTION
**Pull request by Rastusik**
…stanley-cheung/protobuf-php

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1884)

### CODE REVIEW

**Comment by michael-berlin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1884#-:-KN2fmFgQIpYe7AoEhpI:1417088721)*

**Comment by michael-berlin** [comment]
I'll merge this as soon as Travis has passed on it.

**Comment by Rastusik** [comment]
thank you

**Comment by michael-berlin** [comment]
The PHP example is failing:

```
PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, class 'Vitess\Proto\Vtgate\BeginResponse' does not have a method 'deserialize' in /home/travis/gopath/src/github.com/youtube/vitess/php/vendor/grpc/grpc/src/php/lib/Grpc/AbstractCall.php on line 115
```

https://travis-ci.org/youtube/vitess/jobs/145850179

@Rastusik can you fix this?

**Comment by Rastusik** [comment]
@michael-berlin I know where the problem is... :/ the package grpc/grpc has the same dependency, I have to create a new pull request there

**Comment by Rastusik** [comment]
so after considering creating a pull request in grpc/grpc I chose to create a fake repo and to link the composer to the fake repo. The problem is that grpc has already branches named realease_14 and 15, but Vitess only references release_13, so a pull request wouldn't probably make any sense here...

**Comment by michael-berlin** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1884)*

**Comment by michael-berlin** [comment]
@Rastusik if this requires a fix in the grpc repo, can you please still send them a PR?

We'll switch over to newer grpc releases eventually and then we'll profit from that fix.

**Comment by Rastusik** [comment]
@michael-berlin I just realized that it is already fixed in the master branch of grpc

**Pull request merged**
