### PR TITLE
Refactor workflow code to be more UI-friendly.

### PR DESCRIPTION
**Pull request by pivanof**
The main goal of this change is to make not started and finished workflows
visible in the UI. Without this it was possible to create a workflow with
-skip_start option, and then it won't be visible in the UI thus not giving any
ability to actually start it. Also once workflow finishes it was disappearing
from the UI thus not giving any ability to see how it finished and whether it
existed at all or not. Besides this UI problem also workflows were never deleted
from the topo server and were accumulating indefinitely. This change makes
everything from topo server visible in the UI thus giving ability for the user
to delete already finished workflows.

This UI improvement allows the validator workflow to become less awkward and
actually finish once all fixers are done working. I'm modifying the validator
workflow to do that here as well.

### CODE REVIEW

**Comment by alainjobart** [comment]
We should have talked about this, it was on my to-do list to work on this, we got lucky I didn't start on it at the same time... ;)

Overall it looks good, just one comment: there is now a dependency between Workflow and Node, meaning a workflow will always have a UI node. I had tried to avoid that, but I didn't have a good reason to, I just thought it would be cleaner, and maybe we'd have some workflows that don't have a UI, but just do stuff in the background. That may just be too confusing and not worth it. Having the framework create the UI node seems simpler.

Ah and also, I had a UI menu to toggle between running and non-running workflows. That probably needs to go. Eventually, we probably will need some UI filters to show a subset of the workflows. But not now.

**Comment by pivanof** [comment]
I don't see how it would be a good experience to have completely hidden workflows and at the same time have a "Workflows" section in the UI which seem to look as if it has all workflows in it. What kind of workflows you thought could be hidden like this?

Do you want me to remove the running/not running workflows toggle in this PR?

**Comment by alainjobart** [comment]
Originally, the UI design we had was a view with tabs, with 'Running Workflows' as the first tab, and 'Non Running Workflows' as the second tab. Since I wasn't comfortable with the UI side just yet, I just had a toggle in the menu, that made the title be 'Running Workflows' and 'Non Running Workflows'. The idea is that what most people want is what's going on now, not what happened before.

But that was the original design. If the workflows are sorted by state, and the running ones are first, that might just be enough. I'm all for incremental changes and trying it out, so let's go with your changes, and see how it goes.

You can remove the toggle in this PR, or you or I can do it in another, up to you. Since you implemented the display of the non-running workflows, it probably belongs with this PR.

**Comment by pivanof** [comment]
OK. Removed the toggle.

**Comment by alainjobart** [comment]
LGTM thanks.

**Pull request merged**
