### PR TITLE
enable refreshing config on restart of mysqlctld

### PR DESCRIPTION
**Pull request by bbeaudreault**
In kubernetes we keep the my.cnf in a configmap, and when changes are needed we update that and restart the pod. This way, mysqctld will regenerate the config from that template when it starts back up again.

### CODE REVIEW

**Comment by bbeaudreault** [comment]
I'd be happy to do it every time

**Comment by bbeaudreault** [comment]
I think it's useful to log that it actually changed something, and keep the last file. It will help keep someone from scratching their head in the future. But I can remove the option and change to just bytes.Equal.

**Comment by bbeaudreault** [comment]
@alainjobart updated

**Comment by alainjobart** [comment]
LGTM thanks for changing this, I think it is simpler this way...

@sougou can you please review and approve? thanks!

**Pull request merged**
