### PR TITLE
Refactoring vtgate service errors.

### PR DESCRIPTION
**Pull request by alainjobart**
@aaijazi @enisoc
In the process, splitting up vterrors into multiple logical files, and adding documentation.

### CODE REVIEW

**Comment by aaijazi** [comment]
LGTM

**Comment by alainjobart** [comment]
By the way, I also re-enabled the error test cases. They were broken because the first streaming result response should be just the Fields and nothing else, but the test case was expecting a full field + results.

**Comment by alainjobart** [comment]
@aaijazi @enisoc 
Ready for final review now.

**Comment by aaijazi** [comment]
Nice, LGTM!

**Pull request merged**
