### PR TITLE
Add 'SET collation_connection' to the ignore list

### PR DESCRIPTION
**Pull request by guidoiaquinti**
## Description
Add `SET collation_connection` statement to the ignore list.

## References
- [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_collation_connection)

### CODE REVIEW

**Comment by bbeaudreault** [comment]
LGTM but seems like you have a cla issue

**Comment by guidoiaquinti** [comment]
That's weird, I should be covered by Slack corporate agreement 🤔

**Comment by sougou** [comment]
@guidoiaquinti I'm guessing this is because your profile doesn't list your email address. It's either not set or not public. That may be why it's complaining.

**Comment by guidoiaquinti** [comment]
I signed it!

**Comment by guidoiaquinti** [comment]
Good catch, thanks @sougou !

**Comment by sougou** [comment]
I'm wondering if we should at least validate this to be utf or latin1. Do you know what value are being sent? I assume it's some tool sending this.

**Comment by guidoiaquinti** [comment]
In my case `utf8_general_ci` but there are [tons of other projects](https://github.com/search?p=6&q=%22SET+collation_connection%22&type=Code) that are setting different values

**Comment by sougou** [comment]
Alright. I'll merge this for now.

**Pull request merged**
