### PR TITLE
Converting a few python clients to gRPC.

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @sougou @aaijazi 

@enisoc Only one left is the guestbook app, as far as I can tell. It seems like an easy fix, but I don't have the test environment to make it. Do you mind looking at it? Thanks!

### CODE REVIEW

**Comment by alainjobart** [comment]
@dumbunny please look at vtgate_client.py changes.

**Comment by sougou** [comment]
LGTM for v3 changes.

**Comment by michael-berlin** [comment]
Will the v3 demo change be visible in the demo UI? If not, I would prefer to have an indication of that.

(Before this change, the queries matched very well with what was actually expected to happen.)

**Comment by aaijazi** [comment]
reviewed it, generally looks fine, but going to defer to others for their expertise.

**Comment by alainjobart** [comment]
@michael-berlin there is no visible change to the v3 demo. Only the queries that were done internally to show the content of each shard were affected, as expected. So I don't think it's changing anything.

**Comment by enisoc** [comment]
LGTM I'll update the guestbook app after you merge.

**Pull request merged**
