### PR TITLE
java: Update to grpc-java 0.13.1.

### PR DESCRIPTION
**Pull request by enisoc**
@michael-berlin

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1544)

### CODE REVIEW

**Comment by thompsonja** [comment]
lgtm

**Comment by michael-berlin** [comment]
LGTM

**Comment by enisoc** [comment]
@michael-berlin I made the changes we discussed offline. PTAL.

**Comment by michael-berlin** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[java/client/src/main/java/com/youtube/vitess/client/Context.java, line 63 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1544#-KBuo57B21DHAdIjP9Tp:-KBuo57B21DHAdIjP9Tq:1656697151) ([raw file](https://github.com/youtube/vitess/blob/7cf0b69910cb98eaea57630b136b22b1b56abb1b/java/client/src/main/java/com/youtube/vitess/client/Context.java#L63)):*
You could add the @Nullable annotation here.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1544#-:-KBuoP2fwrD5-KyFqdgu:676834233)*

**Comment by michael-berlin** [comment]
Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1544)*

**Comment by enisoc** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[java/client/src/main/java/com/youtube/vitess/client/Context.java, line 63 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1544#-KBuo57B21DHAdIjP9Tp:-KBuptLZDVntztvOiIPE:-499146009) ([raw file](https://github.com/youtube/vitess/blob/7cf0b69910cb98eaea57630b136b22b1b56abb1b/java/client/src/main/java/com/youtube/vitess/client/Context.java#L63)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1544)*

**Comment by michael-berlin** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1544)*

**Pull request merged**
