### PR TITLE
Switch to native Go ZooKeeper client

### PR DESCRIPTION
**Pull request by alainjobart**
WIP for new ZK client library. Not ready for review yet, but I want to see tests pass or fail. Much cleaner for sure.

@enisoc if you're curious.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1853)

### CODE REVIEW

**Comment by alainjobart** [comment]
@enisoc ready for review now. Much simpler all around I think.

**Comment by enisoc** [comment]
I think you can remove the "zookeeper cgo library config" section in dev.env now.

If there's nothing to be done for the one comment below, then :lgtm:.

---

Reviewed 42 of 42 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/zk/zkconn.go, line 152 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1853#-KMCLyS7eP3pujhWLqSB:-KMCLyS8r8VmAM-ZaESW:-1709389015) ([raw file](https://github.com/youtube/vitess/blob/7e1511e09454e1713f34bfaaaa2541316489a7fa/go/zk/zkconn.go#L152)):*
> ```Go
> 			return nil, nil, context.DeadlineExceeded
> 		case event := <-session:
> 			if event.State == zookeeper.StateConnected {
> ```

The old implementation seems to assume that `Dial()` might return `err == nil` and yet later it could indicate failure by sending an event with `State != CONNECTED`. Is that not the case for the new `Connect()` as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1853#-:-KMCJo81n7MqlsRrbuNa:-1385098177)*

**Comment by alainjobart** [comment]
Review status: 41 of 43 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/zk/zkconn.go, line 152 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1853#-KMCLyS7eP3pujhWLqSB:-KMZOpjZmeqCikoFLF4f:-1913206512) ([raw file](https://github.com/youtube/vitess/blob/7e1511e09454e1713f34bfaaaa2541316489a7fa/go/zk/zkconn.go#L152)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> The old implementation seems to assume that `Dial()` might return `err == nil` and yet later it could indicate failure by sending an event with `State != CONNECTED`. Is that not the case for the new `Connect()` as well?
</details>
The problem is we get intermediate events, like one with 'Connecting' state. So we need to ignore these, and just want until the timeout is reached.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1853)*

**Comment by alainjobart** [comment]
@enisoc PTAL at the next set of commits. I cleaned up a few more env variables. I am also wondering how the MYSQL build ever worked without the CGO_LDFLAGS line I added...

**Comment by enisoc** [comment]
Reviewed 1 of 1 files at r2, 9 of 9 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[dev.env, line 92 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1853#-KMaZ04uUqWaLEZUgzC9:-KMaZ04uUqWaLEZUgzCA:50574551) ([raw file](https://github.com/youtube/vitess/blob/db2688d05c5c7d45edab88dca212119f3e165234/dev.env#L92)):*
> ```
>     export LD_LIBRARY_PATH=$(prepend_path $LD_LIBRARY_PATH $VT_MYSQL_ROOT/lib)
>     export CGO_CFLAGS="$CGO_CFLAGS -I$VT_MYSQL_ROOT/include"
>     export CGO_LDFLAGS="$CGO_LDFLAGS -L$VT_MYSQL_ROOT/lib"
> ```

So the mysql cgo build broke when you removed the zk cgo configs below?

That's really weird... In fact, the `CGO_CFLAGS` line above this should also be unnecessary.

We generate the `pkg-config` file here, according to what `mysql_config` recommends:

https://github.com/youtube/vitess/blob/master/bootstrap.sh#L181

Then we tell CGO to use those flags with this line:

https://github.com/youtube/vitess/blob/master/go/mysql/mysql.go#L10

---

*[go/zk/zkconn.go, line 152 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1853#-KMCLyS7eP3pujhWLqSB:-KMaXrlJw-kGo8-rLOqg:1821192280) ([raw file](https://github.com/youtube/vitess/blob/7e1511e09454e1713f34bfaaaa2541316489a7fa/go/zk/zkconn.go#L152)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> The problem is we get intermediate events, like one with 'Connecting' state. So we need to ignore these, and just want until the timeout is reached.
</details>
Yeah so the trade-off is either we ignore all except `StateConnected` and let any other errors become timeouts, or we come up with a whitelist or blacklist to distinguish good states from bad ones. Since the states are enumerated, it shouldn't be too hard to come up with this list, right? That would help us to fail fast rather than converting all connection errors into timeouts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1853)*

**Comment by alainjobart** [comment]
Review status: 49 of 52 files reviewed at latest revision, 2 unresolved discussions.

---

*[dev.env, line 92 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1853#-KMaZ04uUqWaLEZUgzC9:-KMdp3vXY9LpcPfPvhaq:-1375544931) ([raw file](https://github.com/youtube/vitess/blob/db2688d05c5c7d45edab88dca212119f3e165234/dev.env#L92)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> So the mysql cgo build broke when you removed the zk cgo configs below?
> 
> That's really weird... In fact, the `CGO_CFLAGS` line above this should also be unnecessary.
> 
> We generate the `pkg-config` file here, according to what `mysql_config` recommends:
> 
> https://github.com/youtube/vitess/blob/master/bootstrap.sh#L181
> 
> Then we tell CGO to use those flags with this line:
> 
> https://github.com/youtube/vitess/blob/master/go/mysql/mysql.go#L10
</details>
I think it might be a weird interaction between dev.env, and prepend_path that has different behavior with the first path it adds vs the next ones (first doesn't have to exist). Trying to get to the bottom of it.

---

*[go/zk/zkconn.go, line 152 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1853#-KMCLyS7eP3pujhWLqSB:-KMdpJj5m-UDR9xg9PxC:-38610955) ([raw file](https://github.com/youtube/vitess/blob/7e1511e09454e1713f34bfaaaa2541316489a7fa/go/zk/zkconn.go#L152)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Yeah so the trade-off is either we ignore all except `StateConnected` and let any other errors become timeouts, or we come up with a whitelist or blacklist to distinguish good states from bad ones. Since the states are enumerated, it shouldn't be too hard to come up with this list, right? That would help us to fail fast rather than converting all connection errors into timeouts.
</details>
Fixing this, I think only the AuthFailed state should be looked at.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1853)*

**Comment by alainjobart** [comment]
Gonna merge this, and I'll fix forward. I think we verbally agreed this will work.

**Pull request merged**
