### PR TITLE
Update protos

### PR DESCRIPTION
**Pull request by aaijazi**
@michael-berlin

### CODE REVIEW

**Comment by aaijazi** [comment]
Going to merge this as it's breaking all Travis builds.

**Comment by michael-berlin** [comment]
LGTM

The python files should have changed as well? But you didn't include them?

**Comment by aaijazi** [comment]
Nope, that's all that changed...

**Comment by michael-berlin** [comment]
The Python proto files changed on my machine because I didn't have the latest protobuf + gRPC version installed :-)

I had to delete dist/protobuf and dist/grpc and then re-run bootstrap.sh :-)

**Pull request merged**
