### PR TITLE
[Vitss JDBC] Changes to create context object while executing query

### PR DESCRIPTION
**Pull request by naveen-nahata**
This change is [Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1557)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 875 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1557#-KC_MJGWluhbU5RilhtH:-KC_LSvN1CLJ5atVkL7K:1692573598) ([raw file](https://github.com/youtube/vitess/blob/2a30f700a66cbe55a235b8f7e6bc4ce2f6d29510/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L875)):*
Move this method out of context and place in Utility class as this is required by other classes to create context.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 305 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1557#-KC_NHbofmE9ENxohwyn:-KC_NHbpp-bO-OFZcGGm:480328170) ([raw file](https://github.com/youtube/vitess/blob/2a30f700a66cbe55a235b8f7e6bc4ce2f6d29510/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L305)):*
integer limit can exceed. Change back queryTimeoutInMillis to long type

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1557)*

**Comment by naveen-nahata** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 875 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1557#-KC_MJGWluhbU5RilhtH:-KCaDT1CjiUByYt_0ONh:75452554) ([raw file](https://github.com/youtube/vitess/blob/2a30f700a66cbe55a235b8f7e6bc4ce2f6d29510/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L875)):*
Planning to modify this method with callerID, which will going access vitessConnection  properties. 

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 305 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1557#-KC_NHbofmE9ENxohwyn:-KCaHkyNCXh6vJ1Kk4N8:-106758770) ([raw file](https://github.com/youtube/vitess/blob/2a30f700a66cbe55a235b8f7e6bc4ce2f6d29510/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L305)):*
Incorporated comment and pushed with commit :  https://github.com/youtube/vitess/commit/90789d60515eef6d619510e7af1de16b79c0df85

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1557)*

**Comment by enisoc** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1557)*

**Comment by harshit-gangal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1557#-:-KCdM7YDF4wqI5s4zo45:1417088721)*

**Pull request merged**
