### PR TITLE
Adding 'unused' go code hook.

### PR DESCRIPTION
**Pull request by alainjobart**
It is from this repository: https://github.com/dominikh/go-unused

As part of this change:
- adding download of the tool to bootstrap.sh.
- re-enabling a few tests that were disabled.
- removing a bunch of unused code.

### CODE REVIEW

**Comment by alainjobart** [comment]
OK reverted that file and rebased.

**Comment by enisoc** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/2005/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)

**Comment by michael-berlin** [comment]
LGTM as well.

I like how much the tool uncovered. Thank you for doing this!
Our coverage should increase with these changes :)

The next time we add a hook, we should try to generalize the code :)

btw: One problem right now is that external contributors might skip the precommit. This happened in the past. I've already looked into this and found one way to solve this: That's external services who run things like "go lint" for us on the PR. 

Another alternative would be to add these checks ourselves as part of the test. But since most tools don't have a way to exclude files, this could become annoying.

**Comment by alainjobart** [comment]
I fixed all the these in the way that made most sense to me... each change is mostly in one file, so it should be very obvious. If it is not obvious, please comment on the change (as you did anyway, didn't you?). Didn't think I'd need to write an essay on each simple change.

reviewable.io is not working for me, probably because of history rewrite with squash, I'll address your comments here.

honnef.co / github.com: the github.com install page says to use that. The package will stay up to date if the hosting changes. Pro: we'll get newer versions. Con: for security reasons the tool might move. I went with keeping the tool up to date.

SplitQueryV2SplitCount: after adding the test in, it failed. I had to fix the comparison (note the original SplitQuery test also does integer compare, not reflect.deepequal, as one is int and the other int64).

memorytopo: I am not sure why the diff shows these two methods, they're not part of the change. Probably a merge artifact.

I'll address the unused script comments in another PR.

**Comment by alainjobart** [comment]
'go get github.com/dominikh/go-unused' doesn't work, the import path is enforced in the package:

package github.com/dominikh/go-unused: code in directory /usr/local/google/home/alainjobart/workspace/src/github.com/dominikh/go-unused expects import "honnef.co/go/unused"

so that one I can't fix.

The extra memorytopo code was my mistake, I got confused about the merge. Removed in a subsequent PR.

**Pull request merged**
