### PR TITLE
Set Ruby version for netlify.com.

### PR DESCRIPTION
**Pull request by michael-berlin**
I'm setting it to 2.2.3 because that's also the local version I have
installed and which works with our Gemfile.lock file.

This should fix the current netlify.com error:

> activesupport-5.1.4 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.2p95

### CODE REVIEW

**Comment by michael-berlin** [comment]
I also fixed our build command for NetLify.

@derekperkins building works now :)

The next problem is that the font for the symbols on the homepage somehow seems to be missing.

**Comment by michael-berlin** [comment]
console errors re: the font:

> deploy-preview-3223--vitess.netlify.com/:9 Mixed Content: The page at 'https://deploy-preview-3223--vitess.netlify.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'. This request has been blocked; the content must be served over HTTPS.
deploy-preview-3223--vitess.netlify.com/:1 Access to Font at 'https://d33wubrfki0l68.cloudfront.net/css/5635f80f2754296bfdde164aa444f990bee865be/fonts/fontawesome-webfont.woff2?v=4.4.0' from origin 'https://deploy-preview-3223--vitess.netlify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://deploy-preview-3223--vitess.netlify.com' is therefore not allowed access. The response had HTTP status code 404.
deploy-preview-3223--vitess.netlify.com/:1 Access to Font at 'https://d33wubrfki0l68.cloudfront.net/css/5635f80f2754296bfdde164aa444f990bee865be/fonts/fontawesome-webfont.woff?v=4.4.0' from origin 'https://deploy-preview-3223--vitess.netlify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://deploy-preview-3223--vitess.netlify.com' is therefore not allowed access. The response had HTTP status code 404.
deploy-preview-3223--vitess.netlify.com/:1 Access to Font at 'https://d33wubrfki0l68.cloudfront.net/css/5635f80f2754296bfdde164aa444f990bee865be/fonts/fontawesome-webfont.ttf?v=4.4.0' from origin 'https://deploy-preview-3223--vitess.netlify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://deploy-preview-3223--vitess.netlify.com' is therefore not allowed access. The response had HTTP status code 404.
deploy-preview-3223--vitess.netlify.com/:1 Mixed Content: The page at 'https://deploy-preview-3223--vitess.netlify.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'. This request has been blocked; the content must be served over HTTPS.

**Comment by derekperkins** [comment]
Awesome. @tannerlinsley and I are planning on looking through this more tomorrow to get it fully functional.

**Comment by sougou** [comment]
LGTM
Green builds!

**Pull request merged**
