### PR TITLE
v3: write_only support for unique lookup vindexes

### PR DESCRIPTION
**Pull request by sougou**
The first commit changes the vindex API to allow for unique vindexes to return a keyrange instead of a specific keyspace id. This is a way for a unique vindex to tell the engine that it doesn't know the keyspace id, and ask it to scatter the query.

The second commit uses the above feature to support write_only mode for unique vindexes: during this mode the vindex will be written to, but not read from, allowing you to backfill missing entries while new ones continue to be populated. Once the back-fill is complete, write_only can be turned off.

### CODE REVIEW

**Comment by sougou** [comment]
@alainjobart I had to resolve a merge conflict with executor.go. Can you verify that I interpreted your change correctly?

**Comment by tirsen** [comment]
This does not contain "autocommit" yet? Or has that been merged separately?

**Comment by sougou** [comment]
@alainjobart this can be merged.

**Comment by alainjobart** [comment]
LGTM

**Pull request merged**
