### PR TITLE
Update end2end Reparent test (kubernetes)

### PR DESCRIPTION
**Pull request by thompsonja**
@enisoc 
Most of these changes were approved internally already.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1809)

### CODE REVIEW

**Comment by enisoc** [comment]
Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kubernetes/vtctld-controller-template.yaml, line 53 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1809#-KKuEK1TFtiBNj-4RDjJ:-KKuEK1UA5ve2fSF0Yee:-1577727291) ([raw file](https://github.com/youtube/vitess/blob/5a25e5bea307df503f32f09312e6a67aadefe085/examples/kubernetes/vtctld-controller-template.yaml#L53)):*
> ```YAML
>               -tablet_manager_protocol grpc
>               -etcd_global_addrs http://etcd-global:4001
>               -enable_queries
> ```

I'm hesitant to put this in the default template. That implies we recommend running with this on. The point of putting it behind a flag was to discourage use of those commands other than by tests and during development work.

Is there some way to only enable this for test envs?

---

*[test/sharding_utils.py, line 10 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1809#-KKuLhJHjz2i2pNjqe5Y:-KKuLhJHjz2i2pNjqe5Z:1640595376) ([raw file](https://github.com/youtube/vitess/blob/5a25e5bea307df503f32f09312e6a67aadefe085/test/sharding_utils.py#L10)):*
> ```Python
> 
>   A single shard name is simply 0; otherwise it will attempt to split up 0x100
>   into multiple shards.  For example, shard 1 of 2 is -80, shard 2 of 2 is 80-.
> ```

This line seems to imply `shard` is 1-based, which conflicts with below.

Also please document that this assumes 256 or fewer equal-sized shards, which is not a requirement. Otherwise people may look at this and be misled about how shard names work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1809)*

**Comment by thompsonja** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[examples/kubernetes/vtctld-controller-template.yaml, line 53 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1809#-KKuEK1TFtiBNj-4RDjJ:-KL2nbBr-L2H6I5H4yXw:1407082321) ([raw file](https://github.com/youtube/vitess/blob/5a25e5bea307df503f32f09312e6a67aadefe085/examples/kubernetes/vtctld-controller-template.yaml#L53)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> I'm hesitant to put this in the default template. That implies we recommend running with this on. The point of putting it behind a flag was to discourage use of those commands other than by tests and during development work.
> 
> Is there some way to only enable this for test envs?
</details>
Done.  I added a test_flags variable to the vtctld template.  If TEST_MODE is specified (which can be passed specifically to vtctld-up.sh or plumbed through via vitess-up.sh, it'll add the -enable_queries flag to the template.

---

*[test/sharding_utils.py, line 10 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1809#-KKuLhJHjz2i2pNjqe5Y:-KL3-dVAxiaozopbWN0O:-499146009) ([raw file](https://github.com/youtube/vitess/blob/5a25e5bea307df503f32f09312e6a67aadefe085/test/sharding_utils.py#L10)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This line seems to imply `shard` is 1-based, which conflicts with below.
> 
> Also please document that this assumes 256 or fewer equal-sized shards, which is not a requirement. Otherwise people may look at this and be misled about how shard names work.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1809)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[examples/kubernetes/vtctld-controller-template.yaml, line 53 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1809#-KKuEK1TFtiBNj-4RDjJ:-KL3CT2RB_kfkLIpU5hc:1994240721) ([raw file](https://github.com/youtube/vitess/blob/5a25e5bea307df503f32f09312e6a67aadefe085/examples/kubernetes/vtctld-controller-template.yaml#L53)):*
<details><summary><i>Previously, thompsonja wrote…</i></summary>
> Done.  I added a test_flags variable to the vtctld template.  If TEST_MODE is specified (which can be passed specifically to vtctld-up.sh or plumbed through via vitess-up.sh, it'll add the -enable_queries flag to the template.
</details>
What happens if `{{test_flags}}` is empty? Would it confuse the YAML parser to have a blank line? I think we can avoid that concern altogether if you place it on the same line as `{{backup_flags}}`. Actually that may have been why `{{backup_flags}}` is where it is.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1809#-:-KL3CuVRTclbG_wkw1Rt:1417088721)*

**Comment by thompsonja** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[examples/kubernetes/vtctld-controller-template.yaml, line 53 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1809#-KKuEK1TFtiBNj-4RDjJ:-KL3HRJLZH4ym_qbe2Il:-867658353) ([raw file](https://github.com/youtube/vitess/blob/5a25e5bea307df503f32f09312e6a67aadefe085/examples/kubernetes/vtctld-controller-template.yaml#L53)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> What happens if `{{test_flags}}` is empty? Would it confuse the YAML parser to have a blank line? I think we can avoid that concern altogether if you place it on the same line as `{{backup_flags}}`. Actually that may have been why `{{backup_flags}}` is where it is.
</details>
The YAML parser is fine with blank lines (surprising, right?).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1809)*

**Pull request merged**
