### PR TITLE
Second effort at selecting python2 on all systems. Also quiet wget.

### PR DESCRIPTION
**Pull request by acharis**
The previous PR on this topic broke some systems. The current PR has been more widely tested.

### CODE REVIEW

**Comment by michael-berlin** [comment]
LGTM

Regarding the wget progress: I would like to keep it. Is there a reason you want to remove it?

**Comment by acharis** [comment]
re wget progress, i just didn't see a need for the few hundred lines like:
3950K .......... .......... .......... .......... .......... 23% 55.6M 4s

no big deal though, feel free to drop the `-nv` options, or i can.

**Comment by acharis** [comment]
removed `-nv` options

**Comment by michael-berlin** [comment]
Thanks!

These annoying lines only show up when run non-interactive.

But the script is foremost run interactively and then it's good to show users that something is happening. In particular, these network downloads can be slow sometimes.

I'm going to merge this now. Tests started to fail for unrelated reasons.

**Pull request merged**
