### PR TITLE
[Bug Fix] - fixes client for using multiple connection

### PR DESCRIPTION
**Pull request by harshit-gangal**
LastCall check made at VTGate connection level which avoided any client to use multiple connection.
It is moved to session level. So that for a session multiple calls are not made which can corrupt the transaction.
Now, a single VTGate connection can be used by Connection pool.

### CODE REVIEW

**Comment by bbeaudreault** [comment]
@acharis not sure if you and @harshit-gangal already discussed this, but this looks like the bug we ran into last week.

**Comment by harshit-gangal** [comment]
@acharis @bbeaudreault Can you take a look?

**Comment by acharis** [comment]
tested internally  :+1:

**Comment by sougou** [comment]
LGTM

**Pull request merged**
