### PR TITLE
Dropping IDLE and SCRAP types.

### PR DESCRIPTION
**Pull request by alainjobart**
Not yet ready for review, I wanna see all the tests pass first.

### CODE REVIEW

**Comment by alainjobart** [comment]
@enisoc ready for review now.

**Comment by enisoc** [comment]
Can you also remove the ScrapTablet and ScrapTabletForce actions from web/vtctld/shard.js?

**Comment by alainjobart** [comment]
@enisoc PTAL I think this is ready now, addressed your comments, and more.

(Note I didn't auto-generate the PHP proto files, as I couldn't get all the pieces installed on my workstation, so I manually fixed it).

**Comment by enisoc** [comment]
Since you changed the tablet type values in the proto, we also need to change the vtTabletTypes array in app.js. It's used to translate the index to name, so it should match the order of the proto values. It's on my todo list to make a test for the JS stuff, but it will likely require selenium to be really useful...

**Comment by alainjobart** [comment]
Maybe we can compile some protos for JS too, and use that... Anyway, fixed that file, will merge once tests pass.

**Comment by sougou** [comment]
BTW, unit_race reported a race in wrangler after yesterday's pull.

**Comment by michael-berlin** [comment]
Sugu: Anthony has a fix for a race in his etcd pull request: https://github.com/youtube/vitess/pull/1248

Is it the same race? If you still have the stacktrace around, please create an internal bug.

**Pull request merged**
