### PR TITLE
Converting more of vtgate's internal types.

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @dumbunny

### CODE REVIEW

**Comment by alainjobart** [comment]
@enisoc @sougou @guoliang100 
This is a big change now. Easy, but big. I know it probably broke java and php unit tests, will fix these.

**Comment by enisoc** [comment]
LGTM. Look like the java+php tests just need some test strings updated now that the echo server is formatting results differently.

**Comment by sougou** [comment]
lgtm

**Comment by alainjobart** [comment]
OK all fixed now, will merge and do an import after Michael's import is in, either later this afternoon or early Monday morning.

**Comment by HeisenbergUncertain** [comment]
waster omn masyeryt

**Comment by michael-berlin** [comment]
I've blocked @HeisenbergUncertain and filed an abuse request with Github. These spams are annoying.

**Pull request merged**
