### PR TITLE
vtctl: Add timeout to RefreshState step in MigrateServedTypes to avoid h...

### PR DESCRIPTION
**Pull request by michael-berlin**
...anging forever.

@aaijazi

### CODE REVIEW

**Comment by alainjobart** [comment]
I don't think this is the right place to put this in. The operation itself
already has an overall timeout (in the context), that should be in use
already?

Or are you trying to solve something else?

(in any case, it shouldn't be a hard-coded value in there. I know we do
that for workers, but it's more of a workaround until we fix it right).

We can talk about it face-to-face on Monday too. :)

**Comment by michael-berlin** [comment]
It looks like the operation doesn't have a timeout yet. I agree that a fixed timeout is far from perfect.

Let's talk about that on Monday.

**Comment by aaijazi** [comment]
I think a better place to put this would be in RefreshTabletsByShard. A RefreshState on a single tablet should have a pretty specific upper bound on how long it could take (even if the context for the overall MigrateServedTypes is much higher).

However, definitely makes sense to talk to alain about this as we're trying to clean up our timeout stories across vitess in general.

**Comment by alainjobart** [comment]
(my comment on timeouts was that this command is called from vtctl, which by default creates a context with an action timeout of 1h I think, and therefore has one. But that's definitely not a very good value, too generic).

**Comment by michael-berlin** [comment]
Adding @sougou to verify our reasoning about the maximum time of RefreshState / the QueryService restart.

**Comment by sougou** [comment]
30s is only the default timeout. But then, you can't practically coordinate that value with vtctl. So, 1m sounds fine, heuristically.

**Comment by aaijazi** [comment]
lgtm

**Pull request merged**
