### PR TITLE
Removing KeyspaceIdType from StreamKeyRange queries.

### PR DESCRIPTION
**Pull request by alainjobart**
Effect is far-reaching to tabletmanager, which doesn't need to
read KeyspaceInfo any more. Cool!

@enisoc @erzel I'll run an import after merge, as it changes the APIs.

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM. You got proto-gen-php to work?

**Comment by alainjobart** [comment]
OK busted, no, I fixed the php file manually. ;)

**Comment by enisoc** [comment]
Ah I should have known because the last-changed date wasn't updated. :)

You did a good job though. I checked out your branch and ran proto-gen-php. There were no diffs except for the date.

**Comment by alainjobart** [comment]
Thanks hehe I try. ;)

**Pull request merged**
