### PR TITLE
Convert Java client to asynchronous RPCs.

### PR DESCRIPTION
**Pull request by enisoc**
@erzel 

To get the old synchronous behavior, append `.checkedGet()` to a call
that returns SQLFuture. For example:

```
Cursor cursor = vtgateConn.execute(...).checkedGet();
```

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1511)

### CODE REVIEW

**Comment by erzel** [comment]
Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqK0vIczC5ruYowBue:-KAqK0vIczC5ruYowBuf:2023887499) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java#L27)):*
It's a little confusing here to say that you don't implement that interface because you do, you just don't declare that you do.
So perhaps rephrase to say: "this class does not declare that it implements the interface"

---

*[java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java, line 97 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqWBcJPA7VqI4gc6z2:-KAqWBcJPA7VqI4gc6z3:2102336424) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java#L97)):*
So you're wrapping the ExecutionException in the SQLException not the underlying SQLException?

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqgLGjDmeYEzCapGNr:-KAqgLGjDmeYEzCapGNs:879622433) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L42)):*
Agreed. I'm wondering what are the use-cases for an asynchronous Transaction API. It would simplify this code if we can get away with only allowing a synchronous API.
If we do allow asynchronous calls here I think you should add enforcement for this (e.g. throw an exception if there's already an op in progress). Currently, if the caller issues two queries after a begin() they could end up executed in different MySQL connections.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 43 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqiga4jVtP7_VuSckh:-KAqfmQ1GgT6I2leFyIJ:-774722008) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L43)):*
I'm unclear as to why you need synchronized in the Vitess API methods.

---

*[java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java, line 48 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqoN_GYM14OPxo7EdG:-KAqoN_H59kzwYKtLCEK:1012179231) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java#L48)):*
Did GRPC change their API?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1511)*

**Comment by erzel** [comment]
Looks nice. Sorry for the delay in reviewing.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1511#-:-KAqp1GfJlwSY5bpAdfB:-139468135)*

**Comment by enisoc** [comment]
PTAL

---

Review status: 36 of 38 files reviewed at latest revision, 5 unresolved discussions.

---

*[java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java, line 27 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqK0vIczC5ruYowBue:-KAr3PuyWu0hAt1PDH-L:-499146009) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java#L27)):*
Done.

---

*[java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java, line 97 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqWBcJPA7VqI4gc6z2:-KAr3brwz9esX_cWrwmD:-896360688) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java#L97)):*
Yes, although I was torn about whether that's the right thing to do. In the end, I thought more information is better?

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqgLGjDmeYEzCapGNr:-KAr4wly1lwNBHDygg_2:-197040595) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L42)):*
Certainly for commit() I could imagine wanting to do other work while waiting for the server to get back to you. You can also do reads as part of a transaction, and you may want those async too for the same reasons our customers want async queries in general. Since the underlying RpcClient interface is async anyway, the alternative is to have VTGateTx call checkedGet() for you. I'd rather leave the option in the user's hands.

I agree it would be nice to enforce the in-flight operation limit. Originally I was thinking the second attempted operation would block until the previous one finished, but that seemed too complicated and prone to deadlock. I like your suggestion to just throw an exception to say that's not allowed.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 43 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqiga4jVtP7_VuSckh:-KAr4A0wCF67p-q29ydu:618933742) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L43)):*
The session field gets updated by the async callback, which could be in a different thread. In order for the next call to execute (for example) to be guaranteed to see the new session value, it must be synchronized. Otherwise the Java memory model allows it to see the old value from a thread-local cache.

---

*[java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java, line 48 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqoN_GYM14OPxo7EdG:-KAr6ahh4P1VAPiYKOq_:-439768439) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java#L48)):*
Yes I updated the Maven dependency to grpc-java 0.12 to match the rest of our project being updated to grpc 0.12.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1511#-:-KArMg-KQLMgUPaPyR_f:676965300)*

**Comment by erzel** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java, line 97 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqWBcJPA7VqI4gc6z2:-KAuxJzoh8UjrPAjbYPw:677042770) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/SQLFuture.java#L97)):*
SGTM

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 42 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqgLGjDmeYEzCapGNr:-KAvXOzlhd203EYhxzaA:461834102) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L42)):*
Fair enough. I think you've convinced me about the need for asynchronicity in transactions.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 43 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqiga4jVtP7_VuSckh:-KAuzHJ8YGDMfB62z-E3:-793279429) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L43)):*
You're right. I was confused about the meaning of synchronized in Java. 
Can you just move the word "only" to after the word "synchronized" in the comment to make this slightly clearer.

---

*[java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java, line 48 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqoN_GYM14OPxo7EdG:-KAvYSAHpiPN-KNSshce:1382242728) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/grpc-client/src/main/java/com/youtube/vitess/client/grpc/GrpcStreamAdapter.java#L48)):*
LGTM, but please see one last comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1511)*

**Comment by enisoc** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java, line 43 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1511#-KAqiga4jVtP7_VuSckh:-KAvapgdqvruvzavRY_S:-499146009) ([raw file](https://github.com/youtube/vitess/blob/21b63573a1fbf95aa847f61e4beac425cb70697e/java/client/src/main/java/com/youtube/vitess/client/VTGateTx.java#L43)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1511)*

**Pull request merged**
