### PR TITLE
Adding a db merge end to end test.

### PR DESCRIPTION
**Pull request by alainjobart**
And fix all the bugs it un-covers.

@enisoc @michael-berlin

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1635)

### CODE REVIEW

**Comment by michael-berlin** [comment]
LGTM

But I'm not happy with the degree of duplication in the test. I think it's time for a utils_resharding.py module or something similar.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[test/merge_sharding.py, line 47 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFj7uem2o8V3Evk5cN:-KFFj7uem2o8V3Evk5cO:-713817895) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L47)):*
It could be a bit more intuitive that this is the merged shard e.g. call it shard_01_master ?

---

*[test/merge_sharding.py, line 57 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFhAuZVsMfzFJXWBB3:-KFFhAu_8-6vHyos_KXI:-990607952) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L57)):*
You could put all these in a list and loop over it.

---

*[test/merge_sharding.py, line 164 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFik_7ArfWAvZZHuxj:-KFFik_8_UQFCwRch5kt:-1300549857) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L164)):*
Document here the return value?

---

*[test/merge_sharding.py, line 179 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFi-BVULA2i1ZprS3I:-KFFi-BVULA2i1ZprS3J:-1819356456) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L179)):*
Is the comma after "custom_sharding_key)" necessary?

---

*[test/merge_sharding.py, line 211 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFjJULxArOopT713nV:-KFFjJULxArOopT713nW:-1911886085) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L211)):*
Align the id with the shard numbers e.g.

self._insert_value(shard_0_master, 'resharding1', 0, 'msg1',

? Or:

self._insert_value(shard_1_master, 'resharding1', 1, 'msg1',

---

*[test/merge_sharding.py, line 235 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFjyHaZFlOCoaqWDIk:-KFFjyHaZFlOCoaqWDIl:-1699295667) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L235)):*
You could add a check here that count + base must be < 10000 or there will be duplicate rows during the merge?

---

*[test/merge_sharding.py, line 236 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFjYWV2YcqNQw8-RyQ:-KFFjYWV2YcqNQw8-RyR:-144187635) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L236)):*
Same comment here as above. I would prefer if the shard number is aligned with the content of the rows e.g.

self._insert_value(shard_1_master, 'resharding1', 1, 'msg1',

---

*[test/merge_sharding.py, line 263 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFkdMKq3c_HZoLxkWb:-KFFkdMKq3c_HZoLxkWc:750439349) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L263)):*
We have utils.wait_step(). Maybe you can use that?

---

*[test/merge_sharding.py, line 273 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFlXZ6yz_gDkBJ3yRw:-KFFlXZ6yz_gDkBJ3yRx:-2118576502) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L273)):*
This is copied from resharding.py.

Can you please deduplicate it?

I would like to avoid duplicate resharding test code as much as possible.

---

*[test/merge_sharding.py, line 304 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFl4Jwld28EqbjfAAh:-KFFl4Jwld28EqbjfAAi:1720148347) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L304)):*
Why not just start them with it?

You'll probably still want the explicit healthcheck here to not wait for the next periodic one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1635#-:-KFFtphLe-W2sI6VZM1c:1732352249)*

**Comment by alainjobart** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[test/merge_sharding.py, line 47 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFj7uem2o8V3Evk5cN:-KFKA7OOxD-4I9ioskd1:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L47)):*
Done.

---

*[test/merge_sharding.py, line 57 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFhAuZVsMfzFJXWBB3:-KFK9R4LnYE7XJX5tYNY:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L57)):*
Done.

---

*[test/merge_sharding.py, line 164 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFik_7ArfWAvZZHuxj:-KFKAe0wlBDHWi9kk4b_:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L164)):*
Done.

---

*[test/merge_sharding.py, line 179 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFi-BVULA2i1ZprS3I:-KFK7K0XOR_ngQa6qPWV:1565845) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L179)):*
Yes it is, to make it a tuple. python will remove () around a tuple if it's only one value:

>>> print ('a')
a
>>> print ('a',)
('a',)

---

*[test/merge_sharding.py, line 211 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFjJULxArOopT713nV:-KFKArTKZoQZjoQn1kEQ:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L211)):*
Done.

---

*[test/merge_sharding.py, line 235 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFjyHaZFlOCoaqWDIk:-KFKC0L5TcKEOqk45KfI:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L235)):*
Done.

---

*[test/merge_sharding.py, line 236 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFjYWV2YcqNQw8-RyQ:-KFKC0ixtqRxlHsMPO7B:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L236)):*
Done.

---

*[test/merge_sharding.py, line 263 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFkdMKq3c_HZoLxkWb:-KFKCp208vpqq9m3jAdC:-499146009) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L263)):*
Done.

---

*[test/merge_sharding.py, line 273 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFlXZ6yz_gDkBJ3yRw:-KFK8bDlqhA_BCTfpNmZ:-865043672) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L273)):*
There is a lot to do in this regard. I will work on some of it.

---

*[test/merge_sharding.py, line 304 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFFl4Jwld28EqbjfAAh:-KFK8OFajU5YQ8IxD59P:188153827) ([raw file](https://github.com/youtube/vitess/blob/1152cc675bfd56c3323d85bfcbdf84f2796e1b99/test/merge_sharding.py#L304)):*
Exactly, we have to explicitly do it anyway. So there is little value in having the tablet do it manually.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1635)*

**Comment by alainjobart** [comment]
@michael-berlin PTAL I factored out a bunch of stuff. We can still do better.

**Comment by michael-berlin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2, 6 of 6 files at r3, 5 of 5 files at r4, 5 of 5 files at r5, 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/resharding.py, line 21 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFLZhM8NsceY8BDFKrF:-KFLZhM8NsceY8BDFKrG:-2018689013) ([raw file](https://github.com/youtube/vitess/blob/898e9e225bbfca51346619477aa80d8c008c1446/test/resharding.py#L21)):*
typo: SourceShardAdd
typo: SourceShardDelete

I suggest to add "vtctl" to be explicit about it:

- tests vtctl SourceShardAdd and SourceShardDelete.

---

*[test/utils.py, line 382 \[r6\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFLabaZmwB-4qJewC79:-KFLabaZmwB-4qJewC7A:-1511516016) ([raw file](https://github.com/youtube/vitess/blob/f07a42457ca45c20c34f9a40f10fd4972b07d4e4/test/utils.py#L382)):*
waits for vars[var][key]==value.

?

---

*[test/utils.py, line 383 \[r6\]](https://reviewable.io:443/reviews/youtube/vitess/1635#-KFLafNXSwVCirkfsvGQ:-KFLafNXSwVCirkfsvGR:-1511516016) ([raw file](https://github.com/youtube/vitess/blob/f07a42457ca45c20c34f9a40f10fd4972b07d4e4/test/utils.py#L383)):*
waits for vars[var][key]==value.

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1635#-:-KFLcDsUi3qeUMKwhpuC:1417088721)*

**Pull request merged**
