### PR TITLE
Log

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @sougou @aaijazi @yaoshengzhe 
Review of the content appreciated, thanks!

### CODE REVIEW

**Comment by yaoshengzhe** [comment]
LGTM. Please do not forget to publish the site later.

**Comment by enisoc** [comment]
LGTM. I've always wondered if the sharding key is equal to 0x80..., which shard will it go to? It would be nice to mention the answer to that in case anyone else is wondering.

**Comment by alainjobart** [comment]
I have the answer there, feel free to edit the doc to make it clearer... :)

Comparison of Sharding Keys can be a bit tricky, but if one remembers they
are always converted to byte arrays, and then converted, it becomes easier.
For instance, the value [ 0x80 ] is the mid value for Sharding Keys. All
byte sharding keys that start with numbers strictly lower than 0x80 are
lower, and all byte sharding keys that start with number equal or greater
than 0x80 are higher. Note that [ 0x80 ] can also be compared to 64 bits
unsigned integer values: any value that is smaller than 0x8000000000000000
will be smaller, any value equal or greater will be greater.

**Comment by enisoc** [comment]
Ah I see. I missed that.

I did a test of the Jekyll conversion, and it looks like even with the asterisks, those lists are still not being converted to bulleted lists.

**Comment by enisoc** [comment]
It looks like the lists aren't working in Jekyll because the markdown converter we're using (redcarpet) requires a blank line before the list.

**Comment by enisoc** [comment]
I added newlines to make sure all lists had blank lines before them, and it seems to have worked.

**Pull request merged**
