### PR TITLE
Lookup vindex

### PR DESCRIPTION
**Pull request by ashudeep-sharma**
This Pull Request Contains the following changes:

- A generic lookup Vindex which will store the mapping from a columntype to the corresponding keyspaceId in hex encoded format.
-Test cases to cover the lookup Vindex.

The earlier lookup vindexes were storing the mapping of a secondary lookup column  to the shard Key, however the only information that is required to resolve the correct shard is the keyspaceId Value.
Using this Vindex, one can create a lookup Vindex on any type of secondary column to the corresponding keyspaceID.

@sougou : I have created a file lookup.go to define these indexes, please take a look and let me know in case there are any issues and concerns.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1870)

### CODE REVIEW

**Comment by sougou** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[go/vt/vtgate/vindexes/lookup.go, line 114 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmCFaYxlGWed0gEcth:-KMmCFaYxlGWed0gEcti:1152132940) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup.go#L114)):*
> ```Go
> 
> // MapLookupUnique is for a unique vindex.
> func (lkp *lookup) MapLookupUnique(vcursor VCursor, ids []interface{}) ([][]byte, error) {
> ```

Maybe we can consolidate this type into a lookup_internal.go?

---

*[go/vt/vtgate/vindexes/lookup.go, line 130 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmBzwNb4ETpOkx6B_l:-KMmBzwNb4ETpOkx6B_m:-355967583) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup.go#L130)):*
> ```Go
> 			return nil, fmt.Errorf("lookup.Map: unexpected multiple results from vindex %s: %v", lkp.Table, id)
> 		}
> 		source, err := getBytes(result.Rows[0][0].ToNative())
> ```

As mentioned below, if you stored raw bytes, you could directly use row[0].Raw() to the append call.

---

*[go/vt/vtgate/vindexes/lookup.go, line 155 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmB8Z7kjFlxXZHZPv1:-KMmB8Z7kjFlxXZHZPv2:886361481) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup.go#L155)):*
> ```Go
> 		var ksids [][]byte
> 		for _, row := range result.Rows {
> 			source, err := getBytes(row[0].ToNative())
> ```

Same comment as above.

---

*[go/vt/vtgate/vindexes/lookup.go, line 172 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmAVPvNfiLV-HT0weE:-KMmAVPvNfiLV-HT0weF:530438216) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup.go#L172)):*
> ```Go
> // Create creates an association between id and keyspaceid by inserting a row in the vindex table.
> func (lkp *lookup) CreateLookup(vcursor VCursor, id interface{}, ksid []byte) error {
> 	keyspaceID := hex.EncodeToString(ksid)
> ```

I think it's better to store the raw bytes as varbinary. People can always do hex(col) if they want to see the hex value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870)*

**Comment by sougou** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[go/vt/vtgate/vindexes/lookup.go, line 117 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmDbxCMEibBaTARYNj:-KMmDbxCMEibBaTARYNk:1933500313) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup.go#L117)):*
> ```Go
> 	out := make([][]byte, 0, len(ids))
> 	for _, id := range ids {
> 		result, err := vcursor.Execute(lkp.sel, map[string]interface{}{
> ```

We should look at optimizing this code to a single round-trip (not in this PR). It will be helpful when we start working on BatchExecute.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870)*

**Comment by ashudeep-sharma** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 114 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmCFaYxlGWed0gEcth:-KN1j8vHz-Mu25fziVBY:100849027) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L114)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> Maybe we can consolidate this type into a lookup_internal.go?
</details>
Renamed the file to lookup_internal.go

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 117 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmDbxCMEibBaTARYNj:-KN1jDAUsqpP7ebOs9gk:-2110827930) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L117)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> We should look at optimizing this code to a single round-trip (not in this PR). It will be helpful when we start working on BatchExecute.
</details>
Will take care of this.

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 130 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmBzwNb4ETpOkx6B_l:-KN1jHiebWiikUr4nk1q:-469593337) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L130)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> As mentioned below, if you stored raw bytes, you could directly use row[0].Raw() to the append call.
</details>
done.

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 155 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmB8Z7kjFlxXZHZPv1:-KN1jJ-VU1a-uxKdKdCh:-469593337) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L155)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> Same comment as above.
</details>
done.

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 172 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmAVPvNfiLV-HT0weE:-KN1jKRbh4wxxu4OFDiK:-469593337) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L172)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> I think it's better to store the raw bytes as varbinary. People can always do hex(col) if they want to see the hex value.
</details>
done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870)*

**Comment by ashudeep-sharma** [comment]
*[go/vt/vtgate/vindexes/lookup_internal.go, line 117 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmDbxCMEibBaTARYNj:-KN1jmrK3rRGLFpRSLpZ:1581746372) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L117)):*
<details><summary><i>Previously, ashudeep-sharma (Ashu) wrote…</i></summary>
> Will take care of this.
</details>
I think this needs to be done for all the lookup indexes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870)*

**Comment by sougou** [comment]
Reviewed 4 of 17 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 114 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmCFaYxlGWed0gEcth:-KN1ySpw5X210tWPj2-R:2102851428) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L114)):*
<details><summary><i>Previously, ashudeep-sharma (Ashu) wrote…</i></summary>
> Renamed the file to lookup_internal.go
</details>
I meant that the lookup type be moved to lookup_internal. I think it still makes sense to keep lookup.go and lookup_hash.go as before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870)*

**Comment by ashudeep-sharma** [comment]
- Made the changes to refactor the lookup type in lookup_internal.go
- Removed the Redundant code from lookup_hash.go and lookup.go and moved it to lookup_internal.go
- Added isHashedIndex as lookup type property to identify whether the vindex is of simple lookup type or lookup_hash type.

**Comment by ashudeep-sharma** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/vtgate/vindexes/lookup_internal.go, line 114 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1870#-KMmCFaYxlGWed0gEcth:-KN318SCMue_h457QKH7:-469593337) ([raw file](https://github.com/youtube/vitess/blob/74522d56d4978bba1dee5cdf7c4d31d9b9cb9a63/go/vt/vtgate/vindexes/lookup_internal.go#L114)):*
<details><summary><i>Previously, sougou wrote…</i></summary>
> I meant that the lookup type be moved to lookup_internal. I think it still makes sense to keep lookup.go and lookup_hash.go as before.
</details>
done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870)*

**Comment by sougou** [comment]
:lgtm:

---

Reviewed 1 of 17 files at r2, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1870#-:-KN33FpSMZTx7A-Lvk3d:1417088721)*

**Pull request merged**
