### PR TITLE
Replication

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @aaijazi prep work for migration to proto3's Tablet.

### CODE REVIEW

**Comment by alainjobart** [comment]
Ping, I'd like a review so I can move forward with this, otherwise after lunch I'll submit and fix forward :)

**Comment by alainjobart** [comment]
(broken travis test passes in my local tree)

**Comment by aaijazi** [comment]
Changes LGTM, but I have no context on the removal of Tablet :)

**Comment by enisoc** [comment]
LGTM

Some context for @aaijazi:

We're switching to using the proto-generated struct as the canonical representation of a tablet inside Vitess. Adding methods to proto-generated structs is discouraged, and tooling is not designed to let you do it. The recommended way is to wrap it in another type declaration, but then we'd need to keep doing conversions to and from the proto. We decided it's not worth the extra steps for a purely syntactic win, so instead we're moving from methods with implicit receivers (`func (Tablet) doSomething()`) to functions with explicit receivers (`func doSomething(Tablet)`).

**Pull request merged**
