### PR TITLE
Do not change type or health map for health reasons.

### PR DESCRIPTION
**Pull request by alainjobart**
WIP, not ready for review yet.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1685)

### CODE REVIEW

**Comment by enisoc** [comment]
Reviewed 56 of 58 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[go/vt/mysqlctl/health.go, line 34 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMQIn-FrybrSyUqYRf:-KHMQIn0-PzShRNPRRcd:-1230053366) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/mysqlctl/health.go#L34)):*
> ```Go
> 	if err != nil {
> 		if !mrl.lastKnownTime.IsZero() {
> 			// we can extrapolate
> ```

We should note in the comment that this is a worst case extrapolation. It's possible that it caught up in between polls, but we'll assume the worst.

---

*[go/vt/mysqlctl/health.go, line 36 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMPt2Bh-idmrwqlDXS:-KHMPt2Bh-idmrwqlDXT:-1578860411) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/mysqlctl/health.go#L36)):*
> ```Go
> 			// we can extrapolate
> 			elapsed := mrl.now().Sub(mrl.lastKnownTime)
> 			return elapsed + time.Duration(mrl.lastKnownValue)*time.Second, nil
> ```

This would be cleaner if you make `lastKnownValue` be of type `time.Duration`. Then you do the conversion in only one place (when setting `lastKnownValue`) and at the end you `return mrl.lastKnownValue`.

---

*[go/vt/tabletmanager/action_agent.go, line 187 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMT2UfvMFsLzoGd4yQ:-KHMT2UfvMFsLzoGd4yR:-569862666) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/tabletmanager/action_agent.go#L187)):*
> ```Go
> 		SchemaOverrides:     schemaOverrides,
> 		History:             history.New(historyLength),
> 		lastHealthMapCount:  stats.NewInt("LastHealthMapCount"),
> ```

This will break some internal monitoring (vtcoproc). That probably needs to be fixed prior to importing this change, since the coproc is rolled out separately.

---

*[go/vt/tabletmanager/action_agent.go, line 199 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMRdtRU48uy2svDveR:-KHMRdtSekXD965i0t64:637762425) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/tabletmanager/action_agent.go#L199)):*
> ```Go
> 	// Publish and set the TargetTabletType. Not a global var
> 	// since it should never be changed.
> 	statsTabletType := stats.NewString("TargetTabletType")
> ```

I think removing this will break internal dashboards and possibly some monitoring (based on my code search for "target-tablet-type"). Are you planning to fix that along with the import? Or should we remove this later after we've migrated the monitoring to some other variable?

---

*[go/vt/tabletmanager/healthcheck.go, line 176 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMU5fh39MXkfUrYqxS:-KHMU5fh39MXkfUrYqxT:1524822088) ([raw file](https://github.com/youtube/vitess/blob/e1118ee3dd170e81c3fe04a4fdc93d900b9b3c55/go/vt/tabletmanager/healthcheck.go#L176)):*
> ```Go
> 	shouldBeServing := false
> 	runUpdateStream := true
> 	if topo.IsRunningQueryService(tablet.Type) && agent.BinlogPlayerMap != nil && !agent.BinlogPlayerMap.isRunningFilteredReplication() {
> ```

Shouldn't this be:

``` go
if IsRunningQueryService() && (BinlogPlayerMap == nil || !BinlogPlayerMap.isRunningFilteredReplication()) {
```
?

---

*[go/vt/tabletmanager/healthcheck.go, line 362 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMZs9Pjch2qcbP3DvA:-KHMZs9Pjch2qcbP3DvB:2139135283) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/tabletmanager/healthcheck.go#L362)):*
> ```Go
> 	// Note that this is where we might block for *gracePeriod, depending on the
> 	// type of state change. See changeCallback() for details.
> 	if err := agent.refreshTablet(agent.batchCtx, "healthcheck"); err != nil {
> ```

Without this call, we'll stop going into lameduck when transitioning healthy -> not healthy (for replica or batch). That was added to help with vtgate EPM. I think in this new spareless world, the right place to add that lameduck back is before `disallowQueries()` above? I'm not totally sure yet.

This call also used to detect when the MySQL port changes (due to mysqld restart) when transitioning between healthy and not healthy. Not sure if we rely on that?

---

*[go/vt/tabletmanager/rpc_backup.go, line 61 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMisQZgC_mVuIGAuLx:-KHMisQ_GU6UCc8-v70m:-121082320) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_backup.go#L61)):*
> ```Go
> 
> 	// let's update our internal state (start query service and other things)
> 	if err := agent.refreshTablet(ctx, "after backup"); err != nil {
> ```

Backup() is under RPCWrapLockAction, so it will already call refreshTablet() after this returns.

---

*[go/vt/tabletmanager/rpc_replication.go, line 287 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMjbokysOC-LlV5TIE:-KHMjbokysOC-LlV5TIF:-1740213034) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_replication.go#L287)):*
> ```Go
> 
> // SetMaster sets replication master, and waits for the
> // reparent_journal table entry up to context timeout
> ```

Comment is missing RPCWrap type specification.

---

*[go/vt/tabletmanager/rpc_replication.go, line 330 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMjN3W_hRLnU-t3ISc:-KHMjN3W_hRLnU-t3ISd:1004971001) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_replication.go#L330)):*
> ```Go
> 	}
> 
> 	// change our type to spare if we used to be the master
> ```

Comment is out of date.

---

*[go/vt/vtctl/vtctl.go, line 172 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMl52O0_sVoJ5FFLpd:-KHMl52O0_sVoJ5FFLpe:-650733194) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/vtctl/vtctl.go#L172)):*
> ```Go
> 				"Reloads the tablet record on the specified tablet."},
> 			{"RunHealthCheck", commandRunHealthCheck,
> 				"<tablet alias> <target tablet type>",
> ```

Don't forget to regenerate the doc.

---

*[proto/topodata.proto, line 94 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMJj_DxYbVD0mtJhjo:-KHMJj_DxYbVD0mtJhjp:1139518114) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/proto/topodata.proto#L94)):*
> ```protobuf
> 
>   // tablet health information
>   map<string, string> health_map = 11;
> ```

Since this proto is stored in topo, and we have beta users, I think we should do this field removal the "safe" way according to the [protobuf guide](https://developers.google.com/protocol-buffers/docs/proto#reserved):

```
// OBSOLETE: tablet health information
// map<string, string> health_map = 11;
reserved 11;
```

---

*[proto/topodata.proto, line 223 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMLwjdLszsXSByC4MU:-KHMLwjdLszsXSByC4MV:1662569705) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/proto/topodata.proto#L223)):*
> ```protobuf
> 
>   // The health entries.
>   map<string, string> health_map = 4;
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1685)*

**Comment by alainjobart** [comment]
Review status: 59 of 64 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[go/vt/mysqlctl/health.go, line 34 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMQIn-FrybrSyUqYRf:-KHQ8l-25NuJnSGG9WEg:-499146009) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/mysqlctl/health.go#L34)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> We should note in the comment that this is a worst case extrapolation. It's possible that it caught up in between polls, but we'll assume the worst.</details>
Done.

---

*[go/vt/mysqlctl/health.go, line 36 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMPt2Bh-idmrwqlDXS:-KHQ92G117Vtzc9sZ1Cg:-499146009) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/mysqlctl/health.go#L36)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This would be cleaner if you make `lastKnownValue` be of type `time.Duration`. Then you do the conversion in only one place (when setting `lastKnownValue`) and at the end you `return mrl.lastKnownValue`.</details>
Done.

---

*[go/vt/tabletmanager/action_agent.go, line 199 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMRdtRU48uy2svDveR:-KHQ9Bngb8_bqZU-LUwi:1984097869) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/tabletmanager/action_agent.go#L199)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> I think removing this will break internal dashboards and possibly some monitoring (based on my code search for "target-tablet-type"). Are you planning to fix that along with the import? Or should we remove this later after we've migrated the monitoring to some other variable?</details>
Let's talk about this one, I can leave it as is with the current type easily.

---

*[go/vt/tabletmanager/healthcheck.go, line 176 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMU5fh39MXkfUrYqxS:-KHQAAoSHwm0HJeXFJOU:1641831048) ([raw file](https://github.com/youtube/vitess/blob/e1118ee3dd170e81c3fe04a4fdc93d900b9b3c55/go/vt/tabletmanager/healthcheck.go#L176)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Shouldn't this be:
> 
> ``` go
> if IsRunningQueryService() && (BinlogPlayerMap == nil || !BinlogPlayerMap.isRunningFilteredReplication()) {
> ```
> ?</details>
yes it should be!

---

*[go/vt/tabletmanager/healthcheck.go, line 362 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMZs9Pjch2qcbP3DvA:-KHQB0cXV-1tzGi2Qvke:1910736208) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/tabletmanager/healthcheck.go#L362)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Without this call, we'll stop going into lameduck when transitioning healthy -> not healthy (for replica or batch). That was added to help with vtgate EPM. I think in this new spareless world, the right place to add that lameduck back is before `disallowQueries()` above? I'm not totally sure yet.
> 
> This call also used to detect when the MySQL port changes (due to mysqld restart) when transitioning between healthy and not healthy. Not sure if we rely on that?</details>
I am not sure here. If we're unhealthy, we can't serve anyway, so is there any value in going into lameduck? Ah yes, if droid tells us it's being drained. I will add it then.

Also adding the mysql port change when going from non-serving to serving, good catch.

---

*[go/vt/tabletmanager/rpc_backup.go, line 61 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMisQZgC_mVuIGAuLx:-KHQNzI4O5NY4brjDQ5J:1135403783) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_backup.go#L61)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Backup() is under RPCWrapLockAction, so it will already call refreshTablet() after this returns.</details>
we need the health check to run after the tablet is refreshed though, otherwise it won't get the right type.

I am thinking of re-running health check after a refresh state, so it broadcasts the right state. Then we can leave the restarting of the query service to only be in health check. What do you think?

---

*[go/vt/tabletmanager/rpc_replication.go, line 287 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMjbokysOC-LlV5TIE:-KHQOVL8zRYGb9jGqz3r:-499146009) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_replication.go#L287)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Comment is missing RPCWrap type specification.</details>
Done.

---

*[go/vt/tabletmanager/rpc_replication.go, line 330 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMjN3W_hRLnU-t3ISc:-KHQO_YlgGKpASUu8Xpy:-499146009) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_replication.go#L330)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Comment is out of date.</details>
Done.

---

*[proto/topodata.proto, line 94 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMJj_DxYbVD0mtJhjo:-KHQP3iJ8fo_l_u815IT:-499146009) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/proto/topodata.proto#L94)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Since this proto is stored in topo, and we have beta users, I think we should do this field removal the "safe" way according to the [protobuf guide](https://developers.google.com/protocol-buffers/docs/proto#reserved):
> 
> ```
> // OBSOLETE: tablet health information
> // map<string, string> health_map = 11;
> reserved 11;
> ```</details>
Done.

---

*[proto/topodata.proto, line 223 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMLwjdLszsXSByC4MU:-KHQP42CuS0JTnNAIW3k:-499146009) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/proto/topodata.proto#L223)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Same here.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1685)*

**Comment by enisoc** [comment]
Reviewed 22 of 22 files at r3, 4 of 10 files at r4.
Review status: 63 of 69 files reviewed at latest revision, 6 unresolved discussions, some commit checks broke.

---

*[go/vt/health/health.go, line 107 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHQwKssclgyRZCexsNz:-KHQwKst4F_6s8XX7G-K:-2126753113) ([raw file](https://github.com/youtube/vitess/blob/4000a72f2cb3057b52427d309c4969be99c2aba8/go/vt/health/health.go#L107)):*
> ```Go
> 		switch s.err {
> 		case ErrSlaveNotRunning:
> 			err = ErrSlaveNotRunning
> ```

Perhaps a comment for posterity:

```
// Return the ErrSlaveNotRunning sentinel value, only if there are no other errors.
```

---

*[go/vt/tabletmanager/healthcheck.go, line 371 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHQrDSjF2tfbe0JKVEg:-KHQrDSjF2tfbe0JKVEh:-1894854902) ([raw file](https://github.com/youtube/vitess/blob/9f93aaa784cd8bf0eb4313aece80cc030399f5ae/go/vt/tabletmanager/healthcheck.go#L371)):*
> ```Go
> 	}
> 
> 	// in any case, we're done now
> ```

Previously, the fact that we don't call `disallowQueries()` in `terminateHealthChecks()` for a master was intentional. In case of a master doing a graceful restart, we want it to continue serving during servenv lameduck, because there's nowhere else for master queries to go:

https://github.com/youtube/vitess/blob/master/go/vt/servenv/run.go#L42

After servenv lameduck, the queryservice is stopped from a `servenv.OnClose()` hook:

https://github.com/youtube/vitess/blob/master/go/cmd/vttablet/vttablet.go#L90

---

*[go/vt/tabletmanager/rpc_backup.go, line 61 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMisQZgC_mVuIGAuLx:-KHQsCz3_PBUx7znxBBd:677042770) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_backup.go#L61)):*
<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> we need the health check to run after the tablet is refreshed though, otherwise it won't get the right type.
> 
> I am thinking of re-running health check after a refresh state, so it broadcasts the right state. Then we can leave the restarting of the query service to only be in health check. What do you think?</details>
SGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1685)*

**Comment by alainjobart** [comment]
Review status: 55 of 69 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/vt/health/health.go, line 107 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHQwKssclgyRZCexsNz:-KHRYgnMkWzbsRgUEjHm:-499146009) ([raw file](https://github.com/youtube/vitess/blob/4000a72f2cb3057b52427d309c4969be99c2aba8/go/vt/health/health.go#L107)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Perhaps a comment for posterity:
> 
> ```
> // Return the ErrSlaveNotRunning sentinel value, only if there are no other errors.
> ```</details>
Done.

---

*[go/vt/tabletmanager/action_agent.go, line 187 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMT2UfvMFsLzoGd4yQ:-KHRYiy3FcHXyCron6qZ:1982305535) ([raw file](https://github.com/youtube/vitess/blob/e2ea7654a51d3179ac2efdccd899b4b160f8f633/go/vt/tabletmanager/action_agent.go#L187)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This will break some internal monitoring (vtcoproc). That probably needs to be fixed prior to importing this change, since the coproc is rolled out separately.</details>
So we realized coproc is now obsolete, and will go away.

---

*[go/vt/tabletmanager/healthcheck.go, line 371 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHQrDSjF2tfbe0JKVEg:-KHRYqscHp-L_S_8NbE3:208140403) ([raw file](https://github.com/youtube/vitess/blob/9f93aaa784cd8bf0eb4313aece80cc030399f5ae/go/vt/tabletmanager/healthcheck.go#L371)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Previously, the fact that we don't call `disallowQueries()` in `terminateHealthChecks()` for a master was intentional. In case of a master doing a graceful restart, we want it to continue serving during servenv lameduck, because there's nowhere else for master queries to go:
> 
> https://github.com/youtube/vitess/blob/master/go/vt/servenv/run.go#L42
> 
> After servenv lameduck, the queryservice is stopped from a `servenv.OnClose()` hook:
> 
> https://github.com/youtube/vitess/blob/master/go/cmd/vttablet/vttablet.go#L90</details>
I reverted back, and added a comment.

---

*[go/vt/tabletmanager/rpc_backup.go, line 61 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1685#-KHMisQZgC_mVuIGAuLx:-KHRYuRUYRtSWmngHITy:-257905449) ([raw file](https://github.com/youtube/vitess/blob/a1f9feeac1e8ba86d62b00996772ce71a700cce6/go/vt/tabletmanager/rpc_backup.go#L61)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> SGTM</details>
I ended up just simplifying the logic and remembering it. This is a bigger change that I'm not willing to make just yet.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1685)*

**Comment by enisoc** [comment]
:lgtm: after you regenerate the vtctl doc.

<details><summary><i>Previously, alainjobart (Alain Jobart) wrote…</i></summary>
> #### Do not change type or health map for health reasons\.
> 
> WIP, not ready for review yet.
> 
> 
> </details>


---

Reviewed 5 of 10 files at r4, 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1685#-:-KHS4CL66RS1D_ligC7h:-1538578100)*

**Pull request merged**
