### PR TITLE
Reduce unit test flakiness

### PR DESCRIPTION
**Pull request by guoliang100**
@alainjobart @michael-berlin @enisoc

### CODE REVIEW

**Comment by michael-berlin** [comment]
@guoliang100 Did you run the test in an infinite loop?

cd <path>
while true; do go test || break; done

**Comment by michael-berlin** [comment]
There's at least one flake left:

E0810 17:37:18.659550   22228 srv_topo_server.go:464] GetEndPoints(context.Background.WithDeadline(2015-08-10 17:37:20.659485461 -0700 PDT [1.999887875s]), cell3, test_ks, 0, replica) failed: GetEndPoints: invalid cell: cell3 (no cached value, caching and returning error)
E0810 17:37:18.661086   22228 srv_topo_server.go:464] GetEndPoints(context.Background.WithDeadline(2015-08-10 17:37:20.661004843 -0700 PDT [1.999888591s]), cell3, test_ks, 2, master) failed: GetEndPoints: invalid cell: cell3 (no cached value, caching and returning error)
W0810 17:37:18.662364   22228 srv_topo_server.go:311] GetSrvKeyspace(context.Background.WithDeadline(2015-08-10 17:37:20.662323412 -0700 PDT [1.999928828s]), , test_ks) failed: Unknown keyspace (returning cached value: &{map[]   map[] 0 0} <nil>)
E0810 17:37:18.663658   22228 srv_topo_server.go:308] GetSrvKeyspace(context.Background.WithDeadline(2015-08-10 17:37:20.663632798 -0700 PDT [1.999937568s]), , unknown_ks) failed: Unknown keyspace (no cached value, caching and returning error)
W0810 17:37:18.664009   22228 srv_topo_server.go:311] GetSrvKeyspace(context.Background.WithDeadline(2015-08-10 17:37:20.663969503 -0700 PDT [1.999916752s]), , unknown_ks) failed: Unknown keyspace (returning cached value: <nil> Unknown keyspace)
PASS
--- FAIL: TestResolverExecBatchAsTransaction (0.01s)
	resolver_test.go:555: want 1, got 2

Can you please fix that as well?

**Comment by guoliang100** [comment]
TestResolverExecBatchAsTransaction has problem more than just being flaky. It should be sent to the original author to investigate.

**Comment by guoliang100** [comment]
Add back TestScatterConnClose with flaky fix, and some code improvements.

**Comment by michael-berlin** [comment]
LGTM

Awesome, thanks!

**Pull request merged**
