### PR TITLE
add new vterrors.Wrap and vterrors.Wrapf, properly wrap errors in route.go

### PR DESCRIPTION
**Pull request by bbeaudreault**
@sougou as discussed

### CODE REVIEW

**Comment by sougou** [comment]
Looks like there are some new test errors.

**Comment by bbeaudreault** [comment]
I pushed a fix, was a syntax error -- forgot to expand the varargs when passing to fmt.Sprintf

**Comment by bbeaudreault** [comment]
tests all passing now

**Comment by sougou** [comment]
LGTM

**Pull request merged**
