### PR TITLE
Add parser support for transaction statements

### PR DESCRIPTION
**Pull request by yuananf**

### CODE REVIEW

**Comment by sougou** [comment]
About time :).
Thanks for the work.

There are a couple of more places to fix: all code that switches on the various statement types. I did a quick search and found the following places:
* go/vt/vttablet/tabletserver/planbuilder/permission.go
* go/vt/vttablet/tabletserver/planbuilder/plan.go
* go/vt/vtgate/planbuilder/builder.go

**Comment by yuananf** [comment]
@sougou I looked at these switch codes, my understanding is, for transaction statements, they are all handled at vtgate level, and won't go down to vttablet. And for now the code in vtgate's builder.go will never go to `*sqlparser.Begin`, `*sqlparser.Commit`, etc case.

I'm new to vitess, please correct me if I was wrong.

**Comment by sougou** [comment]
I took a second look. It's better to be defensive and handle those cases if something accidentally slipped through. In this respect:
* builder.go should return an unsupported construct error
* permission.go should no-op (like OhterRead)
* plan.go: no need to change because the default case will catch those.

**Comment by yuananf** [comment]
done

**Comment by sougou** [comment]
LGTM

**Pull request merged**
