### PR TITLE
Add optional effective_caller_id parameter to vtgate_client.py.

### PR DESCRIPTION
**Pull request by dumbunny**

### CODE REVIEW

**Comment by dumbunny** [comment]
@mberlin This small change is needed to support an upcoming effective_caller_id change in the YT code base.

**Comment by alainjobart** [comment]
You should also add tests to python_client_test.py to test this works as expected, see what vtgatecleinttest does with the passed values in callerid.go. Would test the stubby version in google3 as well.

**Comment by guokeno0** [comment]
Please refer to https://github.com/youtube/vitess/blob/master/go/cmd/vtgateclienttest/services/callerid.go
for callerid testing logic and https://github.com/youtube/vitess/blob/master/go/cmd/vtgateclienttest/ contains a mock testing vtgate for testing clients

**Comment by michael-berlin** [comment]
@dumbunny I've reviewed the current state and I'm fine with that. Let me know when you added the tests and I'll review them as well.

Please note that you need to mention @michael-berlin on Github because "mberlin" is already taken :(

**Comment by dumbunny** [comment]
My bad. For some reason, @dumbunny wasn't taken when I got on.

Dean Yasuda

**Pull request merged**
