### PR TITLE
Removing the ability to listen to a secure port ('vts' port).

### PR DESCRIPTION
**Pull request by alainjobart**
This is generally unused, and we'll use encrypted gRPC if needed.

@sougou @enisoc @nurblieh

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM

**Comment by sougou** [comment]
Very nice. I think we can also get rid of the port map. It should just be "port".

**Comment by alainjobart** [comment]
You mean with the gRPC port being on a different port and all? ;)

**Comment by sougou** [comment]
Are you sure? I think gRPC can use the http port. The protocol is supposed to be established in the handshake, or may be URL.

**Comment by alainjobart** [comment]
gRPC uses HTTP 2 streaming protocol, needs an HTTP 2 server, and the go server is not there yet. So it has to be some custom code for now until it's fine.

**Pull request merged**
