### PR TITLE
Fixing SplitQuery API for v3.

### PR DESCRIPTION
**Pull request by alainjobart**
@sougou @erzel

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1789)

### CODE REVIEW

**Comment by sougou** [comment]
LGTM

**Comment by erzel** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/vtgate/vtgate.go, line 566 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1789#-KKAMG4aXDzFDjZ04FKJ:-KKAMG4aXDzFDjZ04FKK:1281289814) ([raw file](https://github.com/youtube/vitess/blob/772a0ddf84ec9371b62f0bf0fee917a6c65aa8ff/go/vt/vtgate/vtgate.go#L566)):*
> ```Go
> 	}
> 	perShardSplitCount := int64(math.Ceil(float64(splitCount) / float64(len(shards))))
> 	// sharding_column_type != KeyspaceIdType_UNSET can happen in one of the following two cases:
> ```

Can you update the comment here and below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1789)*

**Comment by erzel** [comment]
Thanks for doing this! LGTM after you address my comment.

<details><summary><i>Previously, sougou wrote…</i></summary>
> LGTM
> 
> [Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/1789/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)
</details>


---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1789#-:-KKAMiQ1eh5PhPbWc-XH:-2005309003)*

**Comment by harshit-gangal** [comment]
@enisoc This should also be part of 2.0

**Pull request merged**
