### PR TITLE
Bugfix: Vitess backup restore process when using relay-log-info-repository = TABLE

### PR DESCRIPTION
**Pull request by bbeaudreault**
The default value for `relay-log-info-repository` is FILE, and vitess does not override that in its my.cnf files. However, TABLE is good to use because it protects you from unexpected halts in the slave. See https://dev.mysql.com/doc/refman/5.7/en/replication-options-slave.html#option_mysqld_relay-log-info-repository. We run with TABLE and have seen the issues below.

The backup process for Vitess skips backing up relay log files, and does not copy the repository file. For those of us using `relay-log-info-repository = TABLE`, our relay log position gets carried along in the backup. This causes the restore to fail with: `Slave failed to initialize relay log info structure from the repository`. This is because the `mysql.slave_relay_log_info` table points to a relay log file and position that does not exist in a newly restored tablet.

There were 3 options I could think of (open to others):

- Exclude the `mysql/slave_relay_log_info.idb` and `mysql/slave_relay_log_info.frm` files from the backup. This looked like it would be pretty hacky based on the current code, and I'm not totally sure it would be enough.
- Delete the above files from the restored files before starting up mysql. Same points above apply, but seems even more hacky.
- Run `RESET SLAVE` before starting up a newly restored tablet.

The `RESET SLAVE` approach is what I went with because it seemed the least hacky and most robust. It shouldn't cause an issue for those without `TABLE` and fully sets the stage for the new slave to pick up with AUTO_POSITION=1 in the parent code.

### CODE REVIEW

**Comment by bbeaudreault** [comment]
Looking at this more, I wonder if I should either:

1) Put this new code in `restore.startReplication` instead of in `restore.Restore`

2) Add `RESET SLAVE` to `SetSlavePositionCommands`

Thoughts?

**Comment by bbeaudreault** [comment]
I did option 1 to fix travis, but am also open to doing option 2 if you guys think that would be better

**Comment by bbeaudreault** [comment]
@alainjobart @sougou any thoughts on this? would love to get merged

**Comment by sougou** [comment]
@bbeaudreault We're all backlogged on our work. If no one else gets time in the next couple of days, I'll try to carve out time to review this.

**Pull request merged**
