### PR TITLE
add an option to enable graceful stop of the grpc server on sigterm

### PR DESCRIPTION
**Pull request by bbeaudreault**
Added this as an option instead of all the time, but if you'd like we can make it all the time.

Also, they improved the gracefulstop in grpc-go 1.5.1. How do we know what version we are on, and should we upgrade? In the vendor.json I just see a bunch of sha's so hard to know.

I'm testing this in our env now.

### CODE REVIEW

**Comment by bbeaudreault** [comment]
GracefulStop was added https://github.com/grpc/grpc-go/issues/147 -- the idea is to send a GOAWAY to clients, accept no new connections, then allow connections to drain.

**Comment by sougou** [comment]
I think this should be always on. I don't see any harm.

**Comment by bbeaudreault** [comment]
removed the option

**Comment by sougou** [comment]
LGTM

**Pull request merged**
