### PR TITLE
Log

### PR DESCRIPTION
**Pull request by alainjobart**
@aaijazi @ryszard 
This should address both bugs:
- Worker interface is changed to Run(context) error (and the framework remembers the error, so the worker doesn't have to)
- if you use a StatusWorker (where I put a lot of common code), you get the StatusXXX methods for free.

### CODE REVIEW

**Comment by aaijazi** [comment]
A couple of issues that I'd like to see addressed, but this looks like good cleanup otherwise, thanks! I should have made the API changes when I actually added contexts everywhere - not sure why I didn't.

**Comment by alainjobart** [comment]
OK fixed the two issues, PTAL, thanks!

**Comment by alainjobart** [comment]
OK fixed all comments, PTAL

**Comment by aaijazi** [comment]
LGTM

**Comment by ryszard** [comment]
LGTM

**Pull request merged**
