### PR TITLE
Dynamic query rule support for vttablet

### PR DESCRIPTION
**Pull request by guokeno0**
A few changes in this patch:

1. QueryRuleSources top level framework to manage dynamic query rule sources
    - Pluggable machanism for new dynamic query rule implementations
    - Complete decouple of query rule management and query service
2. File based and Zookeeper based dynamic custom rule support
3. Unit and site tests for dynamic query rule machanisms

### CODE REVIEW

**Comment by sougou** [comment]
Looks like this CL has diverged. Can you merge from master & resolve conflicts?

**Comment by guokeno0** [comment]
Master merged. The merge didn't affect the existing patch.

2015-01-02 21:34 GMT-08:00 sougou <notifications@github.com>:

**Comment by guokeno0** [comment]
@sougou 
As discussed, polling is now disabled for file based custom rule, and the function buildQueryRule  is now exported as "BuildQueryRule" to support file formats other than JSON

**Comment by sougou** [comment]
LGTM

**Pull request merged**
