### PR TITLE
tabletserver: retry streaming query on conn error

### PR DESCRIPTION
**Pull request by sougou**
@erzel 
Streaming queries have recently become killable due to context
changes. So, a connection could potentially be dead due to a
previous query kill. So, we should retry streaming queries also
if we get a connection error.

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1539)

### CODE REVIEW

**Comment by michael-berlin** [comment]
Sugu, you accidentally removed the execution bits from ```test.go``` in your first commit.

Can you please restore it?

This is probably the easiest way:
```sh
# Make sure your branch is clear and you don't have pending changes.
git update-index --chmod=-x bootstrap.sh
git commit
```

Thanks!

**Comment by erzel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBtSrc_IHVfeCndcH8I:232021906) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
Shouldn't it be dbconn.Stream in the error message? Also, wouldn't a "panic" be better here?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by sougou** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBte7P4JSNMO1PACWiC:-771475957) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
Done.
This used to be a panic until @aaijazi changed this as part of his error cleanup, but I don't remember the reasons any more.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by aaijazi** [comment]
*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBtkLg8dTQI8nMqGdbj:1000339997) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
I have no idea either. Seems like this PR was when it changed: https://github.com/youtube/vitess/pull/906

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by erzel** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBtldcb7xYPfrCTelDi:961649438) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
IMHO this should be a panic. LGTM otherwise.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by sougou** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBtn45FL7OjEd39l-PD:-499146009) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by sougou** [comment]
LGTM
(proxy-approving for @erzel)

**Comment by sougou** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by sougou** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBuSzTWtLvfhSerwuAm:-499146009) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by sougou** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[go/vt/tabletserver/dbconn.go, line 132 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1539#-KBtSrcZAC8Hl-CWMD1K:-KBuTGue2kFZLrB9kjTI:262832617) ([raw file](https://github.com/youtube/vitess/blob/18f56de4decd6f003c222c63ef8c8996d355a90b/go/vt/tabletserver/dbconn.go#L132)):*
Looks like anyone who said anything has to approve. So, I'm going to override knowing that we're all in agreement.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539)*

**Comment by aaijazi** [comment]
http://www.reactiongifs.com/wp-content/uploads/2013/09/confidence.gif

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1539#-:-KBuT_WIC48PTiwXofd7:-1896639138)*

**Comment by sougou** [comment]
LGTM
again... (apologies for the spam)

**Comment by michael-berlin** [comment]
I think one LGTM is enough.

If I understood @enisoc correctly, you could also just merge changes yourself since you're an admin of our repository.

**Pull request merged**
