### PR TITLE
worker.py: Remove RebuildKeyspaceGraph step.

### PR DESCRIPTION
**Pull request by michael-berlin**
It's not necessary directly after InitShardMaster.

@enisoc @aaijazi @alainjobart

### CODE REVIEW

**Comment by aaijazi** [comment]
LGTM.

To answer your above question: try running the test without and it see if it works :).

**Comment by michael-berlin** [comment]
Ammar, at first I thought the same. But the test won't find out if the topology is not in a consistent state.

I've answered the question myself by looking into the code. See the commit message of the second commit.

@enisoc Can you please confirm and LGTM?

**Comment by enisoc** [comment]
I think we still need RebuildKeyspaceGraph in both cases.

RebuildKeyspaceGraph does more than just rebuild the serving graph. It also looks at each shard's global record to see which types (master, replica, etc.) that shard is serving. It then writes a map to each cell-local SrvKeyspace node, which tells VTGate which set of shards to use for a given type. That way, we can have replica served from the new set of shards, while master is still served from the old set, as part of the transition period.

I looked at the MigrateServedTypes command, and it doesn't appear to trigger a RebuildKeyspaceGraph, so I think we need to keep RKG as an additional step any time the serving state of a shard changes.

**Comment by alainjobart** [comment]
Both MigrateServedTypes and MigrateServedFrom rebuild the Keyspace at the
end, if there is no error. If that is not happening, we should be
investigating that, but it's the intended behavior.

**Comment by enisoc** [comment]
Ah I see it now:

https://github.com/youtube/vitess/blob/master/go/vt/wrangler/keyspace.go#L171

I was looking at Wrangler.migrateServedTypes instead of Wrangler.MigrateServedTypes. For many commands in Wrangler, the only difference is that the public function first acquires a lock before calling the private one. In this case, the public function does more.

In that case, your removals here should be ok, except for the one after InitShardMaster. I think that's still needed.

**Comment by michael-berlin** [comment]
re: the case after InitShardMaster

I'm running RebuildKeyspaceGraph there only for the original source shard, but not for the destination shards.

Until the traffic is migrated, they won't be referenced in the "SrvKeyspace" and therefore we don't need to rebuild that file for them.

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
