### PR TITLE
S3 Backup Storage Plugin

### PR DESCRIPTION
**Pull request by sgrankin**
Implements backup storage on S3 via official aws go sdk.

The code is heavily based on (or copy-pasta'd from) the GCS & Ceph backup plugin.

Review notes:
- The vendored dependencies were fetched as github.com/aws/aws-sdk-go/... It may be possible to bring in a smaller subset.
- Acess is meant to be configured via standard AWS envs/files, which is why there's no config beyond region and bucket (http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs). Should this be documented somewhere? Our deployment uses IAM roles to let the workers access the bucket transparently.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1799)

### CODE REVIEW

**Comment by enisoc** [comment]
This looks great, thanks! Just a couple suggestions/questions in the line comments.

For the vendored dependencies, I'd prefer to use the smallest subset that works. I think it should be enough if you revert your vendor.json changes and run govendor for just the lines that are explicitly imported by the new s3.go:

```sh
govendor fetch "github.com/aws/aws-sdk-go/aws"
govendor fetch "github.com/aws/aws-sdk-go/aws/session"
govendor fetch "github.com/aws/aws-sdk-go/service/s3"
govendor fetch "github.com/aws/aws-sdk-go/service/s3/s3manager"
```

If that ends up being all the same stuff, then so be it. If the above is insufficient to pull in all needed transitive dependencies, then govendor isn't working properly. Please give it a shot and let me know.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFiJcTwvU0NFWoH4Ec:-KKFiJcTwvU0NFWoH4Ed:-1710639973) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L1)):*
> ```Go
> // Package s3backupstorage implements the BackupStorage interface for AWS S3
> ```

You mentioned that AWS configs are pulled in automatically via standard paths and env vars. I think the package comment here is a good place to document that. Turn this into a multi-line block comment, put a period on the end of the summary sentence, and add a paragraph below with the link to the page explaining configs.

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 98 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFdLTuKYGEMtv2gKYe:-KKFdLTvwl0ECwBAqSk-:1337317209) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L98)):*
> ```Go
> 	}
> 	object := objName(bh.dir, bh.name, filename)
> 	out, err := bh.client.GetObject(&s3.GetObjectInput{
> ```

It looks like you used s3manager.Uploader to increase upload concurrency for large files, but here you use S3.GetObject rather than s3manager.Downloader. Is there a reason for that?

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 130 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFeOUOaUFhqB8agvTN:-KKFeOUOaUFhqB8agvTO:-519042937) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L130)):*
> ```Go
> 	var subdirs []string
> 	for {
> 		ojbs, err := c.ListObjectsV2(query)
> ```

Did you mean *objs*?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1799#-:-KKFgR-7vq3vMBwvRRbY:-1370210026)*

**Comment by sgrankin** [comment]
Unfortunately these commands produce this same set of deps I already had, so no change.  (I had some trouble getting govendor to pull in the right deps initially. I suspect the final vendor.json I submitted was the moral equivalent of these commands and not of the `...` fetch I indicated in the first comment).

---

Review status: 4 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFiJcTwvU0NFWoH4Ec:-KKFzEDGAYKPhVMxPZRD:-499146009) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L1)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> You mentioned that AWS configs are pulled in automatically via standard paths and env vars. I think the package comment here is a good place to document that. Turn this into a multi-line block comment, put a period on the end of the summary sentence, and add a paragraph below with the link to the page explaining configs.
</details>
Done.

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 98 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFdLTuKYGEMtv2gKYe:-KKFq8XX_ZKiMBYdthOL:-354876679) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L98)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> It looks like you used s3manager.Uploader to increase upload concurrency for large files, but here you use S3.GetObject rather than s3manager.Downloader. Is there a reason for that?
</details>
Yes, though it was due to interfaces available more than performance considerations.

S3.GetObject returns a ReadCloser, which can be returned directly from ReadFile.
Downloader.Download on the other hand wants an io.WriteAt destination, which I can't provide without either having a File destination or using a memory buffer.
Testing suggests the reader returned by GetObject is streaming the response.

The uploading situation is reversed:
Uploader.Upload takes a io.Reader; I used io.Pipe to return a mated io.WriteCloser from AddFile.
S3.PutObject on the other hand takes an io.ReadSeeker which cannot be matched to a WriteCloser without doing a local File or memory buffer.

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 130 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFeOUOaUFhqB8agvTN:-KKFo276wD8QhVBF9y5P:-271473915) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L130)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Did you mean *objs*?
</details>
😳 yep.  Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1799#-:-KKFn5bT0oX6BBWAxTB_:955665958)*

**Comment by enisoc** [comment]
LGTM. I'll merge once the updated docker bootstrap image is ready.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/mysqlctl/s3backupstorage/s3.go, line 98 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1799#-KKFdLTuKYGEMtv2gKYe:-KKGKVHkAy0Acxm_OtMW:536739810) ([raw file](https://github.com/youtube/vitess/blob/e90cca334bba66b1edaa1d28e4a481adf47fbe0b/go/vt/mysqlctl/s3backupstorage/s3.go#L98)):*
<details><summary><i>Previously, sgrankin (Sergey) wrote…</i></summary>
> Yes, though it was due to interfaces available more than performance considerations.
> 
> S3.GetObject returns a ReadCloser, which can be returned directly from ReadFile.
> Downloader.Download on the other hand wants an io.WriteAt destination, which I can't provide without either having a File destination or using a memory buffer.
> Testing suggests the reader returned by GetObject is streaming the response.
> 
> The uploading situation is reversed:
> Uploader.Upload takes a io.Reader; I used io.Pipe to return a mated io.WriteCloser from AddFile.
> S3.PutObject on the other hand takes an io.ReadSeeker which cannot be matched to a WriteCloser without doing a local File or memory buffer.
> 
</details>
Ah I see. In the future we should refactor our plugin interface to make this less awkward, but I agree that's the best compromise for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1799#-:-KKGL0Sa8qLyCBEIXts2:-1299298594)*

**Comment by sougou** [comment]
If you intend to (or succeed) in using Vitess with S3, please share your experiences :).

**Comment by enisoc** [comment]
@sougou Do you mean wtih S3 or with AWS? S3 should be straightforward, it's just a blobstore...

**Comment by sougou** [comment]
I guess I implied AWS, assuming that it's how S3 will get used.

**Comment by sgrankin** [comment]
AWS, and yep, will do.  Still in early experimentation :) Thanks for the review!

**Pull request merged**
