### PR TITLE
Adding utils.py option to skip builds, using it in the Makefile

### PR DESCRIPTION
**Pull request by alainjobart**
(after adding a rule to build before tests).

Global build takes about 2s to build all binaries, and it saves
about 4s in one run of mysqlctl.py, so it's gonna be good!

@enisoc @michael-berlin @dumbunny This is what I had in mind...

### CODE REVIEW

**Comment by aaijazi** [comment]
LGTM, but make sure that Travis passes before merging. (I just poked your Travis run so that it runs again, the previous failure looked flakey)

**Comment by michael-berlin** [comment]
LGTM

**Comment by enisoc** [comment]
So you're actually seeing a difference? Maybe it's changed in 1.5, but for me the second build is very fast:

```
$ make clean_pkg
$ time make build

real    0m13.822s
user    1m59.504s
sys     0m10.483s
$ time make build

real    0m0.292s
user    0m0.275s
sys     0m0.137s
```

**Comment by alainjobart** [comment]
The difference I see is between running a top-level build (that builds all the binaries at once), versus building each binary individually, one at a time, as the unit tests do by default.

Also, a repeated 'time make build' always takes around 2s for me, dunno how you get to 0.2... ha maybe you have go 1.5?

$ time make build
Fri Aug 21 12:20:58 PDT 2015: Building source tree

real	0m2.119s
user	0m1.991s
sys	0m0.130s

$ time make build
Fri Aug 21 12:21:02 PDT 2015: Building source tree

real	0m2.122s
user	0m2.009s
sys	0m0.117s

**Comment by michael-berlin** [comment]
@alainjobart Yes, Go 1.5 seems to have faster incremental build times :)

**Comment by enisoc** [comment]
Yes I do have 1.5. I bet that's the difference. The new compiler must be better about short-circuiting out when there's nothing to be done. Although the first compile is slower, which they warned would be the case since it's now in Go rather than C.

**Comment by enisoc** [comment]
Actually it's not clear if you ran `make clean_pkg` before your first `make build`. That removes object files for all the dependencies. So maybe the first compile isn't actually slower by much.

**Comment by alainjobart** [comment]
So you guys wanna do this or not? I think it's somewhat cleaner anyway, even if the compile doesn't take that long, building it all at first and then running the test is good. For every day developer usage, it doesn't matter... I can go either way.

**Comment by enisoc** [comment]
I say do it. It's got some benefits, especially for pre-1.5. And it should be invisible otherwise.

**Pull request merged**
