### PR TITLE
Have to white-list BSON, removing SASL.

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @aaijazi

### CODE REVIEW

**Comment by aaijazi** [comment]
I have no idea what motivated this, but sure, LGTM

**Comment by alainjobart** [comment]
@yaoshengzhe here you go!

**Comment by yaoshengzhe** [comment]
@alainjobart 
Fixed username in query executor (see https://github.com/youtube/vitess/pull/1069). Please do a rebase after merging pr/1069.

**Comment by alainjobart** [comment]
OK all fixed now, thanks @yaoshengzhe ! Will merge this when I can run an import to make sure the internal code base still works.

**Pull request merged**
