### PR TITLE
WIP: Change Travis CI to use new container-based infrastructure.

### PR DESCRIPTION
**Pull request by michael-berlin**

### CODE REVIEW

**Comment by alainjobart** [comment]
How do you get gRPC now? Does it install in the container?

**Comment by michael-berlin** [comment]
What was the reason why you had to install gRPC system wide?

This is no longer an option with the container-based infrastructure. But I also don't see any problem why we cannot just install it locally?

**Comment by alainjobart** [comment]
If it works installed locally, sure. I couldn't get the python libraries installed right, but maybe this is fixed in your setup. If stuff works, that's good!

**Comment by michael-berlin** [comment]
Closing this one because we made the switch in a different PR: https://github.com/youtube/vitess/pull/890

**Pull request closed without merging**
