### PR TITLE
ExecuteBatch Implementation

### PR DESCRIPTION
**Pull request by harshit-gangal**
This is client side implementation in JAVA.
It will loop through statement and provide a functionality to application.

When later executeBatch as a functionality is available in Vitess. The application would not be required to change the code and an upgrade of client will do the job.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/2252)

### CODE REVIEW

**Comment by enisoc** [comment]
@erzel and @dumbunny are the new reviewers for Java.

**Comment by erzel** [comment]
Thanks harshit. I'll have to take a look tomorrow since I'm busy today with other stuff on my plate. Sorry about that.

**Comment by harshit-gangal** [comment]
@erzel Gentle Reminder..

**Comment by harshit-gangal** [comment]
*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 348 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWu-PklRwoO2YC7eAZY:-KWw7HxwSsLALKqN-JAV:b-sd0rbf) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L348)):*
> at your implementation kills the previous value of this.bindVari
The expectation is application owner should either do executeBatch or executeUpdate. But, this gives a good point that we should even clear the content of bindVariables when an application calls other methods like execute(), executeQuery(), executeUpdate. I will make those changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252)*

**Comment by harshit-gangal** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 354 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWu-mPt4LEmQXZlDjD2:-KWw8O6_m0DoJ19WzmhB:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L354)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Same comment about 'nbr' to 'num' as for the VitessStatement case (see below). 
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 358 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWu-t479z5Qx04Uplsy:-KWw8RCnWiWVsXLAJI5o:b-bev0ru) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L358)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Why '-3'?
</details>
This is marking as default execution failed. Changed to use Statement.EXECUTE_FAILED.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 513 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWtuEMhQmw-Pr4Ue-Dc:-KWwVjTqsC_ctNo9L3EH:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L513)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> It seems that this method can either halt execution or continue executing statements depending on the type of error that occurred. Please document that precisely, as it's hard to understand from the code what the expected behavior should be. 
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 518 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWtniDiphDQh6N7zdrk:-KWwUlSwAR70IOwpHtOv:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L518)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Does 'nbr' stand for 'number'? Can you rename to 'numCommands' which is more standard?
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 519 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWtoYBR4nYt-uBgMb_Y:-KWwVD9Y-EhOt1d-wuwM:bebggy3) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L519)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> This 'if' statement seem redundant. I think you can remove it, and replace row 542 with return 'updateCounts'.
</details>
Point 1: If condition check if anything is added using addBatch then only operation will be performed.
Point 2: As per JDBC an int[] needs to be returned to we cannot return null in case no command is added in a batch i.e. Batch was empty on calling executeBatch

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 607 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWtqlH2nr4pP6Mev0-E:-KWwVrmTJ5joiZtPqykB:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L607)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> I'm not clear on the purpose of this method. Can you add documentation to it? 
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 613 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWtv5XHFY6us3PMuMx_:-KWwVpG9lWOld9PROng6:b-fecnxg) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L613)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Why set 'EXECUTE_FAILED' here?
</details>
This method halts when executeBatch happens within a transaction and that transaction no longer exists. Hence a commit decision cannot be made. 
So, irrespective of them being success do not make sense as they have been rolled back. Therefore assigning all the executed queries as failed and stopping the execution of pending queries in that batch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252)*

**Comment by harshit-gangal** [comment]
Incorporated all the comments.

---

Review status: 2 of 5 files reviewed at latest revision, 12 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 354 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWu02aMHRTV1bHZnqvZ:-KX1OVwh2Q1Cvz4HuPxH:b-gsk1wt) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L354)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Same comment on this 'if' being redundant as for the VitessStatement case (see below).
</details>
Same reply as in VitessStatement

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252#-:-KX1OQ9k4kk1Eb7buj0k:bq1eqtx)*

**Comment by harshit-gangal** [comment]
Review status: 2 of 5 files reviewed at latest revision, 17 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 348 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWu-PklRwoO2YC7eAZY:-KX9drfwa93gRIbN_jGo:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L348)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Can you document this expectation (that you either call executeBatch or executeUpdate but not both) in the class comment?
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 411 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX8-lFsAin_bg4GJF8y:-KX9e1xm4REVhtfnypkt:byveypq) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L411)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Consider using (here and elsewhere) the java foreach construct. It's clearer and less error-prone:
> for (Map<String, Object> bindVars : this.tachedArgs) {
>   ...
> }
> 
</details>
Yes, that is cleaner when index is not required. Here the index is required to assign values to updateCounts and also when an Exception occurs.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 822 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX85pFzfbaKe9CyqmMV:-KX9lrbDgdvlG95ocZR1:b-8c03j) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L822)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> How can this.batchedArgs be null here? From your code it looks like if it's null then there is some logical error in the program and that is more suited to throwing a runtime exception than returning a null. Consider using Preconditions.checkNotNull() if you want to check that condition. Same comment for the other getBatchedArgs in this PR.
</details>
In the constructor it is initialised. So, no need to check for null. Removed that part.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 519 at r1](https://reviewable.io:443/reviews/youtube/vitess/2252#-KWtoYBR4nYt-uBgMb_Y:-KX9pT8_BOqizz8kDfg3:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/4be73cdb38777aa316980c778c12bb10dde783b7/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L519)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> If you remove the 'if' and change line 542 to:
> 
> return updateCounts;
> 
> your code would return a 0-length int[] array (and not null) if numCommands is 0 and would have less exceptional cases; so it will be easier to reason about.
> 
> Also you can move the initialization of updateCounts into the 'try' block and avoid having a point in time where it is null.
> 
> 
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 497 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX83Gi7KYxeNr6Lru7m:-KX9nupH5YPij2dbDmBm:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L497)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Nit: space after the '//'
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 524 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX8-V0yk144qzsLfWX-:-KX9nzjGF9HusitKA3QK:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L524)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Thanks. Much clearer with the comment. Note that the last sentence in the comment is unfinished.
> Also, can you document that the user should either call executeBatch or one of the other execute... methods
> but not both, since you're overwriting the 'sql' member here.
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 631 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX84snoZsk2UWx5639u:-KXAIM7Te4jHmlglY0lX:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L631)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> The name of this method is not really descriptive of what it does. How about 'throwIfTransactionRolledback?' instead?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252)*

**Comment by harshit-gangal** [comment]
Now pushed.

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXHxz2xEpykcrBgI_Ds:-KXK7yo07SOkGnpez6jq:b-wikvei) (no related file):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Harshit -- I was out yesterday on vacation so sorry for not replying sooner. I've replied to your changes. It looks almost done, but I didn't see some of the changes you said you've done. Perhaps you forgot to push some of them? Also, it's thanksgiving in the US this week, so I'll only look at this PR again next Monday. 
</details>
Incorporated all the points.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 822 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX85pFzfbaKe9CyqmMV:-KXJyRecGQrIXPc5i3mF:b86c4l4) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L822)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Thanks. I missed the fact the you're returning a raw-type List. Please don't use raw-types (in most cases they are avoidable) so that the compiler can check type-safety. Same comment for the other getBatchedArgs.
</details>
This method was only added for test. I have removed it.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 400 at r7](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXHxiQ-jg4ziBuoEeL0:-KXK7oTFFys475cgi2uS:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3aa868a64f820bd2021828bd2edd1dd323ac1464/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L400)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Can you add documentation here (as you added for the similar method in VitessStatement)? 
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 524 at r3](https://reviewable.io:443/reviews/youtube/vitess/2252#-KX8-V0yk144qzsLfWX-:-KXJtyxxOGOIz0nI4dsh:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/6cb2fdec5892e0ef43b1324b9b3f2d7081b718ab/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L524)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> The last sentence is still unfinished.
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 535 at r7](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXHt7tSdryekmjNu2mM:-KXJuh4-GpOz94hji3BY:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/3aa868a64f820bd2021828bd2edd1dd323ac1464/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L535)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> The redundant 'if' is still here. In my opinion the code would be easier to read without it.  Same comment for the analogous line in VitessPreparedStatement.
</details>
Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 621 at r7](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXHvV-g4Yn7-uJWXsfs:-KXJxMfVukOZ_aLTuJxY:b-1tf8sl) ([raw file](https://github.com/youtube/vitess/blob/3aa868a64f820bd2021828bd2edd1dd323ac1464/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L621)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> Nit: It doesn't really 'halt', it throws an exception.
</details>
Done. Changed to what this method does and what happens when the Exception occurs is moved to executeBatch method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252#-:-KXK7wZH2NkWdeVTAAM6:b-9lffy2)*

**Comment by harshit-gangal** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java, line 431 at r8](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXgIyysSKWg3cz5bWcn:-KXilOw2jGFqb3ih8So_:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/e89ae3151a73608439934c98958f4e45872e6e8a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessPreparedStatement.java#L431)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary><blockquote>

'an' --> 'a'
</blockquote></details>

Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 32 at r8](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXgJBM9ykeyfc8cPmqk:-KXiluuwzBjCz0c-n5pK:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/e89ae3151a73608439934c98958f4e45872e6e8a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L32)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary><blockquote>

Consider this rewrite of your second sentence: "When 'executeBatch()' is called, the sql statement is not required; instead all the queries to be executed must be added via the 'addBatch(sql)' method." . I think it's clearer. Also the 'I' in 'In' and 'a' in 'All' should not be capitalized.
</blockquote></details>

Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 560 at r8](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXgJsoSjnhupfEolzvC:-KXilxpoOPKtBNp7uFV6:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/e89ae3151a73608439934c98958f4e45872e6e8a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L560)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary><blockquote>

'an'-->'a'
</blockquote></details>

Done.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 627 at r8](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXgOqPdzCNmf2bm3A94:-KXiuy5VRJyV3X0i-EZT:b-m12sb6) ([raw file](https://github.com/youtube/vitess/blob/e89ae3151a73608439934c98958f4e45872e6e8a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L627)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary><blockquote>

'a'--->'an'
</blockquote></details>

Can you clarify this comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252)*

**Comment by harshit-gangal** [comment]
Review status: 1 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXgQ8LSyNm8QcTctf-D:-KXn0wfQCbA5Ukf93DwF:b9wfkk7) (no related file):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

Merge this PR

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 627 at r8](https://reviewable.io:443/reviews/youtube/vitess/2252#-KXgOqPdzCNmf2bm3A94:-KXn0vJWM-rwn9R6EB9H:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/e89ae3151a73608439934c98958f4e45872e6e8a/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L627)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary><blockquote>

Oh. I didn't realize it could be pronounced 'a see-quel-exception'. Fair enough. I'm fine with either, then.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2252)*

**Comment by harshit-gangal** [comment]
Kindly merge this PR.

**Comment by erzel** [comment]
Sorry Harshit -- I thought you could merge it after I LGTM'd.

 Erez.

**Pull request merged**
