### PR TITLE
vtctld/web: Group shards by serving status.

### PR DESCRIPTION
**Pull request by dsslater**
@michael-berlin @enisoc 

Exposed a new API target called srvkeyspace. This API accepts a URL with 1 parameter called cell_keyspace. This parameter contains the cell and the keyspace where the srvkeyspace can be found in the format <cell>/<keyspace>. The server parses the parameter and uses the <cell> and <keyspace> to return the desired srvkeypace. The client then grabs the first partition in the srvkeyspace and populates the array activeShards with the shards in that partition. This array is then used to sort the shards in the keyspace view.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1815)

### CODE REVIEW

**Comment by michael-berlin** [comment]
David and Priyanka, you did a great job on this starter project today! I'm looking forward to your future contributions :-)

I've left a few small comments (mostly cleanups). Let's wait for Anthony's comments as well.

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[go/vt/vtctld/api.go, line 158 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpeqoxzx3vuUbxAMV3:-KKpeqoyN5h5zod1NwoI:-200754201) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L158)):*
> ```Go
> 
> 		// Get the shard record.
> 		//TODO: Attach serving information
> ```

Format for TODOs should be:

```go
// TODO(ldap): Here goes a full sentence with a trailing period.
```

---

*[go/vt/vtctld/api.go, line 161 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpf1pWewCQlavWshiD:-KKpf1pWewCQlavWshiE:1111449305) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L161)):*
> ```Go
> 		return ts.GetShard(ctx, keyspace, shard)
> 	})
> 	//Srvkeyspace
> ```

SrvKeyspace

---

*[go/vt/vtctld/api.go, line 162 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpf9BfEp-dxiR4WeDH:-KKpf9BfEp-dxiR4WeDI:-1223636088) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L162)):*
> ```Go
> 	})
> 	//Srvkeyspace
> 	handleCollection("srvkeyspace", func(r *http.Request) (interface{}, error) {
> ```

"srv_keyspace" because SrvKeyspace are effectively two words?

---

*[go/vt/vtctld/api.go, line 165 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpfTNpnd1c0tyWk1Q8:-KKpfTNpnd1c0tyWk1Q9:-352157366) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L165)):*
> ```Go
> 		keyspacePath := getItemPath(r.URL.Path)
> 		if !strings.Contains(keyspacePath, "/") {
> 			return nil, fmt.Errorf("invalid srvkeyspace path: %q", keyspacePath)
> ```

I understand you copy and pasted it. But I would like to see a more user-friendly error here e.g.

`invalid /srv_keyspace path: %q expected path: /srv_keyspace/<cell>/<keyspace>`

---

*[go/vt/vtctld/api.go, line 169 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpfqxVUPsuNRMP1LYC:-KKpfqxVUPsuNRMP1LYD:854528783) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L169)):*
> ```Go
> 		parts := strings.SplitN(keyspacePath, "/", 2)
> 		cell := parts[0]
> 		keyspace := parts[1]
> ```

This will result in a panic if `keyspacePath` does not have two `/`.

---

*[go/vt/vtctld/api.go, line 170 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpg1kBjfB0CnhNmbhf:-KKpg1kBjfB0CnhNmbhg:888084117) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L170)):*
> ```Go
> 		cell := parts[0]
> 		keyspace := parts[1]
> 		//TODO: Attach serving information
> ```

See comment above about the TODO format.

---

*[web/vtctld/keyspaces.html, line 47 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKplTOcf7ffR-0jXWmT:-KKplTOcf7ffR-0jXWmU:-1298994804) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.html#L47)):*
> ```HTML
>   <md-grid-list md-cols-sm="2" md-cols-md="4" md-cols-gt-md="8"
>       md-row-height="2:1" md-gutter="1em">
>     <md-grid-tile ng-if="!isActive(shard)" ng-repeat="shard in keyspace.shards" class="shard-tile md-whiteframe-z1">
> ```

Be aware of the overall complexity of rendering this page.

I couldn't find any information about the complexity of the "includes" function which you are using in "isActive". But I assume a single `includes()` call is already O(n). Calling it for all n shard elements will add up.

---

*[web/vtctld/keyspaces.js, line 1 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpj6KqKl3fhzfqVODR:-KKpj6KqKl3fhzfqVODS:1398805578) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L1)):*
> ```JavaScript
> app.controller('KeyspacesCtrl', function($scope, keyspaces, topodata, srvkeyspace, shards, actions) {
> ```

topodata is unused?

---

*[web/vtctld/keyspaces.js, line 10 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpggpogWQAcK3TiaUL:-KKpggpogWQAcK3TiaUM:371134752) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L10)):*
> ```JavaScript
> 
>   $scope.actions = actions;
>   $scope.activeShards = [];
> ```

Let's use "serving" for the variable name as well. I.e. "servingShards"

Please change other occurrences of "active" as well.

---

*[web/vtctld/keyspaces.js, line 13 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpnEVzQYhfCfgLBeBQ:-KKpnEW-zm9ditgYRaMF:-306209653) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L13)):*
> ```JavaScript
> 
>   $scope.isActive = function(name) {
>     return $scope.activeShards.includes(name);
> ```

Is "includes" the function referenced here? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

If that's the case, this code won't work on Internet Explorer or Edge. We should make a decision here where we draw the line which browsers we'll support and which not.

---

*[web/vtctld/keyspaces.js, line 17 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpgtdOxoqf_zfshnf4:-KKpgtdOxoqf_zfshnf5:1113399744) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L17)):*
> ```JavaScript
> 
>   $scope.refreshData = function() {
>     // Get list of keyspace names.
> ```

Comment should be moved below.

---

*[web/vtctld/keyspaces.js, line 20 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKphoK3umod-iZOf8NZ:-KKphoK3umod-iZOf8N_:1181716567) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L20)):*
> ```JavaScript
> 
>     srvkeyspace.get({cell_keyspace: "test/test_keyspace"}).$promise.then(function(value) {
>       var partition = value.partitions[0];
> ```

Let's always use the master partition i.e. where the ServedType of the partition equals the tablet type for master.

---

*[web/vtctld/keyspaces.js, line 22 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpiC6_AaX3UQf0R7GG:-KKpiC6_AaX3UQf0R7GH:225501749) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L22)):*
> ```JavaScript
>       var partition = value.partitions[0];
>       var shard_references = partition.shard_references;
>       var num_shards = shard_references.length;
> ```

No need to have an extra variable for this.

---

*[web/vtctld/keyspaces.js, line 26 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpi5P231WGNVto1D91:-KKpi5P231WGNVto1D92:37361173) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L26)):*
> ```JavaScript
>         $scope.activeShards.push(shard_references[i].name);
>       }
>       console.log($scope.activeShards);
> ```

Please remove debug output.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815#-:-KKpluSnHYvBL2jrfokL:2023246738)*

**Comment by enisoc** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[go/vt/vtctld/api.go, line 169 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpfqxVUPsuNRMP1LYC:-KKtpu5Uw1xidd9p4WqK:832691965) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/go/vt/vtctld/api.go#L169)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> This will result in a panic if `keyspacePath` does not have two `/`.
</details>
It's only necessary that `keyspacePath` has at least one `'/'`, which was already checked above.

---

*[web/vtctld/api.js, line 18 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKtqgej4Uuf7u1eV_QE:-KKtqgekY496bap28kAr:-1385133996) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/api.js#L18)):*
> ```JavaScript
> 
> app.factory('srvkeyspace', function($resource) {
>   return $resource('../api/srvkeyspace/:cell_keyspace');
> ```

Let's separate `:cell_keyspace` into two parameters: `api/srv_keyspace/:cell/:keyspace`. Either way will generate the same URL in the end, but this makes it more convenient for callers on the JS side.

---

*[web/vtctld/keyspaces.js, line 10 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpggpogWQAcK3TiaUL:-KKu0dnsR4jNyP7k8c_d:1513883564) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L10)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Let's use "serving" for the variable name as well. I.e. "servingShards"
> 
> Please change other occurrences of "active" as well.
</details>
Make this a "map" since you're using it to test membership: `$scope.servingShards = {};` To support multiple keyspaces, you can make this a map of maps, so testing membership would look like `if ($scope.servingShards[keyspace] && shard in $scope.servingShards[keyspace])`

---

*[web/vtctld/keyspaces.js, line 13 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKpnEVzQYhfCfgLBeBQ:-KKtrzuJ17kmgaR2SwPQ:-1826112454) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L13)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Is "includes" the function referenced here? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes
> 
> If that's the case, this code won't work on Internet Explorer or Edge. We should make a decision here where we draw the line which browsers we'll support and which not.
</details>
I agree `includes()` is too new to use for compatibility reasons. Since you need to check membership efficiently, it's probably best to pre-process the retrieved SrvKeyspace into a "map", as its called in Go terms. In JS terms it would just be an object (`obj = {};`) whose members you access like `obj['key'] = 'value';`. Then you can check membership with `if ('key' in obj)`.

---

*[web/vtctld/keyspaces.js, line 20 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKtxoGhs5Q_PFzESNYm:-KKtxoGhs5Q_PFzESNYn:-1510522245) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.js#L20)):*
> ```JavaScript
> 
>     srvkeyspace.get({cell_keyspace: "test/test_keyspace"}).$promise.then(function(value) {
>       var partition = value.partitions[0];
> ```

`value` could be undefined or an empty object, e.g. if you request a non-existent keyspace. Or `value.partitions` could be an empty list. You should check that each object property you need is defined before relying on it. In this case, the best thing to do if a property you need isn't there is just to return early, without setting anything in `$scope`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815)*

**Comment by enisoc** [comment]
Reviewed 2 of 4 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[web/vtctld/keyspaces.html, line 43 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKu3EJgKG6JLNEKFA5_:-KKu3EJgKG6JLNEKFA5a:614384805) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.html#L43)):*
> ```HTML
>     </md-grid-tile>
>   </md-grid-list>
>   <br/>
> ```

You shouldn't need `<br/>`. The `<h3>` should have its own `margin-top`. If we want the margins between elements to be bigger, we should use CSS rather than `<br/>`.

---

*[web/vtctld/keyspaces.html, line 44 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKu1oXyiWKajwNxh8pr:-KKu1oXyiWKajwNxh8ps:947753677) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.html#L44)):*
> ```HTML
>   </md-grid-list>
>   <br/>
>   <h3 ng-bind="(keyspace.shards.length - activeShards.length) == 0 ? 'No inactive shards found.' : 'Inactive Shards'"></h3>
> ```

If there are no non-serving shards, let's just hide the entire section. You can wrap both the heading and md-grid-list in a parent div that has an ng-if.

---

*[web/vtctld/keyspaces.html, line 47 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKplTOcf7ffR-0jXWmT:-KKu2K0vYS-GNJayiYgM:-997337375) ([raw file](https://github.com/youtube/vitess/blob/0900e66ae41f0d653d55fea0c5bd6aa8c90f4413/web/vtctld/keyspaces.html#L47)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Be aware of the overall complexity of rendering this page.
> 
> I couldn't find any information about the complexity of the "includes" function which you are using in "isActive". But I assume a single `includes()` call is already O(n). Calling it for all n shard elements will add up.
</details>
Also instead of iterating `keyspace.shards` twice and calling `isActive()` on each item, you can iterate the list once when you retrieve it in `keyspaces.js:refreshData()` and separate it into `keyspace.servingShards` and `keyspace.nonServingShards`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815)*

**Comment by enisoc** [comment]
Reviewed 2 of 4 files at r4.
Review status: 2 of 4 files reviewed at latest revision, 25 unresolved discussions.

---

*[go/vt/vtctld/api.go, line 174 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKybygSg82Da5bMNsFq:-KKybygSg82Da5bMNsFr:1811815512) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L174)):*
> ```Go
> 		parts := strings.SplitN(keyspacePath, "/", 2)
> 		//If no keyspace is provided returns all srvkeyspaces
> 		srvKeyspaces := make(map[string]interface{})
> ```

This should be defined in the block that lists all keyspaces. In the case where a specific keyspace is requested, you should directly return that SrvKeyspace object, rather than putting it in a map of one entry. This better matches conventions of REST-like HTTP APIs: requests for specific single objects return just that object, not a list of length one.

---

*[go/vt/vtctld/api.go, line 178 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKy_ZKu-kxfuuMKEiad:-KKy_ZKu-kxfuuMKEiae:436641000) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L178)):*
> ```Go
> 			//request was incorrectly formatted
> 			return nil, fmt.Errorf("invalid srvkeyspace path: %q  expected path: /srv_keyspace/<cell>/<keyspace>", keyspacePath)
> 		} else if parts[1] == "" {
> ```

You don't need the `else` here, since the above `if` block returns. A good description of when to omit `else` can be found here: https://golang.org/doc/effective_go.html#control-structures

Also this block and the next one duplicate the logic that `cell := parts[0]` and `keyspace := parts[1]`. These can be set before this block so the variables are shared. That will also clarify the condition of this block from `if parts[1] == ""` to `if keyspace == ""`.

---

*[go/vt/vtctld/api.go, line 182 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKyaxQR_I2qbLppY8Hx:-KKyaxQR_I2qbLppY8Hy:1815279437) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L182)):*
> ```Go
> 			keyspaceNames, err := ts.GetSrvKeyspaceNames(ctx, cell)
> 			if err != nil {
> 				return nil, fmt.Errorf("invalid cell: %q  expected usage: /srv_keyspace/<cell>", keyspacePath)
> ```

It's not necessarily the case that `GetSrvKeyspaceNames` failed because the cell is invalid. It could be a network timeout, for instance. So the error should not promise more than it can guarantee. It should also include the `err` it got back, for context.

```go
return nil, fmt.Errorf("can't get list of SrvKeyspaceNames for cell %q: %v", cell, err)
```

---

*[go/vt/vtctld/api.go, line 184 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKycMrh471JtWNotPsy:-KKycMrh471JtWNotPsz:1085873240) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L184)):*
> ```Go
> 				return nil, fmt.Errorf("invalid cell: %q  expected usage: /srv_keyspace/<cell>", keyspacePath)
> 			}
> 			numKeyspaces := len(keyspaceNames)
> ```

In general, you shouldn't need to put `len()` in a variable to optimize a loop. `len()` just reads a value that's already stored - it doesn't compute anything.

But here you can actually use an even more convenient loop form:

```go
for _, keyspaceName := range keyspaceNames {
  ...
}
```

---

*[go/vt/vtctld/api.go, line 191 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKycsCPEYbAU10VyOlm:-KKycsCPEYbAU10VyOln:612926682) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L191)):*
> ```Go
> 				}
> 			}
> 		} else {
> ```

The above block should go ahead and `return` its result. Then this `else` block should be de-indented.

---

*[go/vt/vtctld/api.go, line 195 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKyd3gNnCtuyEZB2rnW:-KKyd3gNnCtuyEZB2rnX:-46044984) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L195)):*
> ```Go
> 			cell := parts[0]
> 			keyspace := parts[1]
> 			err := addSrvkeyspace(ctx, ts, cell, keyspace, srvKeyspaces)
> ```

As mentioned above, for a single object request, just return the one SrvKeyspace.

---

*[go/vt/vtctld/api.go, line 200 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKyd9u_sFfaZTENGpNi:-KKyd9ua4OTWKL8KwsmQ:1438310100) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/go/vt/vtctld/api.go#L200)):*
> ```Go
> 			}
> 		}
> 		//map of srvkeyspace names to srvkeyspaces in wrapped in a Data field
> ```

Didn't we find that `toJSON()` would let us avoid having to do this?

---

*[web/vtctld/keyspaces.js, line 12 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKyegDS7aYHkjpde2eT:-KKyegDS7aYHkjpde2eU:1413618199) ([raw file](https://github.com/youtube/vitess/blob/28d84cba55e37cac687d88276fe55c43dbedd12b/web/vtctld/keyspaces.js#L12)):*
> ```JavaScript
>   $scope.servingShards = {};
> 
>   $scope.isServing = function(name, keyspaceName) {
> ```

`name` is too generic. Let's call it `shard`. Also we usually try to keep `keyspace, shard` parameters in that order by convention.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815)*

**Comment by enisoc** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 22 unresolved discussions.

---

*[web/vtctld/keyspaces.js, line 17 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzgetWN5BES8cCppt1:-KKzgetWN5BES8cCppt2:-629954727) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L17)):*
> ```JavaScript
> 
>   $scope.isServing = function(name, keyspaceName) {
>     return name in $scope.servingShards[keyspaceName];
> ```

First need to check if keyspace exists:

```js
return keyspaceName in $scope.servingShards && name in $scope.servingShards[keyspaceName];
```

---

*[web/vtctld/keyspaces.js, line 21 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzYA2QDViN2LEFKthP:-KKzYA2QDViN2LEFKthQ:215081741) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L21)):*
> ```JavaScript
> 
>   //cleaning the data recieved to ensure that it has only keyspace names
>   function stripResource(shardList) {
> ```

Doesn't `toJSON()` already do this for you?

---

*[web/vtctld/keyspaces.js, line 49 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzYk1Tw2jFXVS42pZo:-KKzYk1Tw2jFXVS42pZp:-1842372295) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L49)):*
> ```JavaScript
>   $scope.refreshData();
>   
>   function getKeyspaceShards(keyspace, keyspaceName) {
> ```

You can just refer to `keyspace.name` and drop the `keyspaceName` parameter.

---

*[web/vtctld/keyspaces.js, line 51 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzYv_ahxl7WBJ7PbZF:-KKzYv_ahxl7WBJ7PbZG:-519655895) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L51)):*
> ```JavaScript
>   function getKeyspaceShards(keyspace, keyspaceName) {
>     shards.query({keyspace: keyspaceName}, function(shardList){
>       $scope.srv_keyspace_query.$promise.then(function(resp) {
> ```

Add a comment here for why you're doing this as a promise callback:

```js
// Chain this callback onto the srv_keyspace_query, since we need the result from that as well.
```

Also chaining on `srv_keyspace_query.$promise` directly won't guarantee that `processSrvKeyspaces` has finished, since that is also chained on the same parent promise (they are siblings). Instead, you want to chain this one onto the promise returned from the `then()` callback in which you call `processSrvKeyspaces`.

---

*[web/vtctld/keyspaces.js, line 54 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzZN6VBMnChv2_CRFh:-KKzZN6VBMnChv2_CRFi:-599976891) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L54)):*
> ```JavaScript
>         shardList = stripResource(shardList);
>         var num_shards = shardList.length;
>         for (var i = 0; i < num_shards; i++) {
> ```

You can just use `i < shardList.length` and remove `num_shards`.

---

*[web/vtctld/keyspaces.js, line 81 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzdSeDCj_CvBR6aRzN:-KKzdSeDCj_CvBR6aRzO:-2004243582) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L81)):*
> ```JavaScript
>     var num_srvKeyspaces = keyspaceNames.length;
>     $scope.servingShards = {}; 
>     for (var k = 0; k < num_srvKeyspaces; k++) {
> ```

Rather than extracting `Object.keys()` and looping over that, you can just do:

```js
for (var keyspace in srvKeyspaceMap) {
  ...
}
```

Then this function only needs to be given `srvKeyspaceMap`.

---

*[web/vtctld/keyspaces.js, line 89 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKze86j9ABytCIbVhWh:-KKze86j9ABytCIbVhWi:1912835540) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L89)):*
> ```JavaScript
> 
>   function addServingShards(partitions, keyspaceName){
>     var num_partitions = partitions.length;
> ```

Don't need to store `.length` in a variable.

You should also make sure `partitions` is actually defined before querying its length. It could be undefined if a SrvKeyspace has no partitions at all.

---

*[web/vtctld/keyspaces.js, line 93 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzeTzjOViKnkpsyYYz:-KKzeTzklO1nEK8mpaq4:-256135610) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L93)):*
> ```JavaScript
>     for (var p = 0; p < num_partitions; p++) {
>       var partition = partitions[p];
>       if (partition.served_type == 1) { //MASTER = 1
> ```

Use `if (vtTabletTypes[partition.served_type] == 'master')`. That way, the mapping is stored in only one place throughout the app (`in vtTabletTypes, defined in `app.js`). Then you don't need the comment as it's self-evident.

---

*[web/vtctld/keyspaces.js, line 102 \[r5\]](https://reviewable.io:443/reviews/youtube/vitess/1815#-KKzfSXPt-JrdxB3s-ox:-KKzfSXPt-JrdxB3s-oy:-2093335664) ([raw file](https://github.com/youtube/vitess/blob/83a12ac842b4c589f05335cca3a3837a3995e636/web/vtctld/keyspaces.js#L102)):*
> ```JavaScript
>   function handleMasterPartion(partition, keyspaceName){
>     var shard_references = partition.shard_references;
>     var num_shards = shard_references.length;
> ```

Don't need a variable for `.length`. Again, check that `shard_references` is defined before accessing members.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815#-:-KL3cZZpCCCsa3n0iDVo:1417088721)*

**Comment by enisoc** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1815)*

**Pull request merged**
