### PR TITLE
Composer files moved to project root folder #1438

### PR DESCRIPTION
**Pull request by Rastusik**

### CODE REVIEW

**Comment by Rastusik** [comment]
not finished yet, sorry

**Comment by enisoc** [comment]
I found one place that's referring to php/composer.json:

https://github.com/youtube/vitess/blob/master/docker/bootstrap/Dockerfile.common#L75

Will this cause the php/vendor dir to be generated in the repo root instead? Or is that configurable to keep it in php/vendor? If we can't avoid moving it, we'll need to update some places like:

```
.gitignore:47
.dockerignore:6
travis/php_grpc.sh:33
docker/test/run.sh:49
```

**Comment by Rastusik** [comment]
it is possible, I'll try to make it run, even with unit tests (but I'm not able to run docker)

**Comment by Rastusik** [comment]
One question - when I try to run make php_test (on OSX), I'm getting this error:

E0113 22:40:01.330574   39878 proc.go:73] unexpected error on port 0: Get http://localhost:0/debug/pid: dial tcp [::1]:0: connect: can't assign requested address, trying to start anyway

why is the port 0? could you show me where I could fix this?

**Comment by enisoc** [comment]
That's coming from here:

https://github.com/youtube/vitess/blob/master/go/proc/proc.go#L73

It's logged as an error, but it only affects the "kill predecessor" feature, which is optional. It shouldn't prevent the test from succeeding.

I think you could fix this by providing a non-zero, unused `-port` value to `vtgateclienttest` here:

https://github.com/youtube/vitess/blob/master/php/tests/VTGateConnTest.php#L57

We don't bother to provide `-port` in the test because we only rely on `-grpc_port` for this particular test.

**Comment by Rastusik** [comment]
Is this sufficient?

**Comment by enisoc** [comment]
Looks good! Thanks for making sure it passes in Travis!

**Pull request merged**
