### PR TITLE
First version of vtctld webdriver test.

### PR DESCRIPTION
**Pull request by thompsonja**
@enisoc 
There are definitely still more test cases that could be added, but this should work as a baseline.  The test right now does the following:
1. Set up two keyspaces with different sharding and tablet counts.
2. Fetches the main vtctld page.
3. Ensures the main page displays all the keyspaces.
4. Ensures the main page displays a link to each shard for each keyspace.
5. Clicks each shard link, checks the tablet types.
6. Compares the master tablet to the master listed in the shard record.

We can add more test cases, like:
1. Check that tablet/shard/keyspace actions work.
2. Multi-cell test cases.

I updated some of the html templates to add some ids to make it easier for selenium to fetch.  You will need to do a 'sudo pip install selenium' as well but I'm not sure where to add this in documentation.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1808)

### CODE REVIEW

**Comment by enisoc** [comment]
:lgtm: once tests pass. Thanks for taking this on!

---

Reviewed 4 of 6 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[bootstrap.sh, line 225 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KKuT62lghgauoFGn-H9:-KKuT62lghgauoFGn-HA:415095074) ([raw file](https://github.com/youtube/vitess/blob/d667bdba69d18c7252d60b40239d5862db92a878/bootstrap.sh#L225)):*
> ```Shell
> $selenium_dist/bin/pip install selenium
> mkdir -p $VTROOT/dist/chromedriver
> wget -N -q http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
> ```

Can you use `curl` instead of `wget`? We already install `curl` in Docker images and guides. No need to add wget as a dependency too.

---

*[test/vtctld_web_test.py, line 89 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KKuQS0uHb4vCnblhuDm:-KKuQS0vN53NqQwo6CCf:1423240303) ([raw file](https://github.com/youtube/vitess/blob/d667bdba69d18c7252d60b40239d5862db92a878/test/vtctld_web_test.py#L89)):*
> ```Python
>       t.start_vttablet(wait_for_state=None,
>                        extra_args=utils.vtctld.process_args())
>     shard_0_replica.create_db('vt_test_keyspace')
> ```

Couldn't `shard_0_replica` be merged into the loop above?

---

*[test/vtctld_web_test.py, line 93 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KKuQm3IMGkP0puMqm_i:-KKuQm3IMGkP0puMqm_j:-252212628) ([raw file](https://github.com/youtube/vitess/blob/d667bdba69d18c7252d60b40239d5862db92a878/test/vtctld_web_test.py#L93)):*
> ```Python
>                                    wait_for_state=None)
> 
>     shard_0_master_ks2.create_db('vt_test_keyspace2')
> ```

Looks like this is the same as the loop below?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1808#-:-KKuUNGInxFFUQ-_QmIC:1298018112)*

**Comment by thompsonja** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[bootstrap.sh, line 225 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KKuT62lghgauoFGn-H9:-KKy-VVx800X8Zp7LDkn:-499146009) ([raw file](https://github.com/youtube/vitess/blob/d667bdba69d18c7252d60b40239d5862db92a878/bootstrap.sh#L225)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Can you use `curl` instead of `wget`? We already install `curl` in Docker images and guides. No need to add wget as a dependency too.
</details>
Done.

---

*[test/vtctld_web_test.py, line 89 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KKuQS0uHb4vCnblhuDm:-KL2a5LasK6NVgnZhAVu:1971578791) ([raw file](https://github.com/youtube/vitess/blob/d667bdba69d18c7252d60b40239d5862db92a878/test/vtctld_web_test.py#L89)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Couldn't `shard_0_replica` be merged into the loop above?
</details>
Done.  In general this was a shameless copy/paste job, looking at the code I think a lot of tablet initialization code across our tests can be simplified, I may look into this next quarter.

---

*[test/vtctld_web_test.py, line 93 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KKuQm3IMGkP0puMqm_i:-KL2aGgWdCkVGlKKDh3v:-499146009) ([raw file](https://github.com/youtube/vitess/blob/d667bdba69d18c7252d60b40239d5862db92a878/test/vtctld_web_test.py#L93)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Looks like this is the same as the loop below?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1808)*

**Comment by enisoc** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bootstrap.sh, line 225 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KL2kloQNis7brmsk8yp:-KL2kloRNj8b9Aok3D4j:1095361262) ([raw file](https://github.com/youtube/vitess/blob/3eff022e2014478f9fc45dc36ed574fa4ae43b79/bootstrap.sh#L225)):*
> ```Shell
> $selenium_dist/bin/pip install selenium
> mkdir -p $VTROOT/dist/chromedriver
> curl http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip > chromedriver_linux64.zip -s
> ```

Recommend `curl -sL` to follow redirects as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1808)*

**Comment by thompsonja** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[bootstrap.sh, line 225 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1808#-KL2kloQNis7brmsk8yp:-KL30u1-mR6F9H1Kqh_s:-499146009) ([raw file](https://github.com/youtube/vitess/blob/3eff022e2014478f9fc45dc36ed574fa4ae43b79/bootstrap.sh#L225)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Recommend `curl -sL` to follow redirects as well.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1808)*

**Comment by enisoc** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1808)*

**Pull request merged**
