### PR TITLE
bucket name based on keyspace and shard, removing bucket info from static config file

### PR DESCRIPTION
**Pull request by raunak-agarwal-flipkart**
Sample script for vtctld and vttablets using ceph enabled backup.
Changed ceph_backup_config.json file to remove bucket information
Create a bucket during backup start process if the bucket doesn't exist

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1831)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 123 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KLRAh0eAQct2mP8YDNI:-KLRAh0eAQct2mP8YDNJ:1147730820) ([raw file](https://github.com/youtube/vitess/blob/a36c57d1387528a81e6a736a4439b6c0c0f18667/go/vt/mysqlctl/cephbackupstorage/ceph.go#L123)):*
> ```Go
> 		return nil, err
> 	}
> 	//	keeping in view the bucket naming conventions for buckets
> ```

move this to a function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831)*

**Comment by harshit-gangal** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831)*

**Comment by harshit-gangal** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831#-:-KLVr7bC8Lnl3rNklWAy:1417088721)*

**Comment by enisoc** [comment]
In S3 and GCS, you are strongly discouraged from creating many buckets. You are supposed to organize objects within a bucket, which is what we do by prefixing the `dir` on the object name. If Ceph works in a similar way, I think all keyspaces and shards should go in a single bucket, for a given Vitess cluster. Can you explain why you think a bucket per shard is necessary?

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 264 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KLXceLpVZcoKZPnaJdO:-KLXceLpVZcoKZPnaJdP:2124106625) ([raw file](https://github.com/youtube/vitess/blob/ab2dd0a8281f14d173da5a36cad9784aee233874/go/vt/mysqlctl/cephbackupstorage/ceph.go#L264)):*
> ```Go
> 
> //	keeping in view the bucket naming conventions
> func alterBucketName(dir string) {
> ```

Since the bucket name now depends on the `dir`, you should get rid of the package-level `bucket` variable altogether. Then this function should just return the bucket name it computes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831#-:-KLXc0bR0lgC9-wfnLUp:857392607)*

**Comment by enisoc** [comment]
@raunak-agarwal-flipkart and I discussed a compromise over chat: Use a separate bucket for each keyspace, but keep the shards of a keyspace in the same bucket. This makes more sense to me; one use case is where the DB team runs one Vitess cluster, but each keyspace may belong to a different dev team who provision their own ceph bucket.

Given this use case, he explained that it's not possible to keep the bucket name as a a flag, nor as a config file. This is because vtctld needs to know how to find the bucket for any given keyspace. Therefore, the plugin itself must know how to generate a bucket name for a given keyspace, which is the purpose of this pull request.

@raunak-agarwal-flipkart If you agree with the compromise, can you modify the pull request to use one bucket per keyspace and address the comment about the package-level `bucket` variable? Thanks!

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831#-:-KN3ss5KkLRcRxv__8Sh:-814138838)*

**Comment by enisoc** [comment]
Reviewed 1 of 5 files at r1, 1 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[doc/BackupAndRestore.md, line 53 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KNcgFEh1AmOgBlepxWL:-KN6IFcyk1Bl96Geq_iM:605536067) ([raw file](https://github.com/youtube/vitess/blob/dfab17245d1229ffdb7d15b18035961a556132ee/doc/BackupAndRestore.md#L53)):*
> ```Markdown
>     <tr>
>       <td><nobr><code>-ceph_backup_storage_config</code></nobr></td>
>       <td>For the <code>ceph</code> plugin, this identifies the path to a text file with a JSON object as configuration. The JSON object requires the following keys: <code>accessKey</code>, <code>secretKey</code> and  <code>endPoint</code>. Bucket name is computed from keyspace and shard name combined.</td>
> ```

This should say just keyspace name now.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 25 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KNctxptOJWDMZp0eK_R:-KNctxptOJWDMZp0eK_S:668997816) ([raw file](https://github.com/youtube/vitess/blob/dfab17245d1229ffdb7d15b18035961a556132ee/go/vt/mysqlctl/cephbackupstorage/ceph.go#L25)):*
> ```Go
> var (
> 	// bucket is where the backups will go.
> 	bucket string
> ```

This package-level variable should be removed, now that the bucket name is no longer constant. See the other comment below on `alterBucketName()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831)*

**Comment by enisoc** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 273 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KNhjxJ75YTV9bnErFrP:-KNhjxJ8QSAk594y-Dww:-1564640724) ([raw file](https://github.com/youtube/vitess/blob/d8e6fe67981479996efe11cb96e43ace5c2d235a/go/vt/mysqlctl/cephbackupstorage/ceph.go#L273)):*
> ```Go
> // only keyspace informations is extracted and used for bucket name
> func alterBucketName(dir string) (string){
> 	bucket = strings.ToLower(dir)
> ```

This is a local variable now, so you need to declare it by using `:=`. Currently the build is failing due to this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831)*

**Comment by harshit-gangal** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[doc/BackupAndRestore.md, line 53 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KNcgFEh1AmOgBlepxWL:-KNk2l4zLLA-amUFVmxA:-499146009) ([raw file](https://github.com/youtube/vitess/blob/dfab17245d1229ffdb7d15b18035961a556132ee/doc/BackupAndRestore.md#L53)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This should say just keyspace name now.
</details>
Done.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 264 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KLXceLpVZcoKZPnaJdO:-KNk2iMbn21xLpXpegUd:-499146009) ([raw file](https://github.com/youtube/vitess/blob/ab2dd0a8281f14d173da5a36cad9784aee233874/go/vt/mysqlctl/cephbackupstorage/ceph.go#L264)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Since the bucket name now depends on the `dir`, you should get rid of the package-level `bucket` variable altogether. Then this function should just return the bucket name it computes.
</details>
Done.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 25 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KNctxptOJWDMZp0eK_R:-KNk2a3_y_yMl1EGC5Vc:-499146009) ([raw file](https://github.com/youtube/vitess/blob/dfab17245d1229ffdb7d15b18035961a556132ee/go/vt/mysqlctl/cephbackupstorage/ceph.go#L25)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This package-level variable should be removed, now that the bucket name is no longer constant. See the other comment below on `alterBucketName()`.
</details>
Done.

---

*[go/vt/mysqlctl/cephbackupstorage/ceph.go, line 273 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1831#-KNhjxJ75YTV9bnErFrP:-KNk2jzN3zUCE0dkI6j4:-499146009) ([raw file](https://github.com/youtube/vitess/blob/d8e6fe67981479996efe11cb96e43ace5c2d235a/go/vt/mysqlctl/cephbackupstorage/ceph.go#L273)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> This is a local variable now, so you need to declare it by using `:=`. Currently the build is failing due to this.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1831#-:-KNoL8JlC7M69CMZwFK6:1417088721)*

**Pull request merged**
