### PR TITLE
v3: how to draw an owl

### PR DESCRIPTION
**Pull request by sougou**
@erzel 
Ref: http://lmgtfy.com/?q=how+to+draw+an+owl
Well, it's not quite the entire owl, but it's close. As parts get ready, I'll point you to them to perform the review.
In this installment, you may start with doc.go. It's just a description of the high level approaches and issues. There should be no surprises there. You can glance at the rest of the stuff for reference, but comments may be outdated or missing.
I'll probably work on polishing symtab next.

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1492)

### CODE REVIEW

**Comment by erzel** [comment]
Thanks Sugu. I'll start looking at this tomorrow.

**Comment by erzel** [comment]
Sugu. I've read doc.go and put some comments.  Thanks for writing it -- it's a good general overview of your approach. I'd like to understand what your doing in more detail, though. Where would you suggest I start? 

---

Review status: 0 of 53 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[go/vt/vtgate/planbuilder/doc.go, line 1 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD0PVPZst68-OcF_ej:-KAD0PVPZst68-OcF_ek:-1777070250) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L1)):*
This  document is very helpful! Thanks for writing it.

---

*[go/vt/vtgate/planbuilder/doc.go, line 14 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACjkIZB6kwcw4ND5wd:-KACjkI_E3n-61lkt2Dv:-1817798094) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L14)):*
Typo in conevenience.

---

*[go/vt/vtgate/planbuilder/doc.go, line 35 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD0Yr-xdCBeytfaSdg:-KAD0Yr0O230A0NHBhOr:793444058) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L35)):*
This description of how you're going to perform a join with a condition without having a Filter primitive in VTGate is too vague to me.
(I don't think I would have understood it just by reading your comment here). I think an example would be helpful. It will
also illustrate what you mean in the last sentence of this paragraph.

---

*[go/vt/vtgate/planbuilder/doc.go, line 48 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD2M6YTXMKZQQ-BKss:-KAD2M6YTXMKZQQ-BKst:480628068) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L48)):*
The reader doesn't know what "tableAliase" and "colysym elements" are here. Can you add a short description of them here before
you're using them later?

---

*[go/vt/vtgate/planbuilder/doc.go, line 79 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACyFvJwnu-v0bIyZQv:-KACyFvJwnu-v0bIyZQw:-2024185753) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L79)):*
I don't know what a "vertical break" mean.  Perhaps this is better explained with an example?

---

*[go/vt/vtgate/planbuilder/doc.go, line 82 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACmdrHKoag-bK4YGit:-KACmdrIi0Ox8oWk7JM0:1090272254) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L82)):*
Typo in partioned.

---

*[go/vt/vtgate/planbuilder/doc.go, line 91 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD3ed3S-zq-nEih6Bv:-KAD3ed3S-zq-nEih6Bw:-1146222433) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L91)):*
You haven't defined wire-up phase here.  Can you somehow define it inline here?

---

*[go/vt/vtgate/planbuilder/doc.go, line 125 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD5t-jtlBewSGtqmCa:-KAD5t-jtlBewSGtqmCb:-462692924) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L125)):*
"to be" -> "is" 

---

*[go/vt/vtgate/planbuilder/doc.go, line 128 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACoelSg9CBFo2OR6gN:-KACoelSg9CBFo2OR6gO:-1431136102) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L128)):*
Insert "is" before "the"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1492#-:-KAD6DnNdodUa5a__1x1:471758084)*

**Comment by sougou** [comment]
Review status: 0 of 57 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[go/vt/vtgate/planbuilder/doc.go, line 1 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD0PVPZst68-OcF_ej:-KAhqibxjxsU8mxvWVk7:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L1)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 14 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACjkIZB6kwcw4ND5wd:-KAhqhaXQLP_lEhInHCV:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L14)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 35 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD0Yr-xdCBeytfaSdg:-KAhqm5bsyI543qzgJk6:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L35)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 48 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD2M6YTXMKZQQ-BKss:-KAhqwkJP_ItJvnZPF0g:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L48)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 79 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACyFvJwnu-v0bIyZQv:-KAhrSLYRmTl1ZB8cj3j:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L79)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 82 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACmdrHKoag-bK4YGit:-KAhrX9TfQl05Wpf7hpb:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L82)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 91 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD3ed3S-zq-nEih6Bv:-KAhrY7ddjMzlwfRDDTS:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L91)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 125 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAD5t-jtlBewSGtqmCa:-KAhrYzwCr77NRPB-kO3:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L125)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 128 \[r2\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KACoelSg9CBFo2OR6gN:-KAhrZuwXRIRrMlWq-sn:-499146009) ([raw file](https://github.com/youtube/vitess/blob/b472691639ddcbc531ab13819442f9c659b1a90c/go/vt/vtgate/planbuilder/doc.go#L128)):*
Done.

---

*[go/vt/vtgate/planbuilder/doc.go, line 102 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KAhqzsAOherroZebddc:-KAhqzsAOherroZebddd:100905882) ([raw file](https://github.com/youtube/vitess/blob/0be2d9e57580a296c7a5045dceac3b1f16fcac8a/go/vt/vtgate/planbuilder/doc.go#L102)):*
I've added this paragraph that explains how things point at each other.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1492)*

**Comment by sougou** [comment]
@erzel 
plan.go, symtab.go, route.go and join.go are ready for review. This covers all the data structures. So, there should hopefully be fewer ambiguities than before.

**Comment by erzel** [comment]
Reviewed 2 of 47 files at r1, 1 of 37 files at r3.
Review status: 3 of 60 files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[go/vt/vtgate/planbuilder/doc.go, line 70 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBAerHG1saAoQu4Y76F:-KBAerHG1saAoQu4Y76G:1098444644) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/doc.go#L70)):*
Double "can".

---

*[go/vt/vtgate/planbuilder/plan.go, line 30 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBFy26zp3fQYFiLYAYD:-KBFy27-2TYv9V4qLxnI:-1056372613) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L30)):*
I don't understand this comment.

---

*[go/vt/vtgate/planbuilder/plan.go, line 37 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBAWEC5HBFB9kDYfkKb:-KBAWEC5HBFB9kDYfkKc:1040325135) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L37)):*
Looks like PlanID refers to a Route and not a "plan", right? Also calling it an "id" makes me think of a unique identifier (like user_id)
Can we find a better name?

---

*[go/vt/vtgate/planbuilder/plan.go, line 54 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBG-CV1z9lQFC2gOP6S:-KBG-CV1z9lQFC2gOP6T:653301131) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L54)):*
Can you move the definition of the Route type to before this 'const'?  So it's easy to look-up the fields when reading these comments?

---

*[go/vt/vtgate/planbuilder/plan.go, line 71 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBFyp3hU34tP_O0eqii:-KBFyp3hU34tP_O0eqij:-1828458379) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L71)):*
s/running/routing

---

*[go/vt/vtgate/planbuilder/plan.go, line 144 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBAX_owJCjuc-Y6ysaB:-KBAX_owJCjuc-Y6ysaC:1955358455) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L144)):*
looks like it's serializing a Route not a Plan. Same comment for the variable name marshalPlan below.

---

*[go/vt/vtgate/planbuilder/plan.go, line 201 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBG0-aHhwaT4DLBhYoC:-KBG0-aHhwaT4DLBhYoD:-1097147115) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L201)):*
Can we have an interface that both Join and Route (and later all other primitives) implement?  This will give us compile-time prevention of other objects getting assigned here.

---

*[go/vt/vtgate/planbuilder/select.go, line 13 \[r8\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBFfKJ5hux8XVuwsNpO:-KBFfKJ5hux8XVuwsNpP:-808327940) ([raw file](https://github.com/youtube/vitess/blob/17906c0a4da442e5f77354643a512c2bcfa00158/go/vt/vtgate/planbuilder/select.go#L13)):*
It's not called buildSelectPlan2 anymore.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1492)*

**Comment by erzel** [comment]
Review status: 3 of 60 files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBG3Ze5xOduRm5IcSJq:-KBG3Ze5xOduRm5IcSJr:1078549376) (no related file):*
I've started reviewing your code. Thanks for the comments. They really help. So far I've only looked at plan.go and published some of my comments.  

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1492)*

**Comment by sougou** [comment]
Review status: 3 of 61 files reviewed at latest revision, 18 unresolved discussions.

---

*[go/vt/vtgate/planbuilder/doc.go, line 70 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBAerHG1saAoQu4Y76F:-KBKvBgu_eYlk99jJO52:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/doc.go#L70)):*
Done.

---

*[go/vt/vtgate/planbuilder/plan.go, line 30 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBFy26zp3fQYFiLYAYD:-KBKvG08jMVdFmyDWhdm:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L30)):*
Done.

---

*[go/vt/vtgate/planbuilder/plan.go, line 37 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBAWEC5HBFB9kDYfkKb:-KBKvHHjcBrxhpJ2zDHk:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L37)):*
Done.

---

*[go/vt/vtgate/planbuilder/plan.go, line 54 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBG-CV1z9lQFC2gOP6S:-KBKvILqnZu_i_6DhCuA:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L54)):*
Done.

---

*[go/vt/vtgate/planbuilder/plan.go, line 71 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBFyp3hU34tP_O0eqii:-KBKvJ-bzk4G-WYUEF8n:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L71)):*
Done.

---

*[go/vt/vtgate/planbuilder/plan.go, line 144 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBAX_owJCjuc-Y6ysaB:-KBKvKBgrXCNo1wc-BlW:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L144)):*
Done.

---

*[go/vt/vtgate/planbuilder/plan.go, line 201 \[r7\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBG0-aHhwaT4DLBhYoC:-KBKvLUL3Ad_Cs6yZHvf:-499146009) ([raw file](https://github.com/youtube/vitess/blob/436700bdb8b7a3bf2f6d3a454c6e1f81a7c45a1c/go/vt/vtgate/planbuilder/plan.go#L201)):*
Done.

---

*[go/vt/vtgate/planbuilder/select.go, line 13 \[r8\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KBFfKJ5hux8XVuwsNpO:-KBKvMchkY__u0qZjSwr:-499146009) ([raw file](https://github.com/youtube/vitess/blob/17906c0a4da442e5f77354643a512c2bcfa00158/go/vt/vtgate/planbuilder/select.go#L13)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1492)*

**Comment by aaijazi** [comment]
Reviewed 1 of 47 files at r1, 4 of 30 files at r2, 1 of 37 files at r3, 2 of 18 files at r9, 1 of 11 files at r10.
Review status: 12 of 61 files reviewed at latest revision, 21 unresolved discussions.

---

*[go/vt/vtgate/planbuilder/doc.go, line 45 \[r13\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KC8p7OSSBSmGNRhiOXa:-KC8p7OSSBSmGNRhiOXb:-2093651170) ([raw file](https://github.com/youtube/vitess/blob/1282cca03b12bd3e10bc73c6026e456f84d51cb3/go/vt/vtgate/planbuilder/doc.go#L45)):*
Should specify which query is LHS and which is RHS here, and the order that queries are run in (always LHS first, then RHS).

---

*[test/vtgatev3_test.py, line 286 \[r13\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KC8s4zn-FnCxS4f_pyy:-KC8s4zn-FnCxS4f_pyz:-1969380589) ([raw file](https://github.com/youtube/vitess/blob/1282cca03b12bd3e10bc73c6026e456f84d51cb3/test/vtgatev3_test.py#L286)):*
Is there any significance to doing `select id, name` instead of `select *`? If so, it would be good to call that out.

---

*[test/vtgatev3_test.py, line 753 \[r13\]](https://reviewable.io:443/reviews/youtube/vitess/1492#-KC8sije6MrC7OTSR49y:-KC8sije6MrC7OTSR49z:619323671) ([raw file](https://github.com/youtube/vitess/blob/1282cca03b12bd3e10bc73c6026e456f84d51cb3/test/vtgatev3_test.py#L753)):*
I feel like TestJoins would be better as its own class, and the insert queries would be part of a setup method. That way, it's more clear what 's actually under test, and you can extend it out to multiple join cases.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1492)*

**Pull request merged**
