### PR TITLE
fix stats.Counters.String method to generate valid JSON for map keys

### PR DESCRIPTION
**Pull request by nerdatmath**

### CODE REVIEW

**Comment by sougou** [comment]
@bbeaudreault can you verify this will work for you?

**Comment by bbeaudreault** [comment]
Cool, I did not know about `%q`.  I'll roll this out internally to verify, but a quick go playground example looked good.

**Comment by bbeaudreault** [comment]
Tested internally and LGTM

**Comment by sougou** [comment]
LGTM

**Pull request merged**
