### PR TITLE
Removing unused variable.

### PR DESCRIPTION
**Pull request by alainjobart**
That happens to fix the last 'go test -race' issue in
vt/wrangler/testlib which is how I found this.

@michael-berlin @guoliang100

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1740)

### CODE REVIEW

**Comment by guoliang100** [comment]
LGTM. I think we do not need it for now and could add it back if required.

**Comment by alainjobart** [comment]
Oh I thought the variable was unused, but it's not, the callback is the last argument that makes it used.

Never mind this fix then, I need something different.

**Comment by alainjobart** [comment]
@guoliang100 PTAL at the new fix. We need the variable, it just needs to be registered only for vtgate when it's a global, not for all other temporary use cases.

@michael-berlin that should help 'go test -race'.

**Comment by guoliang100** [comment]
LGTM

**Comment by alainjobart** [comment]
@michael-berlin was there any other race we needed to address? ;)

**Comment by michael-berlin** [comment]
Thanks for fixing these :)

I need to fix the race detection in Travis to prevent these from happening in the future.

> @michael-berlin was there any other race we needed to address? ;)

There are actually more races :) For example:
$ cd go/vt/wrangler/testlib
$ go test -race
...
```
==================
WARNING: DATA RACE
Write by goroutine 105:
  github.com/youtube/vitess/go/vt/wrangler/testlib.TestPlannedReparentShard()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/wrangler/testlib/planned_reparent_shard_test.go:73 +0xf6a
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Previous read by goroutine 22:
  github.com/youtube/vitess/go/vt/tabletserver/tabletservermock.(*Controller).BroadcastHealth()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/tabletserver/tabletservermock/controller.go:179 +0x134

Goroutine 105 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  main.main()
      github.com/youtube/vitess/go/vt/wrangler/testlib/_test/_testmain.go:106 +0x20f

Goroutine 22 (finished) created at:
  github.com/youtube/vitess/go/vt/tabletmanager.(*ActionAgent).broadcastHealth()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/tabletmanager/state_change.go:111 +0x4dc
  github.com/youtube/vitess/go/vt/tabletmanager.(*ActionAgent).changeCallback()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/tabletmanager/state_change.go:303 +0xa76
  github.com/youtube/vitess/go/vt/tabletmanager.(*ActionAgent).updateState()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/tabletmanager/state_change.go:152 +0x1a4
  github.com/youtube/vitess/go/vt/tabletmanager.(*ActionAgent).Start()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/tabletmanager/action_agent.go:594 +0x1391
  github.com/youtube/vitess/go/vt/tabletmanager.NewTestActionAgent()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/tabletmanager/action_agent.go:284 +0x6ac
  github.com/youtube/vitess/go/vt/wrangler/testlib.(*FakeTablet).StartActionLoop()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/wrangler/testlib/fake_tablet.go:177 +0xb65
  github.com/youtube/vitess/go/vt/wrangler/testlib.TestPlannedReparentShard()
      /usr/local/google/home/mberlin/workspace/vitess/src/github.com/youtube/vitess/go/vt/wrangler/testlib/planned_reparent_shard_test.go:71 +0xeb2
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc
==================

```

I'll file an internal bug for the races which are left.

**Pull request merged**
