### PR TITLE
Some cleanup on the Node-related Go<->javascript API.

### PR DESCRIPTION
**Pull request by pivanof**
- Make the first value of enums (the one that is equal to 0) to be the unknown
  one, so that it was considered a programming error.
- Remove "omitempty" tag from fields where change from some value to empty value
  must be passed in an update to the web UI.
- Add "omitempty" to Children because that's an important special use case.
- Modify javascript to assume that name, state, style and message of an action
  is always there.
- Modify javascript to work when 'children' value was not received.

### CODE REVIEW

**Comment by michael-berlin** [comment]
LGTM

Note that the unit test is currently failing. You probably have to adjust some testdata?

**Comment by pivanof** [comment]
I've fixed the test in the same way as in https://github.com/youtube/vitess/pull/2219.

**Comment by michael-berlin** [comment]
Was the problem that `lastChanged` cannot be reliably faked?

Test fix is LGTM

**Comment by pivanof** [comment]
lastChanged cannot be reliably faked -- that's the problem of #2219. Here the problem was that with all those "omitempty" removed now the result contains much more fields than test expects. And I've decided that having to modify the test every time we do a change in the list of fields (like adding some new one) is not very good, so it's better to just check whatever we know for sure is there.

**Comment by alainjobart** [comment]
LGTM thanks for the fixes.

**Pull request merged**
