### PR TITLE
gRPC and proto3 beta!

### PR DESCRIPTION
**Pull request by alainjobart**

### CODE REVIEW

**Comment by michael-berlin** [comment]
Alain, does it pass locally?

I aggressively cache the outout of the python build process. Cached directories are currently:

  - $HOME/gopath/dist/grpc/.build_finished
  - $HOME/gopath/dist/grpc/grpc/python2.7_virtual_environment
  - $HOME/gopath/dist/grpc/lib/python2.7/site-packages

We probably have to adjust these paths in .travis.yml?

In any case, we need to delete the cache for the "master" branch and this pull request to make the test pass: https://travis-ci.org/youtube/vitess/caches
Otherwise, Travis will just always skip the build of gRPC and protobuf.

**Comment by alainjobart** [comment]
@michael-berlin : Only the grpc python versions should be affected, and we don't test these in travis yet, so I think with the fixed typos, it will just work. gRPC / python is much better now, I think it's close to production quality already.

**Comment by aaijazi** [comment]
Nice! I left a few small comments, LGTM after those are fixed (and Travis passes)

**Comment by michael-berlin** [comment]
@alainjobart grpc python is used by the Travis tests as well. Tests are currently failing due to a Python import.

I've deleted all caches and restarted the failing test shards. For now, Travis should pass without the cache.

To make it pass with the cache, we need to update the cached Python output directories.

**Comment by alainjobart** [comment]
@michael-berlin the python import was my bad, leftover from a debug session. It will work without it, no grpc python involved in travis tests for now.

The caches, once rebuilt, will work. We're getting closer to adding grpc python tests into travis I think.

**Comment by alainjobart** [comment]
(and thanks for the review guys, was waiting for travis to pass to ask for it explicitly :) )

**Pull request merged**
