### PR TITLE
Add pylint pre-commit hook.

### PR DESCRIPTION
**Pull request by dumbunny**
This uses /usr/bin/gpylint; systems without gpylint will
skip this check.

@mberlin

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM thanks for doing this Dean, will be very useful.

**Comment by enisoc** [comment]
I think you meant to tag @michael-berlin :)

**Comment by dumbunny** [comment]
Oops. Sorry, mberlin.

**Comment by michael-berlin** [comment]
LGTM after comments are addressed

Thanks a lot for tackling this :)

**Pull request merged**
