### PR TITLE
Update helm install for Kubernetes and add new k8s Docker image

### PR DESCRIPTION
**Pull request by derekperkins**
The base image in this repo is 3.1 GB, while this is just 140 MB. I'm working on building a helm chart that will allow users to use any base mysql image, which will use this to copy over only the relevant assets. I'd like to set this image to be an automated build, triggered whenever the base image is rebuilt.

### CODE REVIEW

**Comment by derekperkins** [comment]
@enisoc I'm trying to copy the files to the proper destination, as compared to what you are doing in https://github.com/youtube/vitess/pull/3311/files#diff-17c3a71d3c4514bfd55ea66afbcc3e8dR46. I'm hoping to make the InitContainer as simple as possible.

**Comment by derekperkins** [comment]
This would be handy if it ever gets implemented - https://github.com/kubernetes/kubernetes/issues/831

**Comment by derekperkins** [comment]
@jvaidya My original thought here was to provide only the bare minimum to run Vitess in production, and to be honest, I'm not familiar with the things that you mentioned. That being said, I only intend on copying those binaries out, so if there was another specific use case where it would be useful to have these other artifacts, and it didn't bloat the container size much, I wouldn't necessarily be opposed.

**Comment by derekperkins** [comment]
Here is how I anticipate using this image

```
FROM vitess/assets as assets

FROM percona:5.7.20

# Copy binaries
COPY --from=assets $GOBIN $GOBIN/

# copy web admin files
COPY --from=assets $VTROOT/web $VTROOT/web

# copy vitess config
COPY --from=assets /mnt/config /mnt/config

# Create vitess user
RUN groupadd -r vitess && useradd -r -g vitess vitess && \
   mkdir -p /vt/vtdataroot && chown -R vitess:vitess /vt

# Create mount point for actual data (e.g. MySQL data dir)
VOLUME /vt/vtdataroot
```

**Comment by derekperkins** [comment]
Some action items from my conversation today with @enisoc and @sougou
 
- [ ] require that the etcd operator be installed, but the chart will spin up etcd clusters using it
- [ ] stop logging to container files and only ship to stdout/stderr 
- [ ] figure out how to make the mysql image agree on a uid with vttablet (@enisoc)

More work on integrating with Orchestrator will happen in a later PR.

**Comment by derekperkins** [comment]
Here's a discussion related to chowning and root privileges https://github.com/kubernetes/kubernetes/issues/2630#issuecomment-321009380

**Comment by derekperkins** [comment]
@enisoc This should be ready for final review

**Comment by enisoc** [comment]
I've switched this to merge into a new branch, so we can collaborate on the final form without breaking master in the meantime.

LGTM

**Pull request merged**
