### PR TITLE
Updating PIP before installing grpcio.

### PR DESCRIPTION
**Pull request by alainjobart**
Seems to fix travis build.

### CODE REVIEW

**Comment by alainjobart** [comment]
Should fix https://github.com/youtube/vitess/issues/2508

**Comment by bbeaudreault** [comment]
LGTM, also fixed the issue in our build system

**Comment by sougou** [comment]
LGTM

**Comment by michael-berlin** [comment]
Please add a comment why we're doing this. Otherwise, we'll have forgotten this the next time we have to debug this :)

**Pull request merged**
