### PR TITLE
Remove WHERE filters from the full-scan queries.

### PR DESCRIPTION
**Pull request by dumbunny**
Some WHERE clauses are very sparse WRT the PK, causing some
split queries to scan most or all of the table. The full scan
algorithm is more stable with no WHERE filters.

@erzel: Does this work for you?

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/2157)

### CODE REVIEW

**Comment by erzel** [comment]
Looks good, Dean. Just a few comments. Thanks for doing this.

**Comment by dumbunny** [comment]
Comments updated. Changed numRowsPerQueryPart to numRowsPerQueryPart - 1.

**Comment by dumbunny** [comment]
*[go/vt/tabletserver/splitquery/full_scan_algorithm.go, line 112 at r3](https://reviewable.io:443/reviews/youtube/vitess/2157#-KUO8EESuKGGWJkfggWN:-KUOPcvcz8bTNvdZuSKU:b-jv08af) ([raw file](https://github.com/youtube/vitess/blob/de0528c2ee8db541c5790582a81893b7d18a618e/go/vt/tabletserver/splitquery/full_scan_algorithm.go#L112)):*
<details><summary><i>Previously, erzel-bot (Erez Louidor (bot account)) wrote…</i></summary>
> AFAIU LIMIT numRowsPerQueryPart,1 returns the (numRowsPerQueryPart+1)th row as the boundary point. Since the corresponding split-part then uses a strict inequality it would yield numRowsPerQueryPart rows (assuming no filtering); so I think we shouldn't subtract 1, right?
</details>
You're right. I didn't notice it was counting prevBindVariableNames again (using <=) in buildNoninitialQuery. Reverted.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/2157)*

**Comment by dumbunny** [comment]
@enisoc: erzel-bot is not on this list of approvers

**Comment by enisoc** [comment]
I've sent the invite to give @erzel-bot read-only collaborator status. After he accepts that invite, we can add the bot to `.pullapprove.yml`.

**Comment by erzel** [comment]
erzel-bot accepted the invitation...
LGTM from me for now.

**Comment by erzel** [comment]
LGTM

**Pull request merged**
