### PR TITLE
v3 vschema: lower case vindex params

### PR DESCRIPTION
**Pull request by sougou**
@alainjobart 
Camel case vindex params look odd after the rest of the
tags got lowercased. This change makes them also lowercase.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1735)

### CODE REVIEW

**Comment by alainjobart** [comment]
LGTM there is only one vindex that takes parameters?

**Comment by sougou** [comment]
Yes. @ashudeep-sharma just reported that the VSchema displayed by VTGate still uses camel case. I'll add that change also to this PR. It should involve adding a few tags to the non-formal schema.

**Comment by sougou** [comment]
PTAL. The change was slightly bigger than expected.

**Comment by alainjobart** [comment]
How about keeping the formal version around instead, and showing that after a successful load?

**Comment by sougou** [comment]
I think showing the internal version is more important, because it tells us that the vschema was interpreted correctly. For example, if there's a typo in the original that caused a column to point to the wrong vindex, it will show up in this representation.

**Comment by alainjobart** [comment]
LGTM ok cool

**Pull request merged**
