### PR TITLE
Make vtgatev2 test less flaky.

### PR DESCRIPTION
**Pull request by guoliang100**
@alainjobart @sougou

### CODE REVIEW

**Comment by alainjobart** [comment]
That seems like a bandaid fix, but LGTM if it works.

Overall, we need to spend time thinking how we can make these tests a lot less flaky. Using sleep() should be avoided as much as possible, in favor of waiting for a condition to happen (even if it means polling).

**Comment by guoliang100** [comment]
After we get rid of the shard gateway, some of sleeps can be converted to wait for connection count vars.

Removing some of the checks (new_count = old_count+1) because it is an invalid assertion with new gateway implementation (query can happen on either tablet, not the one previously used).

**Comment by alainjobart** [comment]
Regarding the query counts, then you could sum up both tablets counts and check it gets incremented, otherwise we lose the test on the variables... or if we test that somewhere else, that would work too.

**Comment by guoliang100** [comment]
@alainjobart

**Comment by alainjobart** [comment]
LGTM thanks!

**Pull request merged**
