### PR TITLE
travis: Run tests within our "mysql57" bootstrap Docker image instead of natively.

### PR DESCRIPTION
**Pull request by michael-berlin**
This will fix the recent test failures and undo the change from https://github.com/youtube/vitess/issues/3203 where we had to disable the tests "unit" and "mysql_server" because they were constantly failing. With this change, the two tests are enabled again.

More importantly, with this change we no longer have to maintain Vitess' dependencies in the Travis CI environment.

Instead, we'll depend on our "bootstrap" Docker images to run the test.

Note that I had to come up with a caching mechanism for "make build". By default, we provide the test within the Docker container with a clean copy of the Git repository and run "make build" before *each* test i.e. a Travis build with 10 tests in it would have run "make build" 10 times. To avoid this, I added a new option "-use_docker_cache" to test.go which will run "make build" before all tests and use "docker commit" to create a new temporary cache image.

Overall, this change has several consequences:

- Travis CI builds will be dependent on an up to date Docker image. For example, if somebody adds a dependency to vendor/vendor.json and forgets to rebuild and push the used Docker image, "make build" will fail. I'll add a test for this in a separate commit.

- We'll use MySQL 5.7 (instead of MariaDB) for the Travis test runs.

- We can no longer use Travis container infrastructure and have to use the VM infrastructure instead. That means an additional 20 seconds wait time until Travis has started a VM and runs the build.

- More overhead per Travis build because we need to pull the Docker image first (takes up to two minutes). Before, we used Travis' caching mechanism to cache dependencies between builds.

- Slightly slower tests because the VM infrastructure has less resources than the container one (~2 CPUs (bursted) instead of 2 CPUs, see https://docs.travis-ci.com/user/reference/overview/).

- The ".git" directory will be copied into the Docker image as well now because travis/check_make_proto.sh needs it. I'll create a separate commit to integrate this.

### CODE REVIEW

**Comment by sougou** [comment]
Hopefully  the caching of the build will offset some of the loss. The throttler mock is still failing though.

**Comment by alainjobart** [comment]
LGTM

Can we also run some MariaDB tests, and MySQL 5.7 ones now? How about etcd? :)

**Comment by michael-berlin** [comment]
@alainjobart wrote:
> Can we also run some MariaDB tests, and MySQL 5.7 ones now? How about etcd? :)

In theory yes :) In practice, the `test.go` runner doesn't support to run all tests of one flavor + only some select tests from other flavors. Extending that should be easy though. We just have to come up with a good way to specify this :) Maybe specify an optional "testing_flavors" in test/config.json for each test? Other ideas?

**Comment by michael-berlin** [comment]
Alain, the other thing to keep in mind: Testing another flavor will increase the test duration because you have to download that Docker image as well and create a build cache for this second flavor.

We could work around this by splitting this at the Travis test shard level: 4 shards run mysql57 tests, 1 shard runs MariaDB tests.

**Comment by michael-berlin** [comment]
I've pushed rebuilt Docker images and the test is passing now. Merging the change now.

**Pull request merged**
