### PR TITLE
Go client part 1 and other misc changes

### PR DESCRIPTION
**Pull request by sougou**
This has the low level vtgate rpc connection. I've used the same approach as tabletconn so we can plug in other protocols if necessary.
For testing, I'm using @henryanand's approach of launching a cluster. So, I've added a check for -short for those that want to skip these tests.
And @enisoc's comments from the previous CL have been addressed.

### CODE REVIEW

**Comment by enisoc** [comment]
LGTM

**Comment by sougou** [comment]
Looks like travis is not on go1.4 yet. So, it's failing on my TestMain. The feature is still under development. So, I'll just disable the failing test for now, and think of a work-around.

**Comment by enisoc** [comment]
@henryanand tried switching Travis to Go 1.4 a while ago. He only had some minor issues, which I think have been resolved now. It should just be a matter of switching it back and seeing if it works.

If you need TestMain, I guess we should also update GettingStarted.md to say we require Go 1.4 to build/test.

**Comment by sougou** [comment]
I'm kind of leaning in favor of @aaijazi's thoughts on not launching external programs for unit tests. So, I'll see if I can change this into an integration test.
But our code coverage will suffer a bit.

**Comment by henryanand** [comment]
https://github.com/youtube/vitess/pull/326 enables go1.4 on Travis and our tests are green.

https://travis-ci.org/youtube/vitess/builds/47693965

So these tests should be good to go now.

**Pull request merged**
