### PR TITLE
Handling Transaction Timeout

### PR DESCRIPTION
**Pull request by harshit-gangal**
Changes:

- When a query is sent in a transaction and an SQLNonTransient Exception occurs then error message is checked for Not In Transaction Error. If that is the case than transaction object to set to null.
- Removing duplicate code for rollback and commit by calling the methods.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1966)

### CODE REVIEW

**Comment by harshit-gangal** [comment]
@enisoc - Check the PR and let us know if this can be handled any better.

**Comment by harshit-gangal** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 543 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1966#-KPjNVh3IRlP8l64oHpp:-KPjYvqiDBBREQIvTO9z:b-y7mm5z) ([raw file](https://github.com/youtube/vitess/blob/6b65f308f52a9894b42b7f5a5033552740568a43/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L543)):*
<details><summary><i>Previously, enisoc-bot (Anthony Yeh) wrote…</i></summary>
> Rather than parsing the string, we should define a mapping to another exception class. I'm proposing to add this here: https://github.com/youtube/vitess/pull/1971
</details>
Once your changes are merged. I will update it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1966)*

**Comment by harshit-gangal** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 117 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1966#-KPjJnAA7xKmN4gbVWo6:-KPqE809D3rXGH8GxtuL:b53ctuk) ([raw file](https://github.com/youtube/vitess/blob/817c05cf924a89fcd6ad64fc26d1d79471bac4e2/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L117)):*
> checkAutoCommit
Transaction only exists when auto commit is false. So checkAutoCommit() will pass.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java, line 169 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1966#-KPjKXBVoQ7Q7WejuNYg:-KPqG9DJyI2Q1rppXySb:b-hkp60b) ([raw file](https://github.com/youtube/vitess/blob/817c05cf924a89fcd6ad64fc26d1d79471bac4e2/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessConnection.java#L169)):*
<details><summary><i>Previously, enisoc-bot (Anthony Yeh) wrote…</i></summary>
> Similar to above for `commit()`, `rollback()` does an additional `checkAutoCommit()` that I don't think is right for this use case.
</details>
Same applies here.

---

*[java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java, line 543 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1966#-KPjNVh3IRlP8l64oHpp:-KPqGBdJNkmwRrUuzPBc:b-896fix) ([raw file](https://github.com/youtube/vitess/blob/817c05cf924a89fcd6ad64fc26d1d79471bac4e2/java/jdbc/src/main/java/com/flipkart/vitess/jdbc/VitessStatement.java#L543)):*
<details><summary><i>Previously, enisoc-bot (Anthony Yeh) wrote…</i></summary>
> The new exception mapping is merged now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1966)*

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
