### PR TITLE
update vitess documentation

### PR DESCRIPTION
**Pull request by burr86**
Hey, I just went through the tutorial/documentation at vitess.io and fixed some of the documentation as I found old references, incomplete text, typos, etc. This is my first time submitting a pull request to this repository, so please let me know if I should do this some other way.

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1525)

### CODE REVIEW

**Comment by enisoc** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/ShardingKubernetes.md, line 244 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1525#-KBOvMaFkU85-0ALDETW:-KBOvMaG4aCffshFHNZe:-1984362234) ([raw file](https://github.com/youtube/vitess/blob/afedc63d9a3393b0161ba7de0da56a21f258b365/doc/ShardingKubernetes.md#L244)):*
These instructions are actually different from the non-sharded one, mainly because of 'sharded-vttablet-down' instead of 'vttablet-down'. If the instructions say to go back to the unsharded for teardown, I think we should remove that notice and keep this sharding-specific teardown.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1525)*

**Comment by burr86** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[doc/ShardingKubernetes.md, line 244 \[r4\]](https://reviewable.io:443/reviews/youtube/vitess/1525#-KBOvMaFkU85-0ALDETW:-KBtZ7UPuC-TbJEpfd6N:199999786) ([raw file](https://github.com/youtube/vitess/blob/afedc63d9a3393b0161ba7de0da56a21f258b365/doc/ShardingKubernetes.md#L244)):*
Ah, you're right. I misread the instructions, they say to not come back. Removed this commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1525)*

**Comment by enisoc** [comment]
LGTM but it looks like you have merge conflicts. Can you try to resolve those?

**Comment by burr86** [comment]
Fixed!

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1525#-:-KBtnCH6yVRJQAvjAsu8:1758359698)*

**Pull request merged**
