### PR TITLE
Vtgate

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc no functional change, but simplifications / removal of duplicate fields.

(will need an import with google3 changes, will do it as soon as this is submitted).

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1872)

### CODE REVIEW

**Comment by enisoc** [comment]
I noticed you've been adding commits throughout the day. Is this still WIP, or just one of those exploding PRs that gets bigger the longer I take to review it? :P

**Comment by alainjobart** [comment]
The later, the more time you take to review it, the bigger it gets... ;)

Seriously though, most commits are incremental changes, you can just review them one at a time, and I can merge up to what you reviewed... Everything up to the last 2 commits is prep work and clean up, last 2 commits are the start of l2vtgate...

**Comment by alainjobart** [comment]
@enisoc I won't change this any more now, it's really getting too big. Please review so I can import and keep working :)

Only thing left on l2vtgate is the end2end tests, I believe. Will work on it after this is reviewed and submitted.

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 27 of 40 files at r1, 16 of 16 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1872#-:-KNDaA5TMcFfoafPnsrZ:1417088721)*

**Pull request merged**
