### PR TITLE
Renaming SqlQuery to just Query to be shorter.

### PR DESCRIPTION
**Pull request by alainjobart**
Small change, last one in this branch before I switch to forked repository.
@enisoc

### CODE REVIEW

**Comment by aaijazi** [comment]
Heh I'd actually prefer going longer / more specific - QueryService, for easy grepping.

**Comment by alainjobart** [comment]
The stubs generated by proto compiler now are:
QueryClient
QueryServer
I don't mind going to QueryServiceClient and QueryServiceServer, but I thought that was a bit long... Who else has an opinion? :)

**Comment by enisoc** [comment]
In that case, I vote for "service Query".

Or we could go the other way and rename SqlQuery to StructuredSqlQueryLanguage. That reminds me, I need to stop by the automated ATM machine later...

LGTM

**Comment by sougou** [comment]
I don't have a strong opinion, except that SqlQuery sucks :).
How about Tablet or VTTablet? Kind of in line with VTGate.

**Comment by alainjobart** [comment]
I like VTTablet, will do that.

**Comment by alainjobart** [comment]
Hum VTTablet is just too big of a change, then have to rename query.proto to vttablet.proto, and it gets out of hand... I think I'll stick to Query.

**Pull request merged**
