### PR TITLE
Add BeginExecute{,Batch} to gRPC, removing tabletconn.ERR*

### PR DESCRIPTION
**Pull request by alainjobart**
I will keep the flag in gRPC client for now, eventually I'll default it to true.

I still have the server side of the cleanup for error codes to do. I am not sure I need to wait for the client side to roll out or not.

@guoliang100 @enisoc

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1656)

### CODE REVIEW

**Comment by alainjobart** [comment]
@sougou please have a quick look.
@guoliang100 or @enisoc please review now.

I think I'd like that in before the internal cut today.

**Comment by enisoc** [comment]
What happens if the begin succeeds, but one or more queries fail? Does the caller have a way to tell that, so they can rollback?

Also, I'm guessing I should regenerate php protos after this?

---

Reviewed 20 of 22 files at r1, 25 of 25 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1656#-:-KGO5CY7vsIMJLGCZ5YF:1575125642)*

**Comment by alainjobart** [comment]
If the begin succeeds, transaction_id is then set, and the error is sent back as a payload of the response (along with transaction_id). That's what the client looks at.

No need to regenerate other languages, this is vtgate to vttablet, we only support go there.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1656#-:-KGOFa1vRrKdEWT4GpC0:-1219454977)*

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
