### PR TITLE
java/client: Return JDBC-compatible types for BIT and DATE/TIME

### PR DESCRIPTION
**Pull request by enisoc**
@sougou 

These match the [types used by Connector/J](http://dev.mysql.com/doc/connector-j/en/connector-j-reference-type-conversions.html), with one exception: we don't support the special case that BIT(1) is returned as Boolean instead of byte[], because that would require sending field size info along with every query result. If that turns out to be an important use case for users, we can consider workarounds like adding getBoolean() as a convenience to check the first byte.

I haven't found any internal users of the old Joda-based getDateTime(), so it should be safe to break it.

### CODE REVIEW

**Comment by sougou** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/1499/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)

**Comment by enisoc** [comment]
It turns out that toString() and valueOf() on java.sql.(Date|Time|Timestamp) all use the local machine's default timezone. This caused the test to fail on Travis although it passes on my machine.

Ideally we would do everything in UTC to avoid confusion, but they don't provide any parsing or formatting methods for that. I'm looking into it.

**Comment by enisoc** [comment]
@sougou Could you take a look at the new commits?

**Comment by enisoc** [comment]
@sougou I think I figured it out now. The right way to do it is to offer both getDate(...) and getDate(..., Calendar) which is how it's done in both JDBC PreparedStatement (sending side) and JDBC ResultSet (receiving side). When the Calendar isn't specified, we use the user's default time zone. Otherwise, we use the given Calendar to do the conversion. This lets the user tell us, "I know this data is in time zone X, so treat it that way."

To implement this, I had to keep my new MySQL DateTime class, because java.sql.(Date|Time|Timestamp).(toString|valueOf) don't support converting in different time zones. As an added benefit of my custom converters, we support the full MySQL syntax for these values, as opposed to choking on things like fractional seconds in a TIME value, which MySQL allows as of 5.6.

**Comment by sougou** [comment]
lgtm

**Pull request merged**
