### PR TITLE
Resharding

### PR DESCRIPTION
**Pull request by alainjobart**
@enisoc @sougou @aaijazi 
First one to get there :)

### CODE REVIEW

**Comment by alainjobart** [comment]
@sougou @aaijazi 
I also adding a panic handler for tabletserver, and tests to make sure it's called. Will replace the stubby one once I import. Later on we can make it the only panic handler when we convert SqlQuery to not panic for error reporting.

**Comment by alainjobart** [comment]
(btw ServeUpdateStream is not implemented on the stubby side, which is why I don't have unit tests for it, on the binlog player side).

**Comment by enisoc** [comment]
LGTM

**Comment by sougou** [comment]
lgtm

**Pull request merged**
