### PR TITLE
Switched vtgate from controller to pod template to force them to specifi...

### PR DESCRIPTION
**Pull request by thompsonja**
...c nodes

The cluster-up script now automatically calculates the number of gke nodes by adding the number of tablets and vtgates together.  I would have preferred to keep the vtgate templates as controllers, but all I could guarantee is that vtgates are assigned to different nodes than vttablets (multiple vtgates could still share a node).  Once k8s supports better specification of resource requirements, we can revert back to using a controller.

@enisoc @henryanand

### CODE REVIEW

**Comment by henryanand** [comment]
LGTM!

**Comment by enisoc** [comment]
Can we keep it as a controller for non-benchmarking?

**Comment by thompsonja** [comment]
Good question.  It was nice going all the way because then it was just a
matter of specifying different template files in vtgate-up/down.sh.
Keeping it as a controller would probably require that we create/maintain
separate vtgate-up scripts, not sure if that would be better or not...

**Comment by enisoc** [comment]
The reason I ask is because in general I want to use replication controllers as much as possible, in the base k8s example. In addition to being easier to change the number of replicas on-the-fly, the controller will also reschedule pods if (for example) a node goes down. If we don't have to lose those advantages for the non-benchmarking case, I'd like to keep them.

**Comment by enisoc** [comment]
Since the benchmarking setup is diverging, maybe we should split it into examples/benchmark.

**Comment by thompsonja** [comment]
I'm thinking you're right.  I've been fighting it for a while but it's
probably time to split it up :)

**Comment by thompsonja** [comment]
Didn't quite move everything to a new folder but I did keep the controller intact, opting for a separate vtgate-up/down.sh script to use pods for benchmarking purposes.

**Comment by enisoc** [comment]
LGTM

**Pull request merged**
