### PR TITLE
Updated directions in the getting started section of the doc

### PR DESCRIPTION
**Pull request by pkulsh**
@michael-berlin 
Clarified directions on how to clone the github repository.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1813)

### CODE REVIEW

**Comment by michael-berlin** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/GettingStarted.md~, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1813#-KKnrrIqiC_XElf4pu-R:-KKnrrIqiC_XElf4pu-S:1069939237) ([raw file](https://github.com/youtube/vitess/blob/f845aec237fb4a743eccc571a2b93856b1a82ea8/doc/GettingStarted.md~#L1)):*
> ```
> You can build Vitess using either [Docker](#docker-build) or a
> ```

Please delete this temporary file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1813#-:-KKnrtmN5b5P8VrjlZGE:1417088721)*

**Comment by pkulsh** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[doc/GettingStarted.md~, line 1 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1813#-KKnrrIqiC_XElf4pu-R:-KKntxsx_8KZ6iKIIuZl:-499146009) ([raw file](https://github.com/youtube/vitess/blob/f845aec237fb4a743eccc571a2b93856b1a82ea8/doc/GettingStarted.md~#L1)):*
<details><summary><i>Previously, michael-berlin (Michael Berlin) wrote…</i></summary>
> Please delete this temporary file.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1813)*

**Comment by pkulsh** [comment]
I signed it!

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1813#-:-KKuVpIVMmr-2_Y61aX2:1417088721)*

**Comment by pkulsh** [comment]
I signed it!

**Pull request merged**
