### PR TITLE
Add RestoreFromBackup command to vtctl

### PR DESCRIPTION
**Pull request by pivanof**
@enisoc @michael-berlin 

Executing the command vttablet will completely delete the existing data and
then replace it from the latest backup. The sequence of actions is basically
the same as vttablet has already used to setup a freshly started replica.

Also mysqlctl interface is extended with ReinitConfig function. It's used by
vttablet to change server_id of the replica before restoring it from backup.
That's necessary to avoid a possible situation when restored replica skips
transactions in the replication stream which have the same server_id.

The new RestoreFromBackup command will be used later in the implementation of
an automated pivot.

This change doesn't add any tests for the new functionality because I didn't
find a place where I could add these tests. Please tell me if there is actually
a place that I missed. Meanwhile I tested this manually on the example
Kubernetes setup.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1841)

### CODE REVIEW

**Comment by alainjobart** [comment]
The right place to test it would probably be in test/backup.py, where we already test the restore from scratch of a tablet.

**Comment by enisoc** [comment]
As Alain said, you should add a test in `backup.py`. One thing that's awkward is that the desired before and after states for `RestoreFromBackup` are the same, so it may be challenging to design a test that will actually fail if you simply comment out the `RestoreFromBackup` command.

---

Reviewed 38 of 38 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[go/vt/tabletmanager/action_agent.go, line 261 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1YDmPnzs6EssLH8Qm:-KM1YDmPnzs6EssLH8Qn:-2131949660) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/action_agent.go#L261)):*
> ```Go
> 			// restoreFromBackup wil just be a regular action
> 			// (same as if it was triggered remotely)
> 			agent.actionMutex.Lock()
> ```

We like to avoid this pattern of manual locking like this: Make`RestoreData()` into a wrapper that acquires the lock and calls `restoreDataLocked()` which does the work. Then in places that already hold the lock, they can call `restoreDataLocked()` directly.

---

*[go/vt/tabletmanager/restore.go, line 90 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1Z81F-eJk6DnFmaDp:-KM1Z81F-eJk6DnFmaDq:-401560519) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/restore.go#L90)):*
> ```Go
> 
> 	// let's update our internal state (start query service and other things)
> 	if err := agent.refreshTablet(ctx, "after backup"); err != nil {
> ```

`"after restore from backup"`

---

*[go/vt/tabletmanager/rpc_backup.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZuG1hzSJne7XGnCi:-KM1ZuG1hzSJne7XGnCj:500099058) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/rpc_backup.go#L74)):*
> ```Go
> // Should be called under RPCWrapLockAction.
> func (agent *ActionAgent) RestoreFromBackup(ctx context.Context, logger logutil.Logger) error {
> 	tablet, err := agent.TopoServer.GetTablet(ctx, agent.TabletAlias)
> ```

Is there a reason you prefer to re-fetch from topo, rather than use `agent.Tablet()`? If so, please add a comment explaining what scenario the re-fetch guards against.

---

*[go/vt/tabletmanager/rpc_backup.go, line 86 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZII3wFhOPdhmxDYG:-KM1ZII3wFhOPdhmxDYH:-598331042) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/rpc_backup.go#L86)):*
> ```Go
> 
> 	// now we can run restore
> 	err = agent.RestoreData(ctx, l, true /* deleteBeforeRestore */)
> ```

Here's an example where you can call `restoreDataLocked()` since you're assumed to be wrapped by `RPCWrapLockAction`.

---

*[go/vt/tabletserver/testutils_test.go, line 91 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1T2NHSiAgjDEJa3RF:-KM1T2NIearMzz29tMQ6:-1750391374) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletserver/testutils_test.go#L91)):*
> ```Go
> 		"",
> 		"",
> 		mysqlctl.NewMycnf(11111, 6802),
> ```

It used to be that some places relied on the MySQL ServerID being the same as the Tablet UID. I fixed those and set two different values here as a regression test. Can you add that back by calling `NewMycnf()` as a separate line, and then setting `cnf.ServerID = 22222`?

---

*[go/vt/vtctl/backup.go, line 31 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZYgXB7O2J7dsa3ux:-KM1ZYgXB7O2J7dsa3uy:442313450) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/vtctl/backup.go#L31)):*
> ```Go
> 		"Removes a backup for the BackupStorage."})
> 
> 	addCommand("Tablets", command{
> ```

Please run the `doc/vtctl_go_reference.py` script to regenerate docs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1841#-:-KM1bkZAy4P5vs5GNrxk:-315170763)*

**Comment by pivanof** [comment]
Thanks! I've added the test now. PTAL.

---

Review status: 25 of 40 files reviewed at latest revision, 6 unresolved discussions.

---

*[go/vt/tabletmanager/action_agent.go, line 261 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1YDmPnzs6EssLH8Qm:-KM1iXkmocjwwd1p0eB9:-499146009) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/action_agent.go#L261)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> We like to avoid this pattern of manual locking like this: Make`RestoreData()` into a wrapper that acquires the lock and calls `restoreDataLocked()` which does the work. Then in places that already hold the lock, they can call `restoreDataLocked()` directly.
</details>
Done.

---

*[go/vt/tabletmanager/restore.go, line 90 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1Z81F-eJk6DnFmaDp:-KM1i_47hj1UImiO6xA8:-499146009) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/restore.go#L90)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> `"after restore from backup"`
</details>
Done.

---

*[go/vt/tabletmanager/rpc_backup.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZuG1hzSJne7XGnCi:-KM1ibfPDiI_V5_y4GQ1:358470057) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/rpc_backup.go#L74)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Is there a reason you prefer to re-fetch from topo, rather than use `agent.Tablet()`? If so, please add a comment explaining what scenario the re-fetch guards against.
</details>
No reason. This was just copied from the Backup() function above. Should I change this or keep consistent?

---

*[go/vt/tabletmanager/rpc_backup.go, line 86 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZII3wFhOPdhmxDYG:-KM1inHLKSwpcwHp-nq7:-499146009) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/rpc_backup.go#L86)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Here's an example where you can call `restoreDataLocked()` since you're assumed to be wrapped by `RPCWrapLockAction`.
</details>
Done.

---

*[go/vt/tabletserver/testutils_test.go, line 91 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1T2NHSiAgjDEJa3RF:-KM1is1ImMVlx2KlYUul:-499146009) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletserver/testutils_test.go#L91)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> It used to be that some places relied on the MySQL ServerID being the same as the Tablet UID. I fixed those and set two different values here as a regression test. Can you add that back by calling `NewMycnf()` as a separate line, and then setting `cnf.ServerID = 22222`?
</details>
Done.

---

*[go/vt/vtctl/backup.go, line 31 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZYgXB7O2J7dsa3ux:-KM1itBcsmv7JDXLvpps:-499146009) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/vtctl/backup.go#L31)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> Please run the `doc/vtctl_go_reference.py` script to regenerate docs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1841#-:-KM1iQQeNL5QoWVKVMqP:-1641909200)*

**Comment by enisoc** [comment]
:lgtm:

---

Reviewed 14 of 15 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/tabletmanager/rpc_backup.go, line 74 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KM1ZuG1hzSJne7XGnCi:-KMBbaVFICIYMGktCMNG:982621159) ([raw file](https://github.com/youtube/vitess/blob/0045955cd3fc107334a3c2e47f3968f34d42b499/go/vt/tabletmanager/rpc_backup.go#L74)):*
<details><summary><i>Previously, pivanof (Pavel Ivanov) wrote…</i></summary>
> No reason. This was just copied from the Backup() function above. Should I change this or keep consistent?
</details>
I see. If it's copied from Backup, let's just keep it consistent for now.

---

*[test/backup.py, line 288 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KMBc4G9p0CqcOSWh7qn:-KMBc4GAXvhRl5h4Nc9p:-1271408812) ([raw file](https://github.com/youtube/vitess/blob/80b72d151ba0b12e5dc03c7cb7a4dfc583e4f14d/test/backup.py#L288)):*
> ```Python
>     self._restore_old_master_test(_restore_using_kill)
> 
>   def test_in_place_restore_vtctl(self):
> ```

I don't think we need to test individual commands through vtctl. We expect it to be the same result as through vtctlclient->vtctld. If there is potential for vtctl to differ from vtctlclient->vtctld, those cases should be targeted in something like vtctld_test.py.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1841#-:-KMBcfCjKpSxGPX1Z8SY:1417088721)*

**Comment by pivanof** [comment]
Review status: 39 of 40 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/backup.py, line 288 \[r3\]](https://reviewable.io:443/reviews/youtube/vitess/1841#-KMBc4G9p0CqcOSWh7qn:-KMQzQiFCC9oIiIZAjIw:-1969159007) ([raw file](https://github.com/youtube/vitess/blob/80b72d151ba0b12e5dc03c7cb7a4dfc583e4f14d/test/backup.py#L288)):*
<details><summary><i>Previously, enisoc (Anthony Yeh) wrote…</i></summary>
> I don't think we need to test individual commands through vtctl. We expect it to be the same result as through vtctlclient->vtctld. If there is potential for vtctl to differ from vtctlclient->vtctld, those cases should be targeted in something like vtctld_test.py.
</details>
I removed the extra test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/youtube/vitess/1841)*

**Pull request merged**
