### PR TITLE
Add vtctl WaitForDrain command.

### PR DESCRIPTION
**Pull request by michael-berlin**
@guoliang100 Please review the first two commits.

@enisoc I recommend to review each commit separately because I touched different parts of the system.

Noteworthy changes:
- I've added a "qps" field to StreamHealthResponse which has the current QPS rate
- QPS rates are now sampled every 5 seconds instead of every 60 seconds
- the tablet QPS graph had another bug which I fixed: values on the X (time) axis were drawn in the wrong order, showing the oldest QPS rate as the most recent one

[Review on Reviewable](https://reviewable.io/reviews/youtube/vitess/1475)

### CODE REVIEW

**Comment by enisoc** [comment]
Review status: 0 of 25 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[go/vt/tabletserver/status.go, line 83 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1475#-K9UNbzbpTHxacB5Jeiv:-K9UNbzbpTHxacB5Jeiw:-395024366) ([raw file](https://github.com/youtube/vitess/blob/f029b8acc04dbe121bd3e748f5e4ecaff8db76d9/go/vt/tabletserver/status.go#L83)):*
missing semicolon

---

*[go/vt/vtctl/vtctl.go, line 563 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1475#-K9UP3baVNkpqEGw6MbS:-K9UP3baVNkpqEGw6MbT:587731755) ([raw file](https://github.com/youtube/vitess/blob/f029b8acc04dbe121bd3e748f5e4ecaff8db76d9/go/vt/vtctl/vtctl.go#L563)):*
We have a utility type StringListValue in vitess/go/flagutil that handles this type of flag. Here's an example of how to use it:

https://github.com/youtube/vitess/blob/5c65d6073a45bf5df03e71d0c1a2763404cf1072/go/vt/servenv/service_map.go#L27

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1475)*

**Comment by enisoc** [comment]
Reviewed 25 of 25 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1475)*

**Comment by michael-berlin** [comment]
Review status: 23 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[go/vt/tabletserver/status.go, line 83 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1475#-K9UNbzbpTHxacB5Jeiv:-K9UWG8R0QpE4lMgAezu:-499146009) ([raw file](https://github.com/youtube/vitess/blob/f029b8acc04dbe121bd3e748f5e4ecaff8db76d9/go/vt/tabletserver/status.go#L83)):*
Done.

---

*[go/vt/vtctl/vtctl.go, line 563 \[r1\]](https://reviewable.io:443/reviews/youtube/vitess/1475#-K9UP3baVNkpqEGw6MbS:-K9UYpGbYXETkwKAz2K8:-499146009) ([raw file](https://github.com/youtube/vitess/blob/f029b8acc04dbe121bd3e748f5e4ecaff8db76d9/go/vt/vtctl/vtctl.go#L563)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1475)*

**Comment by enisoc** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/youtube/vitess/1475)*

**Comment by enisoc** [comment]
LGTM

**Comment by michael-berlin** [comment]
@alainjobart Please review just the very last commit.

Anthony already approved the rest.

**Comment by alainjobart** [comment]
LGTM

**Pull request merged**
