### PR TITLE
replaced dattoo/protobuf-php to stanley-cheung/protobuf-php

### PR DESCRIPTION
**Pull request by mdhheydari**
As discussed in #1879, I made this pull request.

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1880)

### CODE REVIEW

**Comment by mdhheydari** [comment]
@googlebot I signed it!

**Comment by Rastusik** [comment]
the 'repositories' segment of composer.json should be deleted to in this case ...

https://github.com/youtube/vitess/pull/1880/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R2

**Comment by enisoc** [comment]
Thanks for figuring this out! In addition to @Rastusik's comment, I think `composer.lock` also needs to be updated, right?

**Comment by Rastusik** [comment]
@enisoc yes, someone has to run composer update and commit the .lock file

**Comment by Rastusik** [comment]
@mdhheydari would you please finish this pull request today? It slows me down quite a bit. Or can I somehow update this pull request? Or I also might create a new one, if you don't have time for this right now, if that's no problem.

**Comment by michael-berlin** [comment]
@Rastusik You cannot update this pull request because you probably don't have permissions to the branch `mdhheydari:master`.

I suggest an alternative:

If you like, I can merge this now and you can send another PR for the missing fixes.

**Comment by Rastusik** [comment]
@michael-berlin I could do that, thank you

**Comment by michael-berlin** [comment]
LGTM

Merging this pull request now @Rastusik wil fix forward.

[Approved with PullApprove](https://pullapprove.com/youtube/vitess/pull-request/1880/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=youtube/vitess)

**Pull request merged**
